### ISSUE TITLE
extra使用问题

### ISSUE THREAD

**Issue by spyvip** [didi/nightingale#106]
## 旧指标
![image](https://user-images.githubusercontent.com/1212932/79961732-b775fa80-84b9-11ea-91e8-121087d889c2.png)

## 新指标
![image](https://user-images.githubusercontent.com/1212932/79961559-7c73c700-84b9-11ea-8183-f8b503efd541.png)

旧指标：已存在的指标，如果增加了extra字段，在告警界面extra字段是不显示
新指标：没有这样的问题

## 建议
- 是不是就是这样设计的？按我的理解，应该都支持才对
- 这种差异是否可以写到文档中？

**Comment by spyvip** [comment]
`
 curl -X DELETE -d "{\"endpoints\":[\"test-endpoint\"],\"metrics\":[\"test-metric-platform\"]}" http://index.addr/api/index/metrics
`

删除指标后，再重新发起数据，还是一样的

**Comment by UlricQin** [comment]
你每次上报的监控指标都有Extra字段？

**Comment by spyvip** [comment]
> 你每次上报的监控指标都有Extra字段？

@UlricQin  不一定都有

对了，还有个问题，这个extra字段会存到redis的那个消息队列里不？

**Comment by spyvip** [comment]
![image](https://user-images.githubusercontent.com/1212932/79965225-5866b480-84be-11ea-98ad-e2636d046162.png)
我觉得这个extra应该跟【时间、值】统一列，毕竟是那个点时的扩展信息

**Comment by UlricQin** [comment]
不是每次都有的话，就是符合预期的。Extra这里只是展示告警的那个值的Extra，比如你求了一个最近几个点的最大值，最大值那个值恰好没有extra，就不会有了。

放到这个表里，后面确实可以考虑下

**Comment by spyvip** [comment]
@UlricQin 我的测试用例是，一个指标已存在，但是没有extra字段，后续的请求都有extra字段，告警时这些都没有

**Comment by 710leo** [comment]
> @UlricQin 我的测试用例是，一个指标已存在，但是没有extra字段，后续的请求都有extra字段，告警时告警页面这些都没有

你配置的策略是单个条件的，还是与条件的？现在页面的Extra是从最新的上报点中拿的，如果你最新的点中Extra不为空，那页面应该也不会是空的，可以打印下上报数据的日志确定下

**Comment by spyvip** [comment]
@710leo 
- 单个条件
- 上报的数据中是有extra字段的

````
ts=`date +%s`;  curl -X POST -d "[{\"metric\": \"test-metric-platform\", \"endpoint\": \"test-endpoint\", \"timestamp\": $ts,\"step\": 10,\"value\": $RANDOM,\"tags\": \"idc=lg,project=xx\",\"extra\":\"111ss\"}]" http://172.17.8.105:2059/api/collector/push
````

**Comment by CarrotH** [comment]
与条件的时候，好像也还有第一个metric的信息中带extra，第二个metric中是空的

**Comment by 710leo** [comment]
@CarrotH 与条件告警策略，第二个metric是从tsdb查询的数据，所以不会有Extra字段

**Comment by 710leo** [comment]
> ![image](https://user-images.githubusercontent.com/1212932/79965225-5866b480-84be-11ea-98ad-e2636d046162.png)
> 我觉得这个extra应该跟【时间、值】同一列，毕竟是那个点时的扩展信息

最新代码已经换成这种展示方式了

**Comment by spyvip** [comment]
@710leo @UlricQin   问下告警信息里的extra字段有没有传递给redis里的消息队列？

**Comment by 710leo** [comment]
@spyvip 传递了
