### ISSUE TITLE
nodata问题

### ISSUE THREAD

**Issue by spyvip** [didi/nightingale#107]
节点下有两台机器，102，103，策略配置如下，感觉Endpoint和tag 交叉了

![image](https://user-images.githubusercontent.com/1212932/79983937-0ed89280-84db-11ea-916d-ba673e34859f.png)

![image](https://user-images.githubusercontent.com/1212932/79983856-ee103d00-84da-11ea-9f70-2ba9d587f6e3.png)

**Comment by 710leo** [comment]
我看下

**Comment by 710leo** [comment]
多谢反馈，是查到的索引有问题，最新代码已修复
