### ISSUE TITLE
nightingale 是否支持 postgresql 作为存储？

### ISSUE THREAD

**Issue by walnut-tom** [didi/nightingale#108]
nightingale 是否支持 postgresql 作为存储？还是只支持mysql，个人感觉监控用 postgresql 可能更省心点。

**Comment by chenjiandongx** [comment]
如果存储的是配置相关类的数据，MySQL 和 postgresql 都是可以的。但目前代码中只有 MySQL 的实现。

**Comment by UlricQin** [comment]
mysql存储的是配置类数据，非历史监控数据，mysql和pg都能解决问题，但是pg只在新潮的公司才会用到，我周边的同事都是熟悉mysql，所以我们选型时使用mysql

**Comment by walnut-tom** [comment]
> mysql存储的是配置类数据，非历史监控数据，mysql和pg都能解决问题，但是pg只在新潮的公司才会用到，我周边的同事都是熟悉mysql，所以我们选型时使用mysql

这个好像就不是很open的态度

**Comment by UlricQin** [comment]
> > mysql存储的是配置类数据，非历史监控数据，mysql和pg都能解决问题，但是pg只在新潮的公司才会用到，我周边的同事都是熟悉mysql，所以我们选型时使用mysql
> 
> 这个好像就不是很open的态度

这是技术选型的典型考虑啊，怎么就变成不open了呢，做项目肯定首要考虑投入产出比啊。你这边如果有其他异议，可以提出1、2、3罗列想法，看社区反馈，简单一句不是很open，可不是参与社区的做法
