### ISSUE TITLE
endpoint没有自动添加

### ISSUE THREAD

**Issue by CarrotH** [didi/nightingale#111]
我在时区是GMT的机器上安装了n9e，6个组件都起来后，web上看不到任何对象，然后我在数据库中手动插入一个endpoint，在监控看图中就可以查询指标曲线，而且在logs中未找到任务信息。
数据库测试过两个，分别布在GMT和GMT+8的机器上，现象一样

有谁碰到过或者解决过类似问题

**Comment by 710leo** [comment]
@CarrotH 如果你有手动删除过endpoint，之后删除的endpoint不会再继续自动添加了

**Comment by CarrotH** [comment]
多谢@710leo ，暂时通过删除.index目录解决

不过这个本地缓存是否有开关可以控制，endpoint可能出现删除后重新加回的情况

**Comment by UlricQin** [comment]
这是性能的折中，如果来了一个endpoint就去数据库判断，数据库压力就太大了。
如果周期性全量同步一次，也仍然会存在不及时的情况。
所以使用上的建议有两个：
1. endpoint不要删，如果删了，就得确保重新加回来的时候手工再加上
2. 与cmdb结合使用，endpoint就是机器ip，不管index模块是否写入db，都永远使用cmdb的数据，服务树与cmdb打通
