### ISSUE TITLE
集群服务的指标监控

### ISSUE THREAD

**Issue by spyvip** [didi/nightingale#114]
### Issue Description

***Do you want to request a `feature` or report a `bug`?***
假设有两个服务，每个服务的指标是1，简单而言整体就是2，但实际要求是对外提供服务指标需要达到4，才能稳定以及抵抗外部流量

***What is the current behavior?***

***What is the expected behavior?***

***Context / What is the motivation / use case for changing the behavior?***

***Other information*** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context.)

**Comment by UlricQin** [comment]
集群指标聚合功能，后续会放出来，现在还没有
