### ISSUE TITLE
如何设置保存7天的数据量

### ISSUE THREAD

**Issue by spyvip** [didi/nightingale#115]
### Issue Description

***Do you want to request a `feature` or report a `bug`?***

*如何设置保存7天的数据量*
文档上的https://n9e.didiyun.com/zh/docs/operation/tsdb/ 里说的每看懂~~~~

![image](https://user-images.githubusercontent.com/1212932/80068016-76412180-8571-11ea-9172-eb0cedee6bba.png)

***What is the current behavior?***

***What is the expected behavior?***

***Context / What is the motivation / use case for changing the behavior?***

***Other information*** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context.)

**Comment by UlricQin** [comment]
你上报的数据本来就没够2天吧.....

**Comment by spyvip** [comment]
@UlricQin sorry, my mistake
