### ISSUE TITLE
从openfalcon过度到夜莺系统报错

### ISSUE THREAD

**Issue by 527593036** [didi/nightingale#116]
### Issue Description
场景：因为openfalcon的agent机器较多，需要逐步过度到夜莺的collector，因此另外部署一套夜莺服务端，agent上报tansfer通过nginx的tcp代理转发到夜莺系统，出现上报问题

***Do you want to request a `feature` or report a `bug`?***
从openfalcon迁移nightingale问题

***错误日志如下***

2020/04/23 18:38:51 gpu.go:31: Initialize error:  could not load NVML library
2020/04/23 18:38:51 var.go:102: => <Total=89> <Endpoint:office-backup, Metric:agent.alive, Type:GAUGE, Tags:, Step:60, Time:1587638331, Value:1>
2020/04/23 18:38:51 var.go:102: => <Total=9> <Endpoint:office-backup, Metric:df.bytes.free.percent, Type:GAUGE, Tags:mount=/,fstype=xfs, Step:60, Time:1587638331, Value:41.04546480555961>
2020/04/23 18:38:51 transfer.go:62: call Transfer.Update fail: &{{2 1} <nil> 192.168.0.29:5810 1s} invalid character 'H' looking for beginning of value
2020/04/23 18:38:51 var.go:109: <= <Total=0, Invalid:0, Latency=0ms, Message:>
2020/04/23 18:38:51 builtin.go:60: ERROR: invalid character 'H' looking for beginning of value
2020/04/23 18:38:51 var.go:102: => <Total=6> <Endpoint:office-backup, Metric:ss.timewait, Type:GAUGE, Tags:, Step:60, Time:1587638331, Value:72>
2020/04/23 18:38:51 ips.go:40: ERROR: call Agent.TrustableIps fail invalid character 'H' looking for beginning of value
2020/04/23 18:38:51 transfer.go:62: call Transfer.Update fail: &{{2 1} <nil> 192.168.0.29:5810 1s} invalid character 'H' looking for beginning of value
2020/04/23 18:38:51 var.go:109: <= <Total=0, Invalid:0, Latency=0ms, Message:>
2020/04/23 18:38:51 transfer.go:62: call Transfer.Update fail: &{{0 0} <nil> 192.168.0.29:5810 1s} invalid character 'H' looking for beginning of value
2020/04/23 18:38:51 var.go:109: <= <Total=0, Invalid:0, Latency=0ms, Message:>
2020/04/23 18:38:51 plugin.go:71: call Agent.MinePlugin fail: invalid character 'H' looking for beginning of value
2020/04/23 18:38:51 reporter.go:48: call Agent.ReportStatus fail: invalid character 'H' looking for beginning of value Request: {office-backup 192.168.0.9 5.1.2 6d6e75aca1177bfc84327168c0a2134237bac419} Response: {0}

**Comment by UlricQin** [comment]
这两个系统不能这样交互数据。rpc协议发生了变化。

建议的直接部署collector，和falcon-agent同时运行，因为资源消耗都很小，互不干扰。

**Comment by wangdi244** [comment]
目前能否支持falcon-agent直接接入夜莺监控？已部署的服务器很多，涉及到跨部门的问题，沟通成本很高。如果切换夜莺再需要部署agent，是不太可能的操作

**Comment by UlricQin** [comment]
做不到，协议变了，建议两套双跑

> 目前能否支持falcon-agent直接接入夜莺监控？已部署的服务器很多，涉及到跨部门的问题，沟通成本很高。如果切换夜莺再需要部署agent，是不太可能的操作
