### ISSUE TITLE
同一指标并发指标值问题

### ISSUE THREAD

**Issue by spyvip** [didi/nightingale#119]
**What would you like to be added**:

**Why is this needed**:
*目前n9e还只适用于具有周期性的非并发指标监控*

同一时刻有N个并发请求，对同一指标的如何处理？
比如：/api/login,这种业务类指标，在并发时会有N个指标值，n9e可否降级用于存储数据？不知道我理解对不对，请大师指点

据我了解，同一指标并发请求，如果每个请求，tag都加入traceId，这个对曲线、数据来说不太友好

**Comment by UlricQin** [comment]
如果/api/login的qps非常多，那每个周期其实都能吐出指标，日志监控就是类似的逻辑，通常是10秒上报一次，10秒内的所有请求综合计算，求qps，平均延迟等。如果某些指标没有值，其实问题也不大，无非就是监控图上体现为散点图

**Comment by spyvip** [comment]
> 如果/api/login的qps非常多，那每个周期其实都能吐出指标，日志监控就是类似的逻辑，通常是10秒上报一次，10秒内的所有请求综合计算，求qps，平均延迟等。如果某些指标没有值，其实问题也不大，无非就是监控图上体现为散点图

大师就是大师

**Comment by UlricQin** [comment]
据我了解，同一指标并发请求，如果每个请求，tag都加入traceId，这个对曲线、数据来说不太友好
---
traceid不要放到tag里，可以考虑放到extra字段里 @spyvip
