### ISSUE TITLE
监控大盘增加新节点，展示的时候图表不会自动把新节点加上

### ISSUE THREAD

**Issue by Cole-GG** [didi/nightingale#122]
![image](https://user-images.githubusercontent.com/25050370/80330517-f9b38900-8877-11ea-939e-e732bd0571e1.png)
must be first select someone endpoint save ..after then selete add =all save 。

**Comment by UlricQin** [comment]
endpoint不要选择机器，选 =all

**Comment by Cole-GG** [comment]
确实是选择=all 但是新增加endpoint不会在图上面展示，需要我按上面的操作一遍才行。

**Comment by UlricQin** [comment]
我测试了一下，确实有问题 @710leo @jsers 给看看
