### ISSUE TITLE
请求transfer上报数据

### ISSUE THREAD

**Issue by crazylsq** [didi/nightingale#123]
我在一台collector上curl请求transfer接口上报数据，直接nginx返回502

请求方式
1. 确保账号密码验证通过
curl -uxx:xx http://xx/api/portal/self/profile
{"dat":{"id":1,"username":"root","dispname":"超管","phone":"","email":"","im":"","is_root":1},"err":""}

2. 上报数据
curl -uxx:xx -XPOST -d'{"endpoint": "v001", "tags": "service=sshd, port=22", "timestamp": 1588046823, "metric": "process.fd", "extra": "pid=359696", "value": 6400, "counterType": "GAUGE", "step": 20}' "http://xx/api/transfer/push"

nginx返回
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.16.1</center>
</body>
</html>

我有观察到nginx错误日志
2020/04/28 13:20:36 [error] 24239#0: *2041 upstream prematurely closed connection while reading response header from upstream, client: 100.121.84.30, server: n9e.meetsocial.cn, request: "POST /api/transfer/push HTTP/1.1", upstream: "http://172.16.1.61:5810/api/transfer/push", host: "n9e.meetsocial.cn"

我在transfer上直接请求IP+端口 也是不行，这是什么情况，是我请求url或者数据有问题吗

nginx配置跟官方提供的相同

**Comment by UlricQin** [comment]
格式不对，push的数据应该是个数组，另外加个header Content-Type: application/json
