### ISSUE TITLE
🌟案例收集

### ISSUE THREAD

**Issue by 710leo** [didi/nightingale#125]
如果您在使用 Nightingale，欢迎将使用案例补充到这里，然后添加我们小助手的[微信](https://s3-gz01.didistatic.com/n9e-pub/image/didiyun-xiaozhushou-wechat.jpeg)，小助手会邀请各位进入Nightingale交流微信群。

例子
```
- 滴滴出行
- www.didiglobal.com
- 体量：设备量级 10W+ 监控指标体量 7亿+
```

**Comment by weizhenqian** [comment]
- 掌阅科技
-https://www.zhangyue.com/、https://www.ireader.com/
- 体量：设备量级 6K+ 监控指标体量 30 million+

**Comment by spyvip** [comment]
- 某医疗领域
- 体量：100以内 + 主要是系统指标、中间件指标、业务指标

**Comment by hhr66** [comment]
寺库
体量：1000 + 混合云架构，业务已经上k8s

**Comment by jc1981** [comment]
- 卓游信息科技
- www.15166.com
- 体量：设备量级 400+  多云架构 监控指标体量 3000+

**Comment by matao3754** [comment]
新浪网
www.sina.com.cn
监控指标体量 1000000+

**Comment by matao3754** [comment]
- 新浪网
- www.sina.com.cn
- 监控指标体量 1000000+

-

**Comment by ermazi** [comment]
- 二麻教育
- www.ermazi.com
- 体量：设备量级1台 监控指标体量 100+

**Comment by leezer3379** [comment]
新氧网
www.soyoung.com
体量: 75000+

**Comment by u31s** [comment]
某化工制造
体量：设备100+，混合云，监控体量：10000+

**Comment by youtwo123** [comment]
- 跟谁学
- www.baijiahulian.com
- 体量：设备量级 8000+ 监控指标体量 20 million+

**Comment by Catnogood** [comment]
可否出一期交换机监控的视频，现在环境已经搭建完了，但交换机信息收集不到，可以出一期教学吗？

**Comment by kame000** [comment]
- 简网
- [www.linkingcities.com](https://www.linkingcities.com/)
- 体量: 设备量级 200 +  混合云，监控指标：15000+

**Comment by DingGuodong** [comment]
> 如果您在使用 Nightingale，欢迎将使用案例补充到这里，然后添加我们小助手的[微信](https://s3-gz01.didistatic.com/n9e-pub/image/didiyun-xiaozhushou-wechat.jpeg)，小助手会邀请各位进入Nightingale交流微信群。
> 
> 例子
> 
> ```
> - 滴滴出行
> - www.didiglobal.com
> - 体量：设备量级 10W+ 监控指标体量 7亿+
> ```

建议附加使用的版本和部署方式，特别是使用的版本号。
