### ISSUE TITLE
通知结果：已收敛，是什么意思？

### ISSUE THREAD

**Issue by chengang2** [didi/nightingale#126]
通知结果：已收敛
这个怎么理解？

**Comment by UlricQin** [comment]
问题：
监控数据如果触发阈值，就会告警，如果一直没有恢复，就会一直告，这对研发运维人员来说，是一个打扰

设计：
夜莺引入了告警收敛机制，即：在监控策略的配置里，有一个配置是 `在多少分钟内，最多报警几次`。比如一般会配置60分钟内最多报警1次，这样一来，即使监控指标没有恢复，也不会重复告警通知。查看历史告警事件，会发现，第一次告警的时候，显示“已发送”，第二次就不会发送了，显示“以收敛”，这个就是代表：这最近的60分钟内，已经发送过一次告警了，第二次就不用发了，收敛掉。等下个周期（即下个小时）到来，如果没有恢复，才会再发一条告警通知。
