### ISSUE TITLE
关于图表优化的建议

### ISSUE THREAD

**Issue by miniCoconut** [didi/nightingale#127]
![image](https://user-images.githubusercontent.com/15183268/80472058-cdcafd00-8976-11ea-9f9d-b017ea86848a.png)
当前监控看图的图表展示有三个问题

1.鼠标移动到曲线上只能看到某条线的数值而不是所有线的，这样如果多条线很近或者重合，看不到其它endPoint曲线的值

2.如果endPoint在时间区间内只有一个点的数据，完全找不到它的存在

3.在曲线上无法直观看出有几个数据点以及数据点位置

**Comment by UlricQin** [comment]
上面有个Multi的复选框，勾选之后就可以了
