### ISSUE TITLE
collector配置能不能配置多列目录

### ISSUE THREAD

**Issue by hualidi123** [didi/nightingale#128]
**What happened**:
我们不同的监控内容放在不同的目录下面，有的主机需要不同目录下的脚本监控。配置了两列，collector起不来。
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OS (e.g: `cat /etc/os-release`):
- Logs:
- Others:
![image](https://user-images.githubusercontent.com/31085705/80486676-28bc1e80-898e-11ea-956b-2e323679376a.png)
![image](https://user-images.githubusercontent.com/31085705/80486764-47221a00-898e-11ea-9772-eb0a4b8cdb60.png)

现在是需要配置两个目录，有没有办法解决

**Comment by UlricQin** [comment]
不支持的哈，可以把多个监控脚本放到一个目录里去。
