### ISSUE TITLE
按照视频搭建Nightingale监控后发现监控看图选项里面看不到图像，日志里面只有judge有报错get index err:index xclude failed

### ISSUE THREAD

**Issue by NovemberCap** [didi/nightingale#129]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OS (e.g: `cat /etc/os-release`):
- Logs:
- Others:

**Comment by NovemberCap** [comment]
[](url)
![image](https://user-images.githubusercontent.com/64469410/80552041-0232cd80-89f8-11ea-8152-90d05a33355e.png)

**Comment by NovemberCap** [comment]
监控需要的6个模块已经启动

**Comment by UlricQin** [comment]
你是QQ群那个兄弟么？机器时间不对的那个

**Comment by NovemberCap** [comment]
对的，我不咋会弄，不知道写的对不对



 
发件人： ulricqin
发送时间： 2020-04-29 11:47
收件人： didi/nightingale
抄送： NovemberCap; Author
主题： Re: [didi/nightingale] 按照视频搭建Nightingale监控后发现监控看图选项里面看不到图像，日志里面只有judge有报错get index err:index xclude failed (#129)
你是QQ群那个兄弟么？机器时间不对的那个

**Comment by UlricQin** [comment]
行了，就这样吧。

这个问题是机器时间不对，把机器时间调整好，然后看一下tsdb的配置，删除data/5821目录下的内容，然后重启tsdb即可搞定

**Comment by NovemberCap** [comment]
好~
    这个弄好了，我就是想在上面写个问题，然后弄个答案，让大家都知道怎么弄



 
发件人： ulricqin
发送时间： 2020-04-29 13:32
收件人： didi/nightingale
抄送： NovemberCap; Author
主题： Re: [didi/nightingale] 按照视频搭建Nightingale监控后发现监控看图选项里面看不到图像，日志里面只有judge有报错get index err:index xclude failed (#129)
行了，就这样吧。
这个问题是机器时间不对，把机器时间调整好，然后看一下tsdb的配置，删除data/5821目录下的内容，然后重启tsdb即可搞定
