### ISSUE TITLE
服务器双网卡问题 

### ISSUE THREAD

**Issue by skydeadpeng** [didi/nightingale#130]
ifconfig: `--help' gives usage information.:5841 get connection fail: conn <nil>, err address ens34: 未知的主机
ifconfig: `--help' gives usage information.:5841: too many colons in address. proc: Name:ens34: 未知的这个是 transfer 下的日志， 但是 etc 获取ip 的shell 只有在 collector，index 里面才有shell ？

**Comment by UlricQin** [comment]
不止这俩模块，judge好像也有，去etc下各个配置文件都打开看看

**Comment by skydeadpeng** [comment]
好像改了还是有问题，我改了2个shell 获取ip   
  shell: ifconfig ens34|grep inet|awk '{print $2}'|awk -F ':' '{print $NF}'|head -n 1;ifconfig ens192|grep inet|awk '{print $2}'|awk -F ':' '{print $NF}'|head -n 1 。
  我看状态都启动了，还是有点报错信息。
judge 里面的 日志有 2020-04-29 12:53:24.212417 WARNING stra/stra.go:58 get strategy from remote failed, error:parse http://127.0.0.1:5800/api/portal/stras/effective?instance=172.18.10.52
192.168.1.31:5841: net/url: invalid control character in URL
tansfer 下面的日志  192.168.1.31:5841 get connection fail: conn <nil>, err lookup 172.18.10.52
192.168.1.31: no such host. proc: Name:172.18.10.52
192.168.1.31:5841,Cnt:0,active:0,all:0,free:0
2020-04-29 12:54:04.344563 WARNING backend/sender.go:165 send judge 172.18.10.52
192.168.1.31:5841 fail: 172.18.10.52
192.168.1.31:5841 get connection fail: conn <nil>, err lookup 172.18.10.52
192.168.1.31: no such host. proc: Name:172.18.10.52
192.168.1.31:5841,Cnt:0,active:0,all:0,free:0
