### ISSUE TITLE
proposal: version management

### ISSUE THREAD

**Issue by chenjiandongx** [didi/nightingale#134]
**What would you like to be added**:

夜莺这个框架，虽然有一个大的版本的迭代，但是实际上各个模块是相对独立的，是否考虑为每个模块也加上一个指定的版本，这样用户在反馈问题的时候也可以把各模块的版本信息带上，以便排查问题。

但就目前来讲，夜莺在 release 的时候只是简单的打了个 tag，也无把二进制包一起 release 出来。

实际上 open-falcon 是有计划对每个模块打版本的，比如

https://github.com/didi/nightingale/blob/master/src/modules/collector/collector.go#L31

我对版本管理的建议是，各模块的版本同大版本保持一致。但可以管理得更自动化，使用 Golang 的 XOPTION 机制。这里有篇参考的文章 https://www.atatus.com/blog/golang-auto-build-versioning/。

使用这种方法，我们只需要在 build 脚本修改一个全局统一的 version 变量即可，这样每个模块的 -v flag 就都可以显示版本信息。或者如果不需要一个特别的版本号的话，也可以仅使用 githash 以及 buildtime，展示信息如下所示，根据 git hash 也可以很方便地追踪到具体 commit。

```shell
$ ./agent -v
Git Commit Hash: 740e6bd912e5ecd1a9bbb8607c19039a4349db9f
UTC Build Time: 2020-05-07_05:10:18AM
```

**Why is this needed**:

**Comment by UlricQin** [comment]
赞同这个搞法

**Comment by chenjiandongx** [comment]
@UlricQin @710leo 如果都同意的话，我后面会发个 PR 提供这个功能并附上说明。

**Comment by 710leo** [comment]
挺好的，支持
