### ISSUE TITLE
N9E 如何监控容器以及应用 metrics

### ISSUE THREAD

**Issue by ngxlua** [didi/nightingale#139]
感谢 didi 团队对监控领域的不断投入，

n9e 如何监控容器？ didi 团队内部容器方向也是用的 prometheus 吗？

---

我们公司现在使用的是 falcon-plus 和 prometheus 两套监控系统，

* falcon 对宿主机和传统应用
* prometheus 对容器化应用以及新式的应用级监控 (metrics export)

社区版是否可以兼容下 metrics 呢？

**Comment by UlricQin** [comment]
滴滴是做了一个容器的监控插件，容器平台也封装了k8s，创建容器的时候自动挂到某个服务树节点，删除的时候自动从节点踢掉相关容器。

prometheus的metrics exporter还没有看过，可以加个微信探讨探讨😄

**Comment by ngxlua** [comment]
@UlricQin didi 的监控插件有可能开源嘛，学习一下
