### ISSUE TITLE
主站英文文档翻译

### ISSUE THREAD

**Issue by UlricQin** [didi/nightingale#14]
https://n9e.didiyun.com/docs/

**Comment by hantmac** [comment]
@UlricQin 我来认领翻译下试试？不知道还需要什么条件吗？

**Comment by UlricQin** [comment]
> @UlricQin 我来认领翻译下试试？不知道还需要什么条件吗？

好的呀，不需要啥条件，我明天把文档结构调整一下，引入中英文切换，英文部分标记上TODO，然后联系你搞起哈

**Comment by hantmac** [comment]
> > @UlricQin 我来认领翻译下试试？不知道还需要什么条件吗？
> 
> 好的呀，不需要啥条件，我明天把文档结构调整一下，引入中英文切换，英文部分标记上TODO，然后联系你搞起哈

好嘞👌

**Comment by UlricQin** [comment]
https://github.com/n9e/book/tree/master/content/en/docs 主要是翻译这个目录下面的内容，直接把各个页面的中文内容改成英文即可 :-) @hantmac

**Comment by hantmac** [comment]
> https://github.com/n9e/book/tree/master/content/en/docs 主要是翻译这个目录下面的内容，直接把各个页面的中文内容改成英文即可 :-) @hantmac

好的，我着手开始 👌

**Comment by hantmac** [comment]
@UlricQin 应该是搞定了 🛩️

**Comment by UlricQin** [comment]
太棒了，晚上回去我更新一下主站，非常非常感谢对社区做出的贡献 :)

**Comment by hantmac** [comment]
> 太棒了，晚上回去我更新一下主站，非常非常感谢对社区做出的贡献 :)

翻译不妥的地方还请指正哈:)
