### ISSUE TITLE
English web interface

### ISSUE THREAD

**Issue by l2dy** [didi/nightingale#15]
Please support i18n in the web interface, and add English translation.

Default language preference should be configurable.

**Comment by UlricQin** [comment]
Relevant work is in progress.

**Comment by thtantos** [comment]
I want an event

**Comment by jsers** [comment]
English translation is supported, and other languages require community support.

**Comment by jsers** [comment]
The default language by `navigator.language`

**Comment by l2dy** [comment]
> English translation is supported, and other languages require community support.

Thanks! English translation is not complete though.

https://github.com/didi/nightingale/blob/c7e50f223de52a95e8ce8998725da87edb4791f7/web/src/components/Layout/NsTree.tsx#L45

https://github.com/didi/nightingale/blob/c7e50f223de52a95e8ce8998725da87edb4791f7/web/src/components/Layout/index.tsx#L320-L324
