### ISSUE TITLE
屏蔽报警的时候希望能对单个endpoint下所有报警进行屏蔽

### ISSUE THREAD

**Issue by yimeng** [didi/nightingale#150]
**What would you like to be added**:
屏蔽报警的时候希望能对单个endpoint下所有报警进行屏蔽
无监控项传入的时候或者监控项为all关键字的时候希望能对endpoint的所有报警进行屏蔽

**Why is this needed**:
变更或者上线的时候不知道影响什么监控项，因此想屏蔽单个endpoit的所有监控项。

**Comment by UlricQin** [comment]
这个产品上可以支持，欢迎认领

**Comment by UlricQin** [comment]
https://github.com/didi/nightingale/pull/196
