### ISSUE TITLE
环比视图浏览器console 报错

### ISSUE THREAD

**Issue by nxsre** [didi/nightingale#153]
当前最新的代码，前端使用 npm run start 运行
在启用环比时，浏览器报错如下：
![image](https://user-images.githubusercontent.com/32614138/82321777-ff7c3480-9a07-11ea-93e6-fb93b7404ab1.png)

**Comment by jsers** [comment]
这个不影响使用，只是可能前端会有轻微的性能问题，看错误信息应该是前端拿到了相同的指标名去作为 react key。
回头我排查下是数据不正常导致的还是这边逻辑有问题。
