### ISSUE TITLE
希望前端线条配色改成深色方案

### ISSUE THREAD

**Issue by matao3754** [didi/nightingale#155]
**What would you like to be added**:
希望监控大盘修改深色方案,或者配色方案可调
**Why is this needed**:
在监控很多监控大屏时,看不清线条以及阈值,有较大的对比度

**Comment by jsers** [comment]
> 在监控很多监控大屏时,看不清线条以及阈值,有较大的对比度
不太明白这里的监控很多监控大屏时，是什么意思。以及这里的线条是轴的线条还是数据的折线，折线（前面一部分）和阈值都是采用明度和饱和度比较大颜色，和素色的背景还是有比较大的对比度的。

关于深色方案涉及改动比较大，暂时可以考虑 grafana，近期会上 n9e database 或者也可以考虑社区里面打到其他 backend 的方案

**Comment by matao3754** [comment]
监控大屏指的是电视,投影之类的设备

**Comment by jsers** [comment]
n9e 自身目前暂无改造深色方案的计划，有这需求的可以转移到 grafana
https://github.com/n9e/grafana-n9e-datasource
