### ISSUE TITLE
希望增加监控看图别名选择

### ISSUE THREAD

**Issue by lf2180** [didi/nightingale#158]
**What would you like to be added**:
监控看图界面 选项窗口支持别名。 最好也支持别名搜索
![image](https://user-images.githubusercontent.com/30641413/82871741-a3179880-9f64-11ea-8135-c8a0ba89e510.png)

**Why is this needed**:
机器上报的都是ip，但是自定义了别名。
在监控看图里面只能指定机器ip作图不方便。

**Comment by UlricQin** [comment]
辛苦 @jsers 给看看

**Comment by jsers** [comment]
这里是通过类似 habits/identity 的接口去区分展示，还是在 UI 上允许同时展示 ip 和 name ?

**Comment by UlricQin** [comment]
同时展示吧，画图拉数据的时候，只拿着endpoint去查即可

**Comment by leezer3379** [comment]
现在是否还是不支持同时展示

**Comment by UlricQin** [comment]
是的，现在在忙月底大版本，月底大版本发版之后会着手你说的这个需求 Ulric Qin 邮箱：ulric.qin@gmail.com 签名由 网易邮箱大师 定制 在2020年09月25日 19:06，Xiaotian Yin 写道： 现在是否还是不支持同时展示 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by UlricQin** [comment]
清理历史遗留issue，如有问题，请reopen
