### ISSUE TITLE
数据存储时限

### ISSUE THREAD

**Issue by H-YMing** [didi/nightingale#160]
想做个小型的数据查询，空间不够，不想存太久，监控数据可以只存几个小时或者一天吗？在哪里可以修改？

**Comment by 710leo** [comment]
可以修改，可以参考官方文档 [置绘图数据的存储时长](https://n9e.didiyun.com/zh/docs/operation/tsdb/#%E7%BD%AE%E7%BB%98%E5%9B%BE%E6%95%B0%E6%8D%AE%E7%9A%84%E5%AD%98%E5%82%A8%E6%97%B6%E9%95%BF)
