### ISSUE TITLE
本地采用源码编译方式安装夜莺，状态正常但是输入服务器地址无法访问首页请问是什么原因

### ISSUE THREAD

**Issue by HuoYingCunCunZhang** [didi/nightingale#161]
跟着官网老师的视频通过编译方式安装夜莺，最后查看状态显示6大组件安装成功，但是在地址栏输入服务器的IP地址并不能访问网站，下面有图显示。

查看日志发现ERROR.log 一直变大内容基本上都是一个错误，下面贴出具体错误内容

**Environment**:
- OS :Centos7.8
- Logs: 

> 2020-05-29 09:48:35.655725 ERROR stra/cron.go:36 get collect err:get collects from remote:http://127.0.0.1:5800/api/portal/collects/bash: route: 未找到命令
bash: ifconfig: 未找到命令 failed, error:parse "http://127.0.0.1:5800/api/portal/collects/bash: route: 未找到命令\nbash: ifconfig: 未找到命令": net/url: invalid control character in URL

> 2020-05-29 10:07:56.659360 ERROR worker/worker.go:189 [worker][file:/var/log/messages][num:10][id:1][producer error][sid:1048461] : illegal timestamp, greater than current

这个是Log:

> [ERROR.log](https://github.com/didi/nightingale/files/4699411/ERROR.log)

![问题1](https://user-images.githubusercontent.com/46839162/83215353-5a94f080-a199-11ea-9872-dfbe0a1c3490.jpg)
![现象1](https://user-images.githubusercontent.com/46839162/83215356-5bc61d80-a199-11ea-925f-04362fc0eafd.jpg)

- Others:

**Comment by HuoYingCunCunZhang** [comment]
各位大佬，帮忙给看一下是不是哪里没有搞清楚导致的问题？

**Comment by sweetweapen** [comment]
感觉有两个问题，一个是ifconfig 命令没安装 ，一个是服务器时间不对

**Comment by HuoYingCunCunZhang** [comment]
收到您的回复了，我先试试看看可不可以，谢谢您！！这回复太神速了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"sweetweapen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月29日(星期五) 上午10:48
收件人:&nbsp;"didi/nightingale"<nightingale@noreply.github.com&gt;;
抄送:&nbsp;"翟超"<332437232@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [didi/nightingale] 本地采用源码编译方式安装夜莺，状态正常但是输入服务器地址无法访问首页请问是什么原因 (#161)





 
感觉有两个问题，一个是ifconfig 命令没安装 ，一个是服务器时间不对

**Comment by HuoYingCunCunZhang** [comment]
> 2020-05-29 10:07:55.655716 ERROR stra/cron.go:36 get collect err:get collects from remote:http://127.0.0.1:5800/api/portal/collects/bash: route: 未找到命令
bash: ifconfig: 未找到命令 failed, error:parse "http://127.0.0.1:5800/api/portal/collects/bash: route: 未找到命令\nbash: ifconfig: 未找到命令": net/url: invalid control character in URL

这里面一共有几个问题？分别是什么？
