### ISSUE TITLE
希望可以增加时间格式样式或者可以自定义

### ISSUE THREAD

**Issue by Summerdies** [didi/nightingale#163]
这样的格式目前无法匹配  dd/mm/yyyy HH:MM:SS
10.16.9.183 - - [29/05/2020:20:16:32,916 +0800] "POST /plain HTTP/1.1" 200 4 0 10.13.8.182

**Comment by tianyanli** [comment]
case "dd/mm/yyyy:HH:MM:SS":
		pat = `([012][0-9]|3[01])/(0[1-9]|1[012])/(2[0-9]{3}):([01][0-9]|2[0-4])(:[012345][0-9]){2}`
		timeFormat = "02/01/2006:15:04:05"

**Comment by UlricQin** [comment]
3ks @tianyanli  merged https://github.com/didi/nightingale/pull/164 https://github.com/didi/nightingale/pull/165 https://github.com/didi/nightingale/pull/166

**Comment by Summerdies** [comment]
> 3ks @tianyanli merged #164 #165 #166

貌似前端没有增加选项
![image](https://user-images.githubusercontent.com/42688766/83375928-1c9b0500-a403-11ea-8b84-55cde1410046.png)
