### ISSUE TITLE
新增加的时间格式前端标题无法选择

### ISSUE THREAD

**Issue by Summerdies** [didi/nightingale#183]
https://github.com/didi/nightingale/issues/163
搜索了编译后的前端代码Pub目录，没有搜到，尝试自己编译但是报错
fetk: command not found 
![image](https://user-images.githubusercontent.com/42688766/83376442-c929b680-a404-11ea-9f79-954d8bc59fbc.png)

**Comment by jsers** [comment]
@Summerdies 
刚提交了编译好的代码
