### ISSUE TITLE
更新新版本后，collector端 采集日志时报错

### ISSUE THREAD

**Issue by Summerdies** [didi/nightingale#184]
如图，今天更新了新的版本后  采集日志数据开始报错了
![image](https://user-images.githubusercontent.com/42688766/83383842-84a81600-a418-11ea-9189-b40facee316e.png)

2020-06-01 12:06:02.814486 ERROR worker/worker.go:189 [worker][file:/var/log/messages][num:10][id:8][producer error][sid:1048461] : illegal timestamp, greater than current

**Comment by sweetweapen** [comment]
看日志，像是时间不对

**Comment by UlricQin** [comment]
看日志是从日志里读取的时候超前了（与系统时间相比）

**Comment by Summerdies** [comment]
我回退到1.3.0版本 就不会有这个错误了。。。

**Comment by UlricQin** [comment]
我测试一下哈

**Comment by UlricQin** [comment]
确实有问题，刚提交了一段修复代码，可以拉取master分支测试，试试OK了么？ :) @Summerdies

**Comment by Summerdies** [comment]
> 确实有问题，刚提交了一段修复代码，可以拉取master分支测试，试试OK了么？ :) @Summerdies

没问题了～ @UlricQin
