### ISSUE TITLE
希望可以支持通配符匹配日志路径格式

### ISSUE THREAD

**Issue by Summerdies** [didi/nightingale#185]
例：/flume1/a/\*/www/a/logs/server\*.log
实际可能是
/flume1/a/10.244.8.75/www/a/logs/server.log
/flume1/a/10.244.13.13/www/a/logs/server.log
因为收集日志的时候 分散收集了各ip的日志， 不知道可不可以通过*和特定后缀定位到指定log，查出所有符合条件的文件内容，在进行正则匹配

**Comment by UlricQin** [comment]
这个产品上可以支持，不过近期没有精力，先放着吧，后面找时间搞

**Comment by UlricQin** [comment]
清理历史遗留issue，如有问题，请reopen
