### ISSUE TITLE
不同step收集间隔，绘图展示问题

### ISSUE THREAD

**Issue by luxiangqing** [didi/nightingale#186]
不同的采样间隔，如已一开始采集间隔step=60s，后面采样间隔改到300s后，绘图仅展示数据点，未连成线

![image](https://user-images.githubusercontent.com/29593018/83400779-078b9980-a436-11ea-9e96-4e1788c41517.png)

**Comment by UlricQin** [comment]
这个问题实际是一个性能和易用性的折中。正常来讲，一天之后，就会自动更新使用新的step，如果着急，可以调用tsdb的update-index接口手工触发一次全量index的更新
