### ISSUE TITLE
删除的节点，采集数据能上传，但列表不显示

### ISSUE THREAD

**Issue by yapee123456** [didi/nightingale#188]
**What happened**:
删除的节点，采集数据能上传，但列表不显示
**What you expected to happen**:
删除的节点，当有新数据上传时，节点列表能自动显示该节点
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OS (e.g: `cat /etc/os-release`):
- Logs:
- Others:

**Comment by UlricQin** [comment]
endpoint如果删掉就不会有了。需要手工添加，一般endpoint是和cmdb打通的，不要随意删除。如果不需要了，就不要挂载节点了，但不要直接干掉。
