### ISSUE TITLE
k8s和docker是否支持

### ISSUE THREAD

**Issue by lansedebing** [didi/nightingale#189]
**What would you like to be added**:

**Why is this needed**:

**Comment by UlricQin** [comment]
后面支持，也可以先用Open-Falcon社区的容器采集插件

**Comment by UlricQin** [comment]
最近 @710leo 开始牵头做这个事情，完成之前，不建议用夜莺监控K8S、容器

**Comment by UlricQin** [comment]
已经提供容器监控插件：https://github.com/n9e/docker-mon K8S服务端组件都暴露了metrics接口，可以用 https://github.com/n9e/prometheus-exporter-collector
