### ISSUE TITLE
linux系统收集器报error

### ISSUE THREAD

**Issue by yapee123456** [didi/nightingale#191]
**What happened**:
日志：
2020-06-04 09:48:23.350454 ERROR funcs/fsstat.go:89 Open file failed: open /media/yapee/DEEPIN/.fs-detect: read-only file system

**What you expected to happen**:
消除error

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OS (e.g: `cat /etc/os-release`): deepin v20
- Logs:
- Others:

**Comment by UlricQin** [comment]
1，保证collector用root账号启动
2，仍然报错的话可以修改collector配置，把这个分区给ignore掉，有个mountIgnore配置

**Comment by yapee123456** [comment]
> 1，保证collector用root账号启动
> 2，仍然报错的话可以修改collector配置，把这个分区给ignore掉，有个mountIgnore配置

ok，是root运行的，忽视掉目录是没报错了
