### ISSUE TITLE
tsdb服务报错误（打开文件数过多）

### ISSUE THREAD

**Issue by weizhenqian** [didi/nightingale#192]
昨天收到大量agent失活报警，登陆报警客户端查询agent均正常，判断为误报。登陆夜莺监控服务器查询服务信息，发现judge服务大量报错，***AlertUpgrade:{Users:[] Groups:[] Duration:60 Level:1} JudgeInstance:10.100.96.90:5841} get query data err:, call timeout***，判断为tsdb服务连接问题，查询tsdb服务报错信息：***get connection fail: conn <nil>, err dial tcp 10.100.96.92:5831: socket: too many open files..***，查看机器的默认打开文件数为：65535。
其它：昨天报警的时间和copy新报警策略时间刚好重合了，以为是报警策略导致的问题。今天凌晨3点，又出现大量报警，终于确实为tsdb服务打开文件数的问题。这个是通过程序优化，还是我修改自己服务端配置ulimited这样呢？

**Comment by UlricQin** [comment]
需要看看到底是打开的什么文件

**Comment by weizhenqian** [comment]
> 需要看看到底是打开的什么文件

感谢大佬耐心解答！问题已经解决。
查询过程：1.获取tsdb的pid。2.通过/proc/$pid/limits文件查看进程打开文件限制条目。发现为1024。在n9e-tsdb.service配置文件中新增LimitNOFILE=65535(值不要超过ulimit -a 的open file大小)。依次执行：systemctl stop n9e-tsdb、systemctl daemon-reload、systemctl start n9e-tsdb。同上方法检测文件限制条目已经为65535，问题圆满解决。
总结：systemd启动方式的文件句柄数需要单独配置，并不是依据[Service].User。
