### ISSUE TITLE
Error 1243: Unknown prepared statement handler (2517) given to mysqld_stmt_execute

### ISSUE THREAD

**Issue by weizhenqian** [didi/nightingale#193]
mysqld_stmt_execute问题，导致无法查询监控。
昨天服务出现问题是，想通过监控查询监控服务本身相关err信息，通过web端发现报错。
![image](https://user-images.githubusercontent.com/27806578/83711111-e6ed5a80-a654-11ea-9a38-8e53de85fe1e.png)

联系DBA同事咨询，是由于程序程序没有关闭 stmt 导致。调整stmt数值为30000，今天早上又出现同样问题，感觉此处需要优化。

**Comment by UlricQin** [comment]
让DBA给看看是啥SQL导致的，我们所有客户，我们自己，社区用户，你是第一例，哈哈

**Comment by weizhenqian** [comment]
> 让DBA给看看是啥SQL导致的，我们所有客户，我们自己，社区用户，你是第一例，哈哈

经检测为mysql_proxy导致的问题，尝试使用mysql-server就没此问题了。DBA查询经由mysql_proxy的statement达到了30W。（具体原因未深入研究）
