### ISSUE TITLE
通过目录和界面配置plugin不生效

### ISSUE THREAD

**Issue by shijingyu323** [didi/nightingale#197]
使用安装后默认的plugin脚本60_uptime.sh查不到sys.uptime.duration指标
![image](https://user-images.githubusercontent.com/51815361/84011007-0d3e2d80-a9a8-11ea-9d15-e7b9c7f191f8.png)
![image](https://user-images.githubusercontent.com/51815361/84011035-17f8c280-a9a8-11ea-8508-6232eadd780e.png)

**Comment by leezer3379** [comment]
![E365F94D7E9EA50BFEE9839D7F8E29AC](https://user-images.githubusercontent.com/37136385/87542823-2f794880-c6d6-11ea-9db5-5816cad77db7.jpg)
![E3C758E904328CF84945D15ED81BCF46](https://user-images.githubusercontent.com/37136385/87542859-3a33dd80-c6d6-11ea-8728-47f2d7186b41.jpg)
我这是哪里配置错误了还是，采集机制已经更改了，页面搜不到。
说好的放到这个目录里面就能执行的呀

**Comment by czxin788** [comment]
我也遇到这个问题，知道怎么解决吗，版本是v2.7.2

**Comment by chengang2** [comment]
好像是版本问题吧，v2.7.0 正常，在v2.8.0中确实没采集到 @czxin788 。你后面解决了吗
