### ISSUE TITLE
Extra字段的表格有点窄，希望能加长一点

### ISSUE THREAD

**Issue by Summerdies** [didi/nightingale#198]
![image](https://user-images.githubusercontent.com/42688766/84011737-2398b900-a9a9-11ea-854c-728cb290615b.png)

如图

**Comment by 710leo** [comment]
@Summerdies 看截图，日志采集你已经实现把命中的规则的日志写到extra字段了么

**Comment by Summerdies** [comment]
> @Summerdies 看截图，日志采集你已经实现把命中的规则的日志写到extra字段了么

嗯嗯，简单做了修改，实现了这一功能，但是可能不是最好的方法
