### ISSUE TITLE
查看采集策略列表API不传nid报错

### ISSUE THREAD

**Issue by Summerdies** [didi/nightingale#199]
![image](https://user-images.githubusercontent.com/42688766/84112797-040e9880-aa5c-11ea-953b-5c197783b33d.png)
![image](https://user-images.githubusercontent.com/42688766/84112849-17216880-aa5c-11ea-9d8f-12d111646a3e.png)

文档介绍是选填实际是必填，而且没有什么途径能查到nid列表，只能一个一个试或查数据库

**Comment by UlricQin** [comment]
nid就是服务树节点id，这个应该是必填的，文档有问题

**Comment by Summerdies** [comment]
> nid就是服务树节点id，这个应该是必填的，文档有问题

但是应该有个api可以查到nid列表把，现在这个nid 只能从1往上加 一个一个试

**Comment by UlricQin** [comment]
正常逻辑是先通过调用接口拿到整颗服务树，然后根据用户的行为，点击不同的节点，然后去获取策略列表。

**Comment by Summerdies** [comment]
> 正常逻辑是先通过调用接口拿到整颗服务树，然后根据用户的行为，点击不同的节点，然后去获取策略列表。不需要有单独的返回nid的接口，因为服务树的json里就有nid了

方便把 通过调用接口拿到整颗服务树 这个接口告诉我一下不， 我就是想找这个接口没有找到

**Comment by UlricQin** [comment]
所有接口直接看routes.go，/api/portal/tree
