### ISSUE TITLE
告警群组优化

### ISSUE THREAD

**Issue by dup2X** [didi/nightingale#20]
团队那里建议优化下：
1、Team增加IM标识，比如钉钉群的token。

**Comment by UlricQin** [comment]
对于发给钉钉群的需求，能否在用户那里创建一个虚拟的人，这个虚拟人代表某个钉钉群，虚拟人的im字段配置为钉钉群的token

**Comment by adaiLinux** [comment]
> 对于发给钉钉群的需求，能否在用户那里创建一个虚拟的人，这个虚拟人代表某个钉钉群，虚拟人的im字段配置为钉钉群的token

微信同样需要这样的需求...

**Comment by chengang2** [comment]
有同样的需求。倒是可以自己改源码就是了。当然官方支持是最好的

**Comment by UlricQin** [comment]
> > 对于发给钉钉群的需求，能否在用户那里创建一个虚拟的人，这个虚拟人代表某个钉钉群，虚拟人的im字段配置为钉钉群的token
> 
> 微信同样需要这样的需求...

如果用虚拟人的方式可以解决，那就不用改team字段了，这个issue就先关闭了
