### ISSUE TITLE
 ```EXCLUDE``` 可以排除主正则，但tags的正则已经会匹配到值

### ISSUE THREAD

**Issue by Summerdies** [didi/nightingale#200]
![image](https://user-images.githubusercontent.com/42688766/84123241-27414400-aa6c-11ea-8725-28414d0c21a0.png)
**匹配正则**：(?i)\^.\*[error|exception].\*$\`\`\`EXCLUDE\`\`\`\^.\*[nioEventLoopGroup|=|INFO].\*$
**tags**：tagName：key   tagValue：(?i)(error|exception)
**配置验证**：2020-06-09 15:24:38,667 [nioEventLoopGroup-3-3] ERROR c.m.r.n.h.RequestFilterChannelHandler - Connection reset by peer

这样配置后，由于tags 还是会匹配到数据，触发异常报警，非预期。尝试给tags也适用 \`\`\`EXCLUDE\`\`\` 但是提示报错不能使用。

**Comment by UlricQin** [comment]
看不懂，你这个配置配置完成之后，上报了一条什么样的监控数据？metric、tags、value分别是什么
