### ISSUE TITLE
关于模块横向扩展到疑问

### ISSUE THREAD

**Issue by rockpanda** [didi/nightingale#207]
看了辉总的B站的讲解视频，里面有提到组件的横向扩展，有个小疑问，比如redis部署多个的时候，这个多个redis是部署多个单节点的redis 还是说多套的redis集群呢？

**Comment by UlricQin** [comment]
多个单节点的redis。judge里配置这多个redis地址，judge会先尝试推事件给第一个redis，失败了才会尝试第二个。每个redis对应一个monapi来消费
