### ISSUE TITLE
监控看图显示的multi显示所有的

### ISSUE THREAD

**Issue by jc1981** [didi/nightingale#208]
现一个节点中已经监控endpiont 56个，基于业务情况，展示所有的机器情况给产品进行查看，现只有显示15个endpiont的信息
![image](https://user-images.githubusercontent.com/21353424/84370410-cac85b00-ac0a-11ea-9579-c0bd53c6c784.png)

**Comment by UlricQin** [comment]
@jsers 这个浮动的div，前端有数量限制么？他这个意思是，实际应该展示56条

**Comment by jc1981** [comment]
是的，按实际的数据显示最好了

**Comment by jsers** [comment]
这里肯定还是需要有个限制的，目前会受限于图表的高度。
太多的条目对于可读性也是很差的，一般看个 top n 就够了，现在是根据 serie name 排序，后面可以加个针对 value 的排序。

**Comment by UlricQin** [comment]
能分页么

**Comment by UlricQin** [comment]
想了一下加分页有点太复杂， 还是按照value看topn是最合理的，如果要看所有，可以打开legend，看legend
