### ISSUE TITLE
是否支持滚动升级呢？或者升级方面有什么文档吗？

### ISSUE THREAD

**Issue by lincolnhuang** [didi/nightingale#209]
版本迭代比较快，上到线上可能会频繁升级，能否做到滚动升级呢？谢谢！

**Comment by UlricQin** [comment]
release页面可以看到各个版本升级的时候应该更新哪些组件，应该创建什么表结构。目前来看，配置和表结构都变更较少，只是多了一个plugin_collect表，如果从低版本过来的，直接把所有组件的二进制替换，增加这一个表结构即可。

**Comment by AlliotTech** [comment]
3.1.6 -> 3.3.0 需要往etc里新增2个tpl模板 不然tsdb起不来。
