### ISSUE TITLE
 ERROR rpc/push.go:74 send  too many col ons in address

### ISSUE THREAD

**Issue by panzhaohua** [didi/nightingale#21]
请问我用源码自己编译的，go version go1.12 linux/amd64。 运行起来总是报这个错误。too many colons in address。网上流传的加中括号方案会直接导致退出运行，请问各位有遇到我这个问题吗？

地址为默认，安装在一台服务器上面。
PS:
2020-03-24 10:50:36.972499 ERROR rpc/push.go:74 send [0xc00008cc30] to 
index addr:192.168.19.32:5831 fail: addr:192.168.19.32:5831 get connect
ion fail: conn <nil>, err address addr:192.168.19.32:5831: too many col
ons in address. proc: Name:addr:192.168.19.32:5831,Cnt:0,active:0,all:0
,free:0

**Comment by UlricQin** [comment]
judge、index、collector这三个组件的配置中有一条shell用来获取自身的ip地址，但是这个shell无法适配所有的环境，需要你这边根据自己的运行环境修改这个shell。

另外我刚完善了一下这个shell，可以匹配更多场景，你拉取最新的代码重新编译部署，即可解决
