### ISSUE TITLE
load毛刺

### ISSUE THREAD

**Issue by 397334469** [didi/nightingale#210]
load会有规律的出现毛刺
![image](https://user-images.githubusercontent.com/51410244/84454439-1a4f6b00-ac8d-11ea-9900-35a2e6ed9d92.png)
能否参考telegraf的collection_jitter做法，来消除呢

**Comment by UlricQin** [comment]
collection_jitter 是啥做法？你这个11点一次，18点一次，7个小时一次，是你自己的程序导致的，跟监控系统没啥关系哈。监控系统一般1min，或者20s一次。另外load才3，而且是瞬时的，基本可以忽略。3代表当时有3个process在被cpu处理，然后掉下来了，说明很快处理完了，不是啥大事

**Comment by 397334469** [comment]
这台服务器没有跑业务，只跑了collector。没有运行collector时，不会有毛刺。
跟https://zhuanlan.zhihu.com/p/53405837中的 三、一些坑一样，英文也有URL也有讨论过。

摘抄如下：
对于Redis宿主机load异常情况，主要是因为监控程序每1min生成很多进程采集一次数据， System Load采集则是每5.001s采集一次，当telegraf的第一次采集点命中System Load采集点后，第二次则需要5s*(5/0.001)=25000s，导致Load有规律每7小时飙高。

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"

**Comment by UlricQin** [comment]
现在collector的不同采集插件，不同采集函数已经拆了goroutine，并非同时触发。当然，同一个goroutine也会承担多个采集功能。所以在某一时刻有可能load略高。但是如你上图所示，所谓load毛刺也只有3左右，而且不持续，从OS层面看就是毛毛雨，不用关心

**Comment by 397334469** [comment]
这台服务是2C的，另外放大图来看，持续时间还是挺久的。就算知道这不是问题，看着也难受啊。

![image](https://user-images.githubusercontent.com/51410244/84461863-17aa4100-aca0-11ea-9a70-9153838424e2.png)

**Comment by UlricQin** [comment]
那排查一下真实原因吧，等下次7小时之后这个时间，看一下系统中到底是哪个进程引起的负载，同时用strace看看这个进程在干什么。你这个看图持续了5分钟，理论上不是collector引起的，collector采集撑死了1秒搞定

**Comment by 397334469** [comment]
确认过，开启了stra(enable: true)，会有规律的毛刺，设置为false，就不会。

**Comment by UlricQin** [comment]
还是之前说的，你这个看图持续了5分钟，是完全可以抓现场的，抓一下现场哈
