### ISSUE TITLE
在客户端报错module(collector) configuration section not found

### ISSUE THREAD

**Issue by macxiao** [didi/nightingale#212]
1.拉取源代码编译安装2.6.1
2.拷贝etc/address.yml etc/collector.yml  n9e-collector 到客户单
3.修改修改文件配置 到客户端的地址
4. ./n9e-collector 执行
日志如下：
2020/06/15 15:41:01 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
collector start, use configuration file: etc/collector.yml
runner.cwd: /home/tce/agent
2020/06/15 15:41:01 collector.go:72: endpoint: 192.168.8.245
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /api/collector/ping       --> github.com/didi/nightingale/src/modules/collector/http/routes.ping (1 handlers)
[GIN-debug] GET    /api/collector/pid        --> github.com/didi/nightingale/src/modules/collector/http/routes.pid (1 handlers)
[GIN-debug] GET    /api/collector/addr       --> github.com/didi/nightingale/src/modules/collector/http/routes.addr (1 handlers)
[GIN-debug] GET    /api/collector/stra       --> github.com/didi/nightingale/src/modules/collector/http/routes.getStrategy (1 handlers)
[GIN-debug] GET    /api/collector/cached     --> github.com/didi/nightingale/src/modules/collector/http/routes.getLogCached (1 handlers)
[GIN-debug] POST   /api/collector/push       --> github.com/didi/nightingale/src/modules/collector/http/routes.pushData (1 handlers)
[GIN-debug] GET    /api/collector/debug/pprof/ --> github.com/gin-contrib/pprof.pprofHandler.func1 (1 handlers)
[GIN-debug] GET    /api/collector/debug/pprof/cmdline --> github.com/gin-contrib/pprof.pprofHandler.func1 (1 handlers)
[GIN-debug] GET    /api/collector/debug/pprof/profile --> github.com/gin-contrib/pprof.pprofHandler.func1 (1 handlers)
[GIN-debug] POST   /api/collector/debug/pprof/symbol --> github.com/gin-contrib/pprof.pprofHandler.func1 (1 handlers)
[GIN-debug] GET    /api/collector/debug/pprof/symbol --> github.com/gin-contrib/pprof.pprofHandler.func1 (1 handlers)
[GIN-debug] GET    /api/collector/debug/pprof/trace --> github.com/gin-contrib/pprof.pprofHandler.func1 (1 handlers)
[GIN-debug] GET    /api/collector/debug/pprof/allocs --> github.com/gin-contrib/pprof.pprofHandler.func1 (1 handlers)
[GIN-debug] GET    /api/collector/debug/pprof/block --> github.com/gin-contrib/pprof.pprofHandler.func1 (1 handlers)
[GIN-debug] GET    /api/collector/debug/pprof/goroutine --> github.com/gin-contrib/pprof.pprofHandler.func1 (1 handlers)
[GIN-debug] GET    /api/collector/debug/pprof/heap --> github.com/gin-contrib/pprof.pprofHandler.func1 (1 handlers)
[GIN-debug] GET    /api/collector/debug/pprof/mutex --> github.com/gin-contrib/pprof.pprofHandler.func1 (1 handlers)
[GIN-debug] GET    /api/collector/debug/pprof/threadcreate --> github.com/gin-contrib/pprof.pprofHandler.func1 (1 handlers)
module(collector) configuration section not found

**Comment by chenjiandongx** [comment]
@macxiao 你是不是修改了 collector 的配置，从代码逻辑上来看，程序应该是读取到了 address.yml 的内容了，不然启动会直接失败。

https://github.com/didi/nightingale/blob/66d87e403d4ece835d77833da32e50940c513ae2/src/toolkits/address/address.go#L95

**Comment by macxiao** [comment]
是的，就是我的 address.yml 配置文件错了，感谢感谢
