### ISSUE TITLE
几个功能增强建议

### ISSUE THREAD

**Issue by w8589167** [didi/nightingale#215]
有几点小建议：
1：希望在后续版本中，加入用户可配置的，对多个指标的自定义计算，组合成新指标的功能，便于在web端自定义监控指标：如  进程平均cpu使用率=cup使用率/进程数  （只做举例 并无实际意义）
2：希望在后续版本中，加入指标的单位自定义，如百分比，M，G等，以应对第三方采集插件 采集的单位不统一的问题

**Comment by UlricQin** [comment]
1. 后续在做指标聚合的时候一并考虑
2. 单位这个不会加了，这个原因说起来比较复杂，后端时序数据库也是不会感知到单位的，推荐做法是把单位信息放到metric里，比如df.bytes.free，表示磁盘某个分区的剩余量，单位是byte
