### ISSUE TITLE
采集配置无法并存

### ISSUE THREAD

**Issue by jc1981** [didi/nightingale#216]
如图，我在上线节点joygames.mtj中添加了以下的配置
![image](https://user-images.githubusercontent.com/21353424/84848712-481a2280-b086-11ea-8ba9-80c0ab12c776.png)
而这个配置之前是在joygames.mtj.crossgame-server.release ,joygames.mtj.game-server.release joygames.mtj.other 中也是存在的，添加 joygames.mtj 配置后 ，这三个节点的数据都无法正常显示，而其它没有添加这配置的节点可以正常显示
![image](https://user-images.githubusercontent.com/21353424/84848954-c971b500-b086-11ea-9663-7c7eb109419b.png)
![image](https://user-images.githubusercontent.com/21353424/84848979-d7bfd100-b086-11ea-8d02-8e1aabaad07d.png)

**Comment by UlricQin** [comment]
预期的，现在没有覆盖逻辑，把子节点的配置删除吧。正常应该也不会这么用。
