### ISSUE TITLE
订阅图表上报数据太大导致数据库报错

### ISSUE THREAD

**Issue by matao3754** [didi/nightingale#217]
**What happened**:
当一个分组存在几百个endpoint时,在订阅该分组的其中2个endpoint时,会上报该分组下所有endpoint的信息,导致数据库的字段超限报错
<img width="678" alt="WechatIMG711" src="https://user-images.githubusercontent.com/16916249/84894746-dec10080-b0d3-11ea-927e-1a98edce5acb.png">
<img width="1428" alt="WechatIMG716" src="https://user-images.githubusercontent.com/16916249/84894758-e2ed1e00-b0d3-11ea-8110-1fbb5e475a44.png">

**Comment by UlricQin** [comment]
@jsers 看看？他实际需求只是想把两个endpoint放到graph里

**Comment by jsers** [comment]
fixed by this commit [https://github.com/didi/nightingale/commit/8375caaabaa2c3925ded6fbb730f70c3c75bb81a](url)
