### ISSUE TITLE
采集数据统计跨周期会不被统计

### ISSUE THREAD

**Issue by Summerdies** [didi/nightingale#218]
如图 ，我分别差入了3条数据，第一次插入一条数据，采集捕获到了一条，符合预期。
第二次连续插入两条，间隔零点几秒，只被采集捕获了一条数据，不符合预期。
采集周期设置的是10秒，分析如果因为是以每10秒为一个周期，统计30-40秒这个区间 显示 1条数据没问题，问题是 40-50 是不是也应该显示有一条数据。
总之就是插入了三条数据，却只采集到了两条数据，不理解为何丢弃了一条数据。
![image](https://user-images.githubusercontent.com/42688766/85021871-0df37280-b1a5-11ea-89fc-eedaae516f2a.png)
![image](https://user-images.githubusercontent.com/42688766/85022203-91ad5f00-b1a5-11ea-8a2d-779541f4237f.png)

**Comment by UlricQin** [comment]
@710leo 抽空看看吧

**Comment by UlricQin** [comment]
collector有报错日志么？ @Summerdies

**Comment by Summerdies** [comment]
> collector有报错日志么？ @Summerdies

没有报错日志

**Comment by UlricQin** [comment]
应该是这个bug导致的：https://github.com/didi/nightingale/commit/18ef32a34cb429137256fe28eb99c5a2b9c35819 用最新master代码试试，应该ok了
