### ISSUE TITLE
能否将Extra 字段 放到消息通知的内容里

### ISSUE THREAD

**Issue by Summerdies** [didi/nightingale#219]
如图这是目前消息结构，能否将 Extra 也放到里面，可以不用点详情即可看到Extra的具体内容
![image](https://user-images.githubusercontent.com/42688766/85026114-dc7da580-b1aa-11ea-91dc-f57ed952814d.png)
![image](https://user-images.githubusercontent.com/42688766/85026392-341c1100-b1ab-11ea-8b80-98ca6a7d6668.png)

**Comment by UlricQin** [comment]
extra是在历史数据表格里的，历史数据表格有时条数很多，内容太多，不适合放短信或即时通讯里

**Comment by Summerdies** [comment]
> extra是在历史数据表格里的，历史数据表格有时条数很多，内容太多，不适合放短信或即时通讯里

其实是想快速定位到底是什么样的错误日志，可否指点一下 从什么地方入手修改可以达到我说的效果，我在我本地调试下

**Comment by UlricQin** [comment]
extra信息在redis里是有的，从redis里pop出来数据之后，解析出extra信息发送即可
