### ISSUE TITLE
mac goland debug环境

### ISSUE THREAD

**Issue by spyvip** [didi/nightingale#22]
![image](https://user-images.githubusercontent.com/1212932/77383715-9b9a0e80-6dbe-11ea-853b-4cf8d6b0bc5d.png)

debug src/modules/collector/collector.go 说是找不到address.local.yml

**Comment by UlricQin** [comment]
你的运行环境里etc目录下没有address.yml，也没有address.local.yml，所以就启动失败了。

建议跟着视频一步一步操作：https://n9e.didiyun.com/docs/appendix/
