### ISSUE TITLE
监控看图模块中Legend功能增加Series列主机别名显示

### ISSUE THREAD

**Issue by nondevops** [didi/nightingale#222]
**What would you like to be added**:
监控看图模块中Legend功能增加Series列主机别名显示

**Why is this needed**:
从实际运用场景来看,一般不会太用心去记住一个IP地址,反而会用记住别名,可以更加快速的识别和搜索.当前在监控看图里只显示了主机IP,主机数量一旦成千上万,根本在此模块不能快速的辩解出这台机器是干嘛的,对排查问题和故障定位带来检索成本,从而导致故障恢复时长变长,不利于可用性目标维护
![image](https://user-images.githubusercontent.com/12181410/85115555-734f6e00-b24e-11ea-99bf-625f97ab788b.png)

**Comment by UlricQin** [comment]
collector的配置文件有个identify的配置，默认shell取得是机器ip，如果你们的机器名是不重复的，可以把获取identify的shell改成获取hostname的命令。至于看图时增加别名显示，产品上看也是合理的，只是现在没有精力搞这块，后面再看，如果很着急，建议撸一下代码提PR共建社区

**Comment by chenjiandongx** [comment]
@nondevops ，个人建议

1. 使用 shell 获取唯一标识直接上报。
```golang
type IdentitySection struct {
	Specify string `yaml:"specify"`
	Shell   string `yaml:"shell"`
}
```

2. 修改源码，将获取逻辑用编码的方式实现（高度定制化）

**Comment by UlricQin** [comment]
https://github.com/didi/nightingale/issues/158 在这个issue跟进，此issue关闭
