### ISSUE TITLE
监控看图模块取消双击监控指标生成相同的多个图表

### ISSUE THREAD

**Issue by nondevops** [didi/nightingale#223]
**What would you like to be added**:
监控看图模块取消双击监控指标生成相同的多个图表
**Why is this needed**:
现在所有的同一个指标,鼠标双击可以生成多个同一个监控指标的图表,个人觉得这样的功能并不实用(思考的比较肤浅,勿喷),应该没人会对同一个监控指标查看多个图表吧,而且这个页面一旦选择重复多个,其实对监控排查问题反而显得很复杂很杂乱.所以个人建议取消双击同一个指标可生成多个相同的图表,只需要一个就可以了.
![image](https://user-images.githubusercontent.com/12181410/85116067-50718980-b24f-11ea-9e27-4386f1b3c498.png)

**Comment by UlricQin** [comment]
有的时候看a指标，看完了之后又看了其他指标，此时突然举得a和b应该对比着看，此时应该再重新点击a指标和b指标，这样两个图会放一块。
如果你这边一个指标值看一次即可也没问题，看到+1了就说明有图了，就别点了就行了哈
