### ISSUE TITLE
指标列表分类模块增加用户自定义分类功能

### ISSUE THREAD

**Issue by nondevops** [didi/nightingale#226]
**What would you like to be added**:
指标列表分类功能,可以用户自定义分类
**Why is this needed**:
夜莺目前已支持exporter及自定义插件上报监控数据,上报的对象肯定不止一个两个,多则成千上万,按照目前设计归类,取的前缀归类法,自定义和第三方上报的数据则无法按照现有固定的分类方法进行自动归类,也就是会默认在全部这个选项卡里面,数据量多影响这个选项卡性能不说,对排查定位问题也增加了复杂度,所以,建议能让用自定义分类,灵活管控.
![image](https://user-images.githubusercontent.com/12181410/85364784-77cd9c80-b556-11ea-94e8-19ce17839c40.png)

**Comment by UlricQin** [comment]
产品上可以支持，前端好像有个配置文件，可以先直接修改那个配置文件。

**Comment by UlricQin** [comment]
清理历史遗留issue，如有问题，请reopen
