### ISSUE TITLE
2.7.0 版本下的 64位Linux可以下载编译好的包： n9e-2.7.0.tar.gz 链接失效

### ISSUE THREAD

**Issue by FrancisDrakeK** [didi/nightingale#228]
**What happened**:
![image](https://user-images.githubusercontent.com/42175430/85377600-e8cb7f00-b56b-11ea-8bdb-cda85c955631.png)

**Comment by UlricQin** [comment]
再试试

**Comment by FrancisDrakeK** [comment]
问题已解决
