### ISSUE TITLE
采集器名称取消相同名称保存

### ISSUE THREAD

**Issue by nondevops** [didi/nightingale#229]
**What would you like to be added**:
采集器名称取消相同名称保存
**Why is this needed**:
采集器名称可以重名,多个相同的采集器名称无法判断到底用的哪一个采集器,还得点进去一个一个筛查,增加使用复杂度,建议在保存时判断名称是否相同,如果相同,前端渲染提示修改采集器名称后再提交
![image](https://user-images.githubusercontent.com/12181410/85383039-1e736680-b572-11ea-8aff-f4dd3a0f799a.png)

**Comment by UlricQin** [comment]
这个有问题 @710leo 加个校验吧

**Comment by 710leo** [comment]
fix by this https://github.com/didi/nightingale/commit/d741f24e8c36d77434bbea606e343059fb255235
