### ISSUE TITLE
企业微信群机器人告警——求支持

### ISSUE THREAD

**Issue by adaiLinux** [didi/nightingale#23]
目前的微信告警太繁琐了，直接使用机器人token会方便很多。如果可以在UI进行配置and支持配置告警模板，那就更好了

**Comment by UlricQin** [comment]
你是看的wechat-sender么？部署这个sender，然后在用户信息的IM字段填写企业微信的用户账号即可

**Comment by adaiLinux** [comment]
> 你是看的 https://github.com/n9e/wechat-sender 么？部署这个sender，然后在用户信息的IM字段填写企业微信的用户账号即可。而且wechat-sender支持告警模板

想直接使用微信群机器人token来做标识，省去coreID等配置

**Comment by adaiLinux** [comment]
> 你是看的 https://github.com/n9e/wechat-sender 么？部署这个sender，然后在用户信息的IM字段填写企业微信的用户账号即可。而且wechat-sender支持告警模板

同  issue 告警群组优化 #20

**Comment by UlricQin** [comment]
#20 我关了，不需要在team上新增字段，只要创建虚拟user即可，虚拟user的im字段放置你说的token，和wechat-sender的区别是配置方式略有差异，这个issue开放一个月，希望社区同仁来出力建设这种方式，同时看一下社区的反馈，看是否必须要上这种方式的微信告警

**Comment by SupersunnySea** [comment]
> #20 我关了，不需要在team上新增字段，只要创建虚拟user即可，虚拟user的im字段放置你说的token，和wechat-sender的区别是配置方式略有差异，这个issue开放一个月，希望社区同仁来出力建设这种方式，同时看一下社区的反馈，看是否必须要上这种方式的微信告警，如果大家觉得没有必要或者没人关注这个，到时候再关闭。
> 
> 谁有兴趣来做这个token的处理方式，欢迎在下面留言哈

类似wechat-sender重开一个项目吗

**Comment by UlricQin** [comment]
@SupersunnySea 嗯，有兴趣写一个？可以类似wechat-sender那样搞一个新的repo

**Comment by SupersunnySea** [comment]
> @SupersunnySea 嗯，有兴趣写一个？可以类似wechat-sender那样搞一个新的repo

好的，我试试啊

**Comment by SupersunnySea** [comment]
> @SupersunnySea 嗯，有兴趣写一个？可以类似wechat-sender那样搞一个新的repo

请问一下，怎么push到n9e那个group呢？新手

**Comment by UlricQin** [comment]
> > @SupersunnySea 嗯，有兴趣写一个？可以类似wechat-sender那样搞一个新的repo
> 
> 请问一下，怎么push到n9e那个group呢？新手

已经写完了？repo叫什么？我给你创建一个

**Comment by SupersunnySea** [comment]
> > > @SupersunnySea 嗯，有兴趣写一个？可以类似wechat-sender那样搞一个新的repo
> > 
> > 
> > 请问一下，怎么push到n9e那个group呢？新手
> 
> 已经写完了？repo叫什么？我给你创建一个

wechatrobot-sender

**Comment by UlricQin** [comment]
@SupersunnySea 已创建n9e/wechatrobot-sender，直接提交代码即可哈，这个issue我就关了

**Comment by SupersunnySea** [comment]
> @SupersunnySea 已创建n9e/wechatrobot-sender，给你发起邀请了，你这边接受一下，然后直接提交代码即可哈，这个issue我就关了

不好意思，第一次向组织贡献代码，我貌似没收到邀请，或者是哪里能看到邀请呢？

**Comment by UlricQin** [comment]
> > @SupersunnySea 已创建n9e/wechatrobot-sender，给你发起邀请了，你这边接受一下，然后直接提交代码即可哈，这个issue我就关了
> 
> 不好意思，第一次向组织贡献代码，我貌似没收到邀请，或者是哪里能看到邀请呢？

注册github的邮箱，还有github右上角有个notification

**Comment by SupersunnySea** [comment]
> > > @SupersunnySea 已创建n9e/wechatrobot-sender，给你发起邀请了，你这边接受一下，然后直接提交代码即可哈，这个issue我就关了
> > 
> > 
> > 不好意思，第一次向组织贡献代码，我貌似没收到邀请，或者是哪里能看到邀请呢？
> 
> 注册github的邮箱，还有github右上角有个notification

我还是没有从notification里找到邀请，能否把邀请链接发出来一下，多谢
![image](https://user-images.githubusercontent.com/18416672/78038043-ead3d680-739e-11ea-877b-98cb19ce395e.png)

**Comment by UlricQin** [comment]
> > > > @SupersunnySea 已创建n9e/wechatrobot-sender，给你发起邀请了，你这边接受一下，然后直接提交代码即可哈，这个issue我就关了
> > > 
> > > 
> > > 不好意思，第一次向组织贡献代码，我貌似没收到邀请，或者是哪里能看到邀请呢？
> > 
> > 
> > 注册github的邮箱，还有github右上角有个notification
> 
> 我还是没有从notification里找到邀请，能否把邀请链接发出来一下，多谢
> ![image](https://user-images.githubusercontent.com/18416672/78038043-ead3d680-739e-11ea-877b-98cb19ce395e.png)

邮箱里呢

**Comment by UlricQin** [comment]
![image](https://user-images.githubusercontent.com/2769466/78039159-536f8300-73a0-11ea-9f6d-47635c9e033a.png)

@SupersunnySea

**Comment by UlricQin** [comment]
不行就提PR吧：https://github.com/n9e/wechatrobot-sender @SupersunnySea

**Comment by SupersunnySea** [comment]
> 不行就提PR吧，或者你直接访问这个地址应该有提示：https://github.com/n9e/wechatrobot-sender @SupersunnySea

没有提示，我提pr，多谢

**Comment by adaiLinux** [comment]
> > 不行就提PR吧，或者你直接访问这个地址应该有提示：https://github.com/n9e/wechatrobot-sender @SupersunnySea
> 
> 没有提示，我提pr，多谢

👍
