### ISSUE TITLE
调用API修改监控对象别名未生效

### ISSUE THREAD

**Issue by weizhenqian** [didi/nightingale#230]
我调用修改别名的API，返回的结果是{"err":""}。但是在web端查看修改好像没生效，监控对象的ID也是通过夜莺的接口获取的。
![image](https://user-images.githubusercontent.com/27806578/85490782-f84ad680-b604-11ea-8e76-1eea77c0dcc1.png)
![image](https://user-images.githubusercontent.com/27806578/85490835-11538780-b605-11ea-8652-1a050e467002.png)

**Comment by UlricQin** [comment]
是没有加 -H "Content-Type: application/json" ?

**Comment by weizhenqian** [comment]
> 是没有加 -H "Content-Type: application/json" ?

是这个问题，已经解决了，感谢
