### ISSUE TITLE
监控数据丢失问题

### ISSUE THREAD

**Issue by 84372051** [didi/nightingale#231]
![image](https://user-images.githubusercontent.com/45719547/85495616-76ab7680-b60d-11ea-825c-cfb1c2d5123b.png)
![image](https://user-images.githubusercontent.com/45719547/85495762-ba9e7b80-b60d-11ea-9623-5fccd220f6e0.png)

tsdb日志无报错，transfer的DEBUG日志显示正常，但是搜索不到数据，报警设为nodata也会触发，有时候agent.alive也会发生相同现象，日志无异常，客户端无异常，触发nodata报警，但是cpu和disk等别的数据却一直正常更新和查看

**Comment by UlricQin** [comment]
index部署了几个实例？调用一下index的 /api/index/index-total返回什么？
调用一下tsdb的 /api/tsdb/update-index 之后指标是否可以看到？此时再调用index的 /api/index/index-total返回什么？

**Comment by 84372051** [comment]
![image](https://user-images.githubusercontent.com/45719547/85935755-bbddea00-b926-11ea-8f9e-25d1727a2985.png)
![image](https://user-images.githubusercontent.com/45719547/85935761-c5ffe880-b926-11ea-86fb-4b39ff8972b5.png)
![image](https://user-images.githubusercontent.com/45719547/85935764-ca2c0600-b926-11ea-88e2-2f3638e2fc64.png)
![image](https://user-images.githubusercontent.com/45719547/85935787-ff385880-b926-11ea-9e67-44e458221b60.png)

感觉执行以后，正常了，之前查不到数据的那个时间段，现在也能查到了

**Comment by UlricQin** [comment]
那再观察一下，你这个指标是周期性上报的么？多久上报一次

**Comment by 84372051** [comment]
周期性上报的，每120秒上报一次，有时候agent.alive也会在搜索列表里搜不到，然后报nodata报警了，但是看cpu和disk等指标还一直在上报且可查到，现在调用完上面的方法暂时正常了

**Comment by UlricQin** [comment]
那观察一天，正常索引失效时间是一天，只要有数据持续上报，索引就不会失效

**Comment by orcswang-lang** [comment]
我这边也偶尔出现index丢失问题,两台index的index-total接口返回的值不一致，导致nodata报警.

**Comment by UlricQin** [comment]
> 我这边也偶尔出现index丢失问题,两台index的index-total接口返回的值不一致，导致nodata报警.

丢失的指标都是什么样的指标？有规律么？这些指标是周期性上报的么？是collector默认采集的那些指标？

**Comment by UlricQin** [comment]
另外tsdb模块看看有没有报错

**Comment by orcswang-lang** [comment]
丢失的指标没有规律性,tsdb也没有报警，经过几天的观察,这种情况目前只在生产环境出现,测试环境没发现。两个环境指tranfser接收量相差3倍

**Comment by orcswang-lang** [comment]
目前测试环境和生产环境均是两台transfer/tsdb/index/monapi/judge

**Comment by UlricQin** [comment]
更新到2.7.2版本试试

**Comment by youtwo123** [comment]
我更新到2.7.2版本，暂时看可以解决，🐂🐂🐂🐂
