### ISSUE TITLE
judge启动后一直有warning日志

### ISSUE THREAD

**Issue by AstonPudding** [didi/nightingale#232]
judge的warning日志内容：
2020-06-26 23:24:50.404522 WARNING judge/judge.go:307 query index err:empty index addr

单机部署的，其它模块都没有war或err日志，只有judge有war日志。
上面这个内容每10秒就报一次，一直没停过，judge开了debug后也没看出有异常信息，请求帮助。

**Comment by 710leo** [comment]
感谢反馈，这里有点问题，最新代码已经修复了，你在重新拉取下最新的代码试试

**Comment by AstonPudding** [comment]
问题解决了，感谢~
