### ISSUE TITLE
报警功能异常

### ISSUE THREAD

**Issue by levywang** [didi/nightingale#233]
机器指标异常，报警策略也设置了，但是在报警历史里面没有数据，没有发出警告。
查询logs下面的各个日志，没有ERROR日志，judge模块有WARNING日志。
重复一直报错内容如下：
`judge.go:307 query index err:empty index addr`

请问我是哪个环境没配置好吗？谢谢解答

**Comment by 710leo** [comment]
升级到最新的代码即可解决

**Comment by levywang** [comment]
> 升级到最新的代码即可解决

你好，我已经用的最新的2.7.0版本

**Comment by 710leo** [comment]
用master分支最新的代码吧，稍后我们会发布一个新版本

**Comment by levywang** [comment]
> 用master分支最新的代码吧，稍后我们会发布一个新版本

这是n9e自身的bug吗？

**Comment by 710leo** [comment]
是 2.7.0 引入的问题，2.7.1 已经发布，可以用 2.7.1 的版本
