### ISSUE TITLE
说两句实话就被踢，求入群，我还想奉献

### ISSUE THREAD

**Issue by ermazi** [didi/nightingale#234]

**Comment by UlricQin** [comment]
说的啥？被谁踢了？

**Comment by ermazi** [comment]
小助手，我就说排版乱啊，没毛病，事实啊

**Comment by ermazi** [comment]
> 说的啥？被谁踢了？

偷偷修正了，然后把我踢了，这就是大厂气度吗？

**Comment by ermazi** [comment]
> 说的啥？被谁踢了？

说实话，你自己去看看这文章的质量，像是一个专业云厂商写出来的东西吗，不吹不黑，我都看不下去https://zhuanlan.zhihu.com/p/150349656?utm_source=wechat_session&utm_medium=social&utm_oi=635054145552519168&utm_content=sec
