### ISSUE TITLE
monapi Unknown column 'stdin' in 'field list'

### ISSUE THREAD

**Issue by 1029649360** [didi/nightingale#235]
**What happened**:

单机部署，今天上午拉的最新代码

monapi ：
![image](https://user-images.githubusercontent.com/45092668/85950646-a43b4b80-b990-11ea-976f-b7260bf91f75.png)

![image](https://user-images.githubusercontent.com/45092668/85950654-ab625980-b990-11ea-8c46-ea634f21a768.png)

![image](https://user-images.githubusercontent.com/45092668/85950670-bb7a3900-b990-11ea-983b-758dc65c36c2.png)
 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OS (e.g: `cat /etc/os-release`):
- Logs:
- Others:

**Comment by UlricQin** [comment]
https://github.com/didi/nightingale/blob/master/sql/upgrade_2.3.0.sql 需要把这个sql导入
