### ISSUE TITLE
怎么支持短信报警和电话报警

### ISSUE THREAD

**Issue by leezer3379** [didi/nightingale#236]
目前支持电话报警和短信报警吗？
使用什么方法支持呢

**Comment by UlricQin** [comment]
不支持。目前支持邮件、钉钉、微信告警，相关发送模块在这里：https://github.com/n9e 。可以仿照wechat-sender去写一个sms-sender和voice-sender。之所以没有提供电话和短信的sender是因为电话短信通道各异，没有标准；另外也是希望社区共建。

**Comment by leezer3379** [comment]
嗯嗯，发现一个问题，普通用户上来后权限过大，可以随意删除主机和报警策略，然后主机就得手动添加了，好蛋疼

**Comment by UlricQin** [comment]
权限这块，开源版本确实比较简陋，商业版本会非常完善。主机删除这个，后面会在开源版本里做个小功能，找回误删的endpoint
