### ISSUE TITLE
docker-compose无法正常部署

### ISSUE THREAD

**Issue by blank-1** [didi/nightingale#240]
**What happened**:
![image](https://user-images.githubusercontent.com/30788027/86460681-64db7900-bd5b-11ea-961f-6a4053f4f585.png)

**What you expected to happen**:
![image](https://user-images.githubusercontent.com/30788027/86460736-8177b100-bd5b-11ea-8af0-94d60b6a3d59.png)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OS (e.g: `cat /etc/os-release`):
mac os
- Logs:
![image](https://user-images.githubusercontent.com/30788027/86460871-b71c9a00-bd5b-11ea-8f1a-df8d3611d2ed.png)

- Others:
![image](https://user-images.githubusercontent.com/30788027/86460962-dfa49400-bd5b-11ea-9812-3b5f06ed80fc.png)

**Comment by UlricQin** [comment]
用linux哈

**Comment by blank-1** [comment]
官方镜像不能提供吗？docker-compose快速部署不行，太尴尬。。

**Comment by x554462** [comment]
可以试试将vendor/github.com/open-falcon/rrdlite/rrd_c.go的下面这行
`#cgo linux CFLAGS: -std=c99 -DRRD_LITE -D_BSD_SOURCE -DHAVE_CONFIG_H -D_POSIX_SOURCE -DNUMVERS=1.4009 -D_LINUX_OS`
改成
`#cgo linux CFLAGS: -std=c99 -DRRD_LITE -D_DEFAULT_SOURCE -DHAVE_CONFIG_H -D_POSIX_SOURCE -DNUMVERS=1.4009 -D_LINUX_OS`
然后重新build一下

**Comment by blank-1** [comment]
建议搞个docker官方镜像，一键快速部署，不香吗？n9e本身部署特别麻烦，加之容器化必然趋势，往回走，不好吧！！

**Comment by UlricQin** [comment]
抱歉啊，我们也不是全能，对如何制作Docker一键镜像不熟悉，现在的Docker镜像也是社区里的人贡献的。您如果感兴趣，是否可以贡献PR一起共建社区呢？

**Comment by blank-1** [comment]
先看下结构，提个pr吧

**Comment by UlricQin** [comment]
https://github.com/didi/nightingale/tree/master/dockerfiles 感谢 @yimeng 提供docker-compose相关配置文件，v3可以跑通
