### ISSUE TITLE
端口和进程采集异常

### ISSUE THREAD

**Issue by 1029649360** [didi/nightingale#241]
**What happened**:
端口采集和进程采集配置完，不能正常显示指标。只有这一个节点下面的配置有问题，其他节点正常

![image](https://user-images.githubusercontent.com/45092668/86513097-f4575980-be39-11ea-896b-c4ffc14c1123.png)

![image](https://user-images.githubusercontent.com/45092668/86513103-ff11ee80-be39-11ea-9ee6-d0c801893352.png)

tsdb中报错如下：
![image](https://user-images.githubusercontent.com/45092668/86513108-089b5680-be3a-11ea-9e13-fcbafe2ac3f3.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OS (e.g: `cat /etc/os-release`): Centos 7
- Logs:
- Others:

**Comment by UlricQin** [comment]
命令行那个字段只填写zookeeper即可

**Comment by 1029649360** [comment]
刚才删除了原来的采集规则，按照您说的新建了一个，现在可以了。
但是，我看您的讲解视频，命令行的采集方式填写的/proc/<pid>/cmdline内容的全部或一部分。并且另外一个节点是这么配置的就没有问题。

**Comment by UlricQin** [comment]
的确如此，填写的内容会作为target=xxxx的value部分，作为tag的value，不希望里边有特殊字符

**Comment by 1029649360** [comment]
好的明白了，感谢！！！
