### ISSUE TITLE
collect端口问题

### ISSUE THREAD

**Issue by NovemberCap** [didi/nightingale#243]
collect能否固定为一定端口，方便防火墙开通策略

**Comment by UlricQin** [comment]
collector的监听端口是固定的，连接服务端的临时端口是无法固定的，一般防火墙策略不是配置在客户端的临时端口，一般是开放服务端的端口

**Comment by NovemberCap** [comment]
好的谢谢



 
发件人： ulricqin
发送时间： 2020-07-09 10:11
收件人： didi/nightingale
抄送： NovemberCap; Author
主题： Re: [didi/nightingale] collect端口问题 (#243)
collector的监听端口是固定的，连接服务端的临时端口是无法固定的，一般防火墙策略不是配置在客户端的临时端口，一般是开放服务端的端口
