### ISSUE TITLE
服务树项目较多时，查看右侧信息存在用户体验问题。

### ISSUE THREAD

**Issue by yimeng** [didi/nightingale#245]
服务树项目较多 最下面的子节点A B C D
点击A的时候，右边的详情页上面就看不到了。需要再次上滚去查看。
然后又想关注B，又要下滚让服务树能看到B C D。点击，然后再次上滚看详情。

反反复复~~~有点影响用户体验，希望能否解决。比如：
1 服务树和右边详情分开滚动。
2 突出我关注的服务树节点？

**Comment by UlricQin** [comment]
辛苦看看服务树那个DIV能否单独滚动？  @jsers

**Comment by UlricQin** [comment]
v3应该是这样的了
