### ISSUE TITLE
agent标识无法动态刷新

### ISSUE THREAD

**Issue by 84372051** [didi/nightingale#249]
![image](https://user-images.githubusercontent.com/45719547/87264323-48c19f80-c4f2-11ea-9972-40266075a949.png)

![image](https://user-images.githubusercontent.com/45719547/87264360-60008d00-c4f2-11ea-9d80-e18c7ce1cc2e.png)
![image](https://user-images.githubusercontent.com/45719547/87264578-f6cd4980-c4f2-11ea-8656-6f2810a6bec0.png)

如图，标识是通过hostname命令获取的，但是由于虚机克隆改名，agent的标识不会刷新为新的主机名，造成很多机器标识冲突，客户端数据拿不到，只有重启服务器或者重启agent才能解决，是否可以更改agent标识为动态更新

**Comment by UlricQin** [comment]
agent有时扮演了一个转发角色，一些自定义采集器或者插件采集到监控数据之后通过agent转发给服务端，这就意味着，endpoint这个字段会非常频繁的使用，如果不缓存在内存里每次动态获取，会造成机器负载飙高，故而，目前的决策是不准备做成动态更新的

**Comment by 84372051** [comment]
大佬有方法可以在不重启的情况下手动刷新标识呢？标识经常变化的，频繁批量重启风险太高

**Comment by UlricQin** [comment]
所谓的标识就应该是不能随便变化的，如果变化了，我们就认为是一个新机器了
