### ISSUE TITLE
图表聚合问题

### ISSUE THREAD

**Issue by dup2X** [didi/nightingale#25]
假如有endpoint、url、code三个tagk。
我需要根据url来group == 聚合，没生效。
1、结果没根据url来聚合
2、曲线的Legend也没对应更新

**Comment by UlricQin** [comment]
@dup2X 截个图啥的，提供点更详细的信息
@710leo 瞧瞧这个问题

**Comment by 710leo** [comment]
@dup2X @UlricQin  fix by this  [commit](https://github.com/didi/nightingale/commit/a047f19ba37bfdcf383921acfbf0df999cc487e5 )
