### ISSUE TITLE
报警消息过期配置-待认领

### ISSUE THREAD

**Issue by NovemberCap** [didi/nightingale#251]
关闭邮件报警和微信报警，重新打开之后，如果之前有积累的报警消息，就会一瞬间出来特别多的报警消息
建议：
    添加一个报警消息的过期时间设置，超过一定时间，就不发送消息

**Comment by UlricQin** [comment]
从产品上这个配置可以做，提个PR吧 :)

**Comment by libincla** [comment]
+1, 遇到了类似的问题

**Comment by xupeng9** [comment]
请问同种类型报警信息较多的话，现在不能合并了吗？ @UlricQin

**Comment by UlricQin** [comment]
> 请问同种类型报警信息较多的话，现在不能合并了吗？ @UlricQin

v3支持，v2不支持

**Comment by xupeng9** [comment]
> > 请问同种类型报警信息较多的话，现在不能合并了吗？ @UlricQin
> 
> v3支持，v2不支持

OK，谢谢！

**Comment by UlricQin** [comment]
清理历史遗留issue，如有问题，请reopen
