### ISSUE TITLE
前端代码和后端部署在不同服务器访问不了

### ISSUE THREAD

**Issue by xf1688** [didi/nightingale#252]
1.有跨域
2.处理1后发觉，后端基本用户验证都是通过 sesstion处理，前后端分离了自然拿不到

为什么前端使用react了，后端服务还要通过cookies sesstion这种方式处理。
有好办法不用大改后端的方法麻烦也告知下。

**Comment by UlricQin** [comment]
前后端用一个nginx来做代理，etc目录下有nginx.conf供参考
