### ISSUE TITLE
collector 启动失败

### ISSUE THREAD

**Issue by ldtec** [didi/nightingale#253]
**What happened**:
启动方式：源码启动
启动了collector，却没有对象，后来查了collector日志，发现有报错
![image](https://user-images.githubusercontent.com/9960347/87489035-877f6300-c674-11ea-9e30-ce0b04e0c2ec.png)

**Anything else we need to know?**:
collector的ERROR日志
root@ubuntu:~/nightingale/gopath/src/github.com/didi/Nightingale/logs/collector# ll
total 19028
drwxr-xr-x 2 root root    4096 Jul 15 08:00 ./
drwxr-xr-x 8 root root    4096 Jul 14 15:01 ../
-rw-r--r-- 1 root root       0 Jul 15 08:00 DEBUG.log
-rw-r--r-- 1 root root       0 Jul 15 06:00 DEBUG.log.2020071506
-rw-r--r-- 1 root root       0 Jul 15 07:00 DEBUG.log.2020071507
-rw-r--r-- 1 root root   59976 Jul 15 08:25 ERROR.log
-rw-r--r-- 1 root root  141120 Jul 15 06:59 ERROR.log.2020071506
-rw-r--r-- 1 root root  141120 Jul 15 07:59 ERROR.log.2020071507
-rw-r--r-- 1 root root       0 Jul 15 08:00 FATAL.log
-rw-r--r-- 1 root root       0 Jul 15 06:00 FATAL.log.2020071506
-rw-r--r-- 1 root root       0 Jul 15 07:00 FATAL.log.2020071507
-rw-r--r-- 1 root root       0 Jul 15 08:00 INFO.log
-rw-r--r-- 1 root root       0 Jul 15 06:00 INFO.log.2020071506
-rw-r--r-- 1 root root       0 Jul 15 07:00 INFO.log.2020071507
-rw-r--r-- 1 root root 3248696 Jul 15 08:25 WARNING.log
-rw-r--r-- 1 root root 7598792 Jul 15 07:00 WARNING.log.2020071506
-rw-r--r-- 1 root root 7598606 Jul 15 08:00 WARNING.log.2020071507
-rw-r--r-- 1 root root  650671 Jul 15 08:25 stdout.log

cat ERROR.log返回结果
ifconfig: `--help' gives usage information. failed, error:parse "http://127.0.0.1:5800/api/portal/collects/wlan0: Host name lookup failure\nifconfig: `--help' gives usage information.": net/url: invalid control character in URL
2020-07-15 08:16:33.302932 ERROR stra/cron.go:36 get collect err:get collects from remote:http://127.0.0.1:5800/api/portal/collects/wlan0: Host name lookup failure
ifconfig: `--help' gives usage information. failed, error:parse "http://127.0.0.1:5800/api/portal/collects/wlan0: Host name lookup failure\nifconfig: `--help' gives usage information.": net/url: invalid control character in URL

另外我curl了下这个地址，返回结果如图
root@ubuntu:~/nightingale/gopath/src/github.com/didi/Nightingale/logs/collector# curl -vvv http://127.0.0.1:5800/api/portal/collects/wlan0
*   Trying 127.0.0.1:5800...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 5800 (#0)
> GET /api/portal/collects/wlan0 HTTP/1.1
> Host: 127.0.0.1:5800
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Date: Wed, 15 Jul 2020 00:28:44 GMT
< Content-Length: 22
< 
{"dat":null,"err":""}
* Connection #0 to host 127.0.0.1 left intact

**Environment**: 
- OS (e.g: `cat /etc/os-release`):

NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

- Others:

**Comment by UlricQin** [comment]
collector里边有个identity的配置，默认配置了一条shell，collector是用这个shell来获取本机ip，需要保证这个shell可用，你的报错来看是缺少了net-tools库，导致一些命令没有，安装一下哈

**Comment by ldtec** [comment]
多谢您的回复
之前是提示我route 命令 command not found ，后来我装了net-tools，装了之后，就是提示现在这个错

我重新执行安装，已经提示我安装过了
ubuntu@ubuntu:~$ sudo -i
root@ubuntu:~# sudo apt install net-tools
Reading package lists... Done
Building dependency tree       
Reading state information... Done
net-tools is already the newest version (1.60+git20180626.aebd88e-1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.

**Comment by ldtec** [comment]
> collector里边有个identity的配置，默认配置了一条shell，collector是用这个shell来获取本机ip，需要保证这个shell可用，你的报错来看是缺少了net-tools库，导致一些命令没有，安装一下哈

多谢您的回复
之前是提示我route 命令 command not found ，后来我装了net-tools，装了之后，就是提示现在这个错，应该不是net-tools的问题

我重新执行安装，已经提示我安装过了
ubuntu@ubuntu:$ sudo -i
root@ubuntu:# sudo apt install net-tools
Reading package lists... Done
Building dependency tree
Reading state information... Done
net-tools is already the newest version (1.60+git20180626.aebd88e-1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.

**Comment by UlricQin** [comment]
collector.yml里的那条shell未必适配你的环境，你要自己配一个合适的shell（能够获取本机ip的）上去

**Comment by ldtec** [comment]
> collector.yml里的那条shell未必适配你的环境，你要自己配一个合适的shell（能够获取本机ip的）上去

多谢，按照您的提示，修改了shell，collector已经启动成功。
另外全部对象那里还是不显示，我手动导入了192.168.0.188【我的ip】的endpoint，有指标显示了。

有个疑问是 endpoint 不能自动显示吗？
