### ISSUE TITLE
日志监控采集支持使用通配符或正则来匹配多个日志文件-待认领

### ISSUE THREAD

**Issue by libincla** [didi/nightingale#254]
### 建议

您好，在日志采集-日志路径，以后可否能考虑支持日志文件名的通配呢？
```
如您官网所示，目前只是支持日志末尾自带时间格式，例如 /path/access.log.${%Y%m%d%H}
```
比如收集`nginx`日志，有些`nginx`会担任`proxy`角色，服务器上也会有多个不同名称的日志文件。此时使用`n9e`自带的日志采集只能配置多个采集项，不便于迁移到其他节点上。

希望您能予以采纳，多谢。

**Comment by UlricQin** [comment]
从产品功能上来看，这个功能可以支持，我把标题改成待认领，希望社区同仁能够贡献PR

**Comment by leezer3379** [comment]
每个文件名直接打个标签？

**Comment by UlricQin** [comment]
> 每个文件名直接打个标签？

如果是日期作为后缀，每个小时一个日志文件，会有很多日志文件，tag会约来越多，最终压垮index

**Comment by UlricQin** [comment]
清理历史遗留issue，如有问题，请reopen
