### ISSUE TITLE
collector收集磁盘读写导致业务报错

### ISSUE THREAD

**Issue by sunyu129** [didi/nightingale#255]
**What happened**:
collector组件会占用磁盘，导致通过代码进行磁盘解挂的时候，磁盘busy，后续必须手动关闭collector卸载磁盘。
![image](https://user-images.githubusercontent.com/54071226/87736281-4f118d80-c80a-11ea-8c30-21a360b2e4d2.png)

**Comment by sunyu129** [comment]
![image](https://user-images.githubusercontent.com/54071226/87736357-7cf6d200-c80a-11ea-9784-8d2364b3b215.png)

**Comment by UlricQin** [comment]
升级到最新版，ignore掉/var/lib看看效果
