### ISSUE TITLE
报警策略配置 条件1且条件2 触发，发现了一些问题 ，望大神看下

### ISSUE THREAD

**Issue by Summerdies** [didi/nightingale#256]
1.报警详情页只显示一条曲线
![image](https://user-images.githubusercontent.com/42688766/87745390-5ba0e080-c820-11ea-86fc-7e056e7277ba.png)
2.时间点并不一致，如画圈的两个点，并不是同一个时间轴的，期望是 同一个时间的两个点满足条件才报警，
![image](https://user-images.githubusercontent.com/42688766/87745443-7e32f980-c820-11ea-95b2-713c9c85edfc.png)
报警策略如下
![image](https://user-images.githubusercontent.com/42688766/87745542-be927780-c820-11ea-8992-faf0adbe33f0.png)

**Comment by UlricQin** [comment]
这两个尖相差多久

**Comment by Summerdies** [comment]
![image](https://user-images.githubusercontent.com/42688766/88009361-e77a7b80-cb44-11ea-8946-36b5447ea992.png)
![image](https://user-images.githubusercontent.com/42688766/88009376-ef3a2000-cb44-11ea-9843-d19d6f94605e.png)
比如这个，查了得有 7 8 分钟了，这个时间不一定，有的一两分钟

**Comment by 710leo** [comment]
@Summerdies 这两个指标的上报周期都是多少呢？60s？

**Comment by Summerdies** [comment]
> @Summerdies 这两个指标的上报周期都是多少呢？60s？

都是60秒

**Comment by UlricQin** [comment]
清理历史遗留issue，如有问题，请reopen
