### ISSUE TITLE
关于数据存储时限

### ISSUE THREAD

**Issue by AstonPudding** [didi/nightingale#257]
以下是文档中tsdb默认的存储时长配置
rrd:
  rra:
    1:    720   # 存储720个原始点
    6:    4320  # 6点个归档为一个点，保存4320个点
    180:  1440  # 180个点归档为一个点，保存1440个点
    1080: 2880  # 1080个点归档为一个点，保存2880个点

关于这个配置我有几个问题：
1、rrd下面的这些配置是默认的，是不是可写可不写
2、我配置的采集上报周期为20秒，我想把存储时长改为两个月，配置是否如下
   rrd:
     rra:
       1:    720
       6:    4320
       180:  1440
3、采集器的上报周期为20秒，但是插件的采集周期会有10秒或者30秒的，存储时长改为两个月的配置是否还是和上面的一样

**Comment by UlricQin** [comment]
1，可写可不写
2，你这是3个归档策略，20秒一个点，只要计算20秒×1440就存储时长
3，所有的指标都是一个归档策略，10秒采集频率的话，存储时长就是10秒×1440

**Comment by wangwei0326** [comment]
想存储1天的原始点，采集周期是10s，在tsdb.yml中的配置是
rrd:
  storage: data/8011
  rra:
    1:  8640
    6:  4320
    180: 1440
    1080: 2880
重启服务后查看2个小时之前的监控数据，还是被归档了。这个要如何配置解决？

**Comment by UlricQin** [comment]
变更了rra，需要stop tsdb，清空历史数据，即tsdb对应的data目录下的数据，然后重启tsdb。如果想存储原始数据建议是用m3的方案，文档里有写如何对接m3
