### ISSUE TITLE
希望在后续版本报警条件中加入可以对同一个指标进行与或操作

### ISSUE THREAD

**Issue by w8589167** [didi/nightingale#260]
**What would you like to be added**:
希望在后续版本报警条件中加入可以对同一个指标进行与或操作
![image](https://user-images.githubusercontent.com/29417610/88000612-a4aea880-cb30-11ea-956d-b72b2f51bef7.png)
并加入条件组合功能，自由的与 或组合，而不是目前的 只能与，并且只能两个条件
**Why is this needed**:
原因：报警，是一个监控系统的核心功能，重中之重，精确的报警能减少运维人员的工作量，提升用户体验。
夜莺在报警方面功能相对比较弱，如我上次issues中提到的，不支持指标聚合，多指标计算出新指标，以及条件与或，导致用户在使用时只能按照夜莺内置的指标值进行报警策略设置，自由度极低且不准确
如截图中的交换机端口up down判断中，up为1 down为2，若果只判断等于2时报警，那会导致未插线的端口也进行报警；如果只用diff函数判断当新值-上次值=1时报警 ，那ifstatus的所有值中 有多种相减结果等于1时的组合，显然也不够精准。最精准的方式就是当ifstatus=2  且  ifstatus（本次）-上次=1 同时触发，才触发端口报警，这样相对准确。
上述例子只是其中一应用场景，如果接受了我上述建议，夜莺的报警将会更加准确、完善
祝夜莺越做越好

**Comment by 710leo** [comment]
后端目前是支持同一个指标与条件告警的， @jsers 前端可以放开这个限制

**Comment by w8589167** [comment]
@jsers 前端可以放开这个限制

**Comment by w8589167** [comment]
除此之外 在后续版本 期望加入多条件与或   目前是只能两个条件的与
