### ISSUE TITLE
是否可以增加针对cpu.load和和cpu核数的报警？

### ISSUE THREAD

**Issue by walnut-tom** [didi/nightingale#261]
**What would you like to be added**:
cpu.load >= cpu.core
cpu.load >= cpu.core * 2

**Why is this needed**:
就是根据cpu核数配置负载报警策略

**Comment by UlricQin** [comment]
当前还做不到，需要自己写个插件，把cpu.load-cpu.core的值作为一个监控指标上报。后面会做指标聚合，但是要几个月之后才会上线
