### ISSUE TITLE
前端页面报错：invalid connection 

### ISSUE THREAD

**Issue by chengang2** [didi/nightingale#262]
前端页面一段时间没操作，再去操作会报这个错 invalid connection 。刷新又可以了。影响体验

**Comment by UlricQin** [comment]
我这没有遇到这个问题，其他人看看是否遇到，其他人如果也遇到烦请给个comment @chengang2 看看monapi的错误日志

**Comment by chengang2** [comment]
@UlricQin 有看到日志，可能是数据库连接超时。SetConnMaxLifetime 这个设置比数据库的wait_timeout 长，导致的。我改下代码测试下

**Comment by chengang2** [comment]
@UlricQin 已验证确实是连接池断开的问题。建议SetConnMaxLifetime做成可配置的值。
