### ISSUE TITLE
proc.agent.alive 未报警

### ISSUE THREAD

**Issue by chengang2** [didi/nightingale#263]
停掉collector，proc.agent.alive 没上报。前端页面监控看图中proc.agent.alive 停留在之前的时间。但是未告警。monapi没收到对应的event

**Comment by chengang2** [comment]
查看judge的debug日志 没有发现 proc.agent.alive 记录

**Comment by 710leo** [comment]
@chengang2 配置的告警策略和指标的曲线图可以贴一下

**Comment by chengang2** [comment]
代码更新到最新。解决问题
