### ISSUE TITLE
突增突降策略未生效

### ISSUE THREAD

**Issue by Summerdies** [didi/nightingale#264]
数据曲线如图：
![image](https://user-images.githubusercontent.com/42688766/88029541-b615a600-cb6c-11ea-8ba8-a8757c7185ea.png)
这个是配置的策略：
![image](https://user-images.githubusercontent.com/42688766/88029571-c299fe80-cb6c-11ea-9cdc-8c5b7e9d08c5.png)
未能触发报警。。

**Comment by UlricQin** [comment]
https://github.com/didi/nightingale/blob/master/src/modules/judge/judge/func.go#L169 这是代码，我看了一下没有看出问题，你的这个指标所属的机器，是否挂载在你配置的策略下面？或者看看日志啥的

**Comment by Summerdies** [comment]
> https://github.com/didi/nightingale/blob/master/src/modules/judge/judge/func.go#L169 这是代码，我看了一下没有看出问题，你的这个指标所属的机器，是否挂载在你配置的策略下面？或者看看日志啥的

策略是在父节点，机器是在下面的子叶节点挂载的。
![image](https://user-images.githubusercontent.com/42688766/88125953-017a9380-cc03-11ea-85d8-c069bc87c34e.png)
比如这两个策略，都是在父节点， 使用不足那个会正常触发。我看看日志
