### ISSUE TITLE
index 多点部署如何保持数据一致性

### ISSUE THREAD

**Issue by zhangxc** [didi/nightingale#265]
系统中独立的 n9e-index 模块提供了非常重要的指标索引查询功能，这个设计是全新的。

1. tsdb 没有使用一致性哈希来写索引到 index，索引会被推到每一个 index 节点上
2. index 只在初始化的时候尝试从其他 index 节点获取索引压缩包来重建索引 

这里有个关键问题，部署多点 index 后他们之间如何保持数据一致？系统如何解决这个问题？

**Comment by 710leo** [comment]
tsdb 会周期性地将全量的索引推给所有的index，这样可以保证多个index实例的数据最终是一致的

**Comment by zhangxc** [comment]
> 
> 
> tsdb 会周期性地将全量的索引推给所有的index，这样可以保证多个index实例的数据最终是一致的

了解。谢谢。
