### ISSUE TITLE
查看监控数据趋势，能否支持查看同一个endpoint多个metric曲线趋势

### ISSUE THREAD

**Issue by willhope** [didi/nightingale#267]
**What would you like to be added**:
查看同一个endpoint多个metric曲线趋势
**Why is this needed**:
比如查看某一个主机的内存使用率和内存占用率趋势，在同一个图表展现

**Comment by 710leo** [comment]
这个我们有计划做，目前还没有人力，主要是前端的改造，欢迎提pr一起共建: )

**Comment by AstonPudding** [comment]
接grafana可以实现

**Comment by UlricQin** [comment]
清理历史遗留issue，如有问题，请reopen
