### ISSUE TITLE
采集配置-插件-环境变量的删除

### ISSUE THREAD

**Issue by countingwww** [didi/nightingale#270]
**What happened**:
环境变量添加多个后，再次进来要删除的时候，只能从最后面开始删除，才能提交。从上面开始删除的时候无法提交
**What you expected to happen**:

环境变量的删除，只能从最后一个删除，要不提交不了

**Environment**:
- OS (e.g: `cat /etc/os-release`): Chrome
- Others: monitor/collect/modify/plugin/**

**Comment by UlricQin** [comment]
清理历史遗留issue，如有问题，请reopen
