### ISSUE TITLE
前端url加root_dir问题

### ISSUE THREAD

**Issue by hagic-hhj** [didi/nightingale#273]
如何所有路径都加个默认的跟路径location呢？
比如现在访问的路径是 http://192.168.1.2:80/#/sTree/node   要改成：http://192.168.1.2:80/n9e/#/sTree/node
需求来源：
nginx匹配个location /n9e，使其转发访问夜莺前端。
用nginx不行，因为css/js加载不出来。我认为应该和grafana location一样，要加个root_dir

**Comment by UlricQin** [comment]
夜莺是希望作为单独的域名来运行，不准备支持这种需求

**Comment by golden23** [comment]
> 夜莺是希望作为单独的域名来运行，不准备支持这种需求

最为一个功能全面的监控系统，最好还是能够支持root_dir，谢谢！
