### ISSUE TITLE
正则表达式 不支持 (?=pattern) 的用法

### ISSUE THREAD

**Issue by Summerdies** [didi/nightingale#274]
![image](https://user-images.githubusercontent.com/42688766/88768089-221b8e00-d1ad-11ea-9860-2c92cd644df8.png)
在线测试网站可以匹配：
![image](https://user-images.githubusercontent.com/42688766/88768170-42e3e380-d1ad-11ea-903e-5011c2174f64.png)
如图，不知是前端提示错误还是真的不能使用

表达式：(?=.*abc)(?=.*xxx)^.*$
匹配内容：abcxxx

同时collector有错误日志
 stra/log.go:189 compile pattern regexp failed:[sid:5462][pat:(?=.*abc)(?=.*xxx)^.*$][err:error parsing regexp: invalid or unsupported Perl syntax: `(?=`]

**Comment by UlricQin** [comment]
正则也是有多个标准的，看起来你这个写法在这个标准里是不被支持的，想办法换个别的写法吧
