### ISSUE TITLE
于情况下，告警数据和实际数据不符

### ISSUE THREAD

**Issue by jiangnanora** [didi/nightingale#275]
![image](https://user-images.githubusercontent.com/20857328/88904850-31bbd500-d288-11ea-98c9-ed4aba95f5a5.png)

![image](https://user-images.githubusercontent.com/20857328/88904912-413b1e00-d288-11ea-9112-622f68f584cc.png)

$./n9e-collector -v
2020/07/30 17:15:51 maxprocs: Leaving GOMAXPROCS=40: CPU quota undefined
Version: 2.7.2
Git Commit Hash: b6169ac7065c868edae22fcd8695000971faa535
UTC Build Time: 2020-07-17_11:01:21AM

**Comment by UlricQin** [comment]
拉取master上面的最新代码，编译之后替换n9e-judge这个二进制，再测试下试试

**Comment by UlricQin** [comment]
https://github.com/didi/nightingale/issues/287 应该跟这个是一个问题，在这个issue跟进，当前这个关闭
