### ISSUE TITLE
根节点添加插件采集后，子节点没有共同生效

### ISSUE THREAD

**Issue by nondevops** [didi/nightingale#276]
**What happened**:
根节点添加插件采集后，子节点没有共同生效

**What you expected to happen**:
根节点添加插件采集后，子节点也相应生效，这样就不用每个子节点都加相同的采集插件

**How to reproduce it (as minimally and precisely as possible)**:
1.在根节点添加n9e默认的两个采集插件，如10_uptime.sh 10_plugins_status.py
2.查看子节点的图表是否采集到了uptime等指标
3.如果没采集到，则表示该问题复现

**Anything else we need to know?**:
我尝试过修复，发现这样可以处理：
在子节点也要添加采集插件发现就可以上报数据，不过这样一来就失去了公共采集的意义。所以并不知道此种场景正确的处理方案是什么

**Environment**:
- OS (e.g: `cat /etc/os-release`):
centos7.64. selinux off; firewall off;
- Logs:
服务端-collecotor日志
![image](https://user-images.githubusercontent.com/12181410/89124445-99348780-d509-11ea-9192-4bdfb873926f.png)
- Others:
目录树结构：
![image](https://user-images.githubusercontent.com/12181410/89124741-e74a8a80-d50b-11ea-812b-f42c5b1dc52c.png)

**Comment by UlricQin** [comment]
```
cd /
/opt/n9e-collector/plugin/60_plugin_status.py
```

执行这个命令看看输出
