### ISSUE TITLE
个别endpoint数据查不到和数据查询接口的问题

### ISSUE THREAD

**Issue by 84372051** [didi/nightingale#278]
问题一:
![QQ图片20200804104754](https://user-images.githubusercontent.com/45719547/89247484-04807580-d640-11ea-8a06-b1fd00a480f9.png)
![QQ图片20200804104805](https://user-images.githubusercontent.com/45719547/89247490-08ac9300-d640-11ea-90dd-6d5b9f6f7504.png)
transfer日志无报错，tsdb日志无报错，但是个别服务器查不到数据
问题二:
/api/transfer/data    不管查什么数据啥都返回{"err": "query err"}，transfer有报错，index没有报错，但是前段页面是可以展示数据的
![image](https://user-images.githubusercontent.com/45719547/89247669-6f31b100-d640-11ea-9870-c9f1557c031e.png)
![image](https://user-images.githubusercontent.com/45719547/89247683-7658bf00-d640-11ea-899c-8d3ae575cab5.png)
![image](https://user-images.githubusercontent.com/45719547/89247937-07c83100-d641-11ea-8d36-970d6f81e36d.png)

**Comment by UlricQin** [comment]
第一个问题是因为你之前删除过那个endpoint吧

**Comment by 84372051** [comment]
谢谢，第一个问题解决了，确实是很久之前删除过这个enpoint，后来另一台新机器主机名正好又命名为这个，就显示不了了，手动添加可以了

**Comment by chirspan** [comment]
同样的第二个问题

**Comment by chirspan** [comment]
好像是https://github.com/didi/nightingale/commit/433da35d3421580f2f1bcdfbf5e7ff7f750c23b9 这个导致的。把tsdb和index的addresses加上，可以查询到数据了

**Comment by 710leo** [comment]
@chirspan @84372051 你们用的是哪个版本呢

**Comment by chirspan** [comment]
@710leo 2.7.2

**Comment by 84372051** [comment]
@710leo  2.7.2

**Comment by UlricQin** [comment]
经测试最新master代码是ok的了
