### ISSUE TITLE
测试使用有几个问题

### ISSUE THREAD

**Issue by crazylsq** [didi/nightingale#28]
1. 现有的mail-sender貌似不支持o365邮箱发件
2. 我在指定节点新增关于端口的采集配置，然后我将次采集配置删除，但监控图表中仍有此端口的选项
3. 是否可以将url监控做到控制台
4. 用户权限这块，是否可以增加 人和目录树的关联，只能看指定目录树的图表
5. 相同的报警策略，根节点配置了，子节点也配置了，但告警接收人不同，那么子节点的人收到了，根节点的人还能收到吗
6. 是否可以有个清单，比如那些常规监控的插件可以和open-falcon共用
7. 关于短信的sender是否可以提供下，在社区不活跃并且不会编程的人来说，使用上还是有点问题的

**Comment by UlricQin** [comment]
你好，感谢试用夜莺，共建社区：）

1. mail-sender当时测试支持163邮箱，说明smtp本身没问题，o365这个我不清楚
2. 因为索引数据不是实时删除的，系统发现某个数据不再上报，会过几天再清理（具体几天忘记了）
3. url监控不会整合进来，只会出现在商业版，当然，社区同仁如果来做这个事情我们会协助
4. 同3，完善的权限体系只会出现在商业版里，而且权限体系也不是监控的核心，夜莺专注监控，想做的纯粹一点
5. 可以收到，如果想在子节点做特殊配置，可以把对应的策略配置在子节点，根节点的策略里配置排除节点，把子节点的特殊节点排除掉
6. 理论上监控插件都可以共用，只是现在夜莺还不支持counter类型的指标，只能支持gauge类型的，如果有插件上报了counter类型的指标，这部分指标会不正常
7. 短信通道通常是采购的外部厂商，不同的厂商接口不一样，没法统一提供，一般都是http接口但是参数各异，没有统一的规范
