### ISSUE TITLE
[需求]删除或修改endpoint后支持自动上报最新的endpoint

### ISSUE THREAD

**Issue by nondevops** [didi/nightingale#281]
**What would you like to be added**:
[需求]删除或修改endpoint后支持自动上报最新的endpoint
**Why is this needed**:
当前版本2.7.2在endpoint被改变后，无法以最新endpoint进行上报，需要手动添加最新endpoint，给维护带来极大成本。因此建议增加endpoint被变更后可以以最新endpoint上报数据。

该需求背景：
1.有些虚拟机初始化后，可能还没来得及修改主机名就以默认“localhost”作为主机名上报，如实例太多，全都是localhost无法区分。只有修改主机名后才能一一识别；
2.然可以使用IP作为endpoint，但一旦初始化好之后，修改了主机名也需要手动导入最新endpoint，提升操作复杂度和维护成本。

举例：
n9e服务端已存在10.20.1.22这台实例，以IP作为endpoint上报，后IP不具有识别性，需要修改成hostname-ip格式，collector修改重启后，发现在 全部对象 中没有该最新endpoint上报的数据。后来了解到需要手动导入新的endpoint才行。

**Comment by 710leo** [comment]
endpoint 从 ip 改为 hostname-ip 之后，可以当做是一个新的 endpoint 了，理论上会自动出现在全部对象中的，可以看下各个组件有没有报错日志
