### ISSUE TITLE
建议在看图的时候鼠标跟随显示可以把别名也显示上去

### ISSUE THREAD

**Issue by leezer3379** [didi/nightingale#285]
论别名的重要性
1. 显示别名很重要且能避免获得IP再去查询别名（额外增加的工作量）。
2. 把标识改成主机名和IP的方案并不好使（批量新建主机主机名并没有固定，而监控如果是自动添加情况，会造成大量重叠主机监控，标识还是IP比较好）。
3. 既然有别名功能且费时间填写了，必然是在很多地方想用到别名。
4. 现状报警可以看到别名👌，希望在报警历史和报警屏蔽中可以显示别名；希望在监控看图中可以显示别名。

**Comment by UlricQin** [comment]
同意，后面可以做此优化

**Comment by UlricQin** [comment]
清理历史遗留issue，如有问题，请reopen
