### ISSUE TITLE
dashborad

### ISSUE THREAD

**Issue by liuxiankun** [didi/nightingale#286]
**What would you like to be added**: 
同一个metric,不同的tag ,可以像open-falcon一样可以选择在一张图上展示，也可以在每个tag 的 图上展示。（endpoint，counter等方式 ）

**Why is this needed**: 使用习惯，分析方便灵活。

**Comment by UlricQin** [comment]
夜莺的dashboard来自滴滴内部的看图逻辑，和falcon已经没法走在一起了。后面也没法支持。可以用grafana来配置大盘，可以把多个指标放到一个图里：https://github.com/n9e/grafana-n9e-datasource
