### ISSUE TITLE
告警事件详情，两个与条件的现场值显示的值相同，实际不相同，2.7.2版本。

### ISSUE THREAD

**Issue by lahcloud** [didi/nightingale#287]
![n9e](https://user-images.githubusercontent.com/5811825/91381304-af5c0c00-e859-11ea-8e7c-23e59b921f4d.png)

**Comment by UlricQin** [comment]
这个确实有问题

**Comment by smarkm** [comment]
@lahcloud 能帮忙提供下更多信息吗？

**Comment by UlricQin** [comment]
从3.3.0版本开始修复了与条件的问题，可以再试试
