### ISSUE TITLE
查看历史数据存在断点问题,每次缺失15分钟左右数据

### ISSUE THREAD

**Issue by md18733515033** [didi/nightingale#288]
**What happened**:查看最近两个小时数据没有断点,但是查询时间稍长就会出现很多的断点,每个断点间隔15分钟

![2020-08-27 13-59-22 的屏幕截图](https://user-images.githubusercontent.com/42811004/91397292-0bc92680-e86e-11ea-8fc0-c7ef3d02e5f4.png)

**version**: 2.7.2
**env**: centos7

**Comment by UlricQin** [comment]
问题依旧么？数据是否更改过step？

**Comment by bing050802** [comment]
![image](https://user-images.githubusercontent.com/1294242/114664458-4c5aaf00-9d2e-11eb-8307-0d79f8a3c59a.png)
我这边也是每台服务器都出现问题，出现的指标是cpu.idle ，两小时内没问题，拉取到一天或者2天时长就会出现问题，基本是断点15分钟或者30分钟

**Comment by bing050802** [comment]
> **What happened**:查看最近两个小时数据没有断点,但是查询时间稍长就会出现很多的断点,每个断点间隔15分钟
> 
> ![2020-08-27 13-59-22 的屏幕截图](https://user-images.githubusercontent.com/42811004/91397292-0bc92680-e86e-11ea-8fc0-c7ef3d02e5f4.png)
> 
> **version**: 2.7.2
> **env**: centos7

最后是怎么解决的啊，我也遇到了
