### ISSUE TITLE
endpoint的别名怎么在客户端设置

### ISSUE THREAD

**Issue by crazylsq** [didi/nightingale#29]
默认collector上报的endpoint是IP

一般我会在web上别名设置为主机名，将IP和主机名关联起来

如何在collector设置别名，自动上报上来

**Comment by UlricQin** [comment]
这个不支持哈，如果是手工在collector的配置文件配置alias的话，跟在web上配置没有区别了。如果是自动获取机器名的话，就要考虑是以web为准还是以collector的配置为准，比较麻烦，而且各公司可能需求不同。

推荐做法是，如果自己有cmdb，就把cmdb的数据灌进来，如果没有，可以批量调api修改一把。
