### ISSUE TITLE
curl 请求 api/transfer/data报错

### ISSUE THREAD

**Issue by mixsome** [didi/nightingale#292]
n9e版本：2.7.2
Linux版本：centos7

curl请求示例:
curl -X POST   http://192.168.40.80:5810/api/transfer/data      -H 'Content-Type: application/json'   -d '[{"start":1598965614,"end":1598966614,"endpoints":["192.168.40.80"],"counters":["cpu.idle"],"step":20,"dstype":"GAUGE"}]'

错误日志logs/transfer/stdout.log如下：
![image](https://user-images.githubusercontent.com/22359872/91866640-518a5280-eca5-11ea-9ca7-69b3ba581242.png)

**Comment by UlricQin** [comment]
2.7.2确实有问题，得用master上面的最新代码才行
