### ISSUE TITLE
报警策略能够增加描述详情触发报警的时候可以展示详情的内容

### ISSUE THREAD

**Issue by chixianliangGithub** [didi/nightingale#295]
**What would you like to be added**:

**Why is this needed**:

**Comment by UlricQin** [comment]
就直接放到策略标题里呗，报警的时候会带上

**Comment by chixianliangGithub** [comment]
> 就直接放到策略标题里呗，报警的时候会带上

但是每个业务指标 的 描述 会不一样 ，还希望报错可以把error 信息能够带上比如异常信息等

**Comment by spyvip** [comment]
@chixianliangGithub  参考extra
