### ISSUE TITLE
judge中的historymap不定时清理过期数据

### ISSUE THREAD

**Issue by fibbery** [didi/nightingale#297]
https://github.com/didi/nightingale/blob/a8357dffb9fb5bfb37ada5f47df9db0583a646b3/src/modules/judge/cache/history.go#L70

judge模块中的historymap，没看到有做定时清除过期数据的地方，会导致内存数据越来越多吧？

**Comment by UlricQin** [comment]
嗯，会有这个问题，不过问题不大

**Comment by UlricQin** [comment]
清理历史遗留issue，如有问题，请reopen
