### ISSUE TITLE
[bug] 节点下对象 勾选显示挂载节点 报错

### ISSUE THREAD

**Issue by nondevops** [didi/nightingale#3]
问题现象:
节点下对象 勾选显示挂载节点 报错
![image](https://user-images.githubusercontent.com/12181410/76966095-60cc4c80-6960-11ea-9a7f-2ce6ce87ca23.png)

**Comment by UlricQin** [comment]
哈，你这个操作很风骚，节点下没有任何机器，直接勾选了显示挂载节点，此时前端的确会报错，辛苦 @jsers 帮优化一下，这种情况可以不报错

**Comment by jsers** [comment]
@nondevops 已修复
