### ISSUE TITLE
一个用户存在于多个钉钉群，匹配告警

### ISSUE THREAD

**Issue by zhiyuan192shine** [didi/nightingale#302]
一个用户存在于多个钉钉群里，通过不同的 im 来进行告警，目前通过新增不同用户方式解决。
可以实现一个用户匹配多个 im，填写告警人时，通过选择来匹配

**Comment by UlricQin** [comment]
不准备支持这种方式，一般夜莺虚拟用户的IM都是配置的群组token，一个虚拟用户代表一个钉钉群组
