### ISSUE TITLE
前端最大值最小值切换失败

### ISSUE THREAD

**Issue by peng19940915** [didi/nightingale#305]
**What happened**:
当在"监控看图"页面切换最大值，最小值，平均值时，展示的始终是平均值
**What you expected to happen**:
在切换的时候理应能看到折线图的变化。
**How to reproduce it (as minimally and precisely as possible)**:
正常情况下，我获取两小时内的数据，应该是落在最原始的RRD里面也就是没聚合过的：  
![image](https://user-images.githubusercontent.com/25658446/92893057-edf1e900-f44b-11ea-859c-8fe829d6b911.png)  

此时，可以看到有个最大值在7%左右（15：00）  

如果我将时间区间拉到1天内，此时应该会去查归档过后的rrd文件，也就是2分钟一次那个我们能看到15:00那个7%的点已经被聚合了，因为是取的平均值所以是看不到的：    
![image](https://user-images.githubusercontent.com/25658446/92893332-2a254980-f44c-11ea-9399-4be53d7bf0a7.png)

但是当我把聚合方式改为max后，理应能看到15:00那个7%，因为前后一小时都没有比7%更大数据，可是图形依旧显示的是avg的图   
![image](https://user-images.githubusercontent.com/25658446/92893582-648ee680-f44c-11ea-8585-0e5dff489e32.png)

**Anything else we need to know?**:

**Environment**:
- OS (e.g: `cat /etc/os-release`):
```shell
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Logs:
- Others:

**Comment by 710leo** [comment]
目前前端页面的聚合，指的是多条曲线的聚合计算，不是指的rrd的采样方式
