### ISSUE TITLE
无法获取监控数据的问题

### ISSUE THREAD

**Issue by ILOVEQIUXIAOYI** [didi/nightingale#307]
有一台服务器之前是用作监控服务器的，后来做了迁移，只留下了collector，更改了address.yml的配置，服务启动状态也是正在运行的，可是监控服务器无法发现这台主机，手动添加节点之后也没有监控数据返回。

**Comment by UlricQin** [comment]
个别现象，说明非软件问题，需要自行检查配置哈，可以尝试把OK的机器的配置拷贝过去一份
