### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by weixiupc** [didi/nightingale#308]
参照http://n9e.didiyun.com/docs/install/compile/此URL，源码编译，并已经更改好对应的mysql.yml配置。
执行control start all这一步报错如下：

root@SZXHY-10-132-99-163:[/home/gopath/src/github.com/didi/nightingale]./control start all
cannot start monapi

单独执行也是一样[执行其他模块都报同样错误]：
root@SZXHY-10-132-99-163:[/home/gopath/src/github.com/didi/nightingale]./control start monapi
cannot start monapi

查看日志：
root@SZXHY-10-132-99-163:[/home/gopath/src/github.com/didi/nightingale]more logs/monapi/stdout.log 
2020/09/21 16:34:53 maxprocs: Leaving GOMAXPROCS=24: CPU quota undefined
runner.cwd: /home/gopath/src/github.com/didi/nightingale
runner.hostname: SZXHY-10-132-99-163
portal start, use configuration file: etc/monapi.yml
panic: runtime error: index out of range [0] with length 0
goroutine 21 [running]:
github.com/didi/nightingale/src/toolkits/stats.Init(0xd2ae7d, 0xa, 0x0, 0x0, 0x0)
        /home/gopath/src/github.com/didi/nightingale/src/toolkits/stats/init.go:31 +0x2c5
created by main.main
        /home/gopath/src/github.com/didi/nightingale/src/modules/monapi/monapi.go:65 +0x7c

n9e-monapi版本：
root@SZXHY-10-132-99-163:[/home/gopath/src/github.com/didi/nightingale]./n9e-monapi -v
2020/09/21 16:36:23 maxprocs: Leaving GOMAXPROCS=24: CPU quota undefined
Version: 2.7.2
Git Commit Hash: bc884175bed578aec8f56d0ab478055072d5af4e
UTC Build Time: 2020-09-21_07:43:34AM

OS版本：
root@SZXHY-10-132-99-163:[/home/gopath/src/github.com/didi/nightingale]cat /etc/redhat-release 
CentOS release 6.9 (Final)
go版本：
root@SZXHY-10-132-99-163:[/home/gopath/src/github.com/didi/nightingale]go version
go version go1.15.2 linux/amd64

**Comment by UlricQin** [comment]
需要在address.yml的collector部分，增加addresses字段，默认写成 127.0.0.1即可
