### ISSUE TITLE
是否有支持修改节点结构的功能

### ISSUE THREAD

**Issue by developer-tangjun** [didi/nightingale#309]
**What would you like to be added**:
是否有支持修改节点结构的功能，即把指定节点及其所有子节点移到另一个节点下，相应的机器、策略等也做移动
**Why is this needed**:
有这样一个场景：原有的某一节点决定废弃，要将其下的节点相关信息全部移到某个新节点下，由于子节点信息非常多，重新创建一个一模一样的结构非常耗时间，请问有什么好的办法么？

**Comment by UlricQin** [comment]
这个后面会支持，不过排期比较靠后

**Comment by lihuiheng** [comment]
数据库直接修改。

**Comment by UlricQin** [comment]
清理历史遗留issue，如有问题，请reopen
