### ISSUE TITLE
能否支持计算历史记录，生成自动base-line，告警指标中增加baseline对比？

### ISSUE THREAD

**Issue by wudeyong** [didi/nightingale#31]
cat的告警有个功能，生成baseline，业务告警指标可以和baseline对比，这样告警更加符合实际情况，因为业务有平峰和高峰，和历史同期对比才有意义

reference: https://github.com/dianping/cat/wiki/business#%E5%9F%BA%E7%BA%BF

**Comment by UlricQin** [comment]
短期没有精力搞这块，希望社区能有朋友给搞一下
