### ISSUE TITLE
nightingale日志相关的问题

### ISSUE THREAD

**Issue by tongorz** [didi/nightingale#311]
查阅了下官网的文档，日志时间戳这块我没有查到关于时区的内容？是默认的UTC时间还是本地时间？
如果有的系统只支持UTC时间或者只支持本地时间，有推荐的处理方式吗？
日志信息采集后其存储也是"近期几个小时的数据默认存内存, 硬盘存储方式仍然使用rrdtool"吗，日志这块有考虑和elasticsearch等结合吗？

致敬大大们的开源贡献，感谢！

**Comment by UlricQin** [comment]
默认使用机器本地时间

日志这块是在中心配置正则，下发到目标机器agent，agent进行正则匹配，提取metric数据上报服务端，所以，它不会把日志整个内容发送给服务端，和ES思路不同，如果咱们是希望做个日志中心，那还是推荐用ES的
