### ISSUE TITLE
[3.0] 告警接收团队设置后,界面不显示团队名称(2.7可以显示)

### ISSUE THREAD

**Issue by nondevops** [didi/nightingale#315]
**What happened**:
[3.0] 告警接收团队设置后,界面不显示团队名称(2.7可以显示)
**What you expected to happen**:
添加告警策略,选择告警接收团队保存后,无法看到团队名称,2.7版本可以显示.应该是BUG,目前显示的是"-"这样的字符
**How to reproduce it (as minimally and precisely as possible)**:
![image](https://user-images.githubusercontent.com/12181410/94407112-9b336380-01a5-11eb-9c79-776103cf6cad.png)
![image](https://user-images.githubusercontent.com/12181410/94407126-9e2e5400-01a5-11eb-88fc-347bdb154ebe.png)

**Anything else we need to know?**:

**Environment**:
- OS (e.g: `cat /etc/os-release`):
- Logs:
- Others:

**Comment by haozheyu** [comment]
![image](https://user-images.githubusercontent.com/29147597/94407761-74296180-01a6-11eb-9c6d-8f2004ef5bc2.png)
同上

**Comment by UlricQin** [comment]
嗯，确实有问题，辛苦 @jsers 帮处理一下~

**Comment by UlricQin** [comment]
@nondevops @haozheyu  应该是修复了，下载最新的pub.tar.gz试试
