### ISSUE TITLE
界面优化

### ISSUE THREAD

**Issue by greyireland** [didi/nightingale#32]
1、监控报警/监控看图/指标列表    点击各个tab 整体页面抖动

**Comment by UlricQin** [comment]
我这没有复现，做个动态截屏看看？

**Comment by haozheyu** [comment]
同上，浏览器在非全屏的情况下特别明显

**Comment by greyireland** [comment]
![n9e](https://user-images.githubusercontent.com/9276742/77839358-70dcfb00-71ae-11ea-90a1-76f761b1940c.gif)

**Comment by UlricQin** [comment]
好的收到

**Comment by ermazi** [comment]
+1确实有这个情况

**Comment by jsers** [comment]
已修复
