### ISSUE TITLE
v3如何添加监控？

### ISSUE THREAD

**Issue by gcxfd** [didi/nightingale#320]
我首先用 docker-compose启动了v3 , 服务器ip是 192.168.17.15
然后 安装了  n9e-collector-2.7.2-dbd81ee.el7.x86_64.rpm 
然后修改 /usr/local/n9e/etc/address.yml 中的 addresses 的 127.0.0.1 为 192.168.17.15
然后运行 ./n9e-collector
请问，如何让 监控告警系统 中出现这台机器，现在监控告警系统还是空的

**Comment by UlricQin** [comment]
不能用老的collector，需要用3.0版本的agent，agent会自动注册到资产管理系统，在这个系统修改租户，然后去用户资源中心的游离资源页面把这个资源挂到相应的节点上。3.0不纯粹是监控了，引入了资产管理的流程，所以会复杂一些
