### ISSUE TITLE
请问3.0版本还可以使用swcollector对网络设备做监控吗？

### ISSUE THREAD

**Issue by tongorz** [didi/nightingale#322]
希望尝试使用下nightingale，在想是等3.0版本文档出来，还是直接使用2.x版本。

3.0的网络设备监控部分要商业化，请问3.0的开源版本还支持swcollector对网络设备做监控吗？
作为一名网工，希望网络设备监控这块最基础的功能能开源开放使用，针对高级功能和定制化功能再进行商业化。

不管如何，感谢nightingale团队

**Comment by UlricQin** [comment]
swcollector，还是支持的。与2.x的区别是，2.x在监控指标上报的时候会自动提取endpoint出来管理，3.x因为单独搞了一个资产管理系统，所以流程上有些差异，对于网络设备，需要单独在资产管理系统里手工导入

**Comment by tongorz** [comment]
感谢解答
