### ISSUE TITLE
[3.0] 资产管理中心修改设备备注，在用户资源中心还需要再改一次？

### ISSUE THREAD

**Issue by 1029649360** [didi/nightingale#323]
**What happened**:
资产管理中心修改设备备注，在用户资源中心还需要再改一次？
**What you expected to happen**:
可以只在资管管理中心修改一下，修改后的备注信息带到用户资源中心。
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OS (e.g: `cat /etc/os-release`): CentOS 7
- Logs:
- Others: 夜莺3.0

**Comment by UlricQin** [comment]
这俩备注是给不同的人看的，资产管理系统的使用方通常是少部分系统管理员，用户资源中心的使用方通常是应用运维和研发
