### ISSUE TITLE
[3.0]登录页used接口404错误

### ISSUE THREAD

**Issue by zhaoge77** [didi/nightingale#325]
**What happened**:拉的最新master版本编译测试，登录页有一个rdb的接口报404错误： GET http://192.168.5.9:81/api/rdb/ldap/used/used 404 (Not Found)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OS (e.g: `cat /etc/os-release`):
- Logs:
- Others:

**Comment by jsers** [comment]
已修复
https://github.com/n9e/fe/releases/tag/v3.0.1
