### ISSUE TITLE
我想请问一下v3有没有JVM监控的功能

### ISSUE THREAD

**Issue by ILOVEQIUXIAOYI** [didi/nightingale#329]
请问需要有什么调整吗，我将jmx监控模块的配置中的上报接口改为了http://127.0.0.1:2080/v1/push，能成功运行模块并获得监控数据，但是在前端没有找到JMX监控项

**Comment by 710leo** [comment]
可以参考 [这里](https://github.com/didi/nightingale/wiki/FAQ_01_%E7%BB%98%E5%9B%BE%E7%9B%B8%E5%85%B3#q3%E8%87%AA%E5%B7%B1%E5%86%99%E7%A8%8B%E5%BA%8F%E6%8C%89%E7%85%A7%E6%95%B0%E6%8D%AE%E8%A7%84%E8%8C%83%E5%90%91collector%E6%88%96%E8%80%85transfer%E4%B8%8A%E6%8A%A5%E6%95%B0%E6%8D%AE%E4%BD%86%E7%9C%8B%E4%B8%8D%E5%88%B0%E5%9B%BE) 排查一下哪里出问题了

**Comment by AlliotTech** [comment]
v3配置了jmx exporter 后 agent端需要有prometheus-exporter-collector 
在告警策略的采集策略配置里  添加采集策略即可。

**Comment by ILOVEQIUXIAOYI** [comment]
> v3配置了jmx exporter 后 agent端需要有prometheus-exporter-collector
> 在告警策略的采集策略配置里 添加采集策略即可。

谢谢您~
