### ISSUE TITLE
根据层级关系进行告警收敛

### ISSUE THREAD

**Issue by tongorz** [didi/nightingale#334]
请问能否支持根据层级关系进行告警收敛？
比如一台交换机挂了，针对交换机的一系列监控会告警（包括端口和路由协议），交换机下面接入的服务器的基础监控会告警，部署的服务监控也会告警。
这种情况，能不能利用预先设置的层级关系来进行告警收敛，让告警接收方快速判断大量告警产生的原因？

类似的功能在checkmk（基于Nagios）上有描述 `https://checkmk.com/cms_notifications.html`

> 6.5. Parent hosts
Imagine that an important network router to a company location with hundreds of hosts fails. All of its hosts will then be unavailable to the monitoring and become DOWN. Hundreds of notifications will therefore be triggered. Not good.

> In order to avoid such problems the router can be defined as a parent host for its hosts. If there are redundant hosts, multiple parents can also be defined. As soon as all parents enter a DOWN state, the now inaccessible hosts will be flagged with the UNREACH state and their notifications will be suppressed. The problem with the router itself will of course still be notified.

**Comment by UlricQin** [comment]
两个系统告警引擎设计逻辑不同，不太好支持这个场景。

另外，如果这些机器和交换机都是同一个人收报警这样收敛会有用，但是，如果交换机是网工来收报警（一般公司是这样），机器是应用运维来收，这种场景也不太好收敛

**Comment by tongorz** [comment]
> 两个系统告警引擎设计逻辑不同，不太好支持这个场景。
> 
> 另外，如果这些机器和交换机都是同一个人收报警这样收敛会有用，但是，如果交换机是网工来收报警（一般公司是这样），机器是应用运维来收，这种场景也不太好收敛
