### ISSUE TITLE
BUG report： 登陆无法跳转到先前URL

### ISSUE THREAD

**Issue by AlliotTech** [didi/nightingale#339]
**What happened**:
告警邮件中的详情链接  在未登录的情况下点击  -> 跳转到登陆页 -> 登陆后不会自动跳转到先前邮件中的 URL
![image](https://user-images.githubusercontent.com/24980252/96070087-1731e900-0ed2-11eb-921a-2fb351fda7e8.png)

**What you expected to happen**:
未登录情况下点击内链  跳转到登陆页面  登陆后自动跳转到先前的 URL

**Comment by UlricQin** [comment]
清理历史遗留issue，如有问题，请reopen
