### ISSUE TITLE
请问其它一些程序Push的数据到transfer后怎么在前端怎么也看不到？

### ISSUE THREAD

**Issue by hel2o** [didi/nightingale#340]
版本：V3.1.3
之前使用openfalcon+时的一些程序Push到transfer后在夜莺前端怎么也看不到数据
transfer和tsdb debug都有看到接收到了数据
程序提交给transfer后的回复也显示成功了
是否对主动提交的数据V3版本有变化？

**Comment by UlricQin** [comment]
监控数据的endpoint需要设置为某个设备，资产管理系统里边的设备，这个设备要部署agent，agent就会自动上报，自动出现在资产管理系统里

**Comment by hel2o** [comment]
明白了，有没有什么办法能够自动实现设备添加 在Push数据时？

**Comment by UlricQin** [comment]
> 明白了，有没有什么办法能够自动实现设备添加 在Push数据时？

可以调用资源注册的接口提前注册一下
