### ISSUE TITLE
V3版本插件上报的数据在页面上查不到

### ISSUE THREAD

**Issue by gxhak47** [didi/nightingale#341]
V3版本插件上报的数据在页面上查不到：看debug日志数据已传至tsdb，但资产管理里边不显示，游离资源中也不显示

**Comment by UlricQin** [comment]
你所谓的资产管理里看不到，那看来是你的插件上报的endpoint是自定义的一个字符串，不建议这样做，建议endpoint留空。如果非要自定义一个字符串，那就需要在资产管理里手工导入

**Comment by gxhak47** [comment]
手工导入endpoint后可以正常看到上报的数据，但是手工导入比较麻烦，这块儿的逻辑能否优化下，改成跟V2里边一样，插件上报之后能自动显示那种的。谢谢！

**Comment by UlricQin** [comment]
设计逻辑不同了，没法这样做，不过服务端留了接口可以调用接口(可以查看相关模块的router.go文件)先注册一下，然后再上报监控数据
