### ISSUE TITLE
suggest： job模块或alarm模块开关接口

### ISSUE THREAD

**Issue by AlliotTech** [didi/nightingale#342]
任务执行的开关接口或者是告警策略的临时开关接口。

**Why is this needed**:
任务模块与告警模块实现告警自愈是一个很好的逻辑，但是现有的逻辑下会产生这样的场景：  
　　使用n9e监控tomcat业务的健康状态，并添加告警回调，当Tomcat挂掉的时候自动调用任务重新拉起，这样似乎挺好。
但是 当遇到业务发版的时候，需要临时关闭Tomcat，这期间触发了告警并成功回调，就会重新将任务流水线中关闭的Tomcat拉起。导致后面的流水线fail 。
　　所以，设想是不是 **加入一个告警与任务临时开关的接口与状态查询接口，请求后临时将某条告警策略或任务禁用，当流水线完成后再重新调用开关接口将其恢复** 会更能满足实际应用的场景

**Comment by UlricQin** [comment]
我给你支个招，如果是预期内的发版导致的tomcat重启，touch一个标识文件，重启完了再删除这个标识文件。自愈动作的脚本，执行的时候如果看到这个标识文件就不用拉起tomcat了
