### ISSUE TITLE
rdb删除节点不会立刻回收此节点对应的告警策略，而是通过定时任务清理，这么做的考虑是什么呢？这样不是会有一定的空窗期产生误告警

### ISSUE THREAD

**Issue by naivelife** [didi/nightingale#343]
**What would you like to be added**:

**Why is this needed**:

**Comment by UlricQin** [comment]
不会有告警，因为节点和设备的关联关系已经没有了 Ulric Qin 邮箱：ulric.qin@gmail.com 签名由 网易邮箱大师 定制 在2020年10月16日 17:25，naivelife 写道： What would you like to be added: Why is this needed: — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
