### ISSUE TITLE
V2前端编译问题

### ISSUE THREAD

**Issue by Chenghui-web** [didi/nightingale#346]
想请教一下v2版本本地是没有问题的 但是web编译之后部署会出现如图错误= =  请问要如何解决 万分感谢
![image](https://user-images.githubusercontent.com/23331593/96396122-04cced80-11f9-11eb-9446-68659ac6d54f.png)

**Comment by jsers** [comment]
这个错误信息是没办法定位问题的，建议你把本地 dll 删了，重新编译下试试

**Comment by Chenghui-web** [comment]
> 这个错误信息是没办法定位问题的，建议你把本地 dll 删了，重新编译下试试

感谢大兄弟 ~ 删掉重新编译 解决了~

**Comment by Chenghui-web** [comment]
已解决
