### ISSUE TITLE
node节点运行不起来

### ISSUE THREAD

**Issue by AsherHuu** [didi/nightingale#347]
![image](https://user-images.githubusercontent.com/32830348/96534577-97858f00-12c2-11eb-9d94-3267d91d36e0.png)
![image](https://user-images.githubusercontent.com/32830348/96534622-acfab900-12c2-11eb-948f-e79038d6906b.png)

**Comment by UlricQin** [comment]
报错很明显，/home/n9e/etc/agent.yml没有，安装公众号视频一步一步操作哈
