### ISSUE TITLE
资产管理系统页面  内存数值精度  问题

### ISSUE THREAD

**Issue by Lvzhenqian** [didi/nightingale#348]
问题描述：
资产管理系统页面内存显示数值错误

如图：
![image](https://user-images.githubusercontent.com/17487028/96567958-fa464d00-12f9-11eb-82af-897c0f272aa4.png)
监控系统数值是正常的：
![image](https://user-images.githubusercontent.com/17487028/96568125-2b268200-12fa-11eb-95e9-35f640441322.png)

测试API：GET /api/ams-ce/hosts
![image](https://user-images.githubusercontent.com/17487028/96568520-9cfecb80-12fa-11eb-8204-581411c7fd13.png)

**Comment by UlricQin** [comment]
看一下readme，里边有讲agent.yml里有几个shell，是用来获取cpu、mem、disk的信息，你看获取内存的shell如果不合适就改一下完事

**Comment by Lvzhenqian** [comment]
: ) 好吧
