### ISSUE TITLE
Value解析有问题报错err:value [0] is illegal

### ISSUE THREAD

**Issue by banlilin** [didi/nightingale#349]
**What happened**:
一些监控项传值没有问题，但是上传客户端解析value有问题 报错err:value [0] is illegal
如下：
ERROR日志截取片段
2020-10-21 11:19:01.564630 ERROR core/push.go:68 some item push err: illegal item:<MetaData Endpoint:192.168.1.1, Metric:get_hit_ratio, CounterType:GAUGE Timestamp:1603250340, Step:60, Value:[49 48 48 46 48], Tags:port=17073(map[port:17073])> err:value [0] is illegalillegal 
实际监控项日志：
{"endpoint": "192.168.1.1", "tags": "port=17073_mvt_serv
ice", "timestamp": 1603250341, "metric": "get_hit_ratio", "value": "100.0", "counterType": "GAUGE", "step": 60}

**What you expected to happen**:
不知道为什么解析的value成了一个list，报错导致监控项没有，无法添加报警
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OS (e.g: `cat /etc/os-release`): CentOS 6.10
- Logs:
- Others:

**Comment by banlilin** [comment]
用的是open-falcon，相同的脚本没有问题，想迁移到夜莺 发现很多监控项都有这样的问题。

**Comment by UlricQin** [comment]
"value": "100.0" 这是个字符串，不能用字符串，用数字

**Comment by banlilin** [comment]
改成是float了也不行。
