### ISSUE TITLE
建议：删除资产的api接口增加按IP来删除

### ISSUE THREAD

**Issue by yyqs2008** [didi/nightingale#351]
删除资产的api接口好像只能通过id来删除：curl -X DELETE -H "X-User-Token: xxxxxxxxxxxxxxx" -d '{"ids":[1]}' "http://127.0.0.1/api/ams-ce/hosts" 

可以加个功能按IP来删除吗，curl -X DELETE -H "X-User-Token: xxxxxxxxxxxxxxx" -d '{"ip":"1.1.1.1"}' "http://127.0.0.1/api/ams-ce/hosts" ，因为大部份情况下调用删除接口只知道要删除的资产IP是什么，而并不知道其对应的内部ID是什么。

**Comment by UlricQin** [comment]
这个功能开发特别简单，要不要来个PR呀？共建系统~

**Comment by UlricQin** [comment]
https://github.com/didi/nightingale/commit/28a2196143481d61f769d35f3318ee66e3567a72
