### ISSUE TITLE
V3版绘图滞后5分钟，不能实时绘图

### ISSUE THREAD

**Issue by u31s** [didi/nightingale#354]
V3版绘图滞后5分钟，不能实时绘图，step：300s 在哪里修改？是否可以在UI上自定义

**Comment by UlricQin** [comment]
这是你自己上报的数据呀。你是搞了个插件还是swcollector还是什么，这个step是上报的时候给的，跟服务端没关系

**Comment by u31s** [comment]
明白了，谢谢
