### ISSUE TITLE
collector监控客户端报错

### ISSUE THREAD

**Issue by feixia5712** [didi/nightingale#355]
普通用户部署夜莺监控，报错:funcs/fsstat.go:90 Open file failed: open /.fs-detect: permission denied，目前看采集数据正常，请问下这个怎么修复

**Comment by feixia5712** [comment]
是collector报的错

**Comment by UlricQin** [comment]
agent有个机制，自动探测各个分区是否能够读写，你如果不是root启动agent，那就无法往探测根分区，就会报错
