### ISSUE TITLE
夜莺agent模块运行是否有权限限制

### ISSUE THREAD

**Issue by liuyanmei069** [didi/nightingale#358]
在agent端用普通用户运行后在夜莺这边显示这个
![image](https://user-images.githubusercontent.com/25581778/97156665-0034a600-17b2-11eb-8484-03dd468cb237.png)
把/sys/firmware/dmi/tables下的DMI和smbios_entry_point文件赋予444的权限后，获取SN正常了
但是监控这边为空数据
接口/api/index/metrics返回为空
![image](https://user-images.githubusercontent.com/25581778/97156926-5b669880-17b2-11eb-94de-532e4dc74f4a.png)
查看日志报错也是一些文件需要权限
![image](https://user-images.githubusercontent.com/25581778/97157020-7df8b180-17b2-11eb-9922-128884ed8a02.png)
是否agent只能用root运行？

**Comment by UlricQin** [comment]
agent建议用root来跑。看不到监控数据问题可能很多，可以打开agent debug日志，看看上报的什么内容。然后逐层查各个组件的日志
