### ISSUE TITLE
为什么有的主机agent无法被识别

### ISSUE THREAD

**Issue by liuyanmei069** [didi/nightingale#359]
您好，请问为什么有的主机agent无法被识别呢
在夜莺的资产那边没有看到
比较能被识别和不能被识别的主机
http://note.youdao.com/yws/res/6263/WEBRESOURCE6ece88447313db2c9ec14f5c7cea59c1?ynotemdtimestamp=1603766975325
http://note.youdao.com/yws/res/6265/WEBRESOURCE40dd71bd3b0757257d77df25aad092e5?ynotemdtimestamp=1603766975325
没有被识别的主机tcp连接没有这个teradataordbms
数据库ams的host表里也没有识别不到的主机，日志没有发现什么异常，这是什么原因导致呢

**Comment by UlricQin** [comment]
贴agent.yml的配置和agent的日志

**Comment by liuyanmei069** [comment]
昨天在群里已经得到反馈啦，是有yml配置文件的df -m命令执行问题，已经解决，感谢
