### ISSUE TITLE
希望夜莺能支持通过http、tcp或udp上报metric

### ISSUE THREAD

**Issue by tongorz** [didi/nightingale#360]
希望夜莺能支持通过http、tcp或udp上报metric。
相比agent周期运行脚本采集stdout，能更方便的push mertic信息，能更方便的与其他热门监控采集软件结合，比如influxdb的telegraf，netdata，fluentd等

虽然使用其他软件采集metric，暂存到本地，再通过脚本或者log-agent周期上报给夜莺也能实现上面的需求，但是总觉得有点别扭，不够方便。

当然，如果能直接支持其他热门监控采集系统的接入当然更好，可以最大化的借助已有的工具和生态。

**Comment by UlricQin** [comment]
夜莺支持tcp和http方式上报数据，但是每个软件都有自己的协议，未必通用。telegraf的协议是什么样子的，如何与夜莺整合，你这边能否出个详细方案我们讨论一下

**Comment by tongorz** [comment]
- 想法比较简单粗暴，起个http server，接收下telegraf采集的metric，然后翻译夜莺能接受的格式通过http再上报给夜莺就可以了。

- 夜莺tcp/http上报数据的接口和格式有文档和示例吗？

- telegraf的支持多种Input和Output格式
```
https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md
1. InfluxDB Line Protocol
2. Carbon2
3. Graphite
4. JSON
5. Prometheus
6. SplunkMetric
7. Wavefront
8. ServiceNow Metrics
```
- telegraf自家的influxdb协议格式如下
```
https://docs.influxdata.com/influxdb/v1.8/write_protocols/line_protocol_tutorial/
weather,location=us-midwest temperature=82 1465839830100400200
  |    -------------------- --------------  |
  |             |             |             |
  |             |             |             |
+-----------+--------+-+---------+-+---------+
|measurement|,tag_set| |field_set| |timestamp|
+-----------+--------+-+---------+-+---------+
```

- 夜莺支持telegraf采集的话
一是给telegraf贡献夜莺的output插件
二是在夜莺侧支持InfluxDB Line Protocol写入（例如时序数据库victoriametrics就做了influxdb line protocol的支持）
三就是最开始说的简单粗暴的方式，用户起个http server自己做写入格式的翻译

**Comment by tongorz** [comment]
> * 想法比较简单粗暴，起个http server，接收下telegraf采集的metric，然后翻译夜莺能接受的格式通过http再上报给夜莺就可以了。
> * 夜莺tcp/http上报数据的接口和格式有文档和示例吗？
> * telegraf的支持多种Input和Output格式
> 
> ```
> https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md
> 1. InfluxDB Line Protocol
> 2. Carbon2
> 3. Graphite
> 4. JSON
> 5. Prometheus
> 6. SplunkMetric
> 7. Wavefront
> 8. ServiceNow Metrics
> ```
> 
> * telegraf自家的influxdb协议格式如下
> 
> ```
> https://docs.influxdata.com/influxdb/v1.8/write_protocols/line_protocol_tutorial/
> weather,location=us-midwest temperature=82 1465839830100400200
>   |    -------------------- --------------  |
>   |             |             |             |
>   |             |             |             |
> +-----------+--------+-+---------+-+---------+
> |measurement|,tag_set| |field_set| |timestamp|
> +-----------+--------+-+---------+-+---------+
> ```
> 
> * 夜莺支持telegraf采集的话
>   一是给telegraf贡献夜莺的output插件
>   二是在夜莺侧支持InfluxDB Line Protocol写入（例如时序数据库victoriametrics就做了influxdb line protocol的支持）
>   (支持其他兼容的Format写入也可以，但promethues的可能不合适，prometheus不支持写入时间戳)
>   三就是最开始说的简单粗暴的方式，用户起个http server自己做写入格式的翻译

**Comment by tongorz** [comment]
@UlricQin  抱歉，误操作了issue，不小心给关闭了，希望能重新打开

**Comment by UlricQin** [comment]
夜莺支持两种监控数据格式，一种是endpoint字段不为空，称为设备相关指标，一类是是endpoint为空，nid不为空，称为设备无关指标，具体参考：https://github.com/didi/nightingale/wiki/%E4%BD%BF%E7%94%A8_01_%E7%9B%91%E6%8E%A7%E6%8C%87%E6%A0%87 ，如果想简单对接telegraf，按照你上面的描述，可以用设备无关指标的方式来对接，关键是想清楚nid这个字段怎么填，nid是组织结构树节点的id，一定程度起到了namespace的意义。

夜莺agent和transfer都提供上报数据的http接口，transfer还提供了rpc接口，代码在这里：

https://github.com/didi/nightingale/blob/master/src/modules/agent/http/router_collector.go#L14

https://github.com/didi/nightingale/blob/master/src/modules/transfer/http/routes/push_router.go#L13

rpc接口：

https://github.com/didi/nightingale/blob/master/src/modules/transfer/rpc/push.go#L20

可以先了解一下，回头微信联系我，我跟你远程聊一下如何搞

**Comment by tongorz** [comment]
好的，感谢。我先研究研究。
