### ISSUE TITLE
接入grafana用table展示的时候多个query时是否能聚合

### ISSUE THREAD

**Issue by liuyanmei069** [didi/nightingale#362]
希望多个query时能聚合
table这边能根据ip展示行，监控参数展示列
这个可以怎么配置实现呢
https://user-images.githubusercontent.com/25581778/97382758-0be5b100-1907-11eb-8492-83445c14709a.png

**Comment by UlricQin** [comment]
不会用grafana，谁对grafana比较熟可以给点建议~

**Comment by yilingyi** [comment]
我也有相同的问题，当前插件不支持哈。

**Comment by jsers** [comment]
@yilingyi 
https://github.com/n9e/grafana-n9e-datasource/issues/11

**Comment by UlricQin** [comment]
清理历史遗留issue，如有问题，请reopen
