### ISSUE TITLE
任务中心不能拷贝文件，急需这个功能

### ISSUE THREAD

**Issue by sjfbjs** [didi/nightingale#363]
![image](https://user-images.githubusercontent.com/24262176/97413713-11aab900-193e-11eb-8421-eaabaaea1857.png)

**Comment by UlricQin** [comment]
啥意思？是要分发文件？在有原始文件的机器上随便起个httpserver：`python -mSimpleHTTPServer` ，然后批量跑脚本在目标机器下载呗

**Comment by sjfbjs** [comment]
如果机器多了，效率不高，能不能在脚本执行的时候增加一个附件文件的功能，将此次需要的文件提前拷贝至对应路径，然后直接点击任务就可以执行了，不需要先将安装包一个个机器上传

**Comment by UlricQin** [comment]
如果不用p2p类的文件分发能力，都是硬抗，找个机器做下载机，发个wget命令去目标机器下载即可，和内置的文件分发能力没有本质区别
