### ISSUE TITLE
绘图bug：多个endpoint 有相同ifname，在选择ifname的时候无法细分ifname

### ISSUE THREAD

**Issue by Forward-Ky** [didi/nightingale#364]
**前端bug**   _例如我要绘制**2个**服务器的 共2个网卡的 流量：_
endpoint-1 的eth0网卡
endpoint-2 的eth1网卡
那么 选择iface的时候 无法细分ifcae应该归属哪个endpont；导致出图结果是 4个网卡；

希望前端优化 谢谢

**Comment by UlricQin** [comment]
这个夜莺无法做到，未来应该也不会支持，原因说起来比较复杂，是时序库的索引机制决定的
