### ISSUE TITLE
是否将构建出的二进制文件输出到独立的目录更合适？

### ISSUE THREAD

**Issue by smarkm** [didi/nightingale#367]
**What would you like to be added**:
将构建出的二进制文件放到独立的工作目录`target` 或者`build` 作为工作目录
**Why is this needed**:
将构建输出(程序的工作目录)独立于项目文件，方便本地开发和管理

**Comment by UlricQin** [comment]
现在的配置文件读取，是约定的方式，默认去进程工作目录下的etc下找，如果把二进制挪到一个单独的目录，这个约定就不好使了，需要把配置文件也挪过去，其实更不方便~

**Comment by smarkm** [comment]
> 现在的配置文件读取，是约定的方式，默认去进程工作目录下的etc下找，如果把二进制挪到一个单独的目录，这个约定就不好使了，需要把配置文件也挪过去，其实更不方便~

好的，我本地自己调整
