### ISSUE TITLE
算术和函数表达式支持 ?

### ISSUE THREAD

**Issue by zhiyuan192shine** [didi/nightingale#377]
Hi，请问是否有想法支持算术和函数表达式，类似Prometheus一样，很多场景需要对不同指标之间进行表达式计算来绘图和告警。如果支持表达式计算就更加灵活。

**Comment by UlricQin** [comment]
不支持，要监控什么指标还是需要在上报之前提前算好。商业版倒是支持一次流计算方式的指标计算，基于flink的，那个太重了没有开源
