### ISSUE TITLE
上报的数据中endpoint为自定义值，3.x里无法看见此值

### ISSUE THREAD

**Issue by zhiyuan192shine** [didi/nightingale#381]
针对业务指标监控时，在上报的数据中 endpoint 可能为自定义标识值，在 v2 版本 全部对象 中看见该自定义虚拟节点，v3 版无法有该节点。

**Comment by UlricQin** [comment]
是的，这个符合预期。v3演化成了运维平台，会有一些规范性的东西出来，endpoint只能是资产管理中心的设备。
如果是业务指标，可能没法很好的契合这个场景。此时建议：
上报的监控指标endpoint为空，设置nid字段，相当于把指标上报到某个节点上去，原本自定义的endpoint字段，可以作为tag上报，tagkey建议是instance，具体可以参考：https://github.com/didi/nightingale/wiki/%E4%BD%BF%E7%94%A8_01_%E7%9B%91%E6%8E%A7%E6%8C%87%E6%A0%87
