### ISSUE TITLE
关于节点ip获取失败的解决方法（全部对象不显示主机ip）

### ISSUE THREAD

**Issue by xiaobaiskill** [didi/nightingale#39]
```
/usr/sbin/ifconfig `/usr/sbin/route|grep '^default'|awk '{print $NF}'`|grep inet|awk '{print $2}'|head -n 1
```
在主机含有多网络时，该命令无法获取到节点ip,即全部对象不显示节点ip.需在collector.yaml  identity.specify手动设置该主机的ip

**Comment by UlricQin** [comment]
这个shell只是一个例子哈，之所以放到配置文件里，就是希望用户在自己的环境里改成合适的配置，并不是为了解决所有场景，请知悉哈
