### ISSUE TITLE
资源角色无法控制权限

### ISSUE THREAD

**Issue by xianshun163** [didi/nightingale#393]
**What happened**:
给一个用户分配的资源角色没有勾选任务执行中心的权限，但是该用户可以在任务执行中心对该节点的机器执行shell脚本
**What you expected to happen**:
希望通过资源角色可以控制某些用户只能查看监控的数据，不能在任务执行中心执行脚本
**How to reproduce it (as minimally and precisely as possible)**:
1、先配置资源角色：产品管理员，权限点只勾选监控子系统的功能
2、在组织资源树中选定一个部门节点，进行人员授权，角色选产品管理员
3、使用该账号登录，并进入到任务执行中心，执行shell脚本的时候选定上面的部门节点，并执行shell脚本
      授权的时候权限点没有勾，但是可以执行任务。
**Anything else we need to know?**:

**Environment**:
- OS (e.g: `cat /etc/os-release`): centos 7
- Logs: 
- Others:  版本是3.1.16

**Comment by UlricQin** [comment]
如果这个用户是超级管理员，就会有权限；如果这个用户是某个节点的管理员，也会无视人员权限页面的配置，对下面的所有子节点有权限。所以，检查一下这两点
