### ISSUE TITLE
告警列表详情页面，点击放大图表，页面打开空白

### ISSUE THREAD

**Issue by countingwww** [didi/nightingale#395]
**What happened**:

 如标题所示，告警列表中的任意一条记录，点击进入详情页面，再点击右上角放大图表的按钮，新出来的页面空白
v3.16 release版 ，前端 pub-v3.0.2.tar.gz
![image](https://user-images.githubusercontent.com/30268361/98908339-3b95db00-24fb-11eb-8226-b68cc536ccce.png)

![image](https://user-images.githubusercontent.com/30268361/98908607-a0513580-24fb-11eb-8b32-c238ecc28781.png)

**Comment by UlricQin** [comment]
我这没有复现，你是最新版chrome么？还有其他人也有这个问题么？

**Comment by countingwww** [comment]
刚刚更新了Google最新版本，尝试了一下，还是空页面。
我这边是Chrome是win10的系统装的。
下面是页面的调试模式信息。&nbsp; 
目前只有我这边装了一套在研究如何使用。 如果您那边无法复现的话，等下次我再装一套的时候，若是依旧复现再和你反馈。







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "UlricQin"<notifications@github.com&gt;; 
发送时间: 2020年11月12日(星期四) 下午3:56
收件人: "didi/nightingale"<nightingale@noreply.github.com&gt;; 
抄送: "时间偷走初衷"<871138993@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [didi/nightingale] 告警列表详情页面，点击放大图表，页面打开空白 (#395)





 
我这没有复现，你是最新版chrome么？还有其他人也有这个问题么？

**Comment by UlricQin** [comment]
其他人如果也遇到这个问题可以再打开issue
