### ISSUE TITLE
[bug] 树节点管理 灰色的删除按钮点击后弹出删除确认框,但文字提示根节点不能删除

### ISSUE THREAD

**Issue by nondevops** [didi/nightingale#4]
问题现象:
树节点管理 灰色的删除按钮点击后弹出删除确认框,但文字提示根节点不能删除
![image](https://user-images.githubusercontent.com/12181410/76966282-b143aa00-6960-11ea-8e19-ff54878fac16.png)

**Comment by UlricQin** [comment]
@jsers 帮看看哈

**Comment by jsers** [comment]
@nondevops 已修复
