### ISSUE TITLE
spring项目和数据库监控

### ISSUE THREAD

**Issue by Daniel777777** [didi/nightingale#40]
请问java spring项目和数据库可以进行监控吗？

**Comment by UlricQin** [comment]
java程序可以用jmx监控，参看 http://book.open-falcon.com/zh_0_2/usage/jmx.html
mysql可以用mymon监控，参看：https://github.com/n9e/mymon

**Comment by czxin788** [comment]
请问
java程序可以用jmx监控，参看 http://book.open-falcon.com/zh_0_2/usage/jmx.html
这个jmx监控的资料还有吗，新公司用的是夜莺v2.7版本，没看明白这个jmx是怎么监控的，在plugin目录和界面采集配置里面，都找不到关于jmx的配置，但是页面确实有jmx的监控数据。
