### ISSUE TITLE
Dingtalk发送通知配置需要支持不同的安全配置

### ISSUE THREAD

**Issue by smarkm** [didi/nightingale#400]
![image](https://user-images.githubusercontent.com/5517120/99073946-d244c380-25f1-11eb-9e2c-337c62fbf907.png)

**Comment by UlricQin** [comment]
告警内容里会展示P1还是P2告警，所以，自定义关键字这里写个“P”就行了，不是夜莺的问题...是钉钉的安全配置来适配夜莺的告警消息
