### ISSUE TITLE
查询监控数据点的接口返回值的step不对，对应不上数据的时间间隔

### ISSUE THREAD

**Issue by DemoLiang** [didi/nightingale#412]
**What happened**:
1. /api/transfer/data/ui 接口查询监控数据是，返回值的resp的step对不上的问题，无论请求1小时2小时，一天，返回值的step都是30S对应不上返回数据的timestamp 之间的间隔，主要发生在180S的step的时候有问题，也就是查看12小时区间的数据的时候比较明显

**What you expected to happen**:
1.正确的返回值应该是1小时是30S，其它时间的应该对应有相应的归档时间step

**How to reproduce it (as minimally and precisely as possible)**:
1.点击页面监控看图，开F12检查返回数据即可发现

**Anything else we need to know?**:

**Environment**:
- OS (e.g: `cat /etc/os-release`): centos
- Logs:
- Others:

**Comment by UlricQin** [comment]
step这个字段，是数据上报的频率，夜莺的监控数据上报的时候有个step字段，就是返回的那个字段。
不同的时间跨度返回的内容不同，是rrd的降采样和归档机制决定的。
这里无论什么情况都返回step是符合逻辑的。
另外马上要发布的M3DB的版本，step直接就不返回了，后面会慢慢弱化这个字段

**Comment by DemoLiang** [comment]
@UlricQin 其实现在的问题点可能在于，页面查询这个接口的时候，当查询6小时的时候，返回数据的step 依旧是30S，但是实际的values里面的相邻两根timestamp事90S的，这样就回导致前段页面画图不准确，无法用step计算标尺，正确的按理说应该是step返回90 ，这里的改动我看了下没有返回90的原因是计算了这个值，但是没有赋值返回
