### ISSUE TITLE
告警配置的与条件 似乎有问题

### ISSUE THREAD

**Issue by AlliotTech** [didi/nightingale#415]
当前的告警策略配置： 
![image](https://user-images.githubusercontent.com/24980252/99779834-9dd08a80-2b50-11eb-8c64-8cb020e74450.png)

当前的对应 matrics 的状态： 
![image](https://user-images.githubusercontent.com/24980252/99779868-a9bc4c80-2b50-11eb-81b2-cd5ac32679ac.png)

想实现的是  当proc.port.listen <1 与 file.lock.exist < 1都满足的时候  就报警    
当前的状态是满足告警的条件的。 但是并没有触发告警 。

单独配置 不使用 与 条件的时候，是能够分别触发告警的。

**Comment by AlliotTech** [comment]
Version: 3.1.6

**Comment by UlricQin** [comment]
持续10s。。。。你的采集周期是比10s小的？

**Comment by AlliotTech** [comment]
10s是为了测试的时候更快的触发告警。。。    
实际上我保持告警的条件持续不变   10分钟都没有触发告警。。。

**Comment by UlricQin** [comment]
上报频率如果是10s，这里至少要配置20s

**Comment by AlliotTech** [comment]
![image](https://user-images.githubusercontent.com/24980252/99784241-7da3ca00-2b56-11eb-9703-6b85d32c5d26.png)
![image](https://user-images.githubusercontent.com/24980252/99784294-90b69a00-2b56-11eb-8f32-a7ff7a57184a.png)

**Comment by UlricQin** [comment]
你端口那个metric有tag，另一个没有tag吧，与条件要保证tag一致

**Comment by AlliotTech** [comment]
策略中没有配置 TAG过滤。

难道说也要保证2个matrics的TAG数量一致么。。。 
![image](https://user-images.githubusercontent.com/24980252/99786468-7fbb5800-2b59-11eb-8f5d-93adcf376243.png)

**Comment by UlricQin** [comment]
那就不行，proc.port.listen有tag，就是说有很多不同端口的状态指标，系统如何判断是哪个端口呢。与条件的两个metric，必须是上报的数据的tag也一致。比如disk.io.util和disk.io.await这种，tag一致的才能做与条件

**Comment by AlliotTech** [comment]
你好~
现在添加了port这个TAG
![image](https://user-images.githubusercontent.com/24980252/99792674-64087f80-2b62-11eb-89eb-1a43962ad1ef.png)
依旧无法触发告警，意思就是说  
proc.port.listen 有 port  service 2个tag  那么跟他做与条件的  就必须得有这2个TAG  ？

**Comment by UlricQin** [comment]
是。而且tag的值也得一样才能做与。比如metric_a有个tag叫service，metric_b也有个tag叫service，service表示服务，我们这里以transfer这个服务举例：

`metric_a/service=transfer`表示transfer这个服务的metric_a指标
`metric_b/service=transfer`表示transfer这个服务的metric_b指标

此时metric_a和metric_b可以做与条件，相当于transfer这个服务的指标a满足某个条件并且transfer这个服务的指标b也满足某个条件才报警。

如果另一个服务，比如judge也有指标a和指标b，那就会有另外两个series：

```
metric_a/service=judge
metric_b/service=judge
```

如果与条件配置了metric，没有配置tag，系统做与条件的时候，只对tag key & tag value都相同的指标来判断，所以就不会乱，judge的两个指标自行做与，transfer的两个指标自行做与。

**Comment by AlliotTech** [comment]
这样在规划matrics的时候太容易留坑。。。   两个matrics与条件     如果能够对每个matrics设定tag过滤  判断的时候只针对值来   这样就方便多了。。

**Comment by UlricQin** [comment]
可以用tag过滤呀，但是两个做与条件的metric必须保证上报的监控数据的tag相同，维度都不同自然是没法做与条件判断

**Comment by AlliotTech** [comment]
![image](https://user-images.githubusercontent.com/24980252/99940660-935bfe00-2da7-11eb-9234-d17acdaf67b1.png)
![image](https://user-images.githubusercontent.com/24980252/99940663-97881b80-2da7-11eb-8e52-9a86029ee5ef.png)
![image](https://user-images.githubusercontent.com/24980252/99940665-9a830c00-2da7-11eb-984a-eafe9a9951b3.png)
![image](https://user-images.githubusercontent.com/24980252/99940669-9ce56600-2da7-11eb-9641-7bfee6892f63.png)

**Comment by UlricQin** [comment]
@710leo  看看，两个指标上报的tag一样，策略里用了标签过滤，没有报警，看看是否符合预期

**Comment by 710leo** [comment]
@AlliotTech 可以更新到最新版本再试一下

**Comment by AlliotTech** [comment]
先憋几个版本吧   看3.3.1需要更新agent    机器多了更新起来怕出问题
