### ISSUE TITLE
建议-ams支持未分配租户过滤

### ISSUE THREAD

**Issue by xianshun163** [didi/nightingale#416]
**What would you like to be added**:
![image](https://user-images.githubusercontent.com/32457473/99924963-23358400-2d77-11eb-96d9-871d50bcf7eb.png)
1、资产管理子系统查询页面租户选择那里希望可以增加未分配租户的条件，以便方便找出哪些机器还需要分配租户
2、agent那边也建议可以指定默认注册的租户，这样就不需要每次都到资产管理子系统来分配租户
**Why is this needed**:
1、机器多了之后，每次增加一台机器就要到资产管理子系统来把机器分配到租户才能使用，如果只使用一个租户这个步骤就有点多余，如果有很多租户，机器很多的时候，现在的资产管理子系统的查询条件没有一个条件可以快速过滤所有未分配租户的机器。

**Comment by AlliotTech** [comment]
未分配租户 这个真是太同意不过了。。

**Comment by wangwei0326** [comment]
希望添加通过agent配置来注册租户功能

**Comment by UlricQin** [comment]
最新版本支持过滤未分配租户了

**Comment by UlricQin** [comment]
> 希望添加通过agent配置来注册租户功能

这个3.5.1也是支持的，在fields字段下面配置一个`tenant: echo inner`就表示把机器自动给inner租户。echo后面写的是租户的ident
