### ISSUE TITLE
n9e使用shell方式sender插件发送报警信息时总是超时

### ISSUE THREAD

**Issue by chengjiahua** [didi/nightingale#418]
**What happened**:
n9e使用shell方式利用sender插件发送报警信息时总是超时的问题
**How to reproduce it (as minimally and precisely as possible)**:

已经定位到问题。

n9e的报警逻辑是报警信息在redis里面，sender从redis里面获取报警信息然后在通过mail，im或者其他方式发送报警。本人测试mail用smtp形式测试成功，im用wechat，wechat_robot，dingtalk_robot形式均测试成功，其他未测。

但当我用shell脚本形式测试时，出现问题了，rdb的info日志总是提示超时

最初的想法可能是redis操作超时，于是便把mail-sender插件配置文件的超时调大
发现问题依旧存在。于是开始看插件源码，经过问题定位，发现超时的原因时卡在插件redis操作这里reply, err := redis.String(rc.Do("RPOP", queue))这条语句，进入redis查看，发现没有queue这个key

顿时觉得问题复杂了起来，想不明白。只能再看夜莺的rdb服务代码，仔细阅读后发现问题所在。

原来在n9e监控平台这里，不管时哪种方式报警，都会对redis操作 ，把redis的报警信息提出来之后就删掉了（防止一次报警发送多次），然而sender插件这边又对redis进行操作，这时候已经没有了数据  所以获取为空，一直卡住。日志就会报超时的错误。

个人认为应该是监控sender插件没有及时更新，与夜莺监控平台这边出现了脱节。

解决方案，插件代码修改，将对redis的操作去掉，直接用平台调用shell的arg信息发送报警信息。
（刚发现问题就来提问题啦，自己还没有改插件代码）

**Comment by UlricQin** [comment]
如果你用的v3版本，已经不需要使用各sender模块了。发送能力已经内置了。如果想用shell发送告警，看script目录下的两个shell样例即可，把那个脚本改成调用远端接口发送即可
