### ISSUE TITLE
大屏或者即时看图里多曲线显示优化

### ISSUE THREAD

**Issue by xroa** [didi/nightingale#419]
能不能把看图的曲线按曲线数值大小排序  或者鼠标在的曲线的数值高亮显示  要不肉眼解析有点儿困难

**Comment by xroa** [comment]
![image](https://user-images.githubusercontent.com/39758055/100219373-e0c79f00-2f50-11eb-8888-1f3eae8c465c.png)
类似Grafana的这样

**Comment by UlricQin** [comment]
清理历史遗留issue，如有问题，请reopen
