### ISSUE TITLE
磁盘摘掉之后还一直上报disk.io.utils数据

### ISSUE THREAD

**Issue by yongjianchn** [didi/nightingale#423]
**What happened**:
拔掉一块盘之后，collector还会一直上报这块盘的io.utils，必须重启collector才能解决。
**What you expected to happen**:
拔掉盘之后，停止这块盘的探测和上报。
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OS (e.g: `cat /etc/os-release`):
- Logs:
- Others:

**Comment by UlricQin** [comment]
夜莺读取的是OS提供的信息，你所谓的“拔盘”在OS层面还能看到，夜莺就能看到

**Comment by yongjianchn** [comment]
fdisk之类的都看不到了，/dev/sdx也不存在了，我简单看了一下夜莺代码，貌似只能识别到新增盘，识别不到剔除盘。

**Comment by UlricQin** [comment]
/proc/diskstats 还在

**Comment by yongjianchn** [comment]
确认过了，/proc/diskstats里不存在 sde，n9e-collector还在持续上报 sde的数据。

**Comment by yongjianchn** [comment]
我简单说一下我们的使用场景，我们发现线上某SSD坏了，io.utils一直报警100%，然后运维上去把盘从系统里摘除了，然后在报警系统里把”未恢复报警“中的相关报警信息”忽略“了。但是过一段时间，这块盘的报警又出现了。

我们使用的版本是2.6.1，但是看咱们开发计划，2.x已经不更新了，我们抽空自己改改代码吧。但是我猜测这个问题3.x应该也有，所以跟你们汇报一下。
