### ISSUE TITLE
数据库表结构与代码中定义的 xorm 框架 model 不一致

### ISSUE THREAD

**Issue by lostyear** [didi/nightingale#425]
sql 文件中给出的表结构定义中，主键 ID 均为 unsigined int，但是代码中 id 字段用的都是 int64

xorm 框架中的 int64 字段应该是对应数据库的 BigInt 类型， 数据库用 unsigned 的话，使用代码中字段定义用 uint64 应该会更匹配一点。

这个逻辑上不会出现问题，只是仔细看的话感觉不太合理。

[sql文件](/didi/nightingale/blob/master/sql/n9e_rdb.sql)
[代码文件](/didi/nightingale/blob/master/src/models/user.go)

**Comment by UlricQin** [comment]
xorm中int64的Id会自动识别为主键，代码处理过程中uint64也会带来不便，不要掉书袋哈

**Comment by lostyear** [comment]
> xorm中int64的Id会自动识别为主键，代码处理过程中uint64也会带来不便，不要掉书袋哈

我其实主要是觉得数据库里面字段不是 bigint 不太好

**Comment by UlricQin** [comment]
实际数据没有那么大，不需要bigint
