### ISSUE TITLE
rdb的api接口返回资源数据不全

### ISSUE THREAD

**Issue by xfwilliam** [didi/nightingale#437]
1. 通过超管的token权限获取node节点下的所有资源，多次测试最多只返回20个资源的json数据，超过的资源数据没有返回：
curl -v -H "X-User-Token: xxxxxxxxxxxxxxx" 'http://xxxxxxxxxxxxxxx/api/rdb/node/2/resources'
2. 安装的是n9e的3.3.0版本，rdb日志无异常信息。

**Comment by UlricQin** [comment]
有分页机制，撸一下代码就知道了，看看前端发起的请求也能看出来
