### ISSUE TITLE
邮件报警发送多个对象的一个bug

### ISSUE THREAD

**Issue by chengjiahua** [didi/nightingale#439]
场景：邮件报警，配置了多个发送对象，如果有一个或者多个对象的邮箱名错误，则会导致所有对象都接受不到报警信息。理想情况应该是配置错误的对象接收不到报警信息，而配置成功的对象是可以接收到报警信息。

bug定位：发送邮件时，采用的是gomail包中的NewMessage()函数，接受人To的配置为字符串数组，这会导致多个接收人将被视为一个人，只发送一次，只要其中有人的邮件格式不正确，则会导致发送失败。

解决办法（以实现）：
采用多次发送的方式，一次只发送给一个人。就可以避免这个问题，达到理想情况。

**Comment by UlricQin** [comment]
这是个好问题，这样处理确实会容错你说的场景，但是邮件发送就会拆成很多次，一个是增加了smtp的负担，另一个更重要的，是我收到告警消息之后，我不知道是否还有别人收到，有时一个告警出来，如果我有一些结论会直接reply all，这样相关的人就都知道了，但是如果接收人只有我，这个就比较麻烦了。之前考虑过实现成单个的，但是因为上述原因，还是用了现在的方式

**Comment by UlricQin** [comment]
清理历史遗留issue，如有问题，请reopen
