### ISSUE TITLE
即时看图BUG

### ISSUE THREAD

**Issue by y-andybaba** [didi/nightingale#443]
1.修改 采集配置-进程-   修改原来的监控项的名称及service名称。
2.在即时看图中查看进程图形还显示原来的 名称及service
![image](https://user-images.githubusercontent.com/67846787/101280977-637d1380-3807-11eb-8d5b-e3fe32e5f6c5.png)

采集配置-端口也有这样的问题，请问大神，是我设置的问题吗？

**Comment by UlricQin** [comment]
老的索引已经建立了，会在25小时之后自动删除，明天就看不到了
