### ISSUE TITLE
不同机房主机相同ip不能上报吗？

### ISSUE THREAD

**Issue by xupeng9** [didi/nightingale#448]
3.3版本
agent安装在不同机房，但是机房配置的ip有重合了。现在agent上报数据只有一个ip的数据，无法区分？
请问在不能修改主机ip的情况下这个问题怎么解决区分？

**Comment by UlricQin** [comment]
identity.yml 里边有个ident配置，默认取的是 本机ip，可以改成别的，比如加个前缀啥的

**Comment by xupeng9** [comment]
加了不管用

**Comment by xupeng9** [comment]
只显示一台主机另外一台不显示，2.8版本是可以的。而且报警会2台一起报！

**Comment by xupeng9** [comment]
@UlricQin

**Comment by xupeng9** [comment]
> identity.yml 里边有个ident配置，默认取的是 本机ip，可以改成别的，比如加个前缀啥的

我看了agent上报后，2台主机共用了同一个UUID。

**Comment by UlricQin** [comment]
ams库里的host表，把ip的唯一索引去掉

**Comment by xupeng9** [comment]
OK，谢谢
