### ISSUE TITLE
issue: 进程监控-使用命令行采集进程指标  与实际进程状态不符

### ISSUE THREAD

**Issue by AlliotTech** [didi/nightingale#450]
目标进程为java，通过pid找到cmdline，填入监控平台的进程采集里，采集到的数据一直为0  。

 
![image](https://user-images.githubusercontent.com/24980252/101734679-9f5ff380-3afb-11eb-9baf-e20b7c7edb92.png)

![image](https://user-images.githubusercontent.com/24980252/101734633-93743180-3afb-11eb-8c87-ac2f72478d36.png)

![image](https://user-images.githubusercontent.com/24980252/101734487-5019c300-3afb-11eb-92df-9c8a24e3d380.png)

**Comment by UlricQin** [comment]
复制我下面的内容填入cmdline试试，可能有特殊字符：

```
util.VideoCallbackQueue
```

**Comment by AlliotTech** [comment]
我这边用这个字段来筛选的话 会出现2个或以上的进程  因为有另外一个进程也包含这个字段 。    
![image](https://user-images.githubusercontent.com/24980252/101735575-1053db00-3afd-11eb-9416-078e0fec93a1.png)

**Comment by AlliotTech** [comment]
``` shell
# cat cmdline 
/home/jdk/bin/javacom.ovp.util.VideoCallbackQueue 
```

``` shell
# ps -ef|grep VideoCallbackQueue
root     14170 14169  2 Dec04 ?        03:23:00 /home/jdk/bin/java com.ovp.util.VideoCallbackQueue
```
似乎是 `cmdline` 去掉了空格，在采集配置里添加上空格后 采集数据正常了   
跟文档中说的可能有些不一致。   文档可能需要修改一下  
![Uploading image.png…]()

**Comment by AlliotTech** [comment]
已在  [wiki](https://github.com/didi/nightingale/wiki/%E4%BD%BF%E7%94%A8_20_%E8%BF%9B%E7%A8%8B%E7%9B%91%E6%8E%A7) 中注明、

**Comment by UlricQin** [comment]
我知道原因了。最开始的代码是会自动处理空格的问题，后来有一个版本社区提了一个PR，增加了内存cpu和mem的采集，换了一个lib来获取进程的cmdline，这个新的lib处理cmdline空格的问题和之前不同了

**Comment by AlliotTech** [comment]
图表中的target又是自动处理空格的  与配置时候不一致  感觉改成一致比较合适。
