### ISSUE TITLE
suggest：  策略总览图与采集策略总览图

### ISSUE THREAD

**Issue by AlliotTech** [didi/nightingale#451]
**What would you like to be added**:
是不是考虑增加一个能够方便查看全局策略的配置的地方    

**Why is this needed**:
因为机器多  节点多 所以有时候配了策略都不知道哪些节点配置了策略 配置了哪些策略。需要一个个节点去找。。  加上策略有继承性   找起来就很麻烦。。

**Comment by UlricQin** [comment]
后面会把继承的父节点的策略展示出来

**Comment by itwenjian** [comment]
这个确实体验不是很好，有计划啥时候上线吗

**Comment by UlricQin** [comment]
> 这个确实体验不是很好，有计划啥时候上线吗

暂无计划

**Comment by UlricQin** [comment]
清理历史遗留issue，如有问题，请reopen
