### ISSUE TITLE
日志采集模块，如果日志打印比较慢，会出现cnt指标为0的情况

### ISSUE THREAD

**Issue by jjy96** [didi/nightingale#457]
日志采集目前会每10秒填充一次tms并赋值为-1，会导致如果worker latestTms比较老，且新日志打印在当前周期前10秒之后(也即已经出发过一次指标上报的情况，会出现日志cnt指标为0值，新上报的日志无效)。考虑是否需要加入如下判断：
![image](https://user-images.githubusercontent.com/38353946/102047623-89fb0a00-3e18-11eb-8fe8-cbc605c7c6f0.png)

**Comment by lixz3321** [comment]
我遇见的情况是采集数据不全，只有在采集时间点上的日志才会被采集。我设置了采集周期为10s，我的测试程序会每5s写一条带“ERROR”字符的日志行，我的采集正则就是要匹配ERROR字符串，但是我发现每个采集周期cnt都为1（每5s一条，10s内应该2条），后来我修改了日志打印频率，发现是只有和采集时间点一致时间戳的日志行才会被读到和做正则匹配，周期内其他数据点的数据都丢失了

**Comment by UlricQin** [comment]
清理历史遗留issue，如有问题，请reopen
