### ISSUE TITLE
如何彻底删除某个节点的某些metric的索引

### ISSUE THREAD

**Issue by leon0908** [didi/nightingale#466]
正在测试prometheus-exporter-collector，测试配置里带上了两个tag(dept, region)，测试完毕后，想正式上线，取消了apped tag，并且调用api/tsdb/del-rrd-by-counter接口删除了老的数据（已无法在监控界面看到数据
但是在夜莺查看监控数据，始终会有(dept, region)这两个tag，如不勾选取消，则无法查看新的数据
已尝试调用api/index/counter，api/index/metrics， api/tsdb/update-index 这三个接口，但是依然无法正常显示，求大佬指点

**Comment by UlricQin** [comment]
删除索引是用的：https://github.com/didi/nightingale/wiki/%E8%BF%90%E7%BB%B4_05_%E7%B4%A2%E5%BC%95%E7%9B%B8%E5%85%B3 检查下调用的对不对哈，特别是参数

**Comment by UlricQin** [comment]
清理历史遗留issue，如有问题，请reopen
