### ISSUE TITLE
部署m3db集群版时"error":"context deadline exceeded"

### ISSUE THREAD

**Issue by chengjiahua** [didi/nightingale#469]
按照部署_01_m3db接入的要求部署m3db的集群版是

初始化 m3dbnode database
修改 ./m3db/scripts/01-create-db.sh 后，执行：

这一步执行时，会出现{"error":"context deadline exceeded"}的错误
对于m3db也不是很熟，不知道问题出在哪

![image](https://user-images.githubusercontent.com/53223456/103070390-4c5a6600-45fc-11eb-99d4-14cafbbf3d8d.png)

**Comment by UlricQin** [comment]
找4台机器，一台作为部署机，剩下三台作为M3dbnode，严格按照脚本执行，create-db的时候address和id写那3台m3dbnode机器的ip，其他不用动，理论上会成功
