### ISSUE TITLE
对AWS SES的支持

### ISSUE THREAD

**Issue by FredCof** [didi/nightingale#470]
**What would you like to be added**: 邮件配置中加入对AWS SES的支持，目前使用AWS的邮件认证用户名配置无法通过gomail的校验，使用邮箱又通不过认证。

**Why is this needed**: 公司的邮件服务使用的AWS，希望可以继续使用。

**Comment by UlricQin** [comment]
是smtp协议么

**Comment by FredCof** [comment]
> 是smtp协议么

是的，smtp协议，但是认证的用户名是一串字母，配置到系统的时候无法通过gomail的邮箱格式校验

**Comment by UlricQin** [comment]
手工改gomail的代码，去掉格式验证代码重新编译试试
