### ISSUE TITLE
在虚拟机上装包报“未知的主机”

### ISSUE THREAD

**Issue by mqzdh** [didi/nightingale#471]
报错日志为：
2020-12-25 17:12:29.181692 ERROR stra/cron.go:36 get collect err:get collects from remote:http://10.16.1.73:5800/api/portal/collects/ens160: 未知的主机
ifconfig: `--help' gives usage information. failed, error:parse "http://10.16.1.73:5800/api/portal/collects/ens160: 未知的主机\nifconfig: `--help' gives usage information.": net/url: invalid control character in URL

排查过程，
存在ens160网卡，通过/usr/sbin/route|grep '^default'|awk '{print $NF}'  查看返回了两个ens160，但通过ifconfig看只有一个ens160网卡。

**Comment by UlricQin** [comment]
读一下readme，identity.yml里有两条shell，需要能够获取本机ip，如果获取不到，要修改这俩shell，改成一个可以获取你本机ip的shell

**Comment by mqzdh** [comment]
请问readme，identity.yml是在client里面吗？另外目前我通过修改60_uptime.sh和60_plugin_status.py已经可以获取到本级IP了，但是无法将服务器监控信息（如CPU、内存、端口监听情况等）上传至夜莺server端，这种要如何排查问题？
