### ISSUE TITLE
当收集数据大于24小时后，在页面上无法显示

### ISSUE THREAD

**Issue by jc1981** [didi/nightingale#474]
当时服务器数据异常，临时关闭了客户端中的collector，在与技术反馈问题进行排查时，24小时内的监控数据还可以正常显示；由于问题过于复杂，问题处理时间超过了24小时，结果在页面上进行查看，无任何数据，查看的数据已经改为大于2天，7天，30天都无法进行查看，之后重新开启客户端中的collector，后，数据又可以正常查看了，这是什么原因呢

版本：2.7.2

**Comment by UlricQin** [comment]
是因为索引数据会存25小时，因为agent停掉了，索引数据就不更新了，25h后就删了
