### ISSUE TITLE
ERROR: Service 'web' failed to build 

### ISSUE THREAD

**Issue by gmdashan** [didi/nightingale#481]
**What happened**:

#docker-compose up -d
Building web
Step 1/5 : FROM nginx
 ---> f35646e83998
Step 2/5 : WORKDIR /home/n9e
 ---> Using cache
 ---> 084fbf52a169
Step 3/5 : COPY nginx.conf /etc/nginx
 ---> Using cache
 ---> 5450c03e0db4
Step 4/5 : ADD http://116.85.64.82/pub.tar.gz .
ERROR: Service 'web' failed to build : ADD failed: failed to GET http://116.85.64.82/pub.tar.gz with status 404 Not Found: 404 page not found

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OS (e.g: `cat /etc/os-release`):
- Logs:
- Others:

**Comment by UlricQin** [comment]
重新试试，pub.tar.gz 这个包误删了
