### ISSUE TITLE
监控大盘或者其他监控，磁盘能否修改单位

### ISSUE THREAD

**Issue by codeworld-GitHub** [didi/nightingale#485]
**What would you like to be added**:
监控大盘或者其他监控，磁盘能否修改单位，还有 比如我只监控/dev/mapper/centos-root 这个目录下的 总数，已使用，剩余，使用率等信息，感觉并不是很好显示，
纯数字的磁盘还是到字节的，根本不好看
饼图的目录使用率也是不同目录间的使用率，根本体现不出来

比如：这样的一些数字

$> df -h | grep /dev/mapper/centos-root
/dev/mapper/centos-root  192G  117G   75G   62% /

**Why is this needed**:

**Comment by UlricQin** [comment]
没法修改。可以尝试自己写个插件，获取相关指标数据，用自己喜欢的单位
