### ISSUE TITLE
提供tsdb生产扩容文档

### ISSUE THREAD

**Issue by ermazi** [didi/nightingale#49]
rt

**Comment by valyala** [comment]
It would be great to add support for storing data to [VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md).

**Comment by UlricQin** [comment]
https://n9e.didiyun.com/docs/operation/tsdb/#%E5%AD%98%E5%82%A8%E6%89%A9%E5%AE%B9
