### ISSUE TITLE
有计划支持国产数据库吗？例如达梦

### ISSUE THREAD

**Issue by springrain** [didi/nightingale#495]
**What would you like to be added**:

**Why is this needed**:

**Comment by UlricQin** [comment]
你是说夜莺本身的告警策略、告警事件存到达梦里，还是支持对达梦的监控指标采集？

**Comment by springrain** [comment]
> 你是说夜莺本身的告警策略、告警事件存到达梦里，还是支持对达梦的监控指标采集？

都有吧，优先能够把数据保存到达梦数据库，其次最好也能监控达梦数据库性能指标

**Comment by UlricQin** [comment]
1、我们都是用的mysql，不知道达梦是否支持mysql协议，如果完全兼容，那就可以直接用
2、达梦数据库性能指标，这个我们不会直接提供，我们主要做平台，达梦的性能指标采集，希望社区能有人来搞

**Comment by springrain** [comment]
> 1、我们都是用的mysql，不知道达梦是否支持mysql协议，如果完全兼容，那就可以直接用
> 2、达梦数据库性能指标，这个我们不会直接提供，我们主要做平台，达梦的性能指标采集，希望社区能有人来搞

达梦和mysql语法不完全兼容,我准备fork出来把xorm换成zorm,兼容达梦数据库,信创国产化还是很有市场的.
