### ISSUE TITLE
[bug] 树节点管理中 节点重命名及创建子节点 不能有中文

### ISSUE THREAD

**Issue by nondevops** [didi/nightingale#5]
问题现象:
树节点管理中 节点重命名及创建子节点 不能有中文
![image](https://user-images.githubusercontent.com/12181410/76967642-a722ab00-6962-11ea-9104-3e625ba129a4.png)

**Comment by UlricQin** [comment]
这个不是bug，是故意这么设计的。树节点名字当前不允许中文。
