### ISSUE TITLE
server.go:3061: http: Accept error: accept tcp [::]:5820: accept4: too many open files; retrying in 1s

### ISSUE THREAD

**Issue by LeotLiu** [didi/nightingale#50]
日志logs/tsdb下面的stdout.log，一直在产生error：
2020/03/31 23:14:57 server.go:3061: http: Accept error: accept tcp [::]:5820: accept4: too many open files; retrying in 1s
2020/03/31 23:14:58 server.go:3061: http: Accept error: accept tcp [::]:5820: accept4: too many open files; retrying in 1s
2020/03/31 23:14:59 server.go:3061: http: Accept error: accept tcp [::]:5820: accept4: too many open files; retrying in 1s
2020/03/31 23:15:00 server.go:3061: http: Accept error: accept tcp [::]:5820: accept4: too many open files; retrying in 1s
2020/03/31 23:15:01 server.go:3061: http: Accept error: accept tcp [::]:5820: accept4: too many open files; retrying in 1s
2020/03/31 23:15:02 server.go:3061: http: Accept error: accept tcp [::]:5820: accept4: too many open files; retrying in 1s
2020/03/31 23:15:03 server.go:3061: http: Accept error: accept tcp [::]:5820: accept4: too many open files; retrying in 1s

其他信息：
-bash-4.2# ss -ntlp |grep 58
LISTEN     0      128    127.0.0.1:6379                     *:*                   users:(("redis-server",pid=15810,fd=6))
LISTEN     0      128         :::2058                    :::*                   users:(("n9e-collector",pid=13725,fd=12))
LISTEN     0      128         :::5840                    :::*                   users:(("n9e-judge",pid=13699,fd=14))
LISTEN     0      128         :::5841                    :::*                   users:(("n9e-judge",pid=13699,fd=11))
LISTEN     0      128         :::5810                    :::*                   users:(("n9e-transfer",pid=13639,fd=13))
LISTEN     0      128         :::5811                    :::*                   users:(("n9e-transfer",pid=13639,fd=12))
LISTEN     129    128         :::5820                    :::*                   users:(("n9e-tsdb",pid=13656,fd=12))
LISTEN     0      128         :::5821                    :::*                   users:(("n9e-tsdb",pid=13656,fd=13))
LISTEN     0      128         :::5830                    :::*                   users:(("n9e-index",pid=13672,fd=13))
LISTEN     0      128         :::5831                    :::*                   users:(("n9e-index",pid=13672,fd=12))
LISTEN     0      128         :::5800                    :::*                   users:(("n9e-monapi",pid=13620,fd=18))

**Comment by UlricQin** [comment]
跟夜莺无关，是你的机器文件句柄使用过多，调大文件句柄就行了

**Comment by LeotLiu** [comment]
确实是这个情况，调整了，谢谢！
