### ISSUE TITLE
升级3.4.0后出现负载突增情况

### ISSUE THREAD

**Issue by AlliotTech** [didi/nightingale#500]
版本均为最新3.4.0
index与transfer占用CPU很高 ，这期间没有新增过任何机器 只是升级了组件  
机器数量400左右   4核8G  
 
不知道各位有没有这种情况。
![image](https://user-images.githubusercontent.com/24980252/104153019-316d5b80-541c-11eb-908f-405fa5252f40.png)
![image](https://user-images.githubusercontent.com/24980252/104153171-9aed6a00-541c-11eb-95e0-29a558539572.png)

另外就是一批机器正常上报数据 但是告警判断为失联状态，但是在实时监控里看到的数据又是正常上报的。

**Comment by UlricQin** [comment]
失联状态通常是时间不同步导致的

**Comment by AlliotTech** [comment]
失联我看了一下 恢复后还是展示在 未恢复列表里 不知道是BUG还是说本身就是这样。。。
负载的话  确实一直在报  loadavag跑到10几了    index与transfer 占用高  升级之前基本没啥负载

**Comment by UlricQin** [comment]
失联我看了一下 恢复后还是展示在 未恢复列表里
----
就是这样的。nodata告警比较特殊。

负载高重启一下进程试试？另外看看index模块的这个指标：n9e.index.index.all.in ，看7天的

**Comment by AlliotTech** [comment]
![image](https://user-images.githubusercontent.com/24980252/104177581-f848e180-5443-11eb-95b9-0ee51c6bcba3.png)

**Comment by UlricQin** [comment]
看起来突然多了不少指标。像是积压了，之后连通了上报导致的。

**Comment by AlliotTech** [comment]
持续到了现在   进程重启试过了   
积压的话 升级前指标都是正常的  
升级时间在半小时以内 按道理一天过去了 应该索引玩了

**Comment by UlricQin** [comment]
index和tsdb在3.4.0都没有代码变更。可能的原因主要是指标数量变多了，index有个接口来统计索引数量：/api/index/index-total 不过只能看到最新的。另外群里其他人也没有反馈，所以主要的可能点是指标数量变多了

**Comment by AlliotTech** [comment]
尝试清理了时序库 并重启所有组件，负载下来了。
