### ISSUE TITLE
单独安装客户端监控列表是空的

### ISSUE THREAD

**Issue by huangchangbao333** [didi/nightingale#502]
你好，我在单独安装客户端的时候遇到一个问题，按照视频安装完成后，资产管理能发现设备，任务中心也能正常执行任务，但是设备管理监控列表是空的。只有单独安装的客户端出现这个问题，前面部署的服务就没有这个问题。我是单独安装客户端少配置了哪些东西吗？
![image](https://user-images.githubusercontent.com/26081028/104177406-9e72f800-5400-11eb-9047-078f9fd39936.png)
![image](https://user-images.githubusercontent.com/26081028/104177433-a894f680-5400-11eb-8b0e-c13a7fe22a49.png)

**Comment by UlricQin** [comment]
基本的点查了么，比如日志

**Comment by huangchangbao333** [comment]
> 基本的点查了么，

客户端的日志除了INFO都是空的，INFO里也没看出什么问题。是部署客户端的时候，漏了哪个文件吗？

**Comment by UlricQin** [comment]
你的agent侧的identity.yml贴一下

**Comment by huangchangbao333** [comment]
> 你的agent侧的identity.yml贴一下

![image](https://user-images.githubusercontent.com/26081028/104266001-b9f60580-54c9-11eb-8540-3248ac7cd2b9.png)
# 用来做心跳，给服务端上报本机ip
ip:
  specify: ""
  shell: ifconfig `route|grep '^default'|awk '{print $NF}'`|grep inet|awk '{print $2}'|head -n 1|awk -F':' '{print $NF}'

# MON、JOB, judge, prober 的客户端拿来做本机标识
ident:
  specify: "nx-NodeJs.2020"
  shell: echo 'Nginx-NodeJs.2020'

**Comment by UlricQin** [comment]
截图里边看到的设备标识是：
![image](https://user-images.githubusercontent.com/2769466/104266358-72bc4480-54ca-11eb-8c47-2b1774e00077.png)

但是你的配置文件是：nx-NodeJs.2020

没有对应上。。

要检查一下你的配置和使用方法了

**Comment by huangchangbao333** [comment]
这个是正常显示监控指标的
![image](https://user-images.githubusercontent.com/26081028/104268006-e01da480-54cd-11eb-8ef4-426cd2af038b.png)
客户端，把shell改回获取IP就获取得到，改成Nginx-NodeJs.2020没有。
![Uploading image.png…]()
都改成改成Nginx-NodeJs.2020没有也是这样。

**Comment by huangchangbao333** [comment]
> 截图里边看到的设备标识是：
> ![image](https://user-images.githubusercontent.com/2769466/104266358-72bc4480-54ca-11eb-8c47-2b1774e00077.png)
> 
> 但是你的配置文件是：nx-NodeJs.2020
> 
> 没有对应上。。
> 
> 要检查一下你的配置和使用方法了
这个是正常显示监控指标的
![image](https://user-images.githubusercontent.com/26081028/104268006-e01da480-54cd-11eb-8ef4-426cd2af038b.png)
客户端，把shell改回获取IP就获取得到，改成Nginx-NodeJs.2020没有。
![image](https://user-images.githubusercontent.com/26081028/104268145-2f63d500-54ce-11eb-81e6-6ebbc8c26024.png)
都改成改成Nginx-NodeJs.2020没有也是这样。

**Comment by huangchangbao333** [comment]
这个是正常显示监控指标的
![image](https://user-images.githubusercontent.com/26081028/104268006-e01da480-54cd-11eb-8ef4-426cd2af038b.png)
客户端，把shell改回获取IP就获取得到，改成Nginx-NodeJs.2020没有。
![image](https://user-images.githubusercontent.com/26081028/104268145-2f63d500-54ce-11eb-81e6-6ebbc8c26024.png)
都改成改成Nginx-NodeJs.2020没有也是这样。

**Comment by UlricQin** [comment]
把ams里的设备删了，重新启动agent

**Comment by huangchangbao333** [comment]
> 把ams里的设备删了，重新启动agent

凉凉，现在不管是默认的空字符+ip，还是两个一样的中文名称，或者中文名称+ip，都没有监控指标了。

**Comment by UlricQin** [comment]
对系统原理还不熟悉的情况下不要自我创造，先按照默认的方式让它work...

**Comment by huangchangbao333** [comment]
> 对系统原理还不熟悉的情况下不要自我创造，先按照默认的方式让它work...

是的，不过重新从http://116.85.64.82/n9e.tar.gz下载的版本登录不了，前端版本也一直提示浏览器版本过低。所以什么都没干又恢复了原来的版本，监控指标又都能正常显示了。问一下是否从GitHub下载的版本比较稳定一些？

**Comment by UlricQin** [comment]
清理历史遗留issue，如有问题，请reopen
