### ISSUE TITLE
github.com\didi\nightingale\src\models\node.go 代码bug 容易导致panic

### ISSUE THREAD

**Issue by chixianliangGithub** [didi/nightingale#506]
637行代码只判断err不为nil 没有判断node 是否为nil如果node 为nil将为导致panic

	node, err := NodeGet("id=?", nid)
	if err != nil  {
		return nids, err
	}

	nodes, err := node.RelatedNodes()

**Comment by UlricQin** [comment]
3ks，最新master代码已修复
