### ISSUE TITLE
建议看图表的时候可以增加导出报表按钮

### ISSUE THREAD

**Issue by chixianliangGithub** [didi/nightingale#508]
**What would you like to be added**:

**Why is this needed**:

**Comment by UlricQin** [comment]
导出图片？pdf？

**Comment by chixianliangGithub** [comment]
导出Excel 数据 ，这边每个月或者每周都要做统计，这样能够方便SA统计资源使用情况

**Comment by UlricQin** [comment]
这个功能可以做，期待社区PR

**Comment by UlricQin** [comment]
清理历史遗留issue，如有问题，请reopen
