### ISSUE TITLE
无法排除同节点下策略名称存在

### ISSUE THREAD

**Issue by chixianliangGithub** [didi/nightingale#509]
oldStra, _ := models.StraGet("name", stra.Name)
	if oldStra != nil && oldStra.Id != stra.Id && oldStra.Nid == stra.Nid {
		bomb("同节点下策略名称 %s 已存在", stra.Name)
	}

models.StraGet 智能获取一条数据，如果有多条数据的话，取得 正好不是当前节点数据就会导致同节点下策略名称存在相同

**Comment by UlricQin** [comment]
https://github.com/didi/nightingale/commit/f590194fbad94f73559beac345587e435741bec9 已修复
