### ISSUE TITLE
设备无关指标无法设置告警屏蔽

### ISSUE THREAD

**Issue by yilingyi** [didi/nightingale#511]
我屏蔽设备无关告警指标时，发现需要填写屏蔽节点，但屏蔽节点下拉菜单无数据。
![image](https://user-images.githubusercontent.com/36027338/104553677-0e3de880-5676-11eb-939e-ee312f754386.png)

**Comment by UlricQin** [comment]
@jsers 这个根因是告警屏蔽节点的选择没有把当前节点放进去，下拉框里只有子节点导致的。清哥看看哈
