### ISSUE TITLE
建议在插件和告警策略增加暂停/禁用按钮

### ISSUE THREAD

**Issue by yilingyi** [didi/nightingale#512]
在实际运维场景中，可能有些插件或告警策略只是需要临时关闭，只能删除有些暴力，所以建议增加暂停/禁用按钮。
![image](https://user-images.githubusercontent.com/36027338/104554097-b5bb1b00-5676-11eb-8546-9f392c89ffdf.png)

**Comment by UlricQin** [comment]
可以把xx时间内最多发送xx次，这里的xx次改成0次就相当于临时禁用了。不过显式的启用/禁用按钮从产品功能上也确实可以做，接受这种PR，社区的老铁们可以搞起来：）

**Comment by UlricQin** [comment]
清理历史遗留issue，如有问题，请reopen
