### ISSUE TITLE
配置中心

### ISSUE THREAD

**Issue by chainingning** [didi/nightingale#519]
版本：v2.8

场景复现：
夜莺的配置文件在项目的etc目录中，每个实例都有其对应的配置文件，比如transfer的部署依赖的文件是n9e-transfer二进制、etc/transfer.yml、etc/address.yml。要部署20个transfer实例，就需要复制20份etc/transfer.yml、etc/address.yml

痛点：
刚开始部署20个transfer，现在要扩展50个实例，就要修改所有的实例配置文件

想法：
能不能有一个配置中心，比如放在zk中，或者类似springcloud的Config Server，所有的实例，都去拉取这里面的配置，这样当扩展实例的时候，只需要修改配置中心的yaml就可以了

**Comment by UlricQin** [comment]
我们看一下场景，只是扩容transfer，哪些配置要修改。

agent依赖的address.yml，里边要把transfer的addresses改成新的70个地址。

这里如果要用注册中心，就需要agent去连注册中心，如果生产环境有上百万设备，对注册中心压力太大了。
这个场景倒是可以考虑引入LVS，新扩容的实例作为新的rs扩容即可。当然，如果agent数量少不担心agent对注册中心的压力，引入注册中心也可以

另外说一句，扩容transfer的场景其实比较少，扩容存储的场景比较多

**Comment by UlricQin** [comment]
清理历史遗留issue，如有问题，请reopen
