### ISSUE TITLE
能否提供k8s部署方式呢？

### ISSUE THREAD

**Issue by sunnoy** [didi/nightingale#521]
**What would you like to be added**:
k8s部署方式，例如helm chart等
**Why is this needed**:

**Comment by UlricQin** [comment]
监控的部分模块是有状态的，不建议上K8S

**Comment by orcswang-lang** [comment]
> 监控的部分模块是有状态的，不建议上K8S

如果用m3db了，有什么方案可以使用k8s？

**Comment by UlricQin** [comment]
用了M3的话可以看看M3的官方是如何部署到K8S里的。但是，K8S的哲学是pod重启调度是非常正常的，在重数据的场景会造成数据频繁reblance，所以，即使是M3，也不推荐上K8S
