### ISSUE TITLE
v3版本 创建邀请链接 打开后直接跳转到首页

### ISSUE THREAD

**Issue by bolemon** [didi/nightingale#523]
**What happened**:
点击邀请用户，发送给被邀请人

**What you expected to happen**:
邀请人打开邀请链接后，直接跳转到首页
**How to reproduce it (as minimally and precisely as possible)**:
从页面上有全局的登录校验，会导致邀请注册页面也会跳转到登录首页
![image](https://user-images.githubusercontent.com/17025166/105040607-ffec3400-5a9c-11eb-8590-37b107b59ef5.png)

**Anything else we need to know?**:

**Environment**:
- OS (e.g: `cat /etc/os-release`):centos 7
- Logs:
- Others:

**Comment by UlricQin** [comment]
下个版本修复

**Comment by UlricQin** [comment]
清理历史遗留issue，如有问题，请reopen
