### ISSUE TITLE
告警webhook建议

### ISSUE THREAD

**Issue by liverpool8056** [didi/nightingale#527]
**What would you like to be added**:
希望在告警模块中增加webhook功能，用于在特定告警发生时，通过http请求方式hook一个外地地址
**Why is this needed**:
通过提供webhook功能可实现特定告警的关联处理，如关联故障查询、故障自动恢复等。举例：当发生网络专线流量高的告警时，hook到网络管理模块，实现QoS调整，保护重要应用的带宽

**Comment by infinityhacks** [comment]
这个功能在告警策略里已经有了啊
