### ISSUE TITLE
Judge模块取数问题

### ISSUE THREAD

**Issue by CarrotH** [didi/nightingale#53]
Judge模块在判断第一个规则的时候用linkedList.HistoryData(needCount)，如果监控指标在上报过程中丢点，是否存在取到判断周期外的数据

**Comment by UlricQin** [comment]
可能会往前多取一点，从产品上来说，从监控这个产品角度来看，不是个大问题 ：）

**Comment by CarrotH** [comment]
> 可能会往前多取一点，从产品上来说，从监控这个产品角度来看，不是个大问题 ：）

是否可以考虑在min max等操作上取消对limit的限制(或减少数据点个数，如limit/2)，这样可以对监控数据丢点进行容错

**Comment by CarrotH** [comment]
> 可能会往前多取一点，从产品上来说，从监控这个产品角度来看，不是个大问题 ：）

这个有可能导致因过期数据而无法产生告警

**Comment by UlricQin** [comment]
如果丢点了，算进去了历史的点，导致算的不准了，对于监控不是大问题，因为故障如果持续未恢复，会继续上报异常数据，最终总是会触发条件
