### ISSUE TITLE
Docker容器编排部署问题

### ISSUE THREAD

**Issue by JamesJoe-C** [didi/nightingale#530]
docker容器编排方式部署，n9e的dockerfile下载为github源码，无编译后文件。

`RUN git clone  https://hub.fastgit.org/didi/nightingale.git `
应改成
`RUN yum install -y wget`

`RUN wget http://116.85.64.82/n9e.tar.gz
`
`RUN tar -zxvf n9e.tar.gz`

**Comment by UlricQin** [comment]
master上已经更新，可以试试

**Comment by JamesJoe-C** [comment]
确认已修复。
