### ISSUE TITLE
关于数据接入

### ISSUE THREAD

**Issue by sylvia-33** [didi/nightingale#534]
你好，请问怎么接入Prometheus的数据，可以实现自动发现吗

**Comment by JamesJoe-C** [comment]
我看遍了所有文档，目前发现只有接入Prometheus的explore的插件模式。没有【从Prometheus的API拉取数据/把Prometheus当作数据源】的方式，故同问。

**Comment by UlricQin** [comment]
prometheus也可以暴露metrics接口，可以尝试使用prometheus-exporter-collector接入试试。后面我们会尝试对prometheus有更好的支持

**Comment by JamesJoe-C** [comment]
> prometheus也可以暴露metrics接口，可以尝试使用prometheus-exporter-collector接入试试。后面我们会尝试对prometheus有更好的支持

但是这样只是收集Prometheus主节点的相关信息，而并不是Prometheus本身内部存储的时序数据。我理解的对吧？

**Comment by JamesJoe-C** [comment]
如果要做这方面开发，从哪里入手好一点？比如：
![image](https://user-images.githubusercontent.com/38348040/105464887-30b2b000-5ccd-11eb-808c-1d4c01556669.png)
加在这里新的数据源？这样是否可行？

**Comment by UlricQin** [comment]
如果要自己搞，可以在这个菜单这里加个功能。

prometheus不是有联邦机制么，那就意味着中心的prometheus可以拉取其他prometheus的数据，即其他的prometheus是有暴露接口的，那些接口应该可以被prometheus-exporter-collector处理

**Comment by JamesJoe-C** [comment]
多谢指点，多了一个新的方向。

**Comment by sylvia-33** [comment]
> 多谢指点，多了一个新的方向。

可以私信吗？有问题请教

**Comment by JamesJoe-C** [comment]
> > 多谢指点，多了一个新的方向。
> 
> 可以私信吗？有问题请教

可以

**Comment by sylvia-33** [comment]
2237178729 微信，看了说下

**Comment by sylvia-33** [comment]
> > > 多谢指点，多了一个新的方向。
> > 
> > 
> > 可以私信吗？有问题请教
> 
> 可以

2237178729 微信，看了说下



> > > 多谢指点，多了一个新的方向。
> > 
> > 
> > 可以私信吗？有问题请教
> 
> 可以


微信 2237178729  看了说下

**Comment by JamesJoe-C** [comment]
> > > > 多谢指点，多了一个新的方向。
> > > 
> > > 
> > > 可以私信吗？有问题请教
> > 
> > 
> > 可以
> 
> 2237178729 微信，看了说下
> 
> > > > 多谢指点，多了一个新的方向。
> > > 
> > > 
> > > 可以私信吗？有问题请教
> > 
> > 
> > 可以
> 
> 微信 2237178729 看了说下

加你了

**Comment by UlricQin** [comment]
新版本v5可以直接使用Prometheus的数据了：n9e.github.io
