### ISSUE TITLE
夜莺日志收集设置

### ISSUE THREAD

**Issue by shaojie-dot** [didi/nightingale#535]
日志格式为：10-10 11:49:53
但是夜莺日志收集时间格式没有这么个格式，导致日志时间规则匹配不上

**Comment by UlricQin** [comment]
这个产品上可以支持，接受PR，老铁们搞起来吧

**Comment by shaojie-dot** [comment]
> 这个产品上可以支持，接受PR，老铁们搞起来吧

这个怎么弄呀

**Comment by shaojie-dot** [comment]
> 这个产品上可以支持，接受PR，老铁们搞起来吧

已提pr，还请查看下，谢谢
