### ISSUE TITLE
采集配置，日志部分，时间格式只能选择现有的格式

### ISSUE THREAD

**Issue by LeotLiu** [didi/nightingale#54]
采集配置，日志部分，时间格式只能选择现有的格式，不能自己设置。
比如我的环境里日志的时间格式是：
02-APR-2020 15:34:13 * service_died * LsnrAgt * 12537

而时间格式里可选的最接近的是类似   02-Apr-2020 15:34:13，
因为Apr这大小写问题就没法识别了。
希望能优化！！

**Comment by UlricQin** [comment]
@710leo 看看是否可以增加新的时间戳格式

**Comment by 710leo** [comment]
@LeotLiu 已支持
