### ISSUE TITLE
升级3.5.0 rdb启动报错

### ISSUE THREAD

**Issue by 1029649360** [didi/nightingale#541]
**What happened**:
升级3.5.0 rdb启动报错
# cat logs/rdb/stdout.log
runner.cwd: /home/n9e
runner.hostname: n9e-server188-node79.zhiyunyi.net
config.file: etc/rdb.yml
2021/01/23 10:49:44 user.go:132: cannot query user[root] Error 1054: Unknown column 'passwords' in 'field list'

另外升级包里patch文件为空：
![image](https://user-images.githubusercontent.com/45092668/105566882-6f964380-5d69-11eb-8960-e81c8952b52f.png)

**Comment by UlricQin** [comment]
这个报错是n9e_rdb.user表少了passwords字段，这个字段是3.4.0的sql文件里修改的，从老版本往上升级，需要把所有sql/upgrade下的比你当前版本高的sql文件都挨个导入一遍。

**Comment by 1029649360** [comment]
![image](https://user-images.githubusercontent.com/45092668/105569310-b1c88080-5d7b-11eb-9f3a-2905875de594.png)
What happened:
输入用户名，密码跳回到登录页。

其他组件没有发现报错。

**Comment by UlricQin** [comment]
检查配置文件，和github的做对比，特别是rdb.yml

**Comment by 1029649360** [comment]
rdb.yml这个文件不对。感觉差了好几个版本。感谢感谢。
