### ISSUE TITLE
centos6.10 agent收集不到数据

### ISSUE THREAD

**Issue by htcsky** [didi/nightingale#545]
centos6.10 配置agent后能看到基本的硬件信息，但是指标参数为空，

**Comment by fangyt-ect** [comment]
我也是很久才出来数据的，你可以先看下agent和server下transfer的日志有没有信息，或者浏览器的调试中有没有报错
打算学习下源码

**Comment by UlricQin** [comment]
v5新版支持使用Telegraf做采集器，Telegraf估计可以监控6.10
