### ISSUE TITLE
大家是怎么做高可用的

### ISSUE THREAD

**Issue by AlliotTech** [didi/nightingale#549]
生产单套监控跑的话，一旦某个组件出现故障，整个监控就处于无效状态了，不知道大家是怎样做高可用的？ 数据如何做到同步的？

**Comment by UlricQin** [comment]
数据库单独出来做一个高可用的。然后服务端所有组件都部署多个，transfer.yml里配置多个tsdb地址。nginx里配置的那些后端全部搞成多台。nginx前面搞一个vip。一个monapi对应一个redis单机版，judge.yml里配置所有redis地址。齐活。
