### ISSUE TITLE
endpoint概念

### ISSUE THREAD

**Issue by lts120784620** [didi/nightingale#55]
endpoint是否要区分类型的？
有个疑惑点，endpoint设计的理念是监控主体，一般主机指标主体可以是ip（hostname）,但是特殊场景下（比如聚合的集群指标）的endpoint可能会是集群的唯一标识，或者服务树节点编码。

endpoint统一到tags中吗？
endpoint可以看成一是类特殊的tag，业界流行的prometheus,influxdb等指标模型，只是metric+tags+type+...。夜莺的方向会将endpoint整合吗

**Comment by UlricQin** [comment]
不会。endpoint与服务树结合是一个管理机器的非常便利的方式。不同的机器挂到不同的节点配置不同的告警策略。

如果做成tag，就需要把原本属于服务树的分组能力也做成tag上报，才能满足之前用服务树满足的分组能力，太麻烦了
