### ISSUE TITLE
能否考虑支持生产告警事件统计报表

### ISSUE THREAD

**Issue by mhccj** [didi/nightingale#553]
**What would you like to be added**:
能否考虑支持生产告警事件统计报表，编译运维人员查看统计
**Why is this needed**:
现目前没有现成的告警事件报表统计功能

**Comment by UlricQin** [comment]
这块暂时还没想好

**Comment by JamesJoe-C** [comment]
机器\参数纬度的月\年\日环比。
机器\参数纬度的报警数量数据K线。

**Comment by UlricQin** [comment]
统计类的需求，目前不准备做到夜莺里，如果要做也是准备单拎一个新产品来搞，这个issue先关了
