### ISSUE TITLE
prober3.5.2 WARNING Log

### ISSUE THREAD

**Issue by 1029649360** [didi/nightingale#554]
**What happened**:
![image](https://user-images.githubusercontent.com/45092668/105937686-0415e400-6091-11eb-9a70-1e4c83cddad9.png)

prober 3.5.2

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by UlricQin** [comment]
monapi也升级到3.5.2试试

**Comment by 1029649360** [comment]
非常感谢。我的问题，忘记升级prober.yml这个文件了。确认了monapi.yml和prober.yml的token。
