### ISSUE TITLE
通知组优化

### ISSUE THREAD

**Issue by CarrotH** [didi/nightingale#56]
前面有提到用增加虚拟人的方式解决，这样就失去了用户群组管理的优势，所有用户组仍然需要在外部管理。
如果用户组同时包含实际户与虚拟用户的话会导致告警信息重复。
是否考虑在用户组中增加邮件列表和消息群，mail和im的notify中直接放组的mail/im信息，再加单独订阅的用户的信息

**Comment by UlricQin** [comment]
这个改动太大。短期不会支持。

> 如果用户组同时包含实际户与虚拟用户的话会导致告警信息重复

对于这个，你可以不放一个组里。告警接收人支持配置多个，告警接受团队也支持配置多个，而且支持同时配置接收人和接受组
