### ISSUE TITLE
 http.server.requests 的报警bug

### ISSUE THREAD

**Issue by zhangqiang603zq** [didi/nightingale#564]
**What happened**:
我在夜莺的平台设置一个关于  http.server.requests 的报警，tag 的 status 包含
我的应用通过https://github.com/lynxcat/micrometer-registry-nightingale 这个集成，数据已经上报到平台，但是没有触发报警

**What you expected to happen**:
触发报警
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OS (e.g: `cat /etc/os-release`):
- Logs:
- Others:

**Comment by UlricQin** [comment]
这样的issue完全没有办法提供帮助，啥信息都没有，是个很坏的榜样，关掉
