### ISSUE TITLE
关于Jan 2 15:04:05日志格式的问题

### ISSUE THREAD

**Issue by giggs06** [didi/nightingale#568]
之前使用的时候日期是两位数，比如：Jan 12 使用夜莺的Jan 2 15:04:05这个格式没有问题，今天是1号，发现无法匹配了，才发现日志是Feb 01 而夜莺只能匹配Feb 1，还请帮忙看看

**Comment by UlricQin** [comment]
尴尬了，Feb 1 是为了匹配 /var/log/messages
