### ISSUE TITLE
n9e可以增加自定义事件监控和告警吗？

### ISSUE THREAD

**Issue by zhaoge77** [didi/nightingale#573]
**What would you like to be added**:希望能够增加自定义事件的监控和告警

**Why is this needed**:目前n9e对于连续性的指标监控已经做的很棒了，期待能够考虑支持非连续的事件类型监控数据上报、查询与报警的场景，扩大监控报警场景的覆盖范围

**Comment by UlricQin** [comment]
有类似的产品可以借鉴么？感觉这个方向可以做

**Comment by hnuzhoulin** [comment]
直接通过接口上报不就可以吗？
https://n9e.didiyun.com/v4/docs/api/data/
相当于自定义一个index吗，不知道理解对不对，我打算先这样用着
