### ISSUE TITLE
已经将nginx的配置文件更改为etc下配置文件，外网访问响应超时，目前不清楚原因

### ISSUE THREAD

**Issue by lixiaolong41** [didi/nightingale#58]
是我的操作有问题嘛，在服务器搭建的，访问指定端口提示响应超时，netstat -tlunp命令查看都是正常的，就是外面访问不到，nginx都能正常启动无报错

**Comment by UlricQin** [comment]
这个跟夜莺没关系啦，如果是公有云检查一下安全组，另外检查一下本机的iptables规则，关掉firewalld，关掉selinux，setenforce 0
