### ISSUE TITLE
mysql监控插件show slave status返回的指标中将 Slave_IO_Running和Slave_SQL_Running状态显示出来

### ISSUE THREAD

**Issue by gxhak47** [didi/nightingale#583]
mysql监控插件show slave status返回的指标中将 Slave_IO_Running和Slave_SQL_Running状态显示出来

**Comment by UlricQin** [comment]
用的是mymon还是prober，3.5版本开始引入prober模块，可以内置采集一些指标

**Comment by gxhak47** [comment]
用的是prober目前 Slave_IO_Running和Slave_SQL_Running这2个指标出不来，估计需要做个转换把结果'YES'或'NO‘转换成数字

**Comment by UlricQin** [comment]
是的，需要针对这种情况特殊处理，来个PR吧，这个功能值得搞

**Comment by fanpiao** [comment]
请问下 ，现在 3.7版本 prober 对mysql 主从的监控是怎么做的
