### ISSUE TITLE
时序数据库历史数据插入

### ISSUE THREAD

**Issue by JamesJoe-C** [didi/nightingale#584]
历史数据用插件形式读取到，在夜莺调用插件的时候，会报错。
是否考虑增加历史数据倒入的插件支持？

场景：
在插件中读取prometheus的历史数据，存入夜莺。

获取的数据样例：
`->recv:&{Nid: Metric:sum_pod_qps Endpoint: Timestamp:1612108800 Step:30 ValueUntyped:0.2 Value:0 CounterType:GAUGE Tags:instance=PaymentGetway TagsMap:map[instance:PaymentGetway] Extra:}`

其中时间：1612108800 = 2021-02-01 00:00:00

日志报错如下：
`2021-02-21 16:21:35.920215 WARNING rpc/push.go:75 push obj error, obj: <Endpoint:192.168.188.194, Metric:sum_pod_qps, Tags:instance=PaymentGetway, TagsMap:map[instance:PaymentGetway], Value:0.2, TS:1612108800 2021-02-01 00:00:00 DsType:GAUGE, Step:30, Heartbeat:60, Min:U, Max:U>, error: data @1612108800, timestamp old than previous chunk. currentchunk t0: 1613895300`

**Comment by UlricQin** [comment]
导入数据需要先导入更老的数据，再导入最近的数据，不能先有了新数据，后导入老数据，这个特性受制于存储，大部分时序数据库都不能支持不按顺序的写入

**Comment by JamesJoe-C** [comment]
了解，我按照这个方向改造一下。

**Comment by JamesJoe-C** [comment]
目前我在插件中构造历史数据拉取，但是发现有局限性，需要讨论一下。
std配置：
```
QueryTime                string            `json:"history_query_time"`  //获取的历史节点开始时间
HistoryTimeStep          int			   `json:"history_time_step"` //历史数据拉取时间间隔
HistoryLen               int			   `json:"history_len"`  //历史数据拉取布长
```
从QueryTime确定历史数据拉取的开始时间，
从HistoryTimeStep决定每次拉取跳转的时间长度，
从HistoryLen决定拉取多少次数据

但是这样在插件中做依然会遇到因json数据排序的问题导致的时序数据无法插入。

故，我是否应该在夜莺中做这些事？

**Comment by UlricQin** [comment]
应该自己写个导入程序，不需要使用插件机制

**Comment by JamesJoe-C** [comment]
ok
