### ISSUE TITLE
是否能够增加监控告警看板功能

### ISSUE THREAD

**Issue by sun763625521** [didi/nightingale#587]
**What would you like to be added**:
现在告警主要是通过短信或者钉钉方式进行通知，告警发出后有多少告警有跟进处理或者还有多少告警未恢复未处理，无法显示查看。

**Why is this needed**:
对于监控来讲，这个监控告警看板功能还是需要的

**Comment by UlricQin** [comment]
未恢复的告警、所有历史告警，是有页面提供的。更强大的功能，规划在商业版本里
