### ISSUE TITLE
job 横行扩展需要变更agent的address文件问题

### ISSUE THREAD

**Issue by DemoLiang** [didi/nightingale#589]
**What happened**:
启动多个job的时候，负载均衡的话，在server端的话是通过在NGINX做，那么agent请求任务的话，怎么做负载均衡呢，这个时候需要直接在address文件里面写job的地址，这样在做横向扩展job的时候好像就不方便扩展了，每次扩张job需要边跟agent。
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Nightingale Version (`./n9e-rdb -v`):
- OS Version (`uname -a`):
- Logs (stdout/error/warning/http.request/http.response):
- Others:

**Comment by UlricQin** [comment]
两个办法：
1、如你所述，在address.yml里写多个job，job server横向扩展的概率比较小，3台job server可以抗10万台机器
2、使用四层负载均衡，address.yml里配置job的vip
