### ISSUE TITLE
前端页面关于指标列表内的各个指标的中文提示怎么没有了？

### ISSUE THREAD

**Issue by xiaobaiskill** [didi/nightingale#59]
指标列表内的各个指标的中文提示，看你们的视频里面是有的，我这边没有，是我的问题吗，还是你们给去掉了？如果是去掉了，那小白如何知道各个指标是做什么用的呢？

**Comment by UlricQin** [comment]
是最近搞的中英文版本切换，这部分还没有对应的英文文案，所以临时去掉了，后面会补上，可以先用之前版本的前端资源文件，在pub目录下
