### ISSUE TITLE
通过接口获取与设备无关历史监控数据，回复监控数据为空列表

### ISSUE THREAD

**Issue by stiei13wangluo** [didi/nightingale#591]
URL: http://server_Ip/api/transfer/data
提交参数：
data = [{
    'dstype': "GAUGE",
    'end': 1614242452,
    'counters': ['ping.latency'],
    'nids': ['17'],
    'start': 1614238852,
    'step': 10,
}]
Response结果：
{'dat': [{'start': 1614238852, 'end': 1614242452, 'endpoint': '', 'nid': '17', 'counter': 'ping.latency', 'dstype': 'GAUGE', 'step': 10, 'values': []}], 'err': ''}

夜莺平台监控数据截图：
![image](https://user-images.githubusercontent.com/10474594/109128669-aa393480-778a-11eb-9a71-c03a63d06236.png)

**Comment by UlricQin** [comment]
可以用浏览器开发者工具，看看浏览器怎么调用的接口，入参、返回，分别是什么格式，模仿着调用，页面接口使用api调用的方法： https://n9e.didiyun.com/docs/api/

**Comment by stiei13wangluo** [comment]
通过浏览器查看是另外一个URL：http://server_Ip/api/transfer/data/ui   这个URL可以获取设备无关的历史监控数据
http://server_Ip/api/transfer/data这个可以获取装了agent的历史监控数据，设备无关的历史监控不能获取

**Comment by UlricQin** [comment]
@710leo 看看

**Comment by 710leo** [comment]
@stiei13wangluo 存储后端你用的是 m3db 还是 tsdb 呢

**Comment by UlricQin** [comment]
原来的版本区分设备相关指标和设备无关指标，不太好，已经在v5版本里统一，可以试试新版本：n9e.github.io
