### ISSUE TITLE
建议: 子节点告警策略能自动覆盖父节点相同counter的策略

### ISSUE THREAD

**Issue by yanye321** [didi/nightingale#592]
建议:  在服务树上, 子节点上的告警策略与父节点的告警策略 counter相同时,  仅子节点的策略生效, 而不是分发两条策略.
          现在可以在父节点策略配置里面手动排除子节点, 希望能够自动覆盖, 类似面向对象里面的override 

比如: 
       父节点是某个项目所有linux服务器,  把linux系统监控策略挂在此节点,   有一条策略是:  _已用内存>85% 触发告警_
       子节点里面有一台大内存服务器,  单独挂一条策略是: _已用内存 > 90% 触发告警_
       这时子节点会有两条策略, _已用内存>85%_ 和 _已用内存 > 90%_,  如果没有手动排除, 85%这条仍然会先触发告警

**Comment by UlricQin** [comment]
这个功能挺好的，欢迎PR

**Comment by UlricQin** [comment]
v5摒弃了服务树这种方式，完全使用标签来搞，可以试试：n9e.github.io
