### ISSUE TITLE
夜莺版本升级出现的问题

### ISSUE THREAD

**Issue by crazylsq** [didi/nightingale#593]
夜莺版本升级到3.5引入prober后，不管我是添加mysql或者redis的组件监控，都会报一个错误，麻烦看下是哪里的问题

![image](https://user-images.githubusercontent.com/16173894/109135640-41ee5100-7792-11eb-8f3d-fe093220c79c.png)

**Comment by UlricQin** [comment]
把collect_rule表直接drop掉，查看sql/n9e_mon.sql中的collect_rule表，使用最新的collect_rule表结构创建表
