### ISSUE TITLE
任务模板配置的python脚本无法正常执行

### ISSUE THREAD

**Issue by dumengjun-ops** [didi/nightingale#595]
通过告警回调接口执行任务模板配置的python脚本发现，页面上编写的python脚本无法正常执行。到本地的agent/meta下查看发现脚本文件的格式不正确，每个行尾是^M$的格式。查看数据库task_meta表中script字段是text类型，说明页面上配置的脚本把windows的格式带过来了，如何处理才能让python脚本在本地是unix格式。

**Comment by UlricQin** [comment]
在linux下编辑脚本，完事拷贝到web上
