### ISSUE TITLE
index 总是自动掉线，查询k8s几张大屏，切换几次就会崩溃

### ISSUE THREAD

**Issue by mosesyu95** [didi/nightingale#596]
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xd1e79b, 0x16)
        /home/xiaoju/goroot/src/runtime/panic.go:1116 +0x72
runtime.sysMap(0xc69c000000, 0xb4000000, 0x141e018)
        /home/xiaoju/goroot/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x14091c0, 0xb4000000, 0x14091c8, 0x59ef5)
        /home/xiaoju/goroot/src/runtime/malloc.go:715 +0x1cd
runtime.(*mheap).grow(0x14091c0, 0x59ef5, 0x0)
        /home/xiaoju/goroot/src/runtime/mheap.go:1286 +0x11c
runtime.(*mheap).allocSpan(0x14091c0, 0x59ef5, 0x7fca9d560000, 0x141e028, 0x2a)
        /home/xiaoju/goroot/src/runtime/mheap.go:1124 +0x6a0
runtime.(*mheap).alloc.func1()
        /home/xiaoju/goroot/src/runtime/mheap.go:871 +0x64
runtime.(*mheap).alloc(0x14091c0, 0x59ef5, 0x460100, 0x14091c0)
        /home/xiaoju/goroot/src/runtime/mheap.go:865 +0x81
runtime.largeAlloc(0xb3de9a00, 0x460001, 0xc69a233d40)
        /home/xiaoju/goroot/src/runtime/malloc.go:1152 +0x92
runtime.mallocgc.func1()
        /home/xiaoju/goroot/src/runtime/malloc.go:1047 +0x46
runtime.systemstack(0x0)
        /home/xiaoju/goroot/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
        /home/xiaoju/goroot/src/runtime/proc.go:1056

goroutine 1180 [running]:
runtime.systemstack_switch()
        /home/xiaoju/goroot/src/runtime/asm_amd64.s:330 fp=0xc000469120 sp=0xc000469118 pc=0x467580
runtime.mallocgc(0xb3de9a00, 0xbe71c0, 0xc0007f4101, 0xc0007f4170)
        /home/xiaoju/goroot/src/runtime/malloc.go:1046 +0x895 fp=0xc0004691c0 sp=0xc000469120 pc=0x40e8b5
runtime.makeslice(0xbe71c0, 0xb3de9a0, 0xb3de9a0, 0xc387b80000)
        /home/xiaoju/goroot/src/runtime/slice.go:49 +0x6c fp=0xc0004691f0 sp=0xc0004691c0 pc=0x44e6dc
github.com/didi/nightingale/src/modules/index/cache.GetAllCounter(0xc0008b5560, 0xb, 0xb, 0xb, 0x1, 0xc0007f4150)
        /home/xiaoju/gopath/src/github.com/didi/nightingale/src/modules/index/cache/tag.go:107 +0x1f5 fp=0xc0004692c0 sp=0xc0004691f0 pc=0xa3ed45
github.com/didi/nightingale/src/modules/index/http/routes.GetIndexByFullTags(0xc00101c000)
        /home/xiaoju/gopath/src/github.com/didi/nightingale/src/modules/index/http/routes/index_router.go:416 +0x210e fp=0xc000469a08 sp=0xc0004692c0 pc=0xb6c55e
github.com/gin-gonic/gin.(*Context).Next(0xc00101c000)
        /home/xiaoju/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b fp=0xc000469a28 sp=0xc000469a08 pc=0xb4440b
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0000e6000, 0xc00101c000)
        /home/xiaoju/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 +0x666 fp=0xc000469bb0 sp=0xc000469a28 pc=0xb4deb6
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0000e6000, 0xe5d860, 0xc0007c2c40, 0xc0007ea400)
        /home/xiaoju/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 +0x14d fp=0xc000469be8 sp=0xc000469bb0 pc=0xb4d5cd
net/http.serverHandler.ServeHTTP(0x13e3640, 0xe5d860, 0xc0007c2c40, 0xc0007ea400)
        /home/xiaoju/goroot/src/net/http/server.go:2836 +0xa3 fp=0xc000469c18 sp=0xc000469be8 pc=0x705ad3
net/http.(*conn).serve(0xc0031300a0, 0xe601e0, 0xc000e54380)
        /home/xiaoju/goroot/src/net/http/server.go:1924 +0x86c fp=0xc000469fc8 sp=0xc000469c18 pc=0x70143c
runtime.goexit()
        /home/xiaoju/goroot/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000469fd0 sp=0xc000469fc8 pc=0x469691
created by net/http.(*Server).Serve
        /home/xiaoju/goroot/src/net/http/server.go:2962 +0x35c

goroutine 1 [chan receive, 2 minutes]:
main.ending()
        /home/xiaoju/gopath/src/github.com/didi/nightingale/src/modules/index/index.go:105 +0xf8
main.main()
        /home/xiaoju/gopath/src/github.com/didi/nightingale/src/modules/index/index.go:70 +0x237

goroutine 798 [runnable]:
github.com/didi/nightingale/src/modules/index/cache.GetAllCounter(0xc0006243c8, 0xa, 0xa, 0xd0c71f, 0x1, 0xc0008e41a6)
        /home/xiaoju/gopath/src/github.com/didi/nightingale/src/modules/index/cache/tag.go:111 +0x28f
github.com/didi/nightingale/src/modules/index/cache.GetAllCounter(0xc0006243c0, 0xb, 0xb, 0xb, 0x1, 0xc000404150)
        /home/xiaoju/gopath/src/github.com/didi/nightingale/src/modules/index/cache/tag.go:102 +0x1ad
github.com/didi/nightingale/src/modules/index/http/routes.GetIndexByFullTags(0xc00101c2d0)
        /home/xiaoju/gopath/src/github.com/didi/nightingale/src/modules/index/http/routes/index_router.go:416 +0x210e
github.com/gin-gonic/gin.(*Context).Next(0xc00101c2d0)
        /home/xiaoju/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0000e6000, 0xc00101c2d0)
        /home/xiaoju/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 +0x666
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0000e6000, 0xe5d860, 0xc005bf80e0, 0xc0001c4100)
        /home/xiaoju/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 +0x14d
net/http.serverHandler.ServeHTTP(0x13e3640, 0xe5d860, 0xc005bf80e0, 0xc0001c4100)
        /home/xiaoju/goroot/src/net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc003130000, 0xe601e0, 0xc000d40000)
        /home/xiaoju/goroot/src/net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
        /home/xiaoju/goroot/src/net/http/server.go:2962 +0x35c

goroutine 7 [sleep]:
time.Sleep(0xb2d05e00)
        /home/xiaoju/goroot/src/runtime/time.go:188 +0xba
github.com/toolkits/pkg/logger.(*FileBackend).flushDaemon(0xc00028aa80)
        /home/xiaoju/gopath/pkg/mod/github.com/toolkits/pkg@v1.1.3/logger/file.go:87 +0x32
created by github.com/toolkits/pkg/logger.NewFileBackend
        /home/xiaoju/gopath/pkg/mod/github.com/toolkits/pkg@v1.1.3/logger/file.go:244 +0x49a

goroutine 8 [chan receive]:
github.com/toolkits/pkg/logger.(*FileBackend).monitorFiles(0xc00028aa80)
        /home/xiaoju/gopath/pkg/mod/github.com/toolkits/pkg@v1.1.3/logger/file.go:138 +0x383
created by github.com/toolkits/pkg/logger.NewFileBackend
        /home/xiaoju/gopath/pkg/mod/github.com/toolkits/pkg@v1.1.3/logger/file.go:245 +0x4bc

goroutine 9 [sleep]:
time.Sleep(0x3b9aca00)
        /home/xiaoju/goroot/src/runtime/time.go:188 +0xba
github.com/toolkits/pkg/logger.(*FileBackend).rotateByHourDaemon(0xc00028aa80)
        /home/xiaoju/gopath/pkg/mod/github.com/toolkits/pkg@v1.1.3/logger/file.go:111 +0x3c
created by github.com/toolkits/pkg/logger.NewFileBackend
        /home/xiaoju/gopath/pkg/mod/github.com/toolkits/pkg@v1.1.3/logger/file.go:246 +0x4de

goroutine 34 [IO wait]:
internal/poll.runtime_pollWait(0x7fca9c529fc0, 0x72, 0xffffffffffffffff)
        /home/xiaoju/goroot/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc0003a6a18, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
        /home/xiaoju/goroot/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /home/xiaoju/goroot/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0003a6a00, 0xc000410000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /home/xiaoju/goroot/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc0003a6a00, 0xc000410000, 0x1000, 0x1000, 0x43914c, 0xc00006ab58, 0x466040)
        /home/xiaoju/goroot/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000408010, 0xc000410000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /home/xiaoju/goroot/src/net/net.go:184 +0x8e
net/http.(*persistConn).Read(0xc0001f19e0, 0xc000410000, 0x1000, 0x1000, 0xc0004180c0, 0xc00006ac58, 0x406da5)
        /home/xiaoju/goroot/src/net/http/transport.go:1884 +0x75
bufio.(*Reader).fill(0xc000406180)
        /home/xiaoju/goroot/src/bufio/bufio.go:100 +0x103
bufio.(*Reader).Peek(0xc000406180, 0x1, 0x0, 0x0, 0x1, 0x0, 0xc000d43860)
        /home/xiaoju/goroot/src/bufio/bufio.go:138 +0x4f
net/http.(*persistConn).readLoop(0xc0001f19e0)
        /home/xiaoju/goroot/src/net/http/transport.go:2037 +0x1a8
created by net/http.(*Transport).dialConn
        /home/xiaoju/goroot/src/net/http/transport.go:1706 +0xc56

goroutine 13 [chan receive]:
github.com/didi/nightingale/src/toolkits/stats.Push()
        /home/xiaoju/gopath/src/github.com/didi/nightingale/src/toolkits/stats/init.go:46 +0x176
created by github.com/didi/nightingale/src/toolkits/stats.Init
        /home/xiaoju/gopath/src/github.com/didi/nightingale/src/toolkits/stats/init.go:40 +0xe8

goroutine 35 [select]:
net/http.(*persistConn).writeLoop(0xc0001f19e0)
        /home/xiaoju/goroot/src/net/http/transport.go:2336 +0x11c
created by net/http.(*Transport).dialConn
        /home/xiaoju/goroot/src/net/http/transport.go:1707 +0xc7b

goroutine 66 [chan receive, 2 minutes]:
github.com/didi/nightingale/src/modules/index/cache.StartCleaner(0xe10, 0x15f90)
        /home/xiaoju/gopath/src/github.com/didi/nightingale/src/modules/index/cache/indexdb.go:60 +0x58
created by github.com/didi/nightingale/src/modules/index/cache.InitDB
        /home/xiaoju/gopath/src/github.com/didi/nightingale/src/modules/index/cache/indexdb.go:52 +0x1d1

goroutine 67 [chan receive, 2 minutes]:
github.com/didi/nightingale/src/modules/index/cache.StartPersist(0x384)
        /home/xiaoju/gopath/src/github.com/didi/nightingale/src/modules/index/cache/indexdb.go:72 +0x5c
created by github.com/didi/nightingale/src/modules/index/cache.InitDB
        /home/xiaoju/gopath/src/github.com/didi/nightingale/src/modules/index/cache/indexdb.go:53 +0x1f5

goroutine 68 [chan receive]:
github.com/didi/nightingale/src/common/report.Init(0xd0e767, 0x5, 0x1, 0xfa0, 0xbb8, 0xc000335b18, 0x4, 0xc000335b1c, 0x4, 0x0, ...)
        /home/xiaoju/gopath/src/github.com/didi/nightingale/src/common/report/report.go:37 +0xf2
created by main.main
        /home/xiaoju/gopath/src/github.com/didi/nightingale/src/modules/index/index.go:64 +0x1c4

goroutine 69 [IO wait, 2 minutes]:
internal/poll.runtime_pollWait(0x7fca9c529ee0, 0x72, 0x0)
        /home/xiaoju/goroot/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc0000f4198, 0x72, 0x0, 0x0, 0xd10d02)
        /home/xiaoju/goroot/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /home/xiaoju/goroot/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0000f4180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/xiaoju/goroot/src/internal/poll/fd_unix.go:384 +0x1d4
net.(*netFD).accept(0xc0000f4180, 0xc0006b3a00, 0x7fcac5ebf0e8, 0xc0006b3a00)
        /home/xiaoju/goroot/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc0006b2060, 0xc0000eedd8, 0xc0000eede0, 0x18)
        /home/xiaoju/goroot/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc0006b2060, 0xd493e0, 0xc0000e8000, 0xe604e0, 0xc000156000)
        /home/xiaoju/goroot/src/net/tcpsock.go:261 +0x64
github.com/didi/nightingale/src/modules/index/rpc.Start()
        /home/xiaoju/gopath/src/github.com/didi/nightingale/src/modules/index/rpc/rpc.go:37 +0x277
created by main.main
        /home/xiaoju/gopath/src/github.com/didi/nightingale/src/modules/index/index.go:65 +0x1dc

goroutine 82 [IO wait]:
internal/poll.runtime_pollWait(0x7fca9c529e00, 0x72, 0x0)
        /home/xiaoju/goroot/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc0003a6a98, 0x72, 0x0, 0x0, 0xd10d02)
        /home/xiaoju/goroot/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /home/xiaoju/goroot/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0003a6a80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/xiaoju/goroot/src/internal/poll/fd_unix.go:384 +0x1d4
net.(*netFD).accept(0xc0003a6a80, 0x88fdbb28bc036c9c, 0x0, 0x88fdbb28bc036c9c)
        /home/xiaoju/goroot/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc0003f9b40, 0x603f003b, 0xc0000eadd8, 0x4ca336)
        /home/xiaoju/goroot/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc0003f9b40, 0xc0000eae28, 0x18, 0xc0005c2300, 0x705f7c)
        /home/xiaoju/goroot/src/net/tcpsock.go:261 +0x64
net/http.(*Server).Serve(0x13e3640, 0xe5d5a0, 0xc0003f9b40, 0x0, 0x0)
        /home/xiaoju/goroot/src/net/http/server.go:2930 +0x25d
net/http.(*Server).ListenAndServe(0x13e3640, 0x2, 0x2)
        /home/xiaoju/goroot/src/net/http/server.go:2859 +0xb7
github.com/didi/nightingale/src/toolkits/http.Start.func1()
        /home/xiaoju/gopath/src/github.com/didi/nightingale/src/toolkits/http/http.go:40 +0xa1
created by github.com/didi/nightingale/src/toolkits/http.Start
        /home/xiaoju/gopath/src/github.com/didi/nightingale/src/toolkits/http/http.go:38 +0x18e

goroutine 83 [syscall, 2 minutes]:
os/signal.signal_recv(0x0)
        /home/xiaoju/goroot/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
        /home/xiaoju/goroot/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.Notify.func1
        /home/xiaoju/goroot/src/os/signal/signal.go:127 +0x44

goroutine 71 [IO wait]:
internal/poll.runtime_pollWait(0x7fca9c529d20, 0x72, 0xffffffffffffffff)
        /home/xiaoju/goroot/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc0003a6398, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
        /home/xiaoju/goroot/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /home/xiaoju/goroot/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0003a6380, 0xc0001fa000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /home/xiaoju/goroot/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc0003a6380, 0xc0001fa000, 0x1000, 0x1000, 0x756ea1275cc7cd, 0xebb4f491dd5e8e7a, 0xc00046dba8)
        /home/xiaoju/goroot/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00069e130, 0xc0001fa000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /home/xiaoju/goroot/src/net/net.go:184 +0x8e
bufio.(*Reader).Read(0xc0006bb440, 0xc0008bc173, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/xiaoju/goroot/src/bufio/bufio.go:226 +0x24f
github.com/ugorji/go/codec.(*msgpackSpecRpcCodec).parseCustomHeader(0xc000156000, 0xc00046dc00, 0xc0006b3d10, 0xc0006b3d00, 0x4bdc0, 0xc0000e8028)
        /home/xiaoju/gopath/pkg/mod/github.com/ugorji/go/codec@v1.1.7/msgpack.go:1058 +0xa1
github.com/ugorji/go/codec.(*msgpackSpecRpcCodec).ReadRequestHeader(0xc000156000, 0xc0006b3d00, 0xbc1dc0, 0xc000989980)
        /home/xiaoju/gopath/pkg/mod/github.com/ugorji/go/codec@v1.1.7/msgpack.go:1034 +0x45
net/rpc.(*Server).readRequestHeader(0xc0000e8000, 0xe604e0, 0xc000156000, 0xc000989980, 0x16, 0x197, 0x1, 0x0, 0x0)
        /home/xiaoju/goroot/src/net/rpc/server.go:583 +0x67
net/rpc.(*Server).readRequest(0xc0000e8000, 0xe604e0, 0xc000156000, 0xc0000e8000, 0xc0006a9ae0, 0xc0006a9af0, 0xc0000f4000, 0xc0006b3a20, 0xbd54c0, 0xc000723f20, ...)
        /home/xiaoju/goroot/src/net/rpc/server.go:543 +0x5a
net/rpc.(*Server).ServeCodec(0xc0000e8000, 0xe604e0, 0xc000156000)
        /home/xiaoju/goroot/src/net/rpc/server.go:458 +0x97
created by github.com/didi/nightingale/src/modules/index/rpc.Start
        /home/xiaoju/gopath/src/github.com/didi/nightingale/src/modules/index/rpc/rpc.go:50 +0x4f3

goroutine 1176 [runnable]:
github.com/didi/nightingale/src/modules/index/cache.GetAllCounter(0xc0006c9388, 0xa, 0xa, 0xd0c71f, 0x1, 0xc0008b0ac6)
        /home/xiaoju/gopath/src/github.com/didi/nightingale/src/modules/index/cache/tag.go:111 +0x28f
github.com/didi/nightingale/src/modules/index/cache.GetAllCounter(0xc0006c9380, 0xb, 0xb, 0xb, 0x1, 0xc0014a5eb0)
        /home/xiaoju/gopath/src/github.com/didi/nightingale/src/modules/index/cache/tag.go:102 +0x1ad
github.com/didi/nightingale/src/modules/index/http/routes.GetIndexByFullTags(0xc00101c1e0)
        /home/xiaoju/gopath/src/github.com/didi/nightingale/src/modules/index/http/routes/index_router.go:416 +0x210e
github.com/gin-gonic/gin.(*Context).Next(0xc00101c1e0)
        /home/xiaoju/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0000e6000, 0xc00101c1e0)
        /home/xiaoju/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 +0x666
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0000e6000, 0xe5d860, 0xc00295ea80, 0xc002957800)
        /home/xiaoju/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 +0x14d
net/http.serverHandler.ServeHTTP(0x13e3640, 0xe5d860, 0xc00295ea80, 0xc002957800)
        /home/xiaoju/goroot/src/net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc000121cc0, 0xe601e0, 0xc0000a1500)
        /home/xiaoju/goroot/src/net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
        /home/xiaoju/goroot/src/net/http/server.go:2962 +0x35c

**Comment by UlricQin** [comment]
index对tags比较多的场景处理的不太好，建议用m3做存储。未来我们可能会优化index的实现，不过短期暂无计划
