### ISSUE TITLE
报警升级异常问题

### ISSUE THREAD

**Issue by dumengjun-ops** [didi/nightingale#598]
案例一：磁盘告警
配置场景：
设备相关，级别为P2，统计周期为300秒，触发条件为300秒内24次值>80告警，五分钟内最多告警1次
报警升级配置：
留观时长60秒，生效时间周一至周日0:00~23:59，持续480分钟未处理并且未恢复的持续报警升级为P1级别

异常现象：
有时候触发第一次告警时直接触发了告警升级，以P1级别发送告警(前面并没有连续的告警存在)。理论上来说应该在480分钟后发送P1，第一次触发应该发送P2。

案例二：spark集群运行的app数告警
配置场景：
插件采集周期为10s，设备无关，级别为P2，统计周期为300秒，触发条件为300秒内24次值<12告警，15分钟内最多报警1次（没有配置告警团队，只配了告警接收人）
报警升级配置：
留观时长60秒，生效时间周一至周日0:00~23:59，持续480分钟未处理并且未恢复的持续报警升级为P1级别 （只配了告警团队）

异常现象：
在第一次触发告警时直接告警升级以P1级别发送，并没有发送P2，且在P2配置的告警接收人同样收到了P1的电话告警（在告警升级中并没有配置该接收人，只配置了运维团队）

**Comment by UlricQin** [comment]
未复现
