### ISSUE TITLE
进程采集指标能否支持 中文 字符

### ISSUE THREAD

**Issue by shier-1212** [didi/nightingale#604]
在进程采集中，有些windows系统进程可能包含 中文字符，可否在 进程采集   进程名  中支持中文字符。
![进程采集支持中文](https://user-images.githubusercontent.com/73478963/110277370-12e8a280-8010-11eb-82ec-58fe2d18a8c5.jpg)

**What would you like to be added**:

**Why is this needed**:

**Comment by UlricQin** [comment]
@jsers 这个放开限制吧
