### ISSUE TITLE
报警策略的触发条件可否增加或条件

### ISSUE THREAD

**Issue by duval1024** [didi/nightingale#606]
**What would you like to be added**:
希望能在报警策略的触发条件中增加**或条件**，如下：

![image](https://user-images.githubusercontent.com/21072525/110584900-ec12a380-81aa-11eb-83f5-5152d1ee89d8.png)

**Why is this needed**:

工作中会有应用情景，例如："GC停顿时间过长"。其触发条件有两种情况，只要触发其中一种条件就触发告警：
- 60秒内服务的GC停顿时间三次超过300ms；
- 60秒内服务的GC停顿时间单次超过500ms；

如果拆分成两条告警策略的话会显得臃肿。因此，需要或条件的报警策略。

谢谢！

**Comment by UlricQin** [comment]
短期暂不准备支持这个
