### ISSUE TITLE
你好，请问下关于历史采集数据以及历史告警数据的保留期限问题如何进行设置，还是有默认的保留期限？

### ISSUE THREAD

**Issue by feixia5712** [didi/nightingale#608]
你好，请问下关于历史采集数据以及历史告警数据的保留期限问题如何进行设置，还是有默认的保留期限？

**Comment by UlricQin** [comment]
监控数据：https://n9e.didiyun.com/docs/operation/tsdb/ 

告警事件：存100天默认应该是
