### ISSUE TITLE
有没有好的开机自启动服务方式

### ISSUE THREAD

**Issue by loosky** [didi/nightingale#61]
重启服务器后，每次得执行 ./control start all
centos7下面貌似加入/etc/rc.d/rc.local 中没有效果
可否考虑添加一个服务？

**Comment by UlricQin** [comment]
兄台，需要补一下linux基础知识哈

etc/service目录下有一堆service配置文件，可以适当修改使用，这些配置文件是给systemd用的，centos7建议使用systemd来管理夜莺的进程，systemctl enable可以让进程开机自启，百度一下可以找到很多systemd的使用教程哈

**Comment by loosky** [comment]
谢谢，这些都懂，也是这么做的。
只是感觉可以整个启动所有的，会否更简单点。
