### ISSUE TITLE
influxdb 聚合查询QueryData 组合influxdbql查询语句有不对

### ISSUE THREAD

**Issue by DemoLiang** [didi/nightingale#612]
**What happened**:
1.influxdb查询语句,在做聚合查询时组合的查询ql不对，导致页面查询不出数据
**What you expected to happen**:
2.正常应该是可以查询到数据，想TSDB那样
**How to reproduce it (as minimally and precisely as possible)**:
1.接入influxdb作为后端数据源存储，查询聚合数据时就会出现

**Anything else we need to know?**:

![image](https://user-images.githubusercontent.com/23476007/110918757-78ad9500-8356-11eb-905b-e0bbb5035717.png)
![image](https://user-images.githubusercontent.com/23476007/110918768-7ba88580-8356-11eb-8378-00d9efb244c2.png)

**Environment**:
- Nightingale Version (`./n9e-rdb -v`):
- OS Version (`uname -a`):
- Logs (stdout/error/warning/http.request/http.response):
- Others:

**Comment by UlricQin** [comment]
抱歉这块influxdb我们也不太了解，是社区朋友贡献的，夜莺v5已发，可以试试：n9e.github.io 新版本支持promql了
