### ISSUE TITLE
高可用集群报警混乱

### ISSUE THREAD

**Issue by JadeRing** [didi/nightingale#613]
环境:
    server1(192.168.2.102): rdb job ams monapi tsdb index transfer judge agent prober
    server2(192.168.2.103): rdb job ams monapi tsdb index transfer judge agent prober
    server3(10.2.0.36): rdb job ams monapi tsdb index transfer judge agent prober
    client1(10.2.1.27)：agent
    client2(10.2.1.164)：agent

集群方案:
    nginx单点,upstream后端全部搞成三台
    数据库单点
    服务端所有组件都部署三个
    transfer.yml里配置三个tsdb地址
    每个monapi对应本机redis单机版
    每个rdb对应本机redis单机版
    judge.yml里配置所有redis地址
    address.yml里各个组件的addresses字段写成实际的实例列表

测试场景:
    监控agent策略: 
        级别P3 
        报警1次
        报警升级为 P1

    测试主机:client1
        执行./control stop all
        执行./control start all
    结果:  多了一个p3报警
![image](https://user-images.githubusercontent.com/38696086/110931423-26528100-8322-11eb-90e1-5f3cca3b7f80.png)

    测试主机: server3
        执行./control stop all
        执行./control start all
    结果: 多了一个p3恢复
![image](https://user-images.githubusercontent.com/38696086/110931445-2d798f00-8322-11eb-82bf-c909e8674721.png)

    测试主机: server2
        执行./control stop all
        执行./control start all
    结果:  多了两条  client1的 P1报警和P1恢复
![image](https://user-images.githubusercontent.com/38696086/110931473-35393380-8322-11eb-80b0-ed6973cb5d32.png)

    测试主机: server1
        执行./control stop all
        执行./control start all
    结果:  stop后没有任何报警, start后才出现以下报警, 报警级别也不对
![image](https://user-images.githubusercontent.com/38696086/110931486-3b2f1480-8322-11eb-9269-6c789ea3b29a.png)

另外:  
    只有server1上的redis有数据
    如果server1 挂掉之后, 其他机器宕机也不会发报警

**Comment by UlricQin** [comment]
版本需要升级到最新版本，有没有其他人也遇到这个问题？

**Comment by JadeRing** [comment]
> 版本需要升级到最新版本，有没有其他人也遇到这个问题？

用的最新版本 3.7.0

**Comment by UlricQin** [comment]
升级到3.8如果有问题，可以微信联系看看
