### ISSUE TITLE
监控看图网络指标中net.bandwidth.mbits.total;net.in.bits.total.percent;net.out.bits.total.percent数据全是0

### ISSUE THREAD

**Issue by zzcode** [didi/nightingale#618]
夜莺3.2版本和夜莺3.6版本 
在监控看图——网络tab下一下指标数据采集值都是0 
1.net.bandwidth.mbits.total;
2.net.in.bits.total.percent;
3.net.out.bits.total.percent

**Comment by 710leo** [comment]
@zzcode 补充一下操作系统的版本吧

**Comment by zzcode** [comment]
CentOS Linux release 7.0.1406

**Comment by UlricQin** [comment]
容器还是虚拟机还是物理机

**Comment by zzcode** [comment]
虚机

**Comment by UlricQin** [comment]
用什么做的虚拟机？pve？
