### ISSUE TITLE
监控大盘展示问题

### ISSUE THREAD

**Issue by topicgit** [didi/nightingale#62]
问题1: 部分图标经常性出现只展示一个节点的数据，刷新后正常，经常出现，如下图所示：
![image](https://user-images.githubusercontent.com/11975460/78516679-013dc000-77ed-11ea-85b4-d38748a8db2a.png)

问题2: 时间选择一天后图就变成这样了呢？
![image](https://user-images.githubusercontent.com/11975460/78516922-ea4b9d80-77ed-11ea-9a3c-e740b4f3e245.png)

问题3: 时间选择能否支持 6小时 12小时 这样更多的区间段
![image](https://user-images.githubusercontent.com/11975460/78517073-73fb6b00-77ee-11ea-9b21-cbd1c08114a8.png)

感谢。

**Comment by 710leo** [comment]
@topicgit 
- 问题1再详细提供一下信息吧，你的预期是什么样的，结果是什么样的，后端接口返回的数据是什么样的
- 问题2描述的问题，你的意思是数据精度降低了？这个是数据被降采样的原因
- 问题3中描述的问题，下拉列表最后一个选项 `其他` 可以自定义查看的时间范围

**Comment by topicgit** [comment]
![image](https://user-images.githubusercontent.com/11975460/78632412-88fcfa80-78d1-11ea-9be1-421bbb895b34.png)
![image](https://user-images.githubusercontent.com/11975460/78632659-2e17d300-78d2-11ea-93bf-ec053e906b31.png)

问题1 的预期是显示这个节点下所有endpoint的指标， 某些图标会出现不显示或者只显示两三个endpoint的情况，如上图所示 endpoint中没有数据。。。 不知您那遇到过没有

问题2 是前面的图都是折线了，不平滑，估计这个是你说的精度降低的原因， 请问不想让精度降低应当怎么配置？

问题3  可以了，谢谢。

**Comment by 710leo** [comment]
@topicgit 
问题1中接口返回数据异常的时候，前端请求发送的body是什么呢
问题2可以参考这个[文档](https://n9e.didiyun.com/docs/operation/tsdb/#%E7%BD%AE%E7%BB%98%E5%9B%BE%E6%95%B0%E6%8D%AE%E7%9A%84%E5%AD%98%E5%82%A8%E6%97%B6%E9%95%BF)

**Comment by topicgit** [comment]
问题1 ： 我发现后端返回中的数据只有一条，则只显示来一个endpoint的图，理论上应当返回我这个树节点下挂在的所有endpoint的数据
![image](https://user-images.githubusercontent.com/11975460/78976283-6a546900-7b48-11ea-9bd2-8f1fd85c770a.png)

request 
![image](https://user-images.githubusercontent.com/11975460/78976571-041c1600-7b49-11ea-8c8b-4b842999207a.png)
@710leo

**Comment by 710leo** [comment]
@topicgit 对于问题1的解决办法，可以在transfer的配置

**Comment by topicgit** [comment]
> @topicgit 对于问题1，可以在transfer配置文件加一个这个字段，然后重启transfer再看下
> ![image](https://user-images.githubusercontent.com/2169271/79059355-95a39900-7cab-11ea-95cd-529698c429a5.png)

@710leo  感谢大佬，可以了。
