### ISSUE TITLE
升级agent后使用systemctl restart agent，出现将线上服务器pm2 node进程杀掉的情况

### ISSUE THREAD

**Issue by AlliotTech** [didi/nightingale#621]
近百台跑着pm2进程的服务器，在使用 `salt cmd.run` 调用 `systemct restart agent` 的过程中，出现三分之二的服务器 pm2 node进程被 kill 的情况（期间系统各项指标正常，不存在因资源不足而被系统kill的情况）。  
agent 版本 3.7.0  
系统日志：  
![image](https://user-images.githubusercontent.com/24980252/111284557-2ed8ed80-867b-11eb-81d7-fad9b9a6eb5d.png)

![image](https://user-images.githubusercontent.com/24980252/111284400-0d780180-867b-11eb-92fe-e572c54bb26f.png)

补充： 测试将 agent.service 更名为 n9e-agent.service 后没有出现杀死 node 进程的情况。（尝试将其他服务的service 文件改为agent也没出现杀进程的情况）
感觉项目 etc/下的 service 文件加上 n9e- 前缀比较稳妥，直接使用 agent 作为服务名有些泛滥。。（不过，并不能确定是由这个原因引起，因为并不能百分百复现。目前还没找到原因）

**Comment by AlliotTech** [comment]
pm2   v 3.3.2 
salt v 3002.5
CentOS Linux release 7.4.1708 (Core)

**Comment by UlricQin** [comment]
这个可能是systemd或者salt的问题，这个issue在夜莺下面，解决不了哈。至于service名字的问题，大家可以自行修改。

**Comment by AlliotTech** [comment]
emmmm 期待在线平滑升级的agent吧～
