### ISSUE TITLE
在使用插件监控docker-swarm集中应用存活数，脚本写完，但是监控大图没有任何数据

### ISSUE THREAD

**Issue by Menganhaoa** [didi/nightingale#622]
![image](https://user-images.githubusercontent.com/34940125/111412709-e4597e80-8717-11eb-8831-8e1a29ee3a5d.png)
![image](https://user-images.githubusercontent.com/34940125/111412674-cd1a9100-8717-11eb-91c7-3188d5719e90.png)
![image](https://user-images.githubusercontent.com/34940125/111412680-d0ae1800-8717-11eb-98f0-69ce77a5044a.png)

**Comment by UlricQin** [comment]
1，脚本要有可执行权限
2，value字段得是数字
3，app字段是哪里来的？夜莺的DataModel里压根就没有这个字段，可以考虑放到tags里，比如：`tags: "app=xxx,region=yy"`

**Comment by Menganhaoa** [comment]
嗯嗯，已经好了，谢谢
