### ISSUE TITLE
部署夜莺，硬件配置推荐

### ISSUE THREAD

**Issue by wangcc7** [didi/nightingale#623]
因业务发展需要，需要部署一套夜莺用来监控业务服务器，业务服务器目前大概100台左右，后续还会持续增加，能否帮忙推荐一套部署夜莺的硬件配置，感谢！

**Comment by UlricQin** [comment]
8C16G400G SSD，单机版本就够用了

**Comment by wangcc7** [comment]
收到，感谢您的回复
