### ISSUE TITLE
JOB 模块存在内存被消耗光的风险

### ISSUE THREAD

**Issue by DemoLiang** [didi/nightingale#625]
**What happened**:
这里的内存缓存永不过期，如果是一直创建任务，会导致内存不断增长
	cache.Set(taskMetaCacheKey(fmt.Sprint(id)), obj, cache.DEFAULT)

// TaskMetaGet 根据ID获取任务元信息，会用到内存缓存
func TaskMetaGetByID(id interface{}) (*TaskMeta, error) {
	var obj TaskMeta
	if err := cache.Get(taskMetaCacheKey(fmt.Sprint(id)), &obj); err == nil {
		return &obj, nil
	}

	has, err := DB["job"].Where("id=?", id).Get(&obj)
	if err != nil {
		return nil, err
	}

	if !has {
		return nil, nil
	}

	cache.Set(taskMetaCacheKey(fmt.Sprint(id)), obj, cache.DEFAULT)

	return &obj, nil
}

建议修改为：
        cache.Set(taskMetaCacheKey(fmt.Sprint(id)), obj, time.Second*3600)

**What you expected to happen**:
代码逻辑看起来存在内存不断增长的风险

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: master 分支代码
- Nightingale Version (`./n9e-rdb -v`):
- OS Version (`uname -a`):
- Logs (stdout/error/warning/http.request/http.response):
- Others:

**Comment by UlricQin** [comment]
cache.DEFAULT的值就是1小时，time.Second*3600 跟这个一样的

**Comment by DemoLiang** [comment]
那就奇怪了，我开500并发创建任务，2000并发拉去任务压测，job的内存就不断增长了。

**Comment by DemoLiang** [comment]
> cache.DEFAULT的值就是1小时，time.Second*3600 跟这个一样的

那就奇怪了，我开500并发创建任务，2000并发拉去任务压测，job的内存就不断增长了。
