### ISSUE TITLE
all function 不是很稳定

### ISSUE THREAD

**Issue by spyvip** [didi/nightingale#631]
**What happened**:

## 告警事件
![image](https://user-images.githubusercontent.com/1212932/112290031-ccf73400-8cc9-11eb-8313-a68b663a50de.png)

## 策略设置
![image](https://user-images.githubusercontent.com/1212932/112290055-d2547e80-8cc9-11eb-98b7-a2a2ca89dba0.png)

## 监控曲线
![image](https://user-images.githubusercontent.com/1212932/112290076-d8e2f600-8cc9-11eb-8472-49d816320bb2.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Nightingale Version (`./n9e-rdb -v`): 3.7.0
- OS Version (`uname -a`): centos 7
- Logs (stdout/error/warning/http.request/http.response):
- Others:

**Comment by UlricQin** [comment]
报警的那个时间点，180秒内是不是只有一个值，就是0

**Comment by spyvip** [comment]
@UlricQin 不是，值都有，只有一个值是0

**Comment by spyvip** [comment]
我又仔细看了时间点，好像确实是几个数据没写进来
