### ISSUE TITLE
监控告警依赖

### ISSUE THREAD

**Issue by dry1234** [didi/nightingale#633]
能否像zabbix一样支持下告警的依赖，如果A报警依赖B报警，只有B触发了A才触发，比如A在负载高于60%就报警，B高于40%就报警,当B告警是A不告警，当A告警时，B不会告警。

**Comment by UlricQin** [comment]
夜莺支持与条件，可以试试。另外，夜莺是tag匹配，一条策略匹配特别多指标，可能不好实现这个效果
