### ISSUE TITLE
监控看图数据指标多且加载显示慢或页面崩溃时，系统所有告警失效，，必须重启monapi

### ISSUE THREAD

**Issue by sunha0** [didi/nightingale#635]
**What happened**:多次发现当查看某个监控指标如果有多个endpoint时，页面加载缓慢或崩溃后，告警功能失效，必须重启monapi

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Nightingale Version (`./n9e-rdb -v`):
- OS Version (`uname -a`):
- Logs (stdout/error/warning/http.request/http.response):
- Others:

**Comment by UlricQin** [comment]
你是哪个版本，用的什么存储，默认的index+tsdb还是M3，看的什么指标，看了多少机器，图上多少线，各个模块什么日志，哪些有异常日志
