### ISSUE TITLE
 k8s监控数据导入，崩溃 

### ISSUE THREAD

**Issue by 1032231418** [didi/nightingale#636]
k8s 监控数据导入夜莺，夜莺直接挂掉，日志也无错误打印 
![B9D064DC-71AE-44e6-A5AF-1A3035E50115](https://user-images.githubusercontent.com/5716348/112824240-e11da580-90bc-11eb-9c98-040ebe0c4800.png)

**Comment by UlricQin** [comment]
换成M3存储，默认的index对高基数tag的处理有问题

**Comment by 1032231418** [comment]
果然，改成M3 就可以了，谢谢

**Comment by lsy1990** [comment]
@eagle9527  can you share your solution for integrating k8s with nightingale?
