### ISSUE TITLE
index模块bug：一个metric，如果tag不同，会出现无法查询数据的问题

### ISSUE THREAD

**Issue by peng19940915** [didi/nightingale#642]
以es监控指标：elasticsearch_indices_get_total  举例
warm节点的tag是：
```
cluster_name=logs,node_attribute_master=false,node_attribute_max_local_storage_nodes=1,
node_attribute_zone=warm,node_host=xxxxx,node_id=mXJoZ0bcRs-eG1CS7OzGlw,node_name=node-6,node_roles=nil
```
非warm节点tag：  
```
cluster_name=logs,node_attribute_master=false,node_attribute_max_local_storage_nodes=1,
node_host=xxxx,node_id=Nt87-HlXSTO3oRE7jC0iOg,node_name=node-8,node_roles=nil  
```  
那么elasticsearch_indices_get_total  将无法在前端获取到数据  
![image](https://user-images.githubusercontent.com/25658446/113668019-391f6200-96e4-11eb-8697-815516a56ea6.png)  
具体原因应该是index在获取tag的时候，采取的是绝对匹配的方式，如果某个指标，少一个tag，就无法将该指标的数据查询出来

**Comment by UlricQin** [comment]
是的，默认的index有这个问题，后面考虑优化一下

**Comment by UlricQin** [comment]
新版本v5-ga直接对接Prometheus、m3、VictoriaMetrics，没有这些问题了，可以试试：n9e.github.io
