### ISSUE TITLE
Prober采集http_response时，状态码写入tag导致告警恢复故障问题【记录】

### ISSUE THREAD

**Issue by Zayscott** [didi/nightingale#646]
问题如标题，之前在群里反馈过，这里记录跟进下

**Comment by Zayscott** [comment]
通过telegraf采集的大部分指标也存在一样的问题

**Comment by UlricQin** [comment]
这个后面确实需要优化一下，本质是因为telegraf和n9e的设计思路是不同的，现在还没时间，后面一并看看

**Comment by UlricQin** [comment]
v5正式版解决了这个问题：n9e.github.io
