### ISSUE TITLE
是否不支持对windows主机执行任务？

### ISSUE THREAD

**Issue by bavol2000** [didi/nightingale#649]
使用的夜莺版本是3.7版本，完全按照官方视频教程安装使用的，对于windwos主机的数据采集都能采集到，就是通过任务执行中心对windows主机执行的任务全部都是显示timeout,夜莺不准备支持windows主机吗？

**Comment by UlricQin** [comment]
是的，目前不支持

**Comment by bavol2000** [comment]
有计划支持吗？如果是有计划的话，大概什么时候可以出？

**Comment by UlricQin** [comment]
目前没有计划，欢迎PR哈
