### ISSUE TITLE
About development roadmap

### ISSUE THREAD

**Issue by chenjiandongx** [didi/nightingale#65]
Thanks for nightngale-team's contributions. 

nightngale is an awesome project on the monitoring system filed. And I want to know that does nightngale has a development roadmap about its future version?

**Comment by UlricQin** [comment]
This year, we will focus on the following five things:

- Building aggregation module to aggregate metrics
- Integration with K8S ecology
- Writing more monitoring plug-ins
- Integration with grafana
- Providing a new version of UI

**Comment by chenjiandongx** [comment]
@UlricQin Thanks for your response. 

Is this project syncing with DiDi internal version? or it just an opensource project maintained by your guys amateur.

**Comment by UlricQin** [comment]
The core modules are reusable :-)
