### ISSUE TITLE
告警恢复参数取值存在问题

### ISSUE THREAD

**Issue by JamesJoe-C** [didi/nightingale#650]
![image](https://user-images.githubusercontent.com/38348040/114345204-e20e0700-9b93-11eb-9919-122149320cad.png)

如上图，实际当时告警的恢复区间为下图：

![image](https://user-images.githubusercontent.com/38348040/114345263-fce07b80-9b93-11eb-8b55-0c4ef7598c15.png)

观察了很多个告警，均存在这个问题。

**Comment by JamesJoe-C** [comment]
基本定位到问题，如下：
文件位置：src/modules/judge/judge/func.go
问题描述：
在各种结构体的Compute中，没有对数据恢复的判断标准（Operator）参数做反转处理。

**Comment by JamesJoe-C** [comment]
初步修复成功。
整理后提交PR。

**Comment by hnuzhoulin** [comment]
我也发现这个问题，恢复的全部是0，坐等大佬的pr

**Comment by UlricQin** [comment]
试试新发布的v5版本吧：n9e.github.io

**Comment by Ostaer** [comment]
所有的使用**happen**函数的恢复的值都为**0**

大家可以查一下自己的库 
```sql
select sname,endpoint,value from event where info like "%happen%" and event_type="recovery" limit 100;
```

修复方法可以改一下代码重新编译一下judge，这是源代码

https://github.com/didi/nightingale/blob/80259ae8eab6ffd563ed38e8a125d03b44e0964e/src/modules/server/judge/func.go#L251-L263

这是修改后的方法
```golang
func (f HappenFunction) Compute(vs []*dataobj.HistoryData) (leftValue dataobj.JsonFloat, isTriggered bool) {
	for n, i := 0, 0; i < len(vs); i++ {
                 // vs的第一个值就是最新上报上来的数据，赋值最新的值
		if i == 0 {
			leftValue = vs[0].Value
		}
		if checkIsTriggered(vs[i].Value, f.Operator, f.RightValue) {
			n++
			if n == f.Num {
				isTriggered = true
				return
			}
		}
	}
	return
}
```

**Comment by ryetan** [comment]
为啥这个issue直接关掉了。。
