### ISSUE TITLE
feature-细化告警模块

### ISSUE THREAD

**Issue by oslet** [didi/nightingale#657]
1. 告警报表,可按部门级查看统计
2. 告警 接口,接受自定义的告警推送如 webhook或者其它三方系统集成
3. 告警工作流, 产生的告警工单指派,认领,处理等等

类似解决方案:https://github.com/tal-tech/alarm-dog

**Comment by hnuzhoulin** [comment]
个人首选告警模板自定义，现在的短信消息太长，电话的又太简单。

**Comment by UlricQin** [comment]
> 个人首选告警模板自定义，现在的短信消息太长，电话的又太简单。
> 各位大佬评估

etc下有sms.tpl文件就是定义短信告警内容的。电话的还不能自定义

**Comment by UlricQin** [comment]
夜莺v5开始，定位为prom的增强版，这类需求不准备在夜莺里解决，后面可能搞单独的产品
