### ISSUE TITLE
通知信息中的指标列表

### ISSUE THREAD

**Issue by CarrotH** [didi/nightingale#66]
https://github.com/didi/nightingale/blob/master/src/modules/monapi/notify/notify.go
Line 63
指标名称未遍历，hardcore取第一个指标
![image](https://user-images.githubusercontent.com/4654392/78633421-34a74a00-78d4-11ea-8e02-04a65ba94831.png)

**Comment by UlricQin** [comment]
火眼金睛，已修复，多谢反馈
