### ISSUE TITLE
V4版本im wechat通道无法报警！

### ISSUE THREAD

**Issue by MoonStill** [didi/nightingale#665]
2021-04-22 11:45:37.836305 WARNING cron/sender_im.go:101 im wechat send to xxxx fail: invoke getAccessTokenFromWeixin fail: invoke api gettoken fail, ErrCode: 41002, ErrMsg: corpid missing
corpid 配置里已经提供:
server.yml
wechat:
  corp_id: "ww60c7bxxxxxx"
  agent_id: 1000004
  secret: "A9Q6BM6iyqXbWA90yxxxxx"
也已经重启过n9e-server

**Comment by UlricQin** [comment]
检查yaml格式

**Comment by MoonStill** [comment]
![微信截图_20210423181206](https://user-images.githubusercontent.com/71972802/115856753-76fbe480-a45f-11eb-868a-1088b28dcebe.png)
格式没错

**Comment by lynxcat** [comment]
经测试、yaml中的下横线去掉就可以了

**Comment by ipinco** [comment]
> 经测试、yaml中的下横线去掉就可以了
我这边也遇到相同的问题，请问是去掉哪个下划线，我改成了
corpid:      测试也还是有异常
