### ISSUE TITLE
日志手机告知时间格式不正确

### ISSUE THREAD

**Issue by Menganhaoa** [didi/nightingale#672]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Nightingale Version (`./n9e-rdb -v`):
- OS Version (`uname -a`):
- Logs (stdout/error/warning/http.request/http.response):
- Others:

**Comment by Menganhaoa** [comment]
![image](https://user-images.githubusercontent.com/34940125/116398717-b0b35d80-a85a-11eb-9770-61f77006824e.png)
有人有碰过这个问题吗，以前是正常的，然后有一次修改过容器的目录，但是文件名啥的都没改，就出现获取时间格式不正确啦。
![image](https://user-images.githubusercontent.com/34940125/116398844-cfb1ef80-a85a-11eb-8115-adb6e1cc564c.png)
在页面上进行日志检验是没问题的

**Comment by UlricQin** [comment]
原始日志是否有换行
