### ISSUE TITLE
v4 agentd 上报的扩展信息错误

### ISSUE THREAD

**Issue by MoonStill** [didi/nightingale#678]
![微信图片_20210430155931](https://user-images.githubusercontent.com/71972802/116666074-1d4e6980-a9cd-11eb-85de-c95068f8b4d2.png)
扩展信息显示为base64编码

**Comment by UlricQin** [comment]
检查agentd的配置文件里配置的获取cpu、disk、mem的三个shell，看看在你的机器上执行结果是什么

**Comment by MoonStill** [comment]
shell 获取的值显示都是正常的。

**Comment by UlricQin** [comment]
目前这个问题仍无思路，也无法复现，怀疑是机器上的语言配置、编码等导致的
