### ISSUE TITLE
BUG：机器不能挂载多个节点

### ISSUE THREAD

**Issue by bbaobelief** [didi/nightingale#679]
第一次挂载`t.a`成功
![image](https://user-images.githubusercontent.com/3918461/116673574-23951380-a9d6-11eb-84ef-c15370a33f29.png)

第二次挂载`test.b`报错
![image](https://user-images.githubusercontent.com/3918461/116673737-55a67580-a9d6-11eb-8493-3f0c68862812.png)

`{"err":"tx-ops-n9e01 already belongs to copxxx"}`

### 版本信息
```
# ./n9e-server -v
Version: 4.0.0
# cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
# uname -a
Linux tx3-ops-n9e01.bj 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by UlricQin** [comment]
机器只能属于一个租户，可以挂在租户下面的多个不同的节点。正常来说，在资产管理的页面只是用于分配租户，具体的挂载是去服务树的页面挂载，可以去B站搜索滴滴夜莺v3的视频，有讲解如何使用的
