### ISSUE TITLE
监控项有数据，nodata告警策略，告警出来的值是null

### ISSUE THREAD

**Issue by jiangnanora** [didi/nightingale#682]
![image](https://user-images.githubusercontent.com/20857328/117534572-8d3f9e00-b024-11eb-94ac-a400c853d39c.png)

![image](https://user-images.githubusercontent.com/20857328/117534580-9a5c8d00-b024-11eb-9c1f-5306f47815e8.png)

版本V4.0.1

**Comment by UlricQin** [comment]
你看着有数据的是readOnly=1的tag，报警的是readOnly=0

**Comment by jiangnanora** [comment]
不过建议，tag中去除掉read_only和is_slave，因为这2个指标故障切换后就会发生变化

一旦发生变化，告警就一直存在，需要单独做禁用

tag中标明端口其实就能分清是哪个实例

**Comment by jiangnanora** [comment]
![image](https://user-images.githubusercontent.com/20857328/117615876-efbbaa00-b19c-11eb-9faf-afef4f613386.png)

![image](https://user-images.githubusercontent.com/20857328/117615953-07932e00-b19d-11eb-99ed-fbe53b0b3f6e.png)

好像还是有问题

**Comment by jiangnanora** [comment]
![image](https://user-images.githubusercontent.com/20857328/118908330-d3b1c880-b953-11eb-8309-788951c909d3.png)


![image](https://user-images.githubusercontent.com/20857328/118908391-ed531000-b953-11eb-8150-d99ed5bc0c07.png)


1,有值，却说没值？
2,另外我设置了180s nodata，180内只要3个点任意一个有值，也不应该告警

**Comment by shook2012** [comment]
nodata策略我也不太理解。  我上报了一个metric，每两小时上报一次。本想只要有中断上报就告警，但试了下，把告警周期配置成了7200秒或7500秒，希望只要7200秒内，没有数据上报，就告警，但我明明有数据上报，还是一样会报nodata~

**Comment by shook2012** [comment]
级别状态：P3 报警
策略名称：两小时内未自动处理投诉记录
告警设备：tousu_service
设备名称：投诉服务器
设备备注：
挂载节点：
inner.tousu_service
监控指标：sendim.heart.beat
指标标签：flag=success
当前值：sendim.heart.beat: null
报警说明： sendim.heart.beat (nodata,7500s)
触发时间：2021-05-18 10:06:10
报警详情：http://n9e.tianxiaxinyong.com/mon/history/his/548
报警策略：http://n9e.tianxiaxinyong.com/mon/strategy/22
认领报警：http://n9e.tianxiaxinyong.com/mon/history/cur/161

**Comment by shook2012** [comment]
版本，v4.0

**Comment by yhadyh** [comment]
数据上报周期设置成触发报警时间的一半试试，例如 上报周期是30秒，nodata触发条件改为60秒内无数据上报。

**Comment by UlricQin** [comment]
v5直接就没有nodata告警函数了~~~

**Comment by hnuzhoulin** [comment]
那如何处理相应agent故障时的告警？

**Comment by UlricQin** [comment]
用ping监控
