### ISSUE TITLE
请问夜莺v4如何做高可用，数据存储m3db是共用一个，还是每个服务器部署一个

### ISSUE THREAD

**Issue by wangxiajian** [didi/nightingale#684]
**What would you like to be added**:

**Why is this needed**:

**Comment by UlricQin** [comment]
高可用的话，m3db有集群模式，可以参考他们的官网：https://m3db.io/docs/ 然后server可以部署多台，server里边配置m3db的集群列表就可以了。server依赖redis，一个server部署一个本机单机redis，server依赖数据库，数据库搞一个全局的就可以了
