### ISSUE TITLE
在告警策略里排除子节点告警，不生效

### ISSUE THREAD

**Issue by MoonStill** [didi/nightingale#685]
![微信图片_20210511120313](https://user-images.githubusercontent.com/71972802/117756562-f146aa00-b250-11eb-9347-5b4b3adcd5c4.png)
我在告警策略里排除某个节点的告警，为啥不生效呢？ 还是一样会告警。

**Comment by UlricQin** [comment]
告警详情整页截图，机器挂载关系截图
