### ISSUE TITLE
策略相关问题

### ISSUE THREAD

**Issue by jiangnanora** [didi/nightingale#687]
根节点上配置了些策略，但子节点由于某些原因，需要单独配置部分策略

需求：
      这个子节点的策略遵循就近原则，使用本节点自己的策略，非定制的部分策略则沿用根节点的策略  

另外希望提供策略禁用功能

**Comment by UlricQin** [comment]
策略启用禁用会在v5解决，覆盖这个功能巨复杂，而且不好理解，目前不准备实现

**Comment by UlricQin** [comment]
v5已发：n9e.github.io
