### ISSUE TITLE
n9e-server启动过程卡住，导致没有监听8000及8001端口

### ISSUE THREAD

**Issue by hxp-forfun** [didi/nightingale#690]
n9e-4.0.1版本启动n9e-server时日志一直卡在下面这个地方，且没有错误日志，可能是什么原因
![image](https://user-images.githubusercontent.com/61815194/119475326-a3b55b80-bd7f-11eb-816f-89a7fe20d2f7.png)

**Comment by tpinellia** [comment]
![image](https://user-images.githubusercontent.com/49589374/119620279-67453680-be37-11eb-83af-0ff7dddd0324.png)
缺配置

**Comment by hxp-forfun** [comment]
> ![image](https://user-images.githubusercontent.com/49589374/119620279-67453680-be37-11eb-83af-0ff7dddd0324.png)
> 缺配置

我看b站里面的部署教学视频里面启动的时候也有这行日志
https://www.bilibili.com/video/BV1V64y117YY

**Comment by UlricQin** [comment]
m3没有执行curl命令初始化

**Comment by hxp-forfun** [comment]
> m3没有执行curl命令初始化

确实是我漏了这一步，重新初始化后好了，多谢！
