### ISSUE TITLE
能不能完善一下文档啊？

### ISSUE THREAD

**Issue by fengzhao** [didi/nightingale#691]
整个软件设计架构和思路，以及agent部署文档等等，agent与server的通讯等等，感觉文档很散，希望能稍微完善一下文档，帮助初学者更快上手

**Comment by UlricQin** [comment]
https://n9e.didiyun.com/v4/docs/intro/
B站上有视频也可以参考
公众号（运维散兵）也有视频
现在主要精力在v5版本，v5的时候架构做了较大调整，到时候会重新整理文档
