### ISSUE TITLE
自定义api，回调

### ISSUE THREAD

**Issue by Ellis-w** [didi/nightingale#696]
配置自定义API 会一直触发告警   改成回调 也是60秒触发一次 ，就不能 报警触发一次恢复触发一次吗？ 
![image](https://user-images.githubusercontent.com/62194013/120748308-2636db80-c535-11eb-890d-9104841fde3c.png)

**Comment by UlricQin** [comment]
v5-ga已发布，新版本只会调一次，可以试试：n9e.github.io
