### ISSUE TITLE
agent监控每天不定期报失联

### ISSUE THREAD

**Issue by yhadyh** [didi/nightingale#697]
**What happened**:
你好，每天不定期触发agent监控失联，
![image](https://user-images.githubusercontent.com/18721182/121185772-fec77200-c898-11eb-8cd6-db57cc1f55bf.png)
查看监控发现图表并没有断点
![image](https://user-images.githubusercontent.com/18721182/121186107-506ffc80-c899-11eb-97e1-e6f87160bd07.png)

ntpd时间一致，机器无负载压力。无错误日志，请问这种情况应该怎么排查
**Environment**:
- Nightingale Version (`./n9e-rdb -v`): 3.5.2
- OS Version (`uname -a`): Centos 6/Centos 7
- Logs (stdout/error/warning/http.request/http.response):
- Others:

**Comment by yhadyh** [comment]
restart judge组件后，所有的agent都报失联，当前值为: proc.agent.alive: null

**Comment by UlricQin** [comment]
如果你的描述属实，那就是bug

**Comment by yhadyh** [comment]
上报周期是60秒，报警触发条件是： proc.agent.alive持续 60 秒无数据上报

**Comment by sunha0** [comment]
确实是这样

**Comment by UlricQin** [comment]
> 我这边发现，agent上报周期 interval 是60秒，报警触发条件是： proc.agent.alive持续 60 秒无数据上报
> 是不是上报周期时间interval太长 @UlricQin

如果机器时间稍微不准就会报警，逻辑处理也需要时间，所以要避免这种边界情况。interval是60的话，策略里就要配置持续120s无数据上报才告警

**Comment by yhadyh** [comment]
谢谢，已经修改了上报时间 interval 为30秒后，没有在触发类似问题
