### ISSUE TITLE
对接LDAP能否自动获取邮箱和手机号？

### ISSUE THREAD

**Issue by taishen** [didi/nightingale#7]
如果可以，要如何配置？
如果不行，建议支持

**Comment by taishen** [comment]
另外能否支持导入LDAP用户？现在对接LDAP后，只有登录才会显示到用户列表里

**Comment by UlricQin** [comment]
现在不支持自动获取邮箱和手机号，也不支持导入LDAP用户，LDAP这块不太熟，后面找找社区里边是否有同仁对这块比较熟悉的给支持一下

**Comment by freedomkk-qfeng** [comment]
LDAP 登录自动导入手机/邮箱，这个需求我认领了。

**Comment by UlricQin** [comment]
thanks for @freedomkk-qfeng support https://github.com/didi/nightingale/pull/11
