### ISSUE TITLE
在agent下新建文件方式实现端口和进程监控失效

### ISSUE THREAD

**Issue by hnuzhoulin** [didi/nightingale#701]
**What happened**:
参考视频：https://www.bilibili.com/video/BV1dQ4y1N7Aq/
但是看文档上最新的确实没这么写了，是不是不支持了？

1.在某台agent机器上新建/home/n9e/etc/service/20_cmdline_dockerd，内容为 dockerd
2.systemd启动，/etc/systemd/system/agent.service
```
cat /etc/systemd/system/agent.service
[Unit]
Description=n9e agent
After=network-online.target
Wants=network-online.target

[Service]
# modify when deploy in prod env
User=root
Group=root

Type=simple
Environment="GIN_MODE=release"
ExecStart=/home/n9e/n9e-agent
WorkingDirectory=/home/n9e

Restart=always
RestartSec=1
StartLimitInterval=0

[Install]
WantedBy=multi-user.target
```

**What you expected to happen**: 在监控大屏可以看到对应的进程，但是实际没有，只有在界面上添加的sshd进程
![image](https://user-images.githubusercontent.com/6347012/121809283-d374c680-cc8e-11eb-8ec8-1b33512c4505.png)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Nightingale Version (`./n9e-rdb -v`):   
./n9e-agent -v
Version: 3.7.1
- OS Version (`uname -a`):Linux devopslocal001 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Logs (stdout/error/warning/http.request/http.response):
- Others:

**Comment by UlricQin** [comment]
v3 v4 不支持，必须在页面上配置
