### ISSUE TITLE
关于tag的使用--节点属性可以加tag吗

### ISSUE THREAD

**Issue by hnuzhoulin** [didi/nightingale#707]
**What would you like to be added**:
在添加告警策略的时候有tag过滤，但是目前除了自定义推动的告警自己加tag属性外，没有发现其他地方有自己添加这个属性的？
**Why is this needed**:
希望是能够给节点树下的节点添加各种tag，这样可以做到更精准的告警策略控制，尤其是区分灰度、线上不同环境时。

**Comment by UlricQin** [comment]
v5里边已经支持给设备打tag
