### ISSUE TITLE
v5版本，新建策略组会无显示

### ISSUE THREAD

**Issue by Zayscott** [didi/nightingale#709]
**What happened**:
点击【新建策略组】，无内容显示

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Nightingale Version (`v5`):
- OS Version (`3.10.0-957.el7.x86_64`):
![image](https://user-images.githubusercontent.com/26255043/123586787-d8518280-d817-11eb-9220-228d67701ff5.png)
![image](https://user-images.githubusercontent.com/26255043/123586857-f28b6080-d817-11eb-9657-a136f4f6b5f4.png)
![image](https://user-images.githubusercontent.com/26255043/123587019-3716fc00-d818-11eb-83fe-7bef97c4b336.png)

**Comment by UlricQin** [comment]
v5-ga已发版，rc版本的问题均在ga版本中解决，可以试试：n9e.github.io
