### ISSUE TITLE
关于项目开发规范化的一些建议

### ISSUE THREAD

**Issue by chenjiandongx** [didi/nightingale#71]
ping @710leo @UlricQin 

在参与这个项目的过程中，我觉得关于开发规范化可以进一步完善

* Git 协作中，在合并 PR 的时候建议使用 **Squash and merge** 选项（绝大多数的开源项目都使用这种做法）。因为一个 PR 中可能涉及多个小的 commit，这些 commit 大多数时候留在 master 主线记录中并无实际太大的意义，所以建议压缩，这样也可以显得 master 的提交记录清晰简洁。

* 建议使用 [Travis](https://travis-ci.org/) 做 CI 测试，一个优秀的开源项目应该具备良好的可测试性（nightngale 可以成为这样的项目）。

以上只是我个人的一些建议而已，仅供参考。:)

**Comment by UlricQin** [comment]
谢谢建议。

- 合并PR后面可以采用 Squash and merge 选项
- CI有些难度，夜莺的代码是从商业版本里扒出来的，也有一些新写的，很多代码都是经过了很多人的手，缺少自动化测试，CI流程倒是可以搞，只是现阶段可能用处较小
