### ISSUE TITLE
希望V4版本能够持续更新，保持版本的延续性。

### ISSUE THREAD

**Issue by felixglow** [didi/nightingale#711]
V5跟V4版本差距还是比较大的，对于接受或者上线V4的用户，期望能够继续更新V4版本，非常感谢~

**Comment by felixglow** [comment]
项目本身很好的，在给身边朋友推广的时候，有的就很有顾虑，被版本的延续性和方向的跳跃给劝退了

**Comment by UlricQin** [comment]
v4 v5会同步推进
