### ISSUE TITLE
v2版本得n9e服务器，接入ldap，选择ldap登录报错multi users is search, query user

### ISSUE THREAD

**Issue by xincuter** [didi/nightingale#712]
![image](https://user-images.githubusercontent.com/26621341/123773383-35743380-d8ff-11eb-8dd1-c9ee59b34934.png)
![image](https://user-images.githubusercontent.com/26621341/123773467-42912280-d8ff-11eb-93d0-6ebc54fba09f.png)

**Comment by UlricQin** [comment]
说明ldap里有重复用户
