### ISSUE TITLE
v3.7.1的监控看图-时间选择其他-点击时间选择后报错，页面空白

### ISSUE THREAD

**Issue by hnuzhoulin** [didi/nightingale#713]
**What happened**:
V3.7.1的监控看图-时间选择其他-点击时间选择后报错，页面空白
**What you expected to happen**:
正常选择自己想要的时间
**How to reproduce it (as minimally and precisely as possible)**:
![image](https://user-images.githubusercontent.com/6347012/124052918-dffc6b80-da51-11eb-9cbd-048fd3fed942.png)

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/6347012/124052837-c4916080-da51-11eb-9958-76aabb811436.png)

**Environment**:
- Nightingale Version (`./n9e-rdb -v`): Version: 3.7.1
- OS Version (`uname -a`): Linux n9e 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Logs (stdout/error/warning/http.request/http.response):
- Others:

**Comment by UlricQin** [comment]
试试最新的前端release：https://github.com/n9e/fe/releases 我们现在只要精力在v5版本，v5-ga已发版，可以试试新版：n9e.github.io
