### ISSUE TITLE
v5版本 删除资源分组提示网络异常

### ISSUE THREAD

**Issue by wuchenyanghaoshuai** [didi/nightingale#716]
在资源管理页面新建一个资源分组，然后删除以后就会提示网络错误
![image](https://user-images.githubusercontent.com/39818267/124257625-1f64ae00-db5f-11eb-88ea-38de2e031025.png)
![image](https://user-images.githubusercontent.com/39818267/124257646-25f32580-db5f-11eb-90f4-885875ce79c9.png)
![image](https://user-images.githubusercontent.com/39818267/124257676-2be90680-db5f-11eb-8bdb-3456fad3dc59.png)

**Comment by UlricQin** [comment]
这个应该是bug，最新版本已经修复了，官网给了一个测试环境，在上面操作没有复现
