### ISSUE TITLE
【v5.0.0-rc1】对告警指标进行变更后,原有的告警事件不会恢复

### ISSUE THREAD

**Issue by caiwenhao** [didi/nightingale#718]
### 操作记录
1. 新建告警策略 system_cpu_idle 低于80%告警
2. “时间管理”->‘“未恢复告警事件” 中出现对应的 告警事件  表达式: system_cpu_idle(all,60s) <= 80   value=79.782518
3. 修改告警策略 system_cpu_idle 低于50%告警  
4.  “时间管理”->‘“未恢复告警事件”  并没有按照预期的清除告警事件和发送恢复通知  

### 问题
* 对告警指标进行变更后,原有的告警事件不会恢复

**Comment by UlricQin** [comment]
这个应该是bug，我们看一下

**Comment by UlricQin** [comment]
v5-ga版本已发布，rc版本的问题都在ga版本里解掉了：n9e.github.io
