### ISSUE TITLE
V4.0.3   设备管理--详情--扩展字段，编辑某个分类时，其他分类也被同步修改【如图】

### ISSUE THREAD

**Issue by wwyywwyy** [didi/nightingale#725]
![微信截图_20210708204512](https://user-images.githubusercontent.com/50834817/125009827-e1ecad00-e097-11eb-8e1d-b6cf35716dc3.png)

**Comment by UlricQin** [comment]
刷新之后会变正常么

**Comment by wwyywwyy** [comment]
> 刷新之后会变正常么

不会正常

**Comment by UlricQin** [comment]
@jsers 帮看看？

**Comment by UlricQin** [comment]
@wwyywwyy 你的aaa、bbb、机房信息1、名称，这4个字段的key分别是什么？是否有重复

**Comment by wwyywwyy** [comment]
> @wwyywwyy 你的aaa、bbb、机房信息1、名称，这4个字段的key分别是什么？是否有重复

没有重复，如图：
![微信截图_20210712110039](https://user-images.githubusercontent.com/50834817/125224611-87a25500-e300-11eb-84a5-ac313dacdd60.png)

**Comment by wwyywwyy** [comment]
另外，创建窗口的标识、名称，和展示的标识、名称是反的

**Comment by UlricQin** [comment]
![image](https://user-images.githubusercontent.com/2769466/125427217-618c4af1-b59d-4e34-b512-f2205735d625.png)
![image](https://user-images.githubusercontent.com/2769466/125427280-061884ce-2ca8-47c3-aeec-1fa8ce86dbcb.png)
你的版本是最新的么，我这都好好的

**Comment by wwyywwyy** [comment]
> ![image](https://user-images.githubusercontent.com/2769466/125427217-618c4af1-b59d-4e34-b512-f2205735d625.png)
> ![image](https://user-images.githubusercontent.com/2769466/125427280-061884ce-2ca8-47c3-aeec-1fa8ce86dbcb.png)
> 你的版本是最新的么，我这都好好的。用这个前端试试：https://github.com/n9e/fe/releases/tag/3.5.6

 @多个分类就会有问题，一个分类正常，pub-3.5.6版本试了也有问题,
![编辑时](https://user-images.githubusercontent.com/50834817/125714678-6dc39204-8960-48ce-b931-c9ffd1d53952.png)
![保存后](https://user-images.githubusercontent.com/50834817/125714692-362cb15b-ce4e-42b9-a9da-414ee4c5f18d.png)

**Comment by wwyywwyy** [comment]
@UlricQin

**Comment by UlricQin** [comment]
了解了，回头修一下

**Comment by UlricQin** [comment]
后面主要精力会切到v5版本，建议看看v5版本 n9e.github.io
