### ISSUE TITLE
v4.0.3dockerfile和rpc端口问题

### ISSUE THREAD

**Issue by jiangzhen1002** [didi/nightingale#726]
dockerfiles/docker-compose.yaml中并未开放8001端口，但是etc/address.yml中默认rpc端口为8001导致不通，请问是不是我理解有误？是不是需要修改此默认端口号？

**Comment by jiangzhen1002** [comment]
我看出来了，v4.0.3的dockerfiles/n9e/Dockerfile
还是ADD的3.8的代码

**Comment by UlricQin** [comment]
是的，Docker compose是社区朋友在维护，比较滞后，试试v5新版本吧，n9e.github.io
