### ISSUE TITLE
n9e-5.0.0-rc1钉钉报警问题

### ISSUE THREAD

**Issue by VSMDD** [didi/nightingale#727]
版本：n9e-5.0.0-rc1
存储使用的M3db：
我想通过钉钉告警，配置完成后，在n9e页面可以看到事件告警，但是钉钉收不到报警，在ERROR.log 看了有报错日志
报错如下：
2021-07-13 17:07:26.580104 ERROR alert/consume.go:211 notify: exec script ./etc/script/notify.py occur error: exit status 1
2021-07-13 17:07:26.581844 ERROR alert/consume.go:211 notify: exec script ./etc/script/notify.py occur error: exit status 1
现在找不到哪里出了问题

**Comment by VSMDD** [comment]
这个是server中的配置：
![image](https://user-images.githubusercontent.com/31095506/125434362-e1ed4bd3-c728-4fcb-90ba-e4ca828a36c1.png)

**Comment by VSMDD** [comment]
这个是server.yml中的配置：
![image](https://user-images.githubusercontent.com/31095506/125446881-6e10e37b-d891-4cb3-9694-2ae60a26a7b9.png)

**Comment by UlricQin** [comment]
配置文件里的key配置的不对，token是配置到用户信息里的，不是配置到这个配置文件里的。另外要检查python脚本引用的库，是不是没有安装，特别是requests库，检查方式如下，执行下面的命令看是否报错

```
python -c "import requests"
```

**Comment by VSMDD** [comment]
> 配置文件里的key配置的不对，token是配置到用户信息里的，不是配置到这个配置文件里的。另外要检查python脚本引用的库，是不是没有安装，特别是requests库，检查方式如下，执行下面的命令看是否报错
> 
> ```
> python -c "import requests"
> ```

已经解决了，非常感谢
