### ISSUE TITLE
v5-rc1,在监控大盘创建图表成功，未显示

### ISSUE THREAD

**Issue by xvpenghao** [didi/nightingale#729]
**What happened**:
在监控大盘里面，新建图表后，为显示，后台数据返回正确，前端报错
![image](https://user-images.githubusercontent.com/45994122/125710895-e49c05dd-65cb-41d9-8f14-18ce8f96da7a.png)

![image](https://user-images.githubusercontent.com/45994122/125710734-de839de9-80cd-4185-9441-d866249fa13b.png)

![image](https://user-images.githubusercontent.com/45994122/125710778-e8eb534a-4384-401d-b7d0-f9410dc25ac3.png)

![image](https://user-images.githubusercontent.com/45994122/125710249-de707230-b6ac-40a1-9b7e-7f862a77fff3.png)

**What you expected to happen**:
监控大盘，新建图表，并显示我新建的图表

**How to reproduce it (as minimally and precisely as possible)**:
在监控大盘里面，新建图表及可，多创建几个就发现问题了

**Anything else we need to know?**:

**Environment**:
- Nightingale Version (`./n9e-rdb -v`):5.0.0-rc1
- OS Version (`uname -a`):`Linux aliyun-centos 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Logs (stdout/error/warning/http.request/http.response):
- Others:

**Comment by UlricQin** [comment]
116.85.64.82/pub.zip 使用这个前端的包试试
