### ISSUE TITLE
自定义监控api能否支持自定义字段data

### ISSUE THREAD

**Issue by spyvip** [didi/nightingale#73]
````
[
    {
        "metric": "disk.io.util",
        "endpoint": "10.86.12.13",
        "tags": "device=sda",
        "value": 15.4,
        "timestamp": 1554455574,
        "step": 20
    }
]
````

自定义监控api能否支持自定义字段data，data字段不参与指标过滤

场景：
有很多场景下http请求，会有一个traceId，这个是跟tags无关的，没有区分度，基本上是每次都不一样

**Comment by UlricQin** [comment]
这是一个好想法，之前就想搞，一直没来得及论证。因为这个改动比较大，需要把数据全链路都修改。 @710leo 抽空看看，能否支持。只要告警引擎那告警的时候能把这个信息带出来，就意义巨大。

**Comment by 710leo** [comment]
已支持，说明见 [文档](https://github.com/n9e/book/blob/master/content/zh/docs/api/data.md#%E4%B8%8A%E6%8A%A5%E6%95%B0%E6%8D%AE)
