### ISSUE TITLE
功能建议：增加给游客分享图表功能

### ISSUE THREAD

**Issue by dyw770** [didi/nightingale#730]
滴滴的大佬们好，关于夜莺图表分享的功能有点小建议。

**What would you like to be added**:
在多部门协作情况下，有时候需要分享图表给其他部门和同事，或者其他系统需要引入一小部分图表，这个时候希望能以游客的方式访问图表，即无需登录查看图表

**Why is this needed**:
在很多情下将图表分享出去时都是希望能以游客的方式来访问，如果仅仅是想分享给系统内部账号可以通过将对应账号拉到对应的组织下即可实现，所以我觉得分享的图标可以让操作者选择是否允许游客查看。

**Comment by UlricQin** [comment]
在v5里考虑一下这个功能。

**Comment by UlricQin** [comment]
v5 ga 版本已支持，可以试试n9e.github.io
