### ISSUE TITLE
增加api接口监控能力

### ISSUE THREAD

**Issue by huangll99** [didi/nightingale#733]
**What would you like to be added**:   
增加api接口监控能力

**Why is this needed**: 
1.系统自身提供的接口需要监控
2.系统依赖的第三方接口需要监控，依赖接口出现问题及时发现

**Comment by UlricQin** [comment]
v5版本可以使用m3db或者Prometheus做存储，可以使用blackbox_exporter来做api监控，搞一个Prometheus的进程作为抓取器，抓取blackbox_exporter的数据即可
