### ISSUE TITLE
v5-rc1 prometheus 作为存储，通过kafka_exporter采集，n9e配置告警策略后无法看不到告警信息

### ISSUE THREAD

**Issue by VSMDD** [didi/nightingale#736]
v5-rc1 prometheus 作为存储，通过kafka_exporter采集，n9e配置告警策略,触发模式两种都试过了，配置后都看不到告警信息
![image](https://user-images.githubusercontent.com/31095506/126258064-0518bc48-93a6-4941-a9f3-4057e9457fca.png)
![image](https://user-images.githubusercontent.com/31095506/126258158-4380516f-9067-4940-8f6a-7b8908feb1e1.png)

只看到warning中有警告信息：
![image](https://user-images.githubusercontent.com/31095506/126258291-f457afe5-3093-45a5-afec-68b9c57e7828.png)

下面是info.log日志：
![image](https://user-images.githubusercontent.com/31095506/126258322-df19d3e5-5a55-4c28-8fa5-9e4da8b590ef.png)

prometheus中alerts告警：
![image](https://user-images.githubusercontent.com/31095506/126258393-f9436571-c871-4e2f-855f-86512f7e480b.png)

现在不清楚是那块的问题，请告知，谢谢

**Comment by UlricQin** [comment]
按照最新的文档安装一下，新的是rc2版本，如果还有问题我们查一下

**Comment by VSMDD** [comment]
> 按照最新的文档安装一下，新的是rc2版本，如果还有问题我们查一下

我安装了rc2，测试上面提到的问题，还是存在，还是不能发送告警.
麻烦帮忙看下是什么问题，谢谢
这个是info.log
![image](https://user-images.githubusercontent.com/31095506/126745659-9dd97969-6b7e-465c-b44e-e8c243696082.png)

这个是配置server.yml
![image](https://user-images.githubusercontent.com/31095506/126745746-a9465443-ad62-4668-a894-1dec78f87ef2.png)

**Comment by UlricQin** [comment]
`./n9e-server -v` 看看版本

**Comment by UlricQin** [comment]
![image](https://user-images.githubusercontent.com/2769466/126790338-15130a79-afd8-4186-9806-48daab97fa26.png)
![image](https://user-images.githubusercontent.com/2769466/126790383-14d94232-35b1-4910-aa71-bc90e40223ab.png)

我测试了一下没问题，可以生成，数据不是通过n9e-server的，直接通过prometheus抓取exporter的数据的话，只能用prometheus模式配置
