### ISSUE TITLE
docker-compose部署项目，请问api   bash项目无法启动

### ISSUE THREAD

**Issue by williamjie** [didi/nightingale#74]
64e9acb99abc        api:latest                   "bash"                   6 minutes ago       Exited (0) 5 minutes ago                                       nightingale_api_1

单独docker run  api:latest /bin/bash  可以正常运行。

**Comment by williamjie** [comment]
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                     PORTS                               NAMES

64e9acb99abc        api:latest                   "bash"                   6 minutes ago       Exited (0) 5 minutes ago                                       nightingale_api_1

**Comment by williamjie** [comment]
另外还有一个问题：  nightingale_collector_1  docker 提示问题

2020/04/09 08:23:55 beego.go:90: Httplib: parse "http://127.0.0.1:5800/api/portal/collects/bash: route: command not found\nbash: ifconfig: command not found": net/url: invalid control character in URL

**Comment by xiaobaiskill** [comment]
一、你可能时通过后台运行了
这是写好的dockerfile,你可以参考一下，当初想部署在k8s上的
[dockerfile](https://gitee.com/jinmingzhi/nightingale-k8s/tree/master/docker/dockerfile)

二、没有ifconfig 命令

**Comment by UlricQin** [comment]
@williamjie 试试最新的代码
