### ISSUE TITLE
v5-rc3版本，m3db单机版做为后端存储，telegraf直接写入到m3db的数据，即时看图标签不全

### ISSUE THREAD

**Issue by tongorz** [didi/nightingale#742]
v5-rc3版本，m3db单机版做为后端存储，telegraf直接写入到m3db的数据，即时看图标签不全。
grafana画图可以看到所有标签。即时看图，标签搜索功能，可以用hostname，ifName搜索，无法用"ip"标签搜索。

![image](https://user-images.githubusercontent.com/28854458/126933264-610dbeb8-752a-48b8-9bfd-a123615b55d1.png)
![image](https://user-images.githubusercontent.com/28854458/126933296-396131fd-ff4e-4a86-bf45-f75e866dbd88.png)

**Comment by UlricQin** [comment]
你截的两张图的关系是？第一张图是把鼠标放在第二张上面出来的tootip么

**Comment by tongorz** [comment]
> 你截的两张图的关系是？第一张图是把鼠标放在第二张上面出来的tootip么
是的，表明我的监控数据里是有ip这个tag的。

**Comment by UlricQin** [comment]
在微信群里联系我，腾讯会议远程看看

**Comment by tongorz** [comment]
@UlricQin 抱歉哈，公司安全策略可能不允许外部远程。
问题我看可能出在这里。即时看图，用的数据应该是图中红框框的tag-pairs里的数据，这里的数据是不全的，并且输入框交互过程中不会更新数据。应该要根据用户输入的内容去取后端的数据的吧。
配置告警策略这里，用的是绿框框的tag-keys和tag-values，这里用的数据是正确的。
![image](https://user-images.githubusercontent.com/28854458/127090652-1d2e852c-e119-4eda-912a-0089feee5d39.png)

**Comment by UlricQin** [comment]
了解了，这俩接口前端给的limit不同导致的，后面会把limit调大

**Comment by UlricQin** [comment]
v5已发正式版，rc版本的问题都在正式版里解决：n9e.github.io
