### ISSUE TITLE
v5-rc3创建日志采集规则对tag的正则验证失败

### ISSUE THREAD

**Issue by litepastry** [didi/nightingale#754]
**创建日志采集规则时，1 如果不填写tag ，那么页面仍然校验tag . 2  如果填了tag , 即使正则正确，但仍然提示失败**:

**希望1  不填写tag则不要验证tag的正则是否正确。2  tag里的正则正确时，应该通过验证**:

![3](https://user-images.githubusercontent.com/79127039/127730659-d90365f8-d8ac-47dc-a8f9-8d1f9acfde20.png)

![1](https://user-images.githubusercontent.com/79127039/127730672-7e5428e6-32cd-4ca9-8b73-0cffd2e90c7b.png)
![2](https://user-images.githubusercontent.com/79127039/127730676-f0664c0f-7e76-4e0b-b6e4-acbe349d4689.png)

** v5 rc2 rc3 都有此问题**:

**Comment by UlricQin** [comment]
发现一个挺好的工具，可以试试：https://github.com/google/mtail
