### ISSUE TITLE
关于Judge数据的问题

### ISSUE THREAD

**Issue by CarrotH** [didi/nightingale#76]
![image](https://user-images.githubusercontent.com/4654392/78969104-c7e0b980-7b38-11ea-8b0f-712cc7ff747b.png)
这段是不是要求判断过程中不能出现丢点的情况，如果类似‘happen’这种条件也必须要求完整的时序数据，
还是会在存历史数据的时候已经做了处理

**Comment by 710leo** [comment]
可以出现丢点的情况，之前有过关于这个的[讨论](https://github.com/didi/nightingale/issues/53)
