### ISSUE TITLE
to enrich basic machine monitor metrics like openfalcon does

### ISSUE THREAD

**Issue by lizhaoyang1990** [didi/nightingale#765]
**What would you like to be added**:
Right now n9e only got 4   e.g.  CPU NET DISK  MEMORY
We need that many basic metric ,like :
CPU
Load
内存
磁盘
IO
网络相关
内核参数
ss 统计输出
端口采集
核心服务的进程存活信息采集
关键业务进程资源消耗
NTP offset采集
DNS解析采集
check this blog out : https://blog.csdn.net/weixin_30906701/article/details/98614951
**Why is this needed**:
because it is basic and  very important!
help solving problems
so ,please maintain  it ,thanks

**Comment by UlricQin** [comment]
大部分都有，进程、端口、ntp offset等
