### ISSUE TITLE
agent running无法很好的监控告警

### ISSUE THREAD

**Issue by lizhaoyang1990** [didi/nightingale#766]
**What would you like to be added**:
![image](https://user-images.githubusercontent.com/18639238/128983582-7bff2066-19cc-4e59-8785-0c17395a8f49.png)

![image](https://user-images.githubusercontent.com/18639238/128983407-6972fa9f-34c8-40d2-a84e-0783dfaaf62d.png)

当前只能利用absent函数对prometheus数据库中的agent_runing指标配置告警，太难用了，机器少还可以勉强配置，机器多了，就
不好管理和维护了。而且每台机器添加一个告警策略，又回到原始时代了？
**Why is this needed**:
agentrunning 进程本身就是单点的，如果它挂了，没有收到告警，那那台机器就盲点了，所以有多重要！

**Comment by UlricQin** [comment]
这个最佳实践是用blackbox_exporter做所有机器的ping监控，agent使用systemd或者supervisor托管，挂了会自动拉起。所以只要用ping监控做机器存活监控即可

**Comment by lizhaoyang1990** [comment]
那还需要另起一个exporter服务？每次调用ping模块监听写在yaml配置文件里的target机器信息？yaml配置文件维护起来不是很方便啊，机器很多的话，增删改查都不好用，请问下ping模块能否内置到n9e-server，在n9e内部启动一个子线程分管 agent存活？一体化

> 这个最佳实践是用blackbox_exporter做所有机器的ping监控，agent使用systemd或者supervisor托管，挂了会自动拉起。所以只要用ping监控做机器存活监控即可

**Comment by lizhaoyang1990** [comment]
![image](https://user-images.githubusercontent.com/18639238/129509503-b2804b57-c367-44ad-81eb-7c85be00db4b.png)


> 这个最佳实践是用blackbox_exporter做所有机器的ping监控，agent使用systemd或者supervisor托管，挂了会自动拉起。所以只要用ping监控做机器存活监控即可
类似这样：
![image](https://user-images.githubusercontent.com/18639238/129509524-f7ead52e-e9d6-4952-8a31-21b762d4c145.png)

**Comment by lizhaoyang1990** [comment]
> 这个最佳实践是用blackbox_exporter做所有机器的ping监控，agent使用systemd或者supervisor托管，挂了会自动拉起。所以只要用ping监控做机器存活监控即可

类似这样的，对用户透明的
![image](https://user-images.githubusercontent.com/18639238/129509590-e805bd95-14fb-4c63-9f85-c7218c3a8864.png)

**Comment by UlricQin** [comment]
这个不是这么简单的，在分布式环境下判断nodata很麻烦，我们先把基础功能做好，后面考虑这个事情怎么解决

**Comment by chpiter** [comment]
> 那还需要另起一个exporter服务？每次调用ping模块监听写在yaml配置文件里的target机器信息？yaml配置文件维护起来不是很方便啊，机器很多的话，增删改查都不好用，请问下ping模块能否内置到n9e-server，在n9e内部启动一个子线程分管 agent存活？一体化
> 
> > 这个最佳实践是用blackbox_exporter做所有机器的ping监控，agent使用systemd或者supervisor托管，挂了会自动拉起。所以只要用ping监控做机器存活监控即可

同样遇到这种情况
