### ISSUE TITLE
mymon-mysql上报数据问题

### ISSUE THREAD

**Issue by jiangnanora** [didi/nightingale#767]
之前mymon使用通过agent上报数据的，V5不支持agent上报，请问怎么上报数据，api接口是什么？

数据格式是怎样的？

![image](https://user-images.githubusercontent.com/20857328/129129190-635b1a7c-fe58-4307-a63c-26a17e2fe16f.png)

**Comment by UlricQin** [comment]
https://n9e.didiyun.com/docs/appendix/api/ 上报给server，不过数据结构发生了变化，mymon代码得改造适配新的数据结构
