### ISSUE TITLE
自定义标签配置超过3个，只正常显示1个，第二个第三显示异常 

### ISSUE THREAD

**Issue by lizhaoyang1990** [didi/nightingale#768]
**What happened**:
![image](https://user-images.githubusercontent.com/18639238/129315325-abe91cff-bf83-4165-991c-81f75addbd53.png)
![image](https://user-images.githubusercontent.com/18639238/129315414-a419ebc1-0a06-4b99-aefc-f85379fb1fc1.png)

**What you expected to happen**:
自定义标签应该正常正确的展示或者采集
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Nightingale Version (`./n9e-rdb -v`): version: 5.0.0-rc4
- OS Version (`uname -a`):3.10.0-862.el7.x86_64
- Logs (stdout/error/warning/http.request/http.response):
- Others:

**Comment by UlricQin** [comment]
https://github.com/didi/nightingale/commit/ca8a8701b48237774d220bf5f3e211716d06ea8e 在这个commit里修复
