### ISSUE TITLE
nightingale--V5的agentd插件机制问题

### ISSUE THREAD

**Issue by FE-wangjb** [didi/nightingale#770]
“插件输出样例其实没有ident、alias、time字段，因为插件是agentd驱动的，所以agentd会自动补上这些字段，无需插件输出这些字段”
---------------------以上摘自夜莺V5文档。
尊敬的开发者，您好：
我明白agentd这么设定是为了简化插件，使之更轻量化，但是这样的设定却使插件丢失了很多自定义的属性。目前，我遇到的问题是：我们需要从云监控（华为云/阿里云）中拉取某些中间件的监控数据，然后通过nightingale监控并告警。我把这些自定义的插件都放在一台主机上，通过这台主机调用公有云的API获取监控指标，但是上报到nightingale上的ident却只能是作为宿主机的ip，而不是自定义的IP或instance-id，因此导致无法将上报的数据进行合理有效的分组与告警设置，而这些问题在老版本的nightingale中是不存在的，因此，希望开发者能够注意到这个问题，time字段和ident字段可以支持自定义和默认等多种配置。
此致！

**Comment by UlricQin** [comment]
可以直接调用server的接口推送监控数据

**Comment by feixia5712** [comment]
是否可以借助promethues得采集pushgateway然后自定义推送到pushgateway，然后进行告警

**Comment by UlricQin** [comment]
v5正式版直接使用promql来告警，只要数据进了时序库，就可以
