### ISSUE TITLE
插件采集配置在一台hbase master机器上，支持批量采集上报多台regionservers 的metric信息

### ISSUE THREAD

**Issue by lizhaoyang1990** [didi/nightingale#771]
**What would you like to be added**:
目前在资源管理-资源分组下-新建一个插件采集，把一个采集脚本放到hmaster机器上，这个采集脚本将能够通过 hmaster jmx api获取所有regionserver机器信息，并且再次通过for循环获取每一个regionserver的jmx性能指标信息，并且把获取到的json都放到一个数据组里print出来，让agent接收，但是我试了下，ident改不了，都会被脚本所在的机器的ident覆盖，这是为何？
举个列子
[
    {
       "ident":"hbase-regionserver01"
        "metric": "regionserver.readRequestCount",
        "tags": {
            "cluster": "bdhbase"
        },
        "value": 1000,
        "type": "gauge"
    },
    {
       "ident":"hbase-regionserver02"
        "metric": "regionserver.readRequestCount",
        "tags": {
            "cluster": "bdhbase"
        },
        "value": 2000,
        "type": "gauge"
    }
  
]
**Why is this needed**:
因为有时候能够一个脚本管理一个集群的事情，就没必要把脚本拆分，去每个regionserver机器放一个jmx采集脚本
希望能够支持，我们拼装的json串里的ident，alias优先级比较高，不要被agent的给覆盖了。

**Comment by UlricQin** [comment]
把外层的ident和alias留空，写到tags里试试，tags中的key使用__ident__和__alias__

**Comment by lizhaoyang1990** [comment]
> 把外层的ident和alias留空，写到tags里试试，tags中的key使用__ident__和__alias__

好的老大，我试试，

**Comment by lizhaoyang1990** [comment]
![image](https://user-images.githubusercontent.com/18639238/129994309-b5323ff2-a55c-4f80-b3dc-cefd952b652c.png)
可以，我试了下，tags传4个标签，ident生效，然后alias没有啥作用，不传也罢
![image](https://user-images.githubusercontent.com/18639238/129994389-8b983616-7d83-4f84-9b53-42dc468b8d6f.png)

**Comment by UlricQin** [comment]
> 可以，我试了下，tags传4个标签，ident生效，然后alias没有啥作用，不传也罢

alias还是有用的，虽然不会出现在时序数据的标签中，但是会出现在资源管理的列表中，便于查看，后续夜莺版本迭代，也可能会把alias放到标签里，这样信息就会更为丰满
