### ISSUE TITLE
即时看图node前缀6s出来，elastic 19ms 返回没数据

### ISSUE THREAD

**Issue by lizhaoyang1990** [didi/nightingale#773]
**What would you like to be added**:
输入node开头前缀查询，查询node_exporter采集的指标，6s左右可以出来，但是输入elastic前缀查询，怎么等都出不来，
而且19ms就200返回了。这是为何？
![image](https://user-images.githubusercontent.com/18639238/130027249-b503d1eb-f79a-4afc-b046-b8b8332866f8.png)
![image](https://user-images.githubusercontent.com/18639238/130027446-90b03f81-607f-4ab1-843b-cfb97c7e099c.png)

**Why is this needed**:
需要查询prometheus数据

**Comment by lizhaoyang1990** [comment]
server： v5-rc6

**Comment by lizhaoyang1990** [comment]
![image](https://user-images.githubusercontent.com/18639238/130027785-9515d759-700b-4580-b841-a73f9208834f.png)
elastic有数据

**Comment by UlricQin** [comment]
node相关的指标量太大了，本来rc版本想模仿datadog的体验，发现量大了确实无法搞定，试试v5正式版吧 n9e.github.io
