### ISSUE TITLE
agent插件采集超时限制，求放开

### ISSUE THREAD

**Issue by lizhaoyang1990** [didi/nightingale#774]
**What would you like to be added**:
插件采集上报是不是有什么时间限制？可否给一个放开限制的agent二进制，我先run起来，把hbase集群指标监控起来。我的一个脚本抽取所有regionserver上所有region级别指标，汇聚到一起解析出表级别的get put 等metric，随着表的数量和region个数的增加，耗时也越长，观察下来，手动执行脚本耗时10s左右。但是放到agent上执行不了，报错，我用简单的shell脚本在最前面加sleep 10测试了下， 报一样的错。
script.go:194] /opt/n9e/agentd/scripts.d/hbase_metric.py run err signal: killed
script.go:194] /root/test-n9e.sh run err signal: killed
**Why is this needed**:
求放开超时限制，因为有些脚本/二进制，可能需要做大批量聚合计算的，如果是jar包甚至还有初始化等动作。所以耗时不是那么好控制，当然假如耗时过长像我这样10s，那我就会把采集频率调大的，这个我可以通过页面控制，但是agent层面执行插件时候
，求放开下时间限制

**Comment by guguji5** [comment]
@lizhaoyang1990 创建差距采集时 页面上支持了超时时间。 新的前端文件在https://github.com/n9e/fe-v5/releases/tag/v5.0.0-rc1中的pub-v5.0.0-rc1.zip，麻烦下载替换一下你本地的pub文件夹吧。

**Comment by lizhaoyang1990** [comment]
> @lizhaoyang1990 创建差距采集时 页面上支持了超时时间。 新的前端文件在https://github.com/n9e/fe-v5/releases/tag/v5.0.0-rc1
> 麻烦下载替换一下你本地的pub文件夹吧。

我当前的agent版本是比较新的v5-rc8 ，您这个pub版本是rc1？会不会比现在的rc8要老？

**Comment by guguji5** [comment]
这个release的肯定是比较新的～前端的版本和agent，server的是独立的。

**Comment by UlricQin** [comment]
v5正式版使用Telegraf做采集，试试正式版吧 n9e.github.io
