### ISSUE TITLE
新建一个触发模式是prometheus的告警策略，在外面将状态灰色后还是触发告警

### ISSUE THREAD

**Issue by lizhaoyang1990** [didi/nightingale#775]
**What happened**:
![image](https://user-images.githubusercontent.com/18639238/130181729-fcd33fbf-3858-4e13-b768-ed50db2add3a.png)

在这里将prometheus 数据告警（node exporter采集等的数据）状态置为不启用，但是还是告警 
但是如果是n9e采集的数据的告警策略，比如配置的端口采集，然后配置端口告警策略，在外面状态置为不启用，是不会收到告警的。为什么两者不一样呢？
**What you expected to happen**:
状态置为不启用，需要对n9e、prometheus两个触发模式下或者对两个不同方式的采集的metric（一个是agent，一个exporter自己采集的但是数据库是同一个）设置的告警策略都功能一致
**How to reproduce it (as minimally and precisely as possible)**:
histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{application="gateway",}[1m])) by (le)) >0.5
这是我的promsql语句，反正这个指标不是agent采集的就很好复现
**Anything else we need to know?**:

**Environment**: linux centos7
- Nightingale Version (`./n9e-rdb -v`): version: 5.0.0-rc6
- OS Version (`uname -a`): 3.10.0-862.el7.x86_64
- Logs (stdout/error/warning/http.request/http.response):
- Others:

**Comment by UlricQin** [comment]
不会出现这种情况，Nightingale模式和Prometheus模式都会校验status字段：https://github.com/didi/nightingale/blob/master/alert/consume.go#L244 

当然，告警策略会周期性下发，不会立马生效，所以，disable的策略，不会立马生效，20s左右会生效

**Comment by UlricQin** [comment]
v5已发布ga版本，相当于正式版来了，之前的rc版本的很多问题在ga版本里都已解决 n9e.github.io
