### ISSUE TITLE
由于时间戳延迟太大，数据点无法写入m3存储

### ISSUE THREAD

**Issue by pphust** [didi/nightingale#776]
夜莺版本：3.7.0
操作系统：Centos 7.2
问题：使用probe模块的elasticsearch采集，发现有时数据点延迟过大（datapoint too far in past）导致无法写入m3存储
相关日志：
**_2021-08-20 01:20:01.012027_** ERROR m3db/m3db.go:118 unable to writeTagged: failed to meet consistency level majority with 1/3 success, 3 nodes responded, errors: [error writing to host xxxxxxxx: Error({Type:BAD_REQUEST Message:datapoint too far in past: id=a28690fe1f0396b674ede6f4e63eb949, off_by=1s, timestamp=20 Aug 21 01:10 +0800, past_limit=20 Aug 21 01:10 +0800, **_timestamp_unix_nanos=1629393000000000000, past_limit_unix_nanos=1629393001000000000_**}) error writing to host  xxxxxxxx: Error({Type:BAD_REQUEST Message:**_datapoint too far in past_**: id=a28690fe1f0396b674ede6f4e63eb949, off_by=1s, timestamp=20 Aug 21 01:10 +0800, past_limit=20 Aug 21 01:10 +0800, timestamp_unix_nanos=1629393000000000000, past_limit_unix_nanos=1629393001000000000})]

数据采集周期被设置为10分钟一次，日志中当前时间为2021-08-20 01:20:01，past_limit_unix_nanos是1629393001000000000（2021-08-20 01:10:01），timestamp_unix_nanos是1629393000000000000（2021-08-20 01:10:00）。
当前时间与timestamp_unix_nanos恰好相差10分钟（一个采集周期），怀疑是因为收到了上个周期的数据点导致。

**Comment by UlricQin** [comment]
可以调整m3的这个时间，让m3允许更久之前的数据上报，具体是哪个参数我忘记了，可以查查m3官方文档
