### ISSUE TITLE
关于windows下agent不能正常运行的问题 

### ISSUE THREAD

**Issue by Puma000009** [didi/nightingale#780]
**What happened**:
下载二进制包n9e-agentd-5.0.0-rc8.windows.amd64.tar.gz
1.cmd执行命令：.\n9e-agentd.exe -f   f:\agent-win\etc\agentd.yaml
提示错误：[关于token的]

Getting sidstring from current user Error: authentication.tokenAuthFile.init() err: error writing authentication token file on fs: open ./etc/auth_token: The system cannot find the path specified.
E0823 15:24:49.252929    6712 agentd.go:14] authentication.tokenAuthFile.init()err: error writing authentication token file on fs: open ./etc/auth_token: The system cannot find the path specified.
而etc/下根本没有tokenAuth文件。
**What you expected to happen**:
能正常运行起来，
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Nightingale Version (`./n9e-rdb -v`): v5agent
- OS Version (`uname -a`): windows7 agent
- Logs (stdout/error/warning/http.request/http.response):
- Others:

**Comment by misslou** [comment]
老哥解决了么 遇到了同样的情况

**Comment by Puma000009** [comment]
解决了,&nbsp; 测试没问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "didi/nightingale"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月23日(星期四) 上午9:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [didi/nightingale] 关于windows下agent不能正常运行的问题  (#780)





 
老哥解决了么 遇到了同样的情况
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by misslou** [comment]
什么问题呢 求方法。

**Comment by Puma000009** [comment]
我在github.com或者gitee应该写了,




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "didi/nightingale"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月24日(星期五) 上午10:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [didi/nightingale] 关于windows下agent不能正常运行的问题  (#780)





 
什么问题呢 求方法。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Puma000009** [comment]
***@***.*** 我的邮箱




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "didi/nightingale"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月24日(星期五) 上午10:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [didi/nightingale] 关于windows下agent不能正常运行的问题  (#780)





 
什么问题呢 求方法。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Puma000009** [comment]
> 老哥解决了么 遇到了同样的情况

我解决了,而且我记得把我的解决方法公布了,但是现在看不到了,怎么回事? 你可以直接联系我,我帮你,共享互助精神我有的. ce_puma  邮箱 qq的。

**Comment by UlricQin** [comment]
去etc目录的同级目录运行
