### ISSUE TITLE
告警策略状态按钮从未启用切换到启用，无法触发告警，仍然是未启用

### ISSUE THREAD

**Issue by lizhaoyang1990** [didi/nightingale#781]
**问题现象**:
![image](https://user-images.githubusercontent.com/18639238/130441732-b5bab252-e917-4dfc-9467-ba0d4e43cd46.png)

**复现方法**:
随便做个端口采集，然后配置一个告警策略，设置为未启用，然后从外面将其设为启用，并不能触发告警
而且，在外面将状态改变后，INFO日志无信息。下面的日志截图是进入编辑后，啥事不干，就保存退出的日志
**环境信息**:

- 夜莺服务端版本 (通过`./n9e-server -v`可得知版本): rc6
- 夜莺客户端版本 (通过`./n9e-agentd -v`可得知版本): rc8
- 操作系统版本 (通过`uname -a`可得知OS版本):  3.10.0-862.el7.x86_64

**日志线索**:
INFO：
![image](https://user-images.githubusercontent.com/18639238/130441939-2456665b-b311-4da7-86e0-f3de42faf235.png)
无error warning

*日志分两部分，一个是logs目录下，重点查看ERROR日志；另一部分是stdout，如果是systemd托管的，可以通过 `journalctl -u <n9e-server|n9e-agentd> -f` 查看*

**Comment by UlricQin** [comment]
使用v5-ga版本，n9e.github.io
