### ISSUE TITLE
V5.0.0插件采集指标不成功

### ISSUE THREAD

**Issue by kevinniu666** [didi/nightingale#786]
根据官方的文档
https://n9e.didiyun.com/docs/usage/plugin/
配置了插件的采集，但是指标没有在server端显示。信息如下:

server端：
[root@vm10-50-0-80 server]# ./n9e-server -v
version: 5.0.0-rc6

[root@vm10-50-0-80 server]# cat etc/server.yml |grep -v \#
logger:
  dir: logs
  level: DEBUG
  rotatenum: 3

http:
  mode: release
  access: false
  listen: 0.0.0.0:8000
  pprof: false
  cookieName: n9e
  cookieDomain: ""
  cookieMaxAge: 86400
  cookieSecure: false
  cookieHttpOnly: true
  cookieSecret: 4696709ab8cc3ff2fea17b930158516b
  csrfSecret: 15b8ea164b5d3d9254677053c72a19f1

rpc:
  listen: 0.0.0.0:9000

mysql:
  addr: "n9e:Capgemini123!@tcp(10.228.82.239:3306)/n9e?charset=utf8&parseTime=True&loc=Asia%2FShanghai"
  max: 128
  idle: 16
  debug: false

trans:
  enable: true
  backend:
    datasource: "prometheus"
    prometheus:
      enable: true
      name: prometheus
      batch: 100000
      maxRetry: 5
      maxSamples: 50000000
      maxConcurrentQuery: 20
      lookbackDeltaMinute: 2
      maxFetchAllSeriesLimitMinute: 5
      remoteWrite:

        - name: prome01
          url: http://localhost:9090/api/v1/write
          remoteTimeoutSecond: 5
      remoteRead:
        - name: prome01
          url: http://localhost:9090/api/v1/read
          remoteTimeoutSecond: 5

contactKeys:
  - label: "Wecom Robot Token"
    key: wecom_robot_token
  - label: "Dingtalk Robot Token"
    key: dingtalk_robot_token

notifyChannels:
  - email
  - sms
  - voice
  - dingtalk
  - wecom

agent端,agentd.yml文件内容:
agent:
  ident: $ip
  workDir: /data/n9e/agentd
  alias: $hostname
  endpoints:
    - http://10.228.82.233:8000
  exporter:
   port: 8070
  statsd:
     enabled: true
     metricsStatsEnable: true

系统配置截图:
![image](https://user-images.githubusercontent.com/31185341/131277242-3006be7d-2687-4f3e-91c1-86edfeaead77.png)
采集脚本输出:
[root@falconserver-01 agentd]# plugin/n9e-plugin.sh 
[
    {
        "metric": "plugin_example_gauge",
        "tags": {
            "type": "testcase",
            "author": "ulric"
        },
        "value": 1630290753,
        "type": "gauge"
    },
    {
        "metric": "plugin_example_rate",
        "tags": {
            "type": "testcase",
            "author": "ulric"
        },
        "value": 1630290753,
        "type": "rate"
    },
    {
        "metric": "plugin_example_increase",
        "tags": {
            "type": "testcase",
            "author": "ulric"
        },
        "value": 1630290753,
        "type": "increase"
    }
]

**Comment by UlricQin** [comment]
https://github.com/n9e/n9e-agentd/releases/tag/v5.0.0-rc8 用这个最新的agent试试

**Comment by kevinniu666** [comment]
v5.0.0-rc8 这个版本可以采集到数据
![image](https://user-images.githubusercontent.com/31185341/131285833-fc6a392a-cbac-4ff0-bbe1-dfa39fc67788.png)

**Comment by UlricQin** [comment]
ok
