### ISSUE TITLE
告警策略，标签添加bug

### ISSUE THREAD

**Issue by RogerHuOut** [didi/nightingale#788]
**问题现象**:
修改已有的告警策略，标签过滤按端口，无法添加新的对象
![image](https://user-images.githubusercontent.com/41337455/131473606-872ba391-7392-4cba-8761-5c6bec729d60.png)

新建时，可以添加多个对象
![image](https://user-images.githubusercontent.com/41337455/131473367-ea14b256-a8e1-4108-ab25-2db6216379a1.png)

**Comment by guguji5** [comment]
你好，感谢反馈。我是V5的前端开发，这个问题修改了一下。
可以用`wget 116.85.64.82/pub.zip` 替换一下pub文件夹应该就好了。try it

**Comment by hufengjie** [comment]
> 你好，感谢反馈。我是V5的前端开发，这个问题修改了一下。
> 可以用`wget 116.85.64.82/pub.zip` 替换一下pub文件夹应该就好了。try it

你好，替换之后，告警策略页面打开显示空白
![image](https://user-images.githubusercontent.com/41337455/131693196-8089283b-dee3-48d7-9b22-a65bb86975e2.png)

**Comment by guguji5** [comment]
@RogerHuOut 非常抱歉，我又兼容了一下。麻烦再试一下 `wget 116.85.64.82/pub.zip` 替换一下试试看？

**Comment by RogerHuOut** [comment]
> wget 116.85.64.82/pub.zip

感谢，问题已解决

**Comment by RogerHuOut** [comment]
> @RogerHuOut 那就好，如果是前端的问题，前端仓库在 [https://github.com/n9e/fe-v5，可以提issue或pr](https://github.com/n9e/fe-v5%EF%BC%8C%E5%8F%AF%E4%BB%A5%E6%8F%90issue%E6%88%96pr)

**Comment by RogerHuOut** [comment]
> > @RogerHuOut 那就好，如果是前端的问题，前端仓库在 [https://github.com/n9e/fe-v5，可以提issue或pr](https://github.com/n9e/fe-v5%EF%BC%8C%E5%8F%AF%E4%BB%A5%E6%8F%90issue%E6%88%96pr)

ok
