### ISSUE TITLE
没安装n9e-agentd，资源管理--新建资源分组--挂在资源后(随便起的名字)不显示，并且不能删除资源分组

### ISSUE THREAD

**Issue by ys-zhaoyh** [didi/nightingale#790]
**问题现象**:
没安装n9e-agentd，资源管理--新建资源分组--挂在资源后(随便起的名字)不显示，并且不能删除资源分组
**复现方法**:
![image](https://user-images.githubusercontent.com/30956381/131770682-65fee02b-5207-42fb-b51e-adbdb2ceab56.png)
**环境信息**:
单台虚拟机，没安装n9e-agentd

- 夜莺服务端版本 (通过`./n9e-server -v`可得知版本):
- v5
- 夜莺客户端版本 (通过`./n9e-agentd -v`可得知版本):
- 操作系统版本 (通过`uname -a`可得知OS版本):

**日志线索**:

*日志分两部分，一个是logs目录下，重点查看ERROR日志；另一部分是stdout，如果是systemd托管的，可以通过 `journalctl -u <n9e-server|n9e-agentd> -f` 查看*

**Comment by UlricQin** [comment]
新版本已经限制了，不能添加非法资源。已经添加的脏数据，可以手工清理数据库，classpath_resource表

**Comment by ys-zhaoyh** [comment]
好的
