### ISSUE TITLE
tsdb占用内存会持续上涨，直至崩溃

### ISSUE THREAD

**Issue by Livel-tempest** [didi/nightingale#791]
**问题现象**:
item（即seriesID）数量固定的情况下，在tsdb所有的chunks都被写满后，github.com/didi/nightingale/src/modules/tsdb/cache.NewChunk、github.com/dgryski/go-tsz.(*bstream).writeByte (inline)、占用内存还是会持续上涨，原因是ChunksSlots中存储的chunk指针数量在持续增加，落盘到rrd的速度跟不上push到ChunksSlots的速度。

**复现方法**:
keepMinutes: 60
cache.keepMinutes :120
cache.spanInSeconds :900
cache.doCleanInMinutes:10
cache.flushDiskStepMs:1000
cache.flushDiskStepMs:1000
监控数据item为200W，每个item每30s进行一次push，

**环境信息**:

- 夜莺服务端版本 (通过`./n9e-server -v`可得知版本):n9e-v3.0.0
- 夜莺客户端版本 (通过`./n9e-agentd -v`可得知版本):
- 操作系统版本 (通过`uname -a`可得知OS版本):linux-amd64

**日志线索**:

**Comment by UlricQin** [comment]
量太大了，超过了单机能力上限
