### ISSUE TITLE
夜莺告警通知

### ISSUE THREAD

**Issue by ys-zhaoyh** [didi/nightingale#793]
**问题现象**:
![image](https://user-images.githubusercontent.com/30956381/133390613-851845d7-a8fc-44ff-a917-5da636ef652c.png)
prometheus模式触发告警中执行频率是周期性告警吗？（如果告警邮件通知的话）比如60s,60秒后还会再次发送邮件(对于没有恢复的告警)吗？如果是那我设置60s,只发送了一次邮件，后边没有在告警通知。
另外n9e有没有周期性告警通知的设置？

**复现方法**:

**环境信息**:

- 夜莺服务端版本 (通过`./n9e-server -v`可得知版本):
- 5.0.0-rc7-1
- 夜莺客户端版本 (通过`./n9e-agentd -v`可得知版本):
- v5-rc8
- 操作系统版本 (通过`uname -a`可得知OS版本):

**日志线索**:

*日志分两部分，一个是logs目录下，重点查看ERROR日志；另一部分是stdout，如果是systemd托管的，可以通过 `journalctl -u <n9e-server|n9e-agentd> -f` 查看*

**Comment by UlricQin** [comment]
没有周期性告警功能

**Comment by ys-zhaoyh** [comment]
> 没有周期性告警功能

那prometheus中这个执行频率是什么意思？

**Comment by UlricQin** [comment]
promql执行频率

**Comment by ys-zhaoyh** [comment]
奥奥，谢谢你
