### ISSUE TITLE
V5版本是否支持ldap登录

### ISSUE THREAD

**Issue by sunha0** [didi/nightingale#797]
**问题现象**:V5版本是否支持ldap登录

**复现方法**: 在配置文件中启用了配置，但是没看到在哪生效

**环境信息**:

- 夜莺服务端版本 (通过`./n9e-server -v`可得知版本):
- 夜莺客户端版本 (通过`./n9e-agentd -v`可得知版本):
- 操作系统版本 (通过`uname -a`可得知OS版本):

**日志线索**:

*日志分两部分，一个是logs目录下，重点查看ERROR日志；另一部分是stdout，如果是systemd托管的，可以通过 `journalctl -u <n9e-server|n9e-agentd> -f` 查看*

**Comment by UlricQin** [comment]
配置文件启用之后，登录页面填写ldap的用户名和密码即可
