### ISSUE TITLE
如何查看夜莺现在监控数据是多少

### ISSUE THREAD

**Issue by qianxiaodewo** [didi/nightingale#799]
**问题现象**:
1、在POST http://${agent.addr}/v1/push   可以查看主机类的监控数据，也就是有主机名的设备，但是有些是实例，也就是没有主机名，没有ident,那种如何看有多少个metric,我现在的需求就是查看我有多少metrice,但是目前的api 好像不支持，
**复现方法**:

**环境信息**:

- 夜莺服务端版本 (通过`./n9e-server -v`可得知版本):
- 夜莺客户端版本 (通过`./n9e-agentd -v`可得知版本):
- 操作系统版本 (通过`uname -a`可得知OS版本):

**日志线索**:

*日志分两部分，一个是logs目录下，重点查看ERROR日志；另一部分是stdout，如果是systemd托管的，可以通过 `journalctl -u <n9e-server|n9e-agentd> -f` 查看*

**Comment by UlricQin** [comment]
你是哪个版本
