### ISSUE TITLE
对接grafana需求

### ISSUE THREAD

**Issue by UlricQin** [didi/nightingale#8]
夜莺有索引和监控数据获取的api：https://n9e.didiyun.com/docs/api/ 
寻找对grafana比较熟悉的同仁，来跟grafna做个对接，欢迎联系我们认领该issue，共建社区

**Comment by jsers** [comment]
这个我领了吧，最近看了下 grafana，但是准备直接对接 7.0 了，以后的版本会抛弃 Angular 改成 React 实现。目前 7.0 还在 beta 版本正好这段时间慢慢开发，希望发布正式版后能同步上 n9e 的插件。

**Comment by UlricQin** [comment]
赞，咱们自己搞就可以搞得更易用一些了，可以填单个endpoint看图，可以填多个endpoint看图，可以填树节点看图，选树节点甚至可以直接弹出一棵树，这就牛X了 😄

**Comment by jsers** [comment]
https://github.com/n9e/grafana-n9e-datasource
