### ISSUE TITLE
夜莺V5版无法针对prometheus告警策略的复杂PromQL做告警屏蔽

### ISSUE THREAD

**Issue by golden23** [didi/nightingale#801]
**问题现象**:
我设置了一个prometheus的告警策略，策略主体如下：
![image](https://user-images.githubusercontent.com/13659813/134859252-0cbc34a7-d6dc-4663-b7f0-8d70a56fb880.png)
然后我再设置屏蔽规则，但是屏蔽规则中的“屏蔽指标”不管我怎么写，都无法生效，屏蔽指标我写了2种：
1、node_cpu_seconds_total 【promql中包含的原始metric】
2、sum by(instance) (avg without(cpu) (irate(node_cpu_seconds_total{mode="idle"}[5m]))) 【promql表达式】

请问，是我指定的屏蔽指标不对吗？还是现有的屏蔽机制就不支持复杂promql的屏蔽规则？

**Comment by UlricQin** [comment]
要看这个promql输出的内容是什么，你去PromDash里执行一下，把返回内容截个图我看看

**Comment by golden23** [comment]
输出内容如下：
![image](https://user-images.githubusercontent.com/13659813/134900643-ef2305c8-1aa8-479a-89b4-13fbddf39f2c.png)
