### ISSUE TITLE
V5版本触发告警后未恢复告警中显示告警信息，但无法发送钉钉或微信提醒

### ISSUE THREAD

**Issue by xxy-cn** [didi/nightingale#811]
**问题现象**:
V5版本触发告警后平台中未恢复告警中显示告警信息，但钉钉和微信提醒却无法正常发送，同时ERROR.log打印报错信息“ERROR alert/consume.go:208 notify: kill process ./etc/script/notify.py occur error no such process”
**环境信息**:

- 夜莺服务端版本 (5.0.0-rc7-1):
- 夜莺客户端版本 (5.0.0-rc8):
- 操作系统版本 ( 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux):

**日志线索**:
logs下的ERROR日志提示：
2021-11-10 16:08:06.436509 ERROR alert/consume.go:208 notify: kill process ./etc/script/notify.py occur error no such process

**Comment by UlricQin** [comment]
只有这些日志看不出来。我这没遇到问题，notify.py是个py脚本，只要go程序已经调用python脚本了，后面的逻辑都是python来干了，python大家应该都能看得懂，自己debug一下，加点日志啥的，或者等年底的新版本，新版本会简化python脚本，一些逻辑挪到go里，出问题的几率会变小

**Comment by UlricQin** [comment]
可以尝试新版本了，部署架构更简单了，n9e.github.io
