### ISSUE TITLE
arm服务器无法启动m3db和客户端

### ISSUE THREAD

**Issue by sxc-0726** [didi/nightingale#812]
**问题现象**:
1.无法启动m3db
2.客户端启动失败

**复现方法**:
1.cd m3dbnode-single
./scripts/install.sh
2. ./control start all

**环境信息**:
1.  4.0
2. 3.3
- 夜莺服务端版本 (通过`./n9e-server -v`可得知版本):
- 夜莺客户端版本 (通过`./n9e-agentd -v`可得知版本):
- 操作系统版本 (通过`uname -a`可得知OS版本):

**日志线索**:
1.
2. /usr/local/n9e/n9e-agent: /usr/local/n9e/n9e-agent: cannot execute binary file

*日志分两部分，一个是logs目录下，重点查看ERROR日志；另一部分是stdout，如果是systemd托管的，可以通过 `journalctl -u <n9e-server|n9e-agentd> -f` 查看*

**Comment by UlricQin** [comment]
我们提供的二进制是x86的，arm需要自己编译
