### ISSUE TITLE
IP作为唯一值无法满足现实场景

### ISSUE THREAD

**Issue by winthcloud** [didi/nightingale#813]
**问题现象**:
现在平台是以IP作为唯一值来进入监控的设备，现在有一种场景，公司是多云环境两个云之间有相同的IP，这样现该程序无法实现监控。 

**复现方法**:
相同IP的程序启动监控后无法使用，因为是同一个IP指标

**环境信息**:

- 夜莺服务端版本 (通过`./n9e-server -v` 可得知版本):n9e-4.0.3
- 夜莺客户端版本 (通过`./n9e-agentd -v`可得知版本):n9e-4.0.3
- 操作系统版本 (通过`uname -a`可得知OS版本):n9e-4.0.3

**日志线索**:

*日志分两部分，一个是logs目录下，重点查看ERROR日志；另一部分是stdout，如果是systemd托管的，可以通过 `journalctl -u <n9e-server|n9e-agentd> -f` 查看*

**Comment by UlricQin** [comment]
手工修改identity.yml，写个假的ip，或者使用v5.0新版，刚刚发布，文档地址：n9e.github.io
