### ISSUE TITLE
客户端agent.yml自定义report fields字段

### ISSUE THREAD

**Issue by wangwei0326** [didi/nightingale#814]
**What would you like to be added**:
我想在agent.yml中自定义一个字段来表示我这个agent是什么时候创建的，这样就可以知道 我这个机器是什么时候上线的。
在资产管理-->主机设备-->设备管理-->主机详细中只能看到更新时间，想自定义一个上线时间。

**Why is this needed**:
agent.yml自定义report fields字段中自定义字段如何实现

**Comment by UlricQin** [comment]
这个有bug，正常的设计是支持的，在ams里为主机自定义一个字段，然后在agent中为这个字段写一个shell，二者即可打通

**Comment by wangwei0326** [comment]
那这个有计划修改吗？或者有什么变通的办法可以查到agent的首次注册到系统的时间？

**Comment by UlricQin** [comment]
需要二开了得
