### ISSUE TITLE
bug（v5.0.0-ga-01）：告警规则中添加了告警接收者后，触发告警时没有同步

### ISSUE THREAD

**Issue by sansi567** [didi/nightingale#818]
问题现象:
测试端口探测，告警规则中添加了回调地址：${ibex}/1 ，告警时没有执行自愈脚本，在告警事件详情里查看“回调地址”为空。
复现方法:
测试端口探测，在告警规则中添加回调地址：${ibex}/ID ，net_response_result_code != 0 触发

环境信息:

夜莺前端版本：5.0.0-ga-01
夜莺后端版本：5.0.0-ga-01
操作系统版本 (通过uname -a可得知OS版本): CentOS 7.6
截图:
![image](https://user-images.githubusercontent.com/48613613/144823315-a4b0e04b-49d2-42c7-8123-9f1a0f9e03c6.png)
![image](https://user-images.githubusercontent.com/48613613/144823411-97322e35-842d-464b-a33b-3dc6d6e8ea23.png)

**Comment by UlricQin** [comment]
v5.0.0-ga-02 之后的版本已修复
