### ISSUE TITLE
告警策略，可以根据级别筛选

### ISSUE THREAD

**Issue by jiangnanora** [didi/nightingale#819]
![image](https://user-images.githubusercontent.com/20857328/144833074-4213f419-c48a-4f65-b383-96806fb22bc5.png)

**Comment by UlricQin** [comment]
这个可以支持，后面版本迭代进去

**Comment by UlricQin** [comment]
https://github.com/didi/nightingale/releases/tag/v5.0.0-ga-04 这个版本支持了
