### ISSUE TITLE
报警规则问题

### ISSUE THREAD

**Issue by spyvip** [didi/nightingale#82]
同一个metric，如果tag值不同，是不是就重新计算发送疲劳度时间？

还没细看代码。方便的话告知一下是哪个文件的代码

**Comment by 710leo** [comment]
@spyvip 你说的`重新计算发送疲劳度时间`指的是？同一个metric，如果tag值不同，在做异常值检测的时候，可以认为是不同的曲线，之间没有关系。

**Comment by spyvip** [comment]
![image](https://user-images.githubusercontent.com/1212932/79093827-0cae5f80-7d88-11ea-8ccb-110026d16a2a.png)
@710leo  就这个时间段。按照你所说的，同一metric，不同tag值，是不同的曲线，那这个时间段的值应该是**metric+tag进行唯一判断标识**

所以说要是有个扩展字段存储部分数据就好了，就是之前提的需求#73

**Comment by 710leo** [comment]
@spyvip  #73 的需求已完成，是否还有其他问题？
