### ISSUE TITLE
[n9e-v5] n9e-server warning级别  报404

### ISSUE THREAD

**Issue by nondevops** [didi/nightingale#820]
**问题现象**:
[n9e-v5] n9e-server warning级别  报404
![image](https://user-images.githubusercontent.com/12181410/144878350-e83a42d9-6606-4a87-a051-be5f29efea88.png)

**复现方法**:

**环境信息**:

- 夜莺服务端版本 (通过`./n9e-server -v`可得知版本):
- 夜莺客户端版本 (通过`./n9e-agentd -v`可得知版本):
- 操作系统版本 (通过`uname -a`可得知OS版本):

**日志线索**:

*日志分两部分，一个是logs目录下，重点查看ERROR日志；另一部分是stdout，如果是systemd托管的，可以通过 `journalctl -u <n9e-server|n9e-agentd> -f` 查看*

**Comment by UlricQin** [comment]
remote write地址看起来配置错了
