### ISSUE TITLE
[n9e-v5]PromQL:处选择“ALERT” 按“shift+enter”，再选择另一个，点击“执行”报错。

### ISSUE THREAD

**Issue by nondevops** [didi/nightingale#822]
**问题现象**:
![image](https://user-images.githubusercontent.com/12181410/145215295-122ef2b2-a8ea-4940-89f0-c80d9995af1e.png)
invalid parameter 'query': 2:1: parse error: unexpected identifier "ALERTS_FOR_STATE"

**复现方法**:
PromQL:处选择“ALERT” 按“shift+enter”，再选择另一个，点击“执行”报错。

**环境信息**:

- 夜莺服务端版本 (通过`./n9e-server -v`可得知版本):
- 夜莺客户端版本 (通过`./n9e-agentd -v`可得知版本):
- 操作系统版本 (通过`uname -a`可得知OS版本):

**日志线索**:

*日志分两部分，一个是logs目录下，重点查看ERROR日志；另一部分是stdout，如果是systemd托管的，可以通过 `journalctl -u <n9e-server|n9e-agentd> -f` 查看*

**Comment by UlricQin** [comment]
符合预期，去Prometheus的页面执行也是这个效果
