### ISSUE TITLE
v5-rc版本支持自定义开发采集插件脚本的方式正式版怎么搞？

### ISSUE THREAD

**Issue by lizhaoyang1990** [didi/nightingale#825]
**What would you like to be added**:
提咨询罢了，正式版教大家用telegrafa配置采集cpu disk memory network？
这些都是基础运维层面的数据，prometheus的node exporter都已经采集了
我诉求比如要监控大数据组件的监控数据采集，telegrafa支持不了吧

**Why is this needed**:
你比如要采集hadoop的主备是否切换，是否是一个active 一个standby，
你比如获取了一个主的active后，去采集它的jmx用到的监控数据可能还要加以计算等
这些都是要根据具体工作需要自定义的，在rc版本，自己写python脚本采集后，print给n9e-agent

新版本如何用夜莺采集大数据自定义监控数据？

**Comment by UlricQin** [comment]
两个办法：
1. Telegraf也支持插件，https://n9e.gitee.io/quickstart/telegraf/ 文章中有个调研笔记的链接，调研笔记里有exec模块的讲解
2. 直接推送数据给n9e-server的http接口
