### ISSUE TITLE
5.0.0-ga-04，左侧一级菜单滚动条美观问题

### ISSUE THREAD

**Issue by wushanru** [didi/nightingale#826]
**问题现象**:
![image](https://user-images.githubusercontent.com/60475921/145322265-1caa5779-7a95-48d3-b48b-3c6b9cae2a70.png)

**复现方法**:

在左侧打开2个一级菜单时，出现页面错乱，样式不美观问题。
**环境信息**:

- 夜莺服务端版本 (通过`./n9e-server -v`可得知版本):5.0.0-ga-04
- 夜莺客户端版本 (通过`./n9e-agentd -v`可得知版本):5.0.0-ga-02
- 操作系统版本 (通过`uname -a`可得知OS版本):Linux localhost.localdomain 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**日志线索**:

*日志分两部分，一个是logs目录下，重点查看ERROR日志；另一部分是stdout，如果是systemd托管的，可以通过 `journalctl -u <n9e-server|n9e-agentd> -f` 查看*

**Comment by UlricQin** [comment]
提到 github.com/n9e/fe-v5 吧，MacOS下chrome浏览，没有遇到你说的问题~

**Comment by UlricQin** [comment]
试试最新的版本：https://github.com/didi/nightingale/releases/tag/v5.0.0-ga-05
