### ISSUE TITLE
[5.0.0-ga-04]删除业务组后页面跳404

### ISSUE THREAD

**Issue by Songzhizong** [didi/nightingale#828]
**夜莺版本**:
前端版本：5.0.0-ga-02
后端版本：5.0.0-ga-04

**问题和复现方法**:
删除业务组的按钮在业务组详情页面，点击删除后业务组不存在了，但详情页面依然会获取之前业务组的详，此时页面会刷新并报404.

**Comment by UlricQin** [comment]
升级一下试试? https://github.com/didi/nightingale/releases/tag/v5.0.0-ga-04

**Comment by Songzhizong** [comment]
> 升级一下试试? https://github.com/didi/nightingale/releases/tag/v5.0.0-ga-04


抱歉，之前版本号填错了，目前使用的版本正是5.0.0-ga-04。

**Comment by UlricQin** [comment]
> > 升级一下试试? https://github.com/didi/nightingale/releases/tag/v5.0.0-ga-04
> 
> 抱歉，之前版本号填错了，目前使用的版本正是5.0.0-ga-04。

待会我发个5.0.0-ga-05试试，升级完了记得强制刷新浏览器再试

**Comment by UlricQin** [comment]
试试最新的版本：https://github.com/didi/nightingale/releases/tag/v5.0.0-ga-05
