### ISSUE TITLE
【5.0.0-ga-02】大盘变量选择all时无法正常完成promql查询

### ISSUE THREAD

**Issue by jinrongc1986** [didi/nightingale#830]
**夜莺版本**:
前端版本：5.0.0-ga-02
后端版本：5.0.0-ga-04

**问题和复现方法**:
在监控大盘创建了host变量，并且开启multi和all功能
![image](https://user-images.githubusercontent.com/20188576/145661979-9f9c6147-ef96-4759-b2e1-ebafb6e4a169.png)
在图标中使用$host变量查询
![image](https://user-images.githubusercontent.com/20188576/145661996-5e605208-659f-4fd1-98a9-c9f13b530e00.png)
在选择单个host时，能正常查询结果；但是当选择为all模式时，无法正常查询。

**Comment by guguji5** [comment]
https://github.com/n9e/fe-v5/releases/tag/5.0.0-ga-04 优化了一下，试试最新的包吧
