### ISSUE TITLE
【5.0.0-ga-02】大盘变量all-option功能不合理

### ISSUE THREAD

**Issue by jinrongc1986** [didi/nightingale#831]
**夜莺版本**:
前端版本：5.0.0-ga-02
后端版本：5.0.0-ga-04

**问题和复现方法**:
大盘变量all-option功能不合理：当前只有在打开multi功能时，all option功能才能生效，建议前端修改控制逻辑，按照实际可生效的逻辑做界面调整。

**Comment by guguji5** [comment]
@jinrongc1986 如果multi关闭意味着单选，如果展示了all，那么希望查询的时候all 意味着所有？ 

举个例子加入cpu，有cpu1，cpu2，cpu3。如果单选选了all，就把这三个都查出来？

这样的话，multi 开不开，all 都是一样的逻辑，就如上？

**Comment by UlricQin** [comment]
单选时promql中会写=表示equal，多选时promql中会写=~表示正则匹配，只有多选才能有all选项，如果单选，而选择了all，那就变成了cpu=(cpu0|cpu1)，这个是查不出数据的，=后面用了正则，不符合预期。所以，all选项，确实是只能先开启Multi才有用

**Comment by jinrongc1986** [comment]
> 
是的。
首先目前单独开启all option，我看是不会出现all的选择，所以我预计你们并没有准备再未开启multi下让all option生效。
然后是在多选下才开放时，当前抓包看到的信息是你们直接all返回给promql了，我不清楚promql后台是否直接支持all的概念，至少我目前看到是没有生效的，是不是需要你们在前端直接转换为cpu=~(cpu0|cpu1)这种模式才行，而不是传一个all回去。
多选正常
![image](https://user-images.githubusercontent.com/20188576/145706781-803e0928-fee0-490a-9c53-65d1cb59eb70.png)
all异常
![image](https://user-images.githubusercontent.com/20188576/145706796-1f3abaa8-aef4-4b23-bafa-224233cbb422.png)

**Comment by guguji5** [comment]
https://github.com/n9e/fe-v5/releases/tag/5.0.0-ga-04 @jinrongc1986  改了 更新一下前端包吧
