### ISSUE TITLE
v4.0.3 内网环境搭建的夜莺如何设置代理发送企业微信告警

### ISSUE THREAD

**Issue by Kerwin998** [didi/nightingale#832]
问题：内网环境搭建的夜莺如何设置代理发送企业微信告警
背景：我司安全要求较为严格，内网环境部署夜莺监控，v4.0.3版本，怎么设置代理出公网
已知 export ALL_PROXY=socks5://xxx 无效果

**Comment by UlricQin** [comment]
不支持这种方式。

可以使用v5-ga版本，v5是直接使用notify.py一个python脚本发送，可控度高得多，做一个nginx代理来代理企微、钉钉等的url，notify.py里连nginx代理应该好使

**Comment by kubehan** [comment]
经过验证，可以添加环境变量来实现,下面这个是K8s环境下的内网环境部署
          env:
            - name: GIN_MODE
              value: release
            - name: TZ
              value: Asia/Shanghai
            - name: HTTPS_PROXY
              value: 'https://proxy-idc1.cn:80'
            - name: HTTP_PROXY
              value: 'http://proxy-idc1.cn:80'
            - name: NO_PROXY
              value: >-
                localhost,127.0.0.1,10.250.0.0/16,10.254.0.0/16
