### ISSUE TITLE
【5.0.0-ga-05】配置了报警规则，没有触发报警

### ISSUE THREAD

**Issue by webliupeng** [didi/nightingale#833]
**夜莺版本**:5.0.0-ga-05

**问题和复现方法**:
docker compose启动的
这个语句在”即时查询“界面时可以查到的。在历史报警里没有任何记录，容器也没有输出任何日志，是我哪儿没弄对吗？
<img width="1159" alt="Screen Shot 2021-12-13 at 2 18 01 PM" src="https://user-images.githubusercontent.com/3380812/145762281-babd5f48-6a71-43b3-8f46-b14848243a69.png">

**Comment by UlricQin** [comment]
你配置了持续时长60秒，每30秒跑一次，正好一次是0一次是1，一次触发阈值一次没有，所以无法告警。你可以测试cpu_usage_idle>=0

**Comment by webliupeng** [comment]
换了一个指标，一直都为1的，依旧没触发报警。
@UlricQin 
<img width="680" alt="Screen Shot 2021-12-13 at 7 15 36 PM" src="https://user-images.githubusercontent.com/3380812/145803217-e43d0e28-6131-4580-b341-d0ec9b5a0b55.png">
<img width="782" alt="Screen Shot 2021-12-13 at 7 18 14 PM" src="https://user-images.githubusercontent.com/3380812/145803224-6b1bee35-12a4-4284-8e4a-a01d3a4be2ce.png">

**Comment by UlricQin** [comment]
去即时查询里查询这个promql，截图，截全
