### ISSUE TITLE
【5.0.0-ga-05】多集群模式，非default集群无法触发报警

### ISSUE THREAD

**Issue by supermanlb** [didi/nightingale#834]
夜莺版本:5.0.0-ga-05

**问题和复现方法**:
部署多台server,每台server配置一个不同的promethues Writers和Reader。在非default集群里，配置报警规则无法触发报警。另外，添加节点，对象列表里，默认都是在Default集群，必须手动update target表更新。

**Comment by UlricQin** [comment]
你没有弄懂原理，看一下B站上的视频，讲解如何接入多集群的，搜索：夜莺v5.0正式版，系列视频的第11个

**Comment by Ohimma** [comment]
这个解决了吗，是哪的问题啊，我看了好几遍，也没找到问题。。。
