### ISSUE TITLE
图表配置多个legend显示错位

### ISSUE THREAD

**Issue by zhushiyang** [didi/nightingale#836]
**夜莺版本**:
前端版本：5.0.0-ga-04
后端版本：5.0.0-ga-05

**问题和复现方法**:
配置legend显示：
![企业微信截图_16395588721383](https://user-images.githubusercontent.com/30135876/146155824-a1632b37-3bf4-47cf-9c73-96c7573314d1.png)
客户端SYN_SENT数量显示是500多
未配置legend显示：
![image](https://user-images.githubusercontent.com/30135876/146155900-668faa47-fede-45b2-833e-2c5460753cdb.png)

netstat_tcp_established显示是500多

**Comment by UlricQin** [comment]
已修复
