### ISSUE TITLE
图表中变量会显示已经不上报的agent信息

### ISSUE THREAD

**Issue by zhushiyang** [didi/nightingale#837]
**夜莺版本**:
前端版本：5.0.0-ga-04
后端版本：5.1.0

**问题和复现方法**:
问题描述：图表中的变量，会将之前已经不上报数据的信息展示出来

复现方法：将telegra停止掉，过一会在点击变量搜索

**Comment by UlricQin** [comment]
短期停掉的指标，不会立马没有，grafana也是这样的吧，等一段时间应该就没了

**Comment by guguji5** [comment]
根据 https://grafana.com/docs/grafana/latest/datasources/prometheus/#query-variable 来获取大盘变量值。虽然现在前端没传start和end。但是我发现传了 `/api/n9e/prometheus/api/v1/labels?start=1639828843&end=1639828843` start和end 一样，甚至start 大于 end，还是会返回该指标。

所以似乎并没有什么好办法。

**Comment by UlricQin** [comment]
https://github.com/n9e/fe-v5/releases 使用最新的前端的包可以解决
