### ISSUE TITLE
[v4] 使用组件采集数据后,配置nodata的告警策略,server端报错

### ISSUE THREAD

**Issue by pidouzi** [didi/nightingale#839]
**夜莺版本**:
v4
**问题和复现方法**:
错误日志：
2021-12-18 23:44:00.216424 ERROR judge/nodata.go:87 stra:&{Id:22 Name:nodata_service Category:2 Nid:2 ExclNidStr:null AlertDur:30 RecoveryDur:0 RecoveryNotify:1 ExprsStr:[{"eopt":"=","func":"nodata","metric":"prometheus_index_block_gc_cached_searches_matched_sum","params":[],"threshold":0}] TagsStr:[] EnableStime:00:00 EnableEtime:23:59 EnableDaysOfWeekStr:[0,1,2,3,4,5,6] ConvergeStr:[3600,1] Priority:3 Callback: NotifyGroupStr:[] NotifyUserStr:[] Creator:root Created:2021-12-18 22:54:32 +0800 CST LastUpdator:root LastUpdated:2021-12-18 22:54:32 +0800 CST NeedUpgrade:0 AlertUpgradeStr:{"users":[],"groups":[],"duration":60,"level":1} WorkGroupsStr:null Runbook: ExclNid:[] Nids:[2 2] Exprs:[{Eopt:= Func:nodata Metric:prometheus_index_block_gc_cached_searches_matched_sum Params:[] Threshold:0}] Tags:[] EnableDaysOfWeek:[0 1 2 3 4 5 6] Converge:[3600 1] NotifyGroup:[] NotifyGroupDetail:[] NotifyUser:[] NotifyUserDetail:[] LeafNids:[] Endpoints:[] AlertUpgrade:{Users:[] Groups:[] Duration:60 Level:1} JudgeInstance:192.168.228.130:8001 WorkGroups:[]} get query data respData:[0xc00a9d3110 0xc00a9d3180] err

复现：
1. 使用组件新增prometheus配置，告警策略配置nodata的表达式，设备相关中选择 **设备无关**，观察server端日志出现错误。相反带有配置相关设备的指标或策略是可以正常使用的

**Comment by UlricQin** [comment]
get query data respData:[0xc00a9d3110 0xc00a9d3180] err 后面得把这个日志完善一下才能看出来，现在看不出来

**Comment by pidouzi** [comment]
未使用组件
----------------start----------------------
(string) (len=6) "stra: "
(*models.Stra)(0xc00414b500)({
 Id: (int64) 23,
 Name: (string) (len=6) "nodata",
 Category: (int) 1,
 Nid: (int64) 2,
 ExclNidStr: (string) (len=4) "null",
 AlertDur: (int) 30,
 RecoveryDur: (int) 0,
 RecoveryNotify: (int) 1,
 ExprsStr: (string) (len=93) "[{\"eopt\":\"=\",\"func\":\"nodata\",\"metric\":\"nginx_connections_writing\",\"params\":[],\"threshold\":0}]",
 TagsStr: (string) (len=2) "[]",
 EnableStime: (string) (len=5) "00:00",
 EnableEtime: (string) (len=5) "23:59",
 EnableDaysOfWeekStr: (string) (len=15) "[0,1,2,3,4,5,6]",
 ConvergeStr: (string) (len=8) "[3600,1]",
 Priority: (int) 3,
 Callback: (string) "",
 NotifyGroupStr: (string) (len=2) "[]",
 NotifyUserStr: (string) (len=2) "[]",
 Creator: (string) (len=4) "root",
 Created: (time.Time) 2021-12-18 23:11:34 +0800 CST,
 LastUpdator: (string) (len=4) "root",
 LastUpdated: (time.Time) 2021-12-29 11:37:12 +0800 CST,
 NeedUpgrade: (int) 0,
 AlertUpgradeStr: (string) (len=48) "{\"users\":[],\"groups\":[],\"duration\":60,\"level\":1}",
 WorkGroupsStr: (string) (len=4) "null",
 Runbook: (string) "",
 ExclNid: ([]int64) <nil>,
 Nids: ([]string) <nil>,
 Exprs: ([]models.Exp) (len=1 cap=4) {
  (models.Exp) {
   Eopt: (string) (len=1) "=",
   Func: (string) (len=6) "nodata",
   Metric: (string) (len=25) "nginx_connections_writing",
   Params: ([]int) {
   },
   Threshold: (float64) 0
  }
 },
 Tags: ([]models.Tag) {
 },
 EnableDaysOfWeek: ([]int) (len=7 cap=9) {
  (int) 0,
  (int) 1,
  (int) 2,
  (int) 3,
  (int) 4,
  (int) 5,
  (int) 6
 },
 Converge: ([]int) (len=2 cap=4) {
  (int) 3600,
  (int) 1
 },
 NotifyGroup: ([]int64) {
 },
 NotifyGroupDetail: ([]models.Team) <nil>,
 NotifyUser: ([]int64) {
 },
 NotifyUserDetail: ([]models.User) <nil>,
 LeafNids: ([]int64) (len=1 cap=1) {
  (int64) 2
 },
 Endpoints: ([]string) (len=1 cap=1) {
  (string) (len=15) "192.168.228.130"
 },
 AlertUpgrade: (models.AlertUpgrade) {
  Users: ([]int64) {
  },
  Groups: ([]int64) {
  },
  Duration: (int) 60,
  Level: (int) 1
 },
 JudgeInstance: (string) (len=20) "192.168.228.130:8001",
 WorkGroups: ([]int) <nil>
})
(string) (len=10) "respData: "
([]*dataobj.TsdbQueryResponse) (len=1 cap=1) {
 (*dataobj.TsdbQueryResponse)(0xc0040cc930)({
  Start: (int64) 1640750600,
  End: (int64) 1640750691,
  Endpoint: (string) (len=15) "192.168.228.130",
  Nid: (string) "",
  Counter: (string) (len=25) "nginx_connections_writing",
  DsType: (string) "",
  Step: (int) 0,
  Values: ([]*dataobj.RRDData) (len=3 cap=4) {
   (*dataobj.RRDData)(0xc00a95c910)(<RRDData:Value:1 TS:1640750650 2021-12-29 12:04:10>),
   (*dataobj.RRDData)(0xc00a95c920)(<RRDData:Value:1 TS:1640750660 2021-12-29 12:04:20>),
   (*dataobj.RRDData)(0xc00a95c930)(<RRDData:Value:1 TS:1640750680 2021-12-29 12:04:40>)
  }
 })
}
----------------end----------------------




使用组件
----------------start----------------------
(string) (len=6) "stra: "
(*models.Stra)(0xc00a991200)({
 Id: (int64) 22,
 Name: (string) (len=14) "nodata_service",
 Category: (int) 2,
 Nid: (int64) 2,
 ExclNidStr: (string) (len=4) "null",
 AlertDur: (int) 30,
 RecoveryDur: (int) 0,
 RecoveryNotify: (int) 1,
 ExprsStr: (string) (len=104) "[{\"eopt\":\"=\",\"func\":\"nodata\",\"metric\":\"prometheus_nginx_connections_writing\",\"params\":[],\"threshold\":0}]",
 TagsStr: (string) (len=2) "[]",
 EnableStime: (string) (len=5) "00:00",
 EnableEtime: (string) (len=5) "23:59",
 EnableDaysOfWeekStr: (string) (len=15) "[0,1,2,3,4,5,6]",
 ConvergeStr: (string) (len=8) "[3600,1]",
 Priority: (int) 3,
 Callback: (string) "",
 NotifyGroupStr: (string) (len=2) "[]",
 NotifyUserStr: (string) (len=2) "[]",
 Creator: (string) (len=4) "root",
 Created: (time.Time) 2021-12-18 22:54:32 +0800 CST,
 LastUpdator: (string) (len=4) "root",
 LastUpdated: (time.Time) 2021-12-29 11:37:19 +0800 CST,
 NeedUpgrade: (int) 0,
 AlertUpgradeStr: (string) (len=48) "{\"users\":[],\"groups\":[],\"duration\":60,\"level\":1}",
 WorkGroupsStr: (string) (len=4) "null",
 Runbook: (string) "",
 ExclNid: ([]int64) <nil>,
 Nids: ([]string) (len=2 cap=2) {
  (string) (len=1) "2",
  (string) (len=1) "2"
 },
 Exprs: ([]models.Exp) (len=1 cap=4) {
  (models.Exp) {
   Eopt: (string) (len=1) "=",
   Func: (string) (len=6) "nodata",
   Metric: (string) (len=36) "prometheus_nginx_connections_writing",
   Params: ([]int) {
   },
   Threshold: (float64) 0
  }
 },
 Tags: ([]models.Tag) {
 },
 EnableDaysOfWeek: ([]int) (len=7 cap=9) {
  (int) 0,
  (int) 1,
  (int) 2,
  (int) 3,
  (int) 4,
  (int) 5,
  (int) 6
 },
 Converge: ([]int) (len=2 cap=4) {
  (int) 3600,
  (int) 1
 },
 NotifyGroup: ([]int64) {
 },
 NotifyGroupDetail: ([]models.Team) <nil>,
 NotifyUser: ([]int64) {
 },
 NotifyUserDetail: ([]models.User) <nil>,
 LeafNids: ([]int64) <nil>,
 Endpoints: ([]string) <nil>,
 AlertUpgrade: (models.AlertUpgrade) {
  Users: ([]int64) {
  },
  Groups: ([]int64) {
  },
  Duration: (int) 60,
  Level: (int) 1
 },
 JudgeInstance: (string) (len=20) "192.168.228.130:8001",
 WorkGroups: ([]int) <nil>
})
(string) (len=10) "respData: "
([]*dataobj.TsdbQueryResponse) (len=2 cap=2) {
 (*dataobj.TsdbQueryResponse)(0xc00ae73960)({
  Start: (int64) 1640750490,
  End: (int64) 1640750581,
  Endpoint: (string) (len=10) "__nid__2__",
  Nid: (string) (len=1) "2",
  Counter: (string) (len=77) "prometheus_nginx_connections_writing/target=http://192.168.228.1:8080/metrics",
  DsType: (string) "",
  Step: (int) 0,
  Values: ([]*dataobj.RRDData) (len=3 cap=4) {
   (*dataobj.RRDData)(0xc00b077f90)(<RRDData:Value:1 TS:1640750540 2021-12-29 12:02:20>),
   (*dataobj.RRDData)(0xc00b077fa0)(<RRDData:Value:1 TS:1640750560 2021-12-29 12:02:40>),
   (*dataobj.RRDData)(0xc00b077fb0)(<RRDData:Value:1 TS:1640750570 2021-12-29 12:02:50>)
  }
 }),
 (*dataobj.TsdbQueryResponse)(0xc00ae739d0)({
  Start: (int64) 1640750490,
  End: (int64) 1640750580,
  Endpoint: (string) "",
  Nid: (string) (len=1) "2",
  Counter: (string) (len=77) "prometheus_nginx_connections_writing/target=http://192.168.228.1:8080/metrics",
  DsType: (string) "",
  Step: (int) 0,
  Values: ([]*dataobj.RRDData) <nil>
 })
}
----------------end----------------------

**Comment by pidouzi** [comment]
使用插件 len(respData) = 1
使用组件 len(respData) = 2，并且第二个dataobj.TsdbQueryResponse结构体Values值是空的
![image](https://user-images.githubusercontent.com/50960351/147628162-cd2b726f-6816-4c07-842a-15958cc3cdcc.png)

**Comment by UlricQin** [comment]
采集Prometheus的监控数据，建议直接使用v5
