### ISSUE TITLE
告警恢复留观时间

### ISSUE THREAD

**Issue by CarrotH** [didi/nightingale#84]
当前告警恢复后实时发送，留观时长未生效

**Comment by crazylsq** [comment]
我也测试了，告警留观未生效

**Comment by 710leo** [comment]
嗯，这块有点问题，我们解决一下

**Comment by 710leo** [comment]
fixed by this [commit](https://github.com/didi/nightingale/commit/256dceb624b0ba249ebddfde1c5aef8131bdf2ef)
