### ISSUE TITLE
web无法显示容器监控的数据

### ISSUE THREAD

**Issue by Dulingxiao** [didi/nightingale#840]
现象：
宿主机监控指标ok
容器监控 podname展示成功，但是容器监控没有展示数据，
接口返回
![image](https://user-images.githubusercontent.com/30493081/146912243-fdec8986-8ee8-47e2-a7ce-3104d8dc85d3.png)

自查 docker-mon上报数据正常
![image](https://user-images.githubusercontent.com/30493081/146912324-98fe8968-bf73-4d86-9d0a-4f062e33e622.png)

客户端 服务端 容器内 时间对齐

docker-mon 和 n9e-agent日志查询 无异常

请问还有别的原因吗。
或者需要别的什么信息才能定位吗

**Comment by UlricQin** [comment]
查看设备无关的监控数据，也看不到么？我也没有思路
