### ISSUE TITLE
5.1.0 监控大盘正则匹配导致白屏

### ISSUE THREAD

**Issue by bbaobelief** [didi/nightingale#841]
**夜莺版本**:
前端版本：5.0.0-ga-04
后端版本：5.1.0

**问题和复现方法**:
监控大盘自定义变量，如果填写了**筛值正则**会导致页面白屏

![image](https://user-images.githubusercontent.com/3918461/146919041-9a31a1d9-c8e3-4601-a8df-0e9c692922c5.png)

**Comment by guguji5** [comment]
收到，让我修复一下。wait a moment

**Comment by guguji5** [comment]
@bbaobelief 代码修了，还没发release，着急可以自己build一个前端包用 https://github.com/n9e/fe-v5

**Comment by bbaobelief** [comment]
验证已修复。
