### ISSUE TITLE
5.1.0 即时查询白屏

### ISSUE THREAD

**Issue by bbaobelief** [didi/nightingale#842]
**夜莺版本**:
前端版本：5.0.0-ga-04
后端版本：5.1.0

**问题和复现方法**:
即时查询，如果时间选择大一些，比如1个月，点击堆叠图形会白屏（可能是加减过机器，查询的数据不一致）

![image](https://user-images.githubusercontent.com/3918461/147030050-063ee127-d215-4045-a02f-342a9426be70.png)

![image](https://user-images.githubusercontent.com/3918461/147029935-59bb29dc-3f7f-457c-9080-9d64e2e651d5.png)

**Comment by UlricQin** [comment]
https://github.com/n9e/fe-v5/releases 使用最新的前端的包还有问题么？

**Comment by bbaobelief** [comment]
> 

前端版本：5.1.1 测试还有问题。

**Comment by bbaobelief** [comment]
> 模仿了一会有数据，一会没数据的情况，没有复现....

要这样复现：第一次上报的数据有device, 我删除了device标签。然后再这样查询：
` disk_used_percent{ident="xxx-m3db01.bj",path="/"}` 如果指标tag发生了变化就会白屏。
```
disk_used_percent {device=vda1,fstype=ext3,ident=xxx-m3db01.bj,path=/}
disk_used_percent {fstype=ext3,ident=xxx-m3db01.bj,path=/}
```

![image](https://user-images.githubusercontent.com/3918461/150273025-568390e3-ad90-435a-a2e9-be93c93174df.png)

**Comment by UlricQin** [comment]
好，我们看看

**Comment by xuhui54** [comment]
该问答题在以下版本依旧存在
前端版本：5.1.2
后端版本：5.3.4
选择指标查询，切换到该试图页面变白

**Comment by UlricQin** [comment]
https://github.com/n9e/fe-v5/releases/tag/v5.1.5 前端从这个版本开始应该就修复了，可以升级试试
