### ISSUE TITLE
关于夜莺v5屏蔽报警的问题

### ISSUE THREAD

**Issue by tulvqc** [didi/nightingale#843]
关于夜莺v5屏蔽报警的两个问题，帮忙确认一下

1. 在屏蔽报警时，屏蔽的只是后面再触发匹配后的报警，但是对于现在再报的，在活跃报警里并没有消失。能否在活跃报警中也进行删除或者添加silence的静默标识来区分？
2. 报警屏蔽时的标签，因为没有默认的alertname标签项，所以会出现匹配label时会把一些列关于这个label的所有报警也会屏蔽。现在的处理方式我会添加报警时再添加用于区分不同报警名称的标签，这样才能在屏蔽规则时精准屏蔽想要屏蔽的规则。能否对于自动将报警名称也当成一种标签项，自动加到label组里？

**Comment by UlricQin** [comment]
1. 不支持，屏蔽规则是有时间生效范围的，通常的做法是从现在开始屏蔽一段时间，屏蔽开始时间就是创建屏蔽规则的时间，而告警既然已经产生了，说明告警事件的生成时间通常不在该屏蔽规范时间范围内
2. 目前没有什么强力的场景来支持做这样的设计，你具体是什么场景？

**Comment by tulvqc** [comment]
1.第一个，其实我们之前的场景是借助于alertmanager或者或者grafana alert的功能，里面有一个静默silence选项，我不知道咱们的屏蔽 是否跟这个场景类似。因为或多或少的会有这种临时静默或者永久静默的场景，主要是面对不同的人员或者业务人员他们对于这个报警的处理是不同的
2.第二个场景，其实也是我们按照alertmanager中的alertname项，我们来分组报警，然后在通过拆分拆分出来的alertname标签，来具体静默不同的规则

**Comment by UlricQin** [comment]
1. 夜莺不是不支持静默，仍然是支持静默的，只是，已经发送的活跃告警是存在数据库中的，不会再删除，因为静默是有时间范围的，这个逻辑不自洽，就是我上一个回答里说明的。
2. Prometheus里的alert rule是有alertname和summary的配置，你可以把夜莺的告警规模名称当成summary对待，alertname就类似一个标签，所以，可以放appendtags中

**Comment by tulvqc** [comment]
还有一个关于V5版本告警分组、收敛等类似于alertmanager的功能，后面会有规划做么，我看官网上写是吧这块的功能拿掉了，后面会形成一个单独的模块进行开发。这块需求还是挺重要的，因为都是按照label的不同进行收敛和分组。

**Comment by UlricQin** [comment]
不准备在夜莺里做

**Comment by UlricQin** [comment]
看到一个类似项目，好未来出品的啸天犬，可以看看。夜莺里目前不准备搞这个
