### ISSUE TITLE
探讨下V5版本

### ISSUE THREAD

**Issue by 1393467261** [didi/nightingale#844]
夜莺V3落地生产一年半（1000+ app），监控整体架构nightingale+influxdb+grafana，效果十分可观👍。同时也发现该架构的一些短板：1，influxql拓展性差；2，nightingale报警模型较简单
夜莺V5让我眼前一亮，所有问题都解决了！
想学习一下各位作者们是如何想到这个idea的。

**Comment by UlricQin** [comment]
夜莺之前的版本，告警规则不够灵活，在云原生场景下是无法忍受的，如果要做的灵活必须要有ql的能力，而自己搞一个ql就是重复造轮子了，而promql确实是灵活，基本上就是metrics监控领域事实上的标准了，所以我们一定要直接支持promql。

其实Prometheus已经非常完备，但是在公司内落地，需要很多人一起用这个平台，会确实一些协作层面的产品能力，夜莺就是补齐了这个Prometheus的短板

**Comment by 1393467261** [comment]
嗯嗯，ql告警+持久化层兼容Prom+面向企业，相信这条路是对的！感谢解答
