### ISSUE TITLE
5.1.0 监控大盘all变量不生效

### ISSUE THREAD

**Issue by bbaobelief** [didi/nightingale#846]
**夜莺版本**:
前端版本：5.0.0-ga-04
后端版本：5.1.0

**问题和复现方法**:
host选择all, 应该只有5个机器，但是图表显示有7个。

![image](https://user-images.githubusercontent.com/3918461/147331287-24ebeee7-1111-40a8-8294-e45f0425c9d2.png)

![image](https://user-images.githubusercontent.com/3918461/147331186-2a01b6f1-06bc-4e2c-9234-3fdbbd3cfb7b.png)

**Comment by UlricQin** [comment]
看看拉取host下拉框的数据的时候，浏览器发的请求参数以及返回的内容是什么

**Comment by bbaobelief** [comment]
> 看看拉取主机下拉框的数据的时候，浏览器发的请求参数以及返回的内容是什么

如果选择all，请求的参数传的是所有机器，非正则过滤的。
![image](https://user-images.githubusercontent.com/3918461/147428691-0ed730f2-aa98-4fec-99fc-4a91cda29049.png)

**Comment by UlricQin** [comment]
我的意思是展示5台机器那个接口的request和response

**Comment by bbaobelief** [comment]
> 我的意思是展示5台机器那个接口的request和response

Request URL: http://xxx.cn/api/n9e/prometheus/api/v1/series?match[]=system_uptime

![image](https://user-images.githubusercontent.com/3918461/147639878-725c9842-f2ff-4e3b-96ed-971da13ff16f.png)

**Comment by UlricQin** [comment]
看这个返回，是返回了很多机器，你的下拉框里只有5台么？如果是这样可以远程看看哈，我的微信UlricGO

**Comment by bbaobelief** [comment]
> 看这个返回，是返回了很多机器，你的下拉框里只有5台么？如果是这样可以远程看看哈，我的微信UlricGO
接口查出来很多机器，所以我用了正则匹配到5台机器。此时**all**应该等于正则匹配的5台机器不应该是所有机器。这个问题前端修一下就行。

![image](https://user-images.githubusercontent.com/3918461/147720532-e10a5430-8b7f-4906-a00e-b7b9751c7e88.png)

**Comment by guguji5** [comment]
@bbaobelief 感谢反馈，已修改。https://github.com/n9e/fe-v5/releases/tag/v5.1.1

**Comment by bbaobelief** [comment]
验证已修复，感谢。
