### ISSUE TITLE
升级到5.2.0后，前端无法显示多集群

### ISSUE THREAD

**Issue by supermanlb** [didi/nightingale#847]
**夜莺版本**:

前端版本：5.0.0-ga-04
后端版本：5.2.0

**问题和复现方法**:

监控对象-前端列表
![image](https://user-images.githubusercontent.com/7801207/147344920-9eb25ff1-86f0-4bd4-a38e-940c08bdefa8.png)

**Comment by UlricQin** [comment]
你肯定是把webapi.conf配置覆盖了
