### ISSUE TITLE
官方教程看不懂

### ISSUE THREAD

**Issue by willzhang** [didi/nightingale#851]
**What would you like to be added**:
官方教程写详细一点

**Why is this needed**:
小白一脸懵

参考这篇文章使用docker compose up -d 起来后，下一步要做什么并没有说明，整个界面一片空白
https://n9e.github.io/best-practice/linux_host/

监控linux操作系统，这一坨东西是要让我粘贴到什么地方吗，莫名其妙啊
![nightingale.png](https://s2.loli.net/2021/12/26/WBNtJ68kqh9LG1R.png)

**Comment by UlricQin** [comment]
去B站搜视频
