### ISSUE TITLE
n9e单机部署接入prometheus后webui无法识别监控对象

### ISSUE THREAD

**Issue by jkeycat** [didi/nightingale#852]
**我部署的n9e-webapi和n9e-server,版本为5.0.0，接入prometheus**:

**prometheus的数据来源于pushgateway，采集的工具是各种exporter,而不是telegrah**:

**现在的问题是通过即时查询可以查询到监控的数据，但是监控对象里无法正确识别。**:

**是否有方法解决这一问题**:

**我从官方文档了解到可以这样部署，是否还需要其他方式来转换来自prometheus的时序数据**:
**姿势一：只是把Nightingale作为WEBUI
只部署n9e-webapi和n9e-server，配合Prometheus以及各类Exporter，可以在夜莺WEBUI上查看监控数据，配置监控大盘，配置告警规则、屏蔽规则、订阅规则，查看活跃告警、历史告警。且各类配置可以按照业务组拆分归组，相互之间没有影响。

说只是作为WEBUI，其实不止，这种工作模式实际是替换掉了Prometheus内置的告警引擎+alertmanager，只需用Prometheus存时序数据，用Exporter抓取数据即可。**:

**Comment by UlricQin** [comment]
对象列表里没有监控对象也没啥大不了的。照样可以配置告警规则，照样可以配置监控大盘，核心功能都不影响。没有必要非得通过监控对象的视角来使用。

原理上来说，监控数据当中必须带有ident标签，才会被当做监控对象，比如Prometheus生态的各类Exporter，都是用instance标签表示实例，不是ident，所以没法当做监控对象，当然了，也可以考虑把instance通过relabel的方式把标签重命名为ident。

其次，监控对象列表，是从mysql中取的，监控数据上报的时候，流经n9e-server，n9e-server从标签中获取ident的值，把ident值写入mysql，因为通过Exporter采集的监控数据部流经n9e-server，所以，监控对象的mysql表中不会自动出现ident。当然，也可以手工insert到表里去，但是就比较麻烦了，不推荐这么做。

所以，完全使用Prometheus的exporter生态来采集的话，就不要使用监控对象的功能了，不用也没啥，核心功能都不受影响
