### ISSUE TITLE
panic: Empty list of authorized credentials

### ISSUE THREAD

**Issue by zhangzheming629** [didi/nightingale#853]
**夜莺版本**:
n9e version 5.2.0

**问题和复现方法**:
panic: Empty list of authorized credentials
本地调试夜莺webapi，无法启动

go run main.go webapi正常，vscode进行debug报错
![image](https://user-images.githubusercontent.com/38377736/147801672-3d3f9e92-61c6-45e8-b941-3a6a3a56b49d.png)
![image](https://user-images.githubusercontent.com/38377736/147801682-24d1a911-ce23-4c3c-9d43-d417745912d8.png)
![image](https://user-images.githubusercontent.com/38377736/147801736-fdc40a80-c154-4c63-8af6-1bb0af46281d.png)

经排查原因是因为配置是空，但是不知道为什么运行可以，debug就报错，在原来的代码基础上增加了判断  
if len(config.C.BasicAuth) != 0 {
		service := r.Group("/v1/n9e", gin.BasicAuth(config.C.BasicAuth))
		{
			service.Any("/prometheus/*url", prometheusProxy)
			service.POST("/users", userAddPost)
		}
	}

**Comment by zhangzheming629** [comment]
go run main.go webapi
直接run的话打印config.C.BasicAuth是  map[user001:ccc26da7b9aba533cbb263a36c07dcc5]
![image](https://user-images.githubusercontent.com/38377736/147801865-e8110298-9a14-489c-a001-67fb695a2e21.png)

**Comment by UlricQin** [comment]
你用vscode调的时候要通过--conf指定配置文件，当然，这个basic auth的校验也确实可以加上：https://github.com/didi/nightingale/commit/b693e80d757dc2b5d14ebe13de698d3383b137f9
