### ISSUE TITLE
5.1.0 即时查询展示优化

### ISSUE THREAD

**Issue by bbaobelief** [didi/nightingale#854]
**夜莺版本**:
前端版本：5.1.1
后端版本：5.1.0

**问题和复现方法**:
指标太多会卡死，可以参考Prometheus限制展示。

![image](https://user-images.githubusercontent.com/3918461/148049415-5aad07fd-6aea-4463-bb0b-bf7a11dbbbca.png)
![image](https://user-images.githubusercontent.com/3918461/148049446-2ba8718b-f29a-4567-891b-9cf7b5e1a8e9.png)

**Comment by UlricQin** [comment]
这个逻辑应该是和prometheus一样的才对，都有限制，微信联系我，远程看看？
