### ISSUE TITLE
夜莺支持Grafana Loki的接入吗？

### ISSUE THREAD

**Issue by tongorz** [didi/nightingale#855]
夜莺v5.1+ 支持grafana loki的接入吗？
Grafana Loki是支持Prometheus Alertmanager的，只不过查询语言由PromQL扩展成了适合日志的LogQL。
如果夜莺自己没有对PromQL做解析，直接将查询语句传递给Prometheus，支持Loki的告警应该也是没问题的。

[https://grafana.com/docs/loki/latest/rules/](url)
`
Alerting Rules
We support Prometheus-compatible alerting rules. From Prometheus' documentation:

Alerting rules allow you to define alert conditions based on Prometheus expression language expressions and to send notifications about firing alerts to an external service.

Loki alerting rules are exactly the same, except they use LogQL for their expressions.

Example
`

**Comment by UlricQin** [comment]
不支持哈，这块还没有时间研究，你们生产环境用了Loki么？约个会给我们分享一下？看看能否让夜莺支持日志告警

**Comment by tongorz** [comment]
> 不支持哈，这块还没有时间研究，你们生产环境用了Loki么？约个会给我们分享一下？看看能否让夜莺支持日志告警

还没有投入使用，也是在尝试学习中。之前试用Loki时，不支持乱序写入，新版本支持了，就打算折腾下

**Comment by lzpfmh** [comment]
https://flashcat.cloud/blog/nightingale-release-v6.3.0/  夜莺项目发布 v6.3.0 版本，增加 Loki 和 TDEngine 数据源支持
