### ISSUE TITLE
prometheus报错 out of order sample

### ISSUE THREAD

**Issue by bbaobelief** [didi/nightingale#857]
**夜莺版本**:
前端版本：5.1.1
后端版本：5.3.0

**问题和复现方法**:
请问，server写入的时候是否有做排序。prometheus报错：
```
ts=2022-01-16T03:59:30.633Z caller=write_handler.go:57 level=error component=web msg="Out of order sample from remote write" err="out of order sample"
ts=2022-01-16T04:00:20.038Z caller=write_handler.go:57 level=error component=web msg="Out of order sample from remote write" err="out of order sample"
ts=2022-01-16T04:00:30.050Z caller=write_handler.go:57 level=error component=web msg="Out of order sample from remote write" err="out of order sample"
```

**Comment by UlricQin** [comment]
时间不一致的时候容易出现这个问题，server不做排序，客户端上报上来的数据是什么时间戳就用什么时间戳。

**Comment by mamh2021** [comment]
ts=2022-03-03T06:10:46.942Z caller=write_handler.go:102 level=error component=web msg="Out of order sample from remote write" err="duplicate sample for timestamp" series="{__name__=\"cpu_usage_idle\", cpu=\"cpu40\", ident=\"gb-15\"}" timestamp=1646287845000

我也碰到这个错误了。

时间不一致的时候容易出现这个问题

这个可否具体解释一下？

**Comment by jeyrce** [comment]
就是数据采集节点和服务节点系统时间差距太大引起的，需要控制在30s内

**Comment by blankleee** [comment]
hello，找到问题了吗？是时间不一致导致的？  我的情况是：只有在采集K8S集群的数据时出现这种情况 . 并且都检查过容器跟所在节点时间都没问题。grafana-agent 的 job也没有重复

**Comment by jeyrce** [comment]
@blankleee 我遇到的情况：服务器(prometheus所在节点)时间滞后于实际时间，如果有一部分数据落盘了，现在你将服务器时间修改到正常时间（时钟回拨），此时就会出现这种情况，这种数据会写坏，解决方法就是关掉prometheus，直接删掉他的data目录，然后重启

**Comment by blankleee** [comment]
> @blankleee 我遇到的情况：服务器(prometheus所在节点)时间滞后于实际时间，如果有一部分数据落盘了，现在你将服务器时间修改到正常时间（时钟回拨），此时就会出现这种情况，这种数据会写坏，解决方法就是关掉prometheus，直接删掉他的data目录，然后重启

时间应该是一直都没问题的， 我这边还有写入其他资源的数据，例如RDS、REDIS的都没这个问题， 目前只看到K8S资源有这种情况.

**Comment by xiaobaijh** [comment]
> > @blankleee 我遇到的情况：服务器(prometheus所在节点)时间滞后于实际时间，如果有一部分数据落盘了，现在你将服务器时间修改到正常时间（时钟回拨），此时就会出现这种情况，这种数据会写坏，解决方法就是关掉prometheus，直接删掉他的data目录，然后重启
> 
> 时间应该是一直都没问题的， 我这边还有写入其他资源的数据，例如RDS、REDIS的都没这个问题， 目前只看到K8S资源有这种情况.

你好，请问解决了嘛

**Comment by blankleee** [comment]
> > > @blankleee 我遇到的情况：服务器(prometheus所在节点)时间滞后于实际时间，如果有一部分数据落盘了，现在你将服务器时间修改到正常时间（时钟回拨），此时就会出现这种情况，这种数据会写坏，解决方法就是关掉prometheus，直接删掉他的data目录，然后重启
> > 
> > 
> > 时间应该是一直都没问题的， 我这边还有写入其他资源的数据，例如RDS、REDIS的都没这个问题， 目前只看到K8S资源有这种情况.
> 
> 你好，请问解决了嘛

解决了， 因为我的grafana-agent部署的方式是ds，所以会有多个agent同时工作，而我的export-job配置上有一个是通过api接口获取数据的，所以每个agent都会获取这个job的数据。所以就会有时序不对的情况出现。

**Comment by laiwei** [comment]
PR #1128  中提供了一个使用服务器时间的配置选项，一定程度上可以规避agent机器时间不准的问题。
