### ISSUE TITLE
Most command can not work if install with docker compose

### ISSUE THREAD

**Issue by markoxu** [didi/nightingale#859]
**夜莺版本**:
v5.3.0

**问题和复现方法**:
Most command can not work with ibex in docker, maybe related with the dockerfile or environment. However, it works well with stand alone deloyment.

Install Nightingale with docker compose and then run the following default script in the editor. Thanks.

```shell
#!/bin/bash
# e.g.
export PATH=/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:~/bin
ss -tln
```

stderr
```
telegraf01
/app/meta/12/script: line 4: ss: command not found
```

**Comment by UlricQin** [comment]
Ibex in docker is just for test. If it is a production environment, ibex should be deployed on host instead of container.

**Comment by markoxu** [comment]
Got it. Thanks for your timely reply.
