### ISSUE TITLE
telegraf提示这个，对象指标啥都没有

### ISSUE THREAD

**Issue by mensylisir** [didi/nightingale#860]
**夜莺版本**:
5.3.0
**问题和复现方法**:
telegraf提示这个，对象指标啥都没有
2022-01-18T11:45:46Z W! [agent] ["outputs.opentsdb"] did not complete within its flush interval
![F3C76AB1-25BD-49c0-9CAE-083E2DDE5C35](https://user-images.githubusercontent.com/11365685/150053684-198ad080-537f-4c36-bebc-88e9da7b0de3.png)

**Comment by mensylisir** [comment]
![image](https://user-images.githubusercontent.com/11365685/150085345-bc995de5-08cf-4993-8311-464ed43a7f20.png)
w未实现是啥意思

**Comment by UlricQin** [comment]
> W! [agent] ["outputs.opentsdb"] did not complete within its flush interval
