### ISSUE TITLE
屏蔽报警之后web是看不到了,但是邮件还是会发送

### ISSUE THREAD

**Issue by lry789** [didi/nightingale#861]
**夜莺版本**:
5.3.0

**问题和复现方法**:
告警管理->屏蔽规则
屏蔽报警之后活跃告警和历史告警是看不到了,但是告警邮件还是会继续发送

**Comment by UlricQin** [comment]
继续收到的那些是之前夜莺已经发给邮件网关，邮件网关积压的，夜莺自身只要配置了屏蔽规则，发送之前都会判断是否屏蔽了
