### ISSUE TITLE
删除指标

### ISSUE THREAD

**Issue by skyzzk** [didi/nightingale#862]
n9e的V5版本，可以监控指标吗

**Comment by skyzzk** [comment]
可以删除监控指标吗

**Comment by UlricQin** [comment]
> 可以删除监控指标吗

依赖对接的时序库，如果是用Prometheus做时序库，那就用Prometheus的接口删除指标，Prometheus的文档在：https://prometheus.io/

**Comment by skyzzk** [comment]
对接的是m3db，调m3db接口删除是吧，不能通过n9e服务是因为没有实现相关接口是吧

**Comment by UlricQin** [comment]
> 对接的是m3db，调m3db接口删除是吧，不能通过n9e服务是因为没有实现相关接口是吧

n9e只是做了proxy，主要是用于读的，这种维护类的操作调用n9e的接口是多此一举，直接调用后端时序库的接口即可
