### ISSUE TITLE
监控项指标

### ISSUE THREAD

**Issue by skyzzk** [didi/nightingale#863]
**夜莺版本**:
5.3.0

**问题和复现方法**:

`label/__name__/values`接口获取监控指标
参数：match[]={ident=~"12345"}

返回监控指标

但是不属于主机（12345）的监控项也返回了
这是正常的？返回所有监控指标项？
还是这是有问题的

**Comment by UlricQin** [comment]
返回了哪些？

**Comment by skyzzk** [comment]
图片里返回了不相干的指标，容器的指标

![1](https://user-images.githubusercontent.com/48142178/151088418-7c48b6bd-e7e5-4313-bd69-36c892908191.jpg)

**Comment by UlricQin** [comment]
要么就是你的参数不对，要么就是Prometheus的逻辑问题，要么就是这些指标确实带有ident=12647的标签

因为/api/n9e/prometheus打头的接口，都是直接proxy给了后端存储，夜莺自己没有额外的逻辑。如果你的后端存储是Prometheus，你可以直接调用Prometheus的`/api/v1/label/__name__/values?match[]={ident="12647"}`做测试。

我觉得大概率是你的参数的问题，可以看看Prometheus的接口文档，看是否是这么调用
