### ISSUE TITLE
通过docker-compose搭建，但是在测试中发现通过自愈脚本执行命令时会超时

### ISSUE THREAD

**Issue by luke-fu** [didi/nightingale#864]
**夜莺版本**:
前端版本：5.1.1
后端版本：5.3.0
**问题和复现方法**:
通过docker-compose搭建平台，在同一台机器上面运行telegraf作为agent，在测试自愈脚本的时候通过主机名或IP无法执行，会报超时，但是在docker里面运行的一个agent可以正常执行和返回值

**Comment by UlricQin** [comment]
n9e.gitee.io 仔细看一下官方文档，自愈脚本不是通过Telegraf运行的，是通过ibex-agent运行的
