### ISSUE TITLE
prometheus exporter监控对象的自动识别

### ISSUE THREAD

**Issue by lwangrabbit** [didi/nightingale#866]
**What would you like to be added**:
Promethes exporter的监控对象，可以被自动识别并添加到n9e的对象列表；
比如，主机部署了node-exporter，被prometheus拉取以后，主机被添加到n9e的监控对象列表中。

部署了Telegraf的监控对象，可以被自动识别到n9e中；希望prometheus exporter也可以实现这一点。

**Why is this needed**:
实现监控对象的自动发现，便于后续配置对象的告警规则。

**Comment by UlricQin** [comment]
Prometheus的单个的那些exporter做不到，可以用grafana-agent，grafana-agent相当于内置集成了多个Prometheus exporter，把metrics的remote write地址配置成夜莺即可
