### ISSUE TITLE
n9e自身组件中关键指标有哪些

### ISSUE THREAD

**Issue by spyvip** [didi/nightingale#87]
n9e自身组件有很多，哪些指标是关键的

比如：

- collector负载很高
- transfer负载很高
- 等等

![image](https://user-images.githubusercontent.com/1212932/79210430-68a3e180-7e77-11ea-8a29-f36bb35e28cf.png)

**Comment by 710leo** [comment]
可以参考[这里](https://n9e.didiyun.com/zh/docs/operation/monitor/#%E5%8F%8A%E6%97%B6%E5%8F%91%E7%8E%B0%E9%97%AE%E9%A2%98)提到的一些指标
