### ISSUE TITLE
m3db配置

### ISSUE THREAD

**Issue by skyzzk** [didi/nightingale#870]
项目中的数据库采用的是m3db，然后对应的配置如下

[[Writers]]
Name = "default" # 集群名
Url = "http://192.168.121.131:7201/api/v1/prom/remote/write"  # m3db路径
BasicAuthUser = ""
BasicAuthPass = ""
Timeout = 30000
DialTimeout = 10000
TLSHandshakeTimeout = 30000
ExpectContinueTimeout = 1000
IdleConnTimeout = 90000
KeepAlive = 30000
MaxConnsPerHost = 0
MaxIdleConns = 100
MaxIdleConnsPerHost = 100

这个配置下数据可以正常写入

但是m3db是可以创建多个空间的，然后上面的配置将数据写入了默认的default空间

是否有对应的配置，写入到其它的空间（非default空间），比如我要创建一个n9e空间

**Comment by UlricQin** [comment]
这个不太清楚，需要看看m3db 的文档，看看它这个接口是否可以通过某个配置指定
