### ISSUE TITLE
OpenTSDB TCP address cannot be resolved

### ISSUE THREAD

**Issue by rechardwang** [didi/nightingale#873]
**夜莺版本**:
最新版本

**问题和复现方法**:
![image](https://user-images.githubusercontent.com/43982436/154668284-8947bdf4-a17d-4586-9e96-a4f758a6589e.png)

使用docker-compose部署完毕之后 出现这个错误，当前未改动过telegraf配置

**Comment by UlricQin** [comment]
用二进制测试吧
