### ISSUE TITLE
夜莺v4 版本 go build 报错

### ISSUE THREAD

**Issue by One1W** [didi/nightingale#874]
**夜莺版本**: v4.0.0

**问题和复现方法**: 在build n9e-server 时 报错 
在路径 src/modules/server 下执行 go build server.go

# command-line-arguments
./server.go:129:29: conf.Rdb.SendSender undefined (type config.rdbSection has no field or method SendSender)

请问是要配置什么吗？
另外有没有编译安装的文档？

**Comment by One1W** [comment]
➜  ./control build
todo build at 2022-02-23 19:24:40
building server ... # command-line-arguments
src/modules/server/server.go:129:29: conf.Rdb.SendSender undefined (type config.rdbSection has no field or method SendSender)
done

**Comment by s717626120** [comment]
下载夜莺版本V5

**Comment by UlricQin** [comment]
<img width="605" alt="image" src="https://user-images.githubusercontent.com/2769466/160783439-65634561-04da-4894-a936-67a7b86eb333.png">
