### ISSUE TITLE
未授权能查询全部监控对象

### ISSUE THREAD

**Issue by xuhui54** [didi/nightingale#875]
**夜莺版本**:

前端版本：5.1.2
后端版本：5.3.4
**问题和复现方法**:
新建一个test用户，未进行授权，但是可以默认查询出未授权业务组的监控对象
![image](https://user-images.githubusercontent.com/9813785/155446121-f78c4b07-6b1c-421b-80c1-92bec9694198.png)

**Comment by bbaobelief** [comment]
guest用户有以下权限：
```
insert into `role_operation`(role_name, operation) values('Guest', '/metric/explorer');
insert into `role_operation`(role_name, operation) values('Guest', '/object/explorer');
insert into `role_operation`(role_name, operation) values('Guest', '/help/version');
insert into `role_operation`(role_name, operation) values('Guest', '/help/contact');
```

**Comment by UlricQin** [comment]
楼上正解，默认guest就是这么个权限配置，觉得不合适可以自己修改数据库

**Comment by xuhui54** [comment]
明白有这些目录的权限。我截图是指未授权给改用户的监控对象，该用户也能查询到并且查看所有指标。

**Comment by UlricQin** [comment]
符合预期，这是查的时序库，能看到所有

> 明白有这些目录的权限。我截图是指未授权给改用户的监控对象，该用户也能查询到并且查看所有指标。
