### ISSUE TITLE
找不到新增用户角色

### ISSUE THREAD

**Issue by bbaobelief** [didi/nightingale#876]
**夜莺版本**:
前端版本：5.1.2
后端版本：5.3.4

**问题和复现方法**:
在数据库里新增了dev和sre角色，但前端无法获取到。前端角色写死了？
![image](https://user-images.githubusercontent.com/3918461/155478618-acb1914f-db22-457a-bbf3-05dfd5904b8e.png)

![image](https://user-images.githubusercontent.com/3918461/155478369-40ba0016-e012-4414-a56f-436efefeb14b.png)

**Comment by UlricQin** [comment]
不可能写死，可以看看代码

**Comment by bbaobelief** [comment]
看了下前端代码，是写死的
https://github.com/n9e/fe-v5/blob/master/src/pages/user/component/userForm/index.tsx#L27
