### ISSUE TITLE
优化建议: 在【活跃告警】直接去点击规则屏蔽，默认生效的集群并不是针对此条活跃告警事件的集群

### ISSUE THREAD

**Issue by ArvinChen1991** [didi/nightingale#877]
**夜莺版本**:
v5.3.4

**问题和复现方法**:
在多集群数据源的前提下，在【活跃告警】直接去点击规则屏蔽，在规则屏蔽页面中，有个“生效集群”，默认是选择多数据源的第一个，并不会自动关联当前事件的数据源

**Comment by UlricQin** [comment]
@guguji5 可以瞧瞧呢

**Comment by guguji5** [comment]
是个好建议，有空了支持

**Comment by guguji5** [comment]
代码已提交，可以等下一个release

**Comment by UlricQin** [comment]
[fe-v5.1.7](https://github.com/n9e/fe-v5/releases/tag/v5.1.7)  release
