### ISSUE TITLE
希望V5版本 能够添加v4版本用户Token，暴露的接口能够通过固定token进行接口访问

### ISSUE THREAD

**Issue by xuhui54** [didi/nightingale#882]
功能：
希望V5版本 能够添加v4版本用户Token，暴露的接口能够通过固定token进行接口访问
场景
1、我司有统一的用户管理中心，需要增量 和全量同步用户到夜莺用户管理，现在如果基于V5开发遇到access_token认证问题，需要调用时固定配置一个账号进行登录后获取token。
2、在需要外部调用资源等功能，也会遇到用户接口类似问题。

**Comment by UlricQin** [comment]
仔细看一下router.go那个文件，v1打头的相关接口直接使用basic auth认证，很方便，v1打头的接口如果有缺失，提pr补充一下就行，完全可以和api打头的接口复用
