### ISSUE TITLE
优化建议：事件里记录原始Vector Labels用以功能扩展

### ISSUE THREAD

**Issue by clude** [didi/nightingale#884]
现在的CurrentEvent和HistoryEvent里的标签信息是Vector Labels叠加Rule的Tags生成的，建议额外保存下原始的Vector Labels, 这个可以解决几个问题
1. 查看告警详情时，可以提供一个用Vector Labels 叠加时间条件去查询告警这个指标当时的历史曲线，现在告警详情里直接用rule的PromQL去查历史数据基本没效果。
2. 后续可以利用这个给恢复告警增加恢复值的功能。

这个可以做为一个实验性功能供大家选择是否启用，毕竟在复杂的PromQL里Vector Labels应该会不合预期，但80%以上的基础告警这个功能应该都是适用的

**Comment by UlricQin** [comment]
rule中的promql，直接进即时查询页面，然后手工删除比较运算符和阈值，就可以看图了；你提的这个建议也如你所言，不能解决100%的问题

**Comment by clude** [comment]
查看一个告警消息时，其实是期望看这条告警对应的ident那个时间点对应指标的一个曲线情况的。比如：cpu_usage_idle{cpu="cpu-total"} < 10，  触发了告警，甚至可能过10分钟后就修复了，我们去查看的时候，用cpu_usage_idle{cpu="cpu-total"}查肯定是不完全符合合预期的，只能再额外叠加查询条件cpu_usage_idle{cpu="cpu-total", ident="xx.xx.xx.xx"}这样去查。保留vector-labels主要目的是能为了一般场景下能快速叠加上这些条件。
