### ISSUE TITLE
告警规则搜索时建议大小写设置为不敏感

### ISSUE THREAD

**Issue by hel2o** [didi/nightingale#885]
**夜莺版本**:
5.4.0
**问题和复现方法**:
目前对大小写敏感，搜索起来很不方便

**Comment by guguji5** [comment]
代码已提交，可以等下一个release，也可以用最新的源码build使用 @hel2o

**Comment by hel2o** [comment]
> 代码已提交，可以等下一个release，也可以用最新的源码build使用 @hel2o
