### ISSUE TITLE
即时查询增加采集时间字段显示

### ISSUE THREAD

**Issue by nondevops** [didi/nightingale#888]
**What would you like to be added**:
![image](https://user-images.githubusercontent.com/12181410/158639284-88658646-73c3-4510-9dd2-8c61b31bda8a.png)

**Why is this needed**:
加了之后可便于查看每项监控指标的上报时间，便于排查分析问题。

**Comment by UlricQin** [comment]
这个接口返回的数据好像是有时间戳的，可以考虑展示出来

**Comment by bbaobelief** [comment]
> 这个接口返回的数据好像是有时间戳的，可以考虑展示出来

接口返回的时间是查询时间，没意义。
