### ISSUE TITLE
worker

### ISSUE THREAD

**Issue by skyzzk** [didi/nightingale#890]
**夜莺版本**:
v5

**问题和复现方法**:

![impicture_20220321_210405](https://user-images.githubusercontent.com/48142178/159266229-ba206359-abb1-4f51-b369-82c9c4572fc7.png)

engine疯狂刷屏，且报错

然后影响到查询，查询也变得很慢

把server关掉，查询就变正常

engine/worker  报错完会继续重试吗？

**Comment by UlricQin** [comment]
你配置了多少条告警规则？很多重复的规则？

**Comment by skyzzk** [comment]
一个业务组有8个规则，大概有90个业务组

**Comment by UlricQin** [comment]
1、你的截图只能看到请求m3报错了，但是具体报的什么错，没有截出来，systemd托管的进程可以用journalctl -u xxx.service的方式看日志，systemctl status xxx.service的方式看日志看不全
2、你的m3所在的机器或许要更高配置才可以
3、你可能需要尽量多用一下订阅规则，这样可以大幅减少告警规则的数量，比如cpu_util只配置一条告警规则，然后各个业务组来订阅这个规则，通过标签过滤的方式，只订阅自己关注的事件

**Comment by skyzzk** [comment]
1.请求m3报错，server报的是超时timeout

m3的日志看不出什么，m3的日志如下
![impicture_20220322_100905](https://user-images.githubusercontent.com/48142178/159392878-2f68cd6e-be35-4279-9214-d881982c6661.png)

2.目前3台8核16G，看监控数据的使用率暂未达到瓶颈

**Comment by skyzzk** [comment]
![impicture_20220322_181002](https://user-images.githubusercontent.com/48142178/159456830-796da397-f56f-4537-af6e-46d2f9706abc.png)

请问这个是否会影响到 worker的并发呢

**Comment by UlricQin** [comment]
这个配置影响不大。请参考之前我的回答的3条，多使用订阅规则

**Comment by skyzzk** [comment]
好的，谢谢
