### ISSUE TITLE
【bug】监控大盘资源无法删除

### ISSUE THREAD

**Issue by YokeCheng** [didi/nightingale#892]
**夜莺版本**:
前端版本：5.1.5
后端版本：5.4.1

**问题和复现方法**:
手误将告警规则json导入到监控大盘中了，能导入但是无法删除。

**其他建议**:
【优化建议】：希望增加监控大盘中的批量操作。

**Comment by bbaobelief** [comment]
无法删除的问题已经修复了：https://github.com/didi/nightingale/pull/889

批量操作的功能还没有。

**Comment by 2bstronger** [comment]
希望增加监控大盘中的批量操作。

**Comment by UlricQin** [comment]
无法删除的问题已修复，请使用 v5.5.0 版本
