### ISSUE TITLE
对象视角中，右边的监控指标会丢失

### ISSUE THREAD

**Issue by mensylisir** [didi/nightingale#896]
**夜莺版本**:
  前端版本：5.1.2
  后端版本：5.3.4
**问题和复现方法**:
  随机出现，几乎每天都会出现，重启server后就会正常，但是可能过几个小时又没了

**Comment by UlricQin** [comment]
一般都是机器的时间不一致导致的，所有机器的时间要校准一致。另外，要升级到最新版本，后端 5.5.0 前端 5.1.7
