### ISSUE TITLE
v5.5.0-监控大盘 all选型无法看图

### ISSUE THREAD

**Issue by bbaobelief** [didi/nightingale#899]
**夜莺版本**:
前端版本：5.1.7
后端版本：5.5.0

**问题和复现方法**:
如果选择了all选项，无法看图。看api是直接把all传给了后端，之前版本传的是实际ident。
![image](https://user-images.githubusercontent.com/3918461/161913883-a8fd22b5-7773-4d23-ab18-69609b8040be.png)

**Comment by guguji5** [comment]
host 下拉里边有值吗？

**Comment by guguji5** [comment]
哦，明白了 https://github.com/n9e/fe-v5/commit/4ca0be562669a5a73ebd2ffa87862cd138245fde 已经修复了这个问题，还没发release 等等下一个release或者用源码build一下吧
