### ISSUE TITLE
v5.5.0-无法编辑业务组

### ISSUE THREAD

**Issue by bbaobelief** [didi/nightingale#900]
**夜莺版本**:
前端版本：5.1.7
后端版本：5.5.0

**问题和复现方法**:
新加的业务组可以编辑，以前创建的业务组无法修改，空白。

![image](https://user-images.githubusercontent.com/3918461/161914931-5c22c11a-ebc3-495d-a528-7374b35b8c28.png)

**Comment by UlricQin** [comment]
去数据库里查一下这个业务组我看看

**Comment by bbaobelief** [comment]
找到问题了，数据库中有为null的，我清理下。
![image](https://user-images.githubusercontent.com/3918461/162105054-986ab614-f1d6-49de-bf5c-245c14e81980.png)
