### ISSUE TITLE
v5.5.0-大盘变量获取失败

### ISSUE THREAD

**Issue by bbaobelief** [didi/nightingale#901]
**夜莺版本**:
前端版本：5.1.7
后端版本：5.5.0

**问题和复现方法**:
大盘变量超过长度被截断了
`label_values(event_gauge{busigroup="$busigroup",event="runtime.NumGoroutine"},ident)`

![image](https://user-images.githubusercontent.com/3918461/161936882-b82180e6-aa78-4df3-a3b3-818cda76bd11.png)

**Comment by guguji5** [comment]
https://github.com/n9e/fe-v5/releases 最新的release解决了这个问题，可以试试。直接升级后端也可以

**Comment by UlricQin** [comment]
建议前后端一起升级，后端升级到 5.6.0 前端升级到 5.2.0
