### ISSUE TITLE
监控大盘变量丢失

### ISSUE THREAD

**Issue by bbaobelief** [didi/nightingale#909]
**夜莺版本**:
前端版本：5.2.0
后端版本：5.6.0

**问题和复现方法**:
导入 `HOST - Telegraf 模板`，新增变量并保存，整个变量都会丢失。
![image](https://user-images.githubusercontent.com/3918461/163145756-ba93b2a0-d411-4bde-a181-92ecf93d332b.png)
![image](https://user-images.githubusercontent.com/3918461/163146236-726ee65a-68c6-4d3d-81fe-3f9aff9413b4.png)

点击确认，刷新页面
![image](https://user-images.githubusercontent.com/3918461/163146307-70cc2125-4164-401f-ba93-3338c792c764.png)

**Comment by UlricQin** [comment]
没有复现，你能稳定复现？其他人有遇到么？可以回帖说说

**Comment by bbaobelief** [comment]
> 没有复现，你能稳定复现？其他人有遇到么？可以回帖说说

可以复现，我刚看了请求时因为ident数量太多被截断了。这个问题之前修复过，最新版5.6.0又出现了。
![image](https://user-images.githubusercontent.com/3918461/163306871-0017aed3-8a2e-40ca-9af4-88dbeb6dc9f3.png)

get请求到的数据configs字段被截断了
`https://xxx.com/api/n9e/busi-group/114/dashboard/191`

**Comment by guguji5** [comment]
@bbaobelief configs字段有293kB数据，它是一个json string，能帮看看是里边的哪个字段这么长吗？

**Comment by bbaobelief** [comment]
> @bbaobelief configs字段有293kB数据，它是一个json string，能帮看看是里边的哪个字段这么长吗？
options
```
configs: "{\"var\":[{\"name\":\"ident\",\"definition\":\"label_values(system_load1,ident)\",\"options\":[\"tx-xxx-admin02.bj\",
```

**Comment by guguji5** [comment]
https://github.com/n9e/fe-v5/releases/tag/v5.2.1 @bbaobelief  确实是有bug，感谢反馈，试试最新的前端包
