### ISSUE TITLE
index突然挂了，看看有没有有用的信息

### ISSUE THREAD

**Issue by spyvip** [didi/nightingale#91]
[stdout.log](https://github.com/didi/nightingale/files/4484308/stdout.log)

版本应该是比较早的
3-31号时的代码编译的

**Comment by 710leo** [comment]
@spyvip 这个问题还可以复现么

**Comment by 710leo** [comment]
fixed by this [commit](https://github.com/didi/nightingale/commit/0b2d4d6d1970f8c30127711440f8075c2966ef81)

**Comment by spyvip** [comment]
> @spyvip 这个问题还可以复现么

重启之后没有了
