### ISSUE TITLE
环比展示的一些建议

### ISSUE THREAD

**Issue by CarrotH** [didi/nightingale#92]
现在在图表中增加了环比信息的展示，不过现在当前曲线跟历史曲线不好区分，是否可以在颜色和线条类型上优化下，比如：相同tag的用相同的颜色，然后不同时间的用不同的线条，实线，虚线，点划线。。

**Comment by jsers** [comment]
这个建议不错，近期支持下

**Comment by CarrotH** [comment]
图形在展示离散点时，单个点的情况下页面无法显示，是否可以增加图标，使其能展示单个的数据点

**Comment by jsers** [comment]
不同形态的线条这个后面还需要讨论下，目前已支持针对今天、昨天、上周对比场景的曲线颜色做了固定设置。
离散点现在是支持的。

**Comment by CarrotH** [comment]
现在的固定颜色对区分不同tag不太友好，个人觉得用颜色来区分tag，用线条形状区分不同时间(昨天，上周)会比较直观，因为一个图中的tag数可能会较多，用颜色可选的范围比较大，进行同比环比时，选的时间相对不会太多(一般就两个)，所以用虚线/实线就可以覆盖，这样显示可能会体验好点

**Comment by UlricQin** [comment]
没人参与讨论，说明大家对这个没有那么在意，另外，后面主打grafana，内置的看图能简单用就行。该issue暂时关掉
