### ISSUE TITLE
大盘 数据重复展示

### ISSUE THREAD

**Issue by alangong114** [didi/nightingale#920]
**夜莺版本**:
前端版本：5.2.0
后端版本：5.6.0

**问题和复现方法**:

监控node时  出现大盘卡片数据展示重复  。 **非必现**
![image](https://user-images.githubusercontent.com/4981060/164187167-311a4c08-d96a-4699-9db2-c03b200b66b8.png)

实际：
![image](https://user-images.githubusercontent.com/4981060/164187251-fdb2ac35-5bfa-4def-b993-9ee0d314b66b.png)

复现方法：
运行一段时间后出现，刷新页面依然存在
![image](https://user-images.githubusercontent.com/4981060/164187746-c3911237-5420-4b4f-a606-465ad100f513.png)

**Comment by alangong114** [comment]
请求：
http://10.167.169.92:18000/api/n9e/prometheus/api/v1/query_range?start=1650440600&end=1650444200&step=14&query=%28node_memory_MemTotal_bytes%7Binstance%3D%22k8s-node02%22%7D%20-%20node_memory_MemFree_bytes%7Binstance%3D%22k8s-node02%22%7D%20-%20%28node_memory_Cached_bytes%7Binstance%3D%22k8s-node02%22%7D%20%2B%20node_memory_Buffers_bytes%7Binstance%3D%22k8s-node02%22%7D%29%29%2Fnode_memory_MemTotal_bytes%7Binstance%3D%22k8s-node02%22%7D%2A100
响应：
![image](https://user-images.githubusercontent.com/4981060/164189496-018c254d-6a51-4ada-9e34-2fbd9f1ab585.png){"status":"success","data":{"resultType":"matrix","result":[{"metric":{"beta_kubernetes_io_arch":"amd64","beta_kubernetes_io_os":"linux","ident":"k8s-node02","instance":"k8s-node02","ip":"10.167.169.94","job":"kubernetes-nodes","kubernetes_io_arch":"amd64","kubernetes_io_hostname":"k8s-node02","kubernetes_io_os":"linux","node":"k8s-node02"},"values":[[1650440600,"20.280066615411492"],[1650440614,"20.24624994677912"],[1650440628,"20.27047462257221"],[1650440642,"20.248158557599183"],[1650440656,"20.280653880279207"],[1650440670,"20.272627927087154"],[1650440684,"20.289364975816923"],[1650440698,"20.264601973895097"],[1650440712,"20.23744097376345"],[1650440726,"20.23744097376345"],[1650440740,"20.23744097376345"],[1650440754,"20.23744097376345"],[1650440768,"20.23744097376345"],[1650440782,"20.23744097376345"],[1650440796,"20.23744097376345"],[1650440810,"20.23744097376345"],[1650440824,"20.23744097376345"]]},{"metric":{"beta_kubernetes_io_arch":"amd64","beta_kubernetes_io_os":"linux","ident":"k8s-node02","instance":"k8s-node02","job":"kubernetes-nodes","kubernetes_io_arch":"amd64","kubernetes_io_hostname":"k8s-node02","kubernetes_io_os":"linux"},"values":[[1650441020,"20.27830482080836"],[1650441034,"20.656405518136452"],[1650441048,"20.208273485333795"],[1650441062,"20.64245797752831"],[1650441076,"20.233476935906403"],[1650441090,"20.233476935906403"],[1650441104,"20.630272231523303"],[1650441118,"20.286820161390175"],[1650441132,"20.70940617244739"],[1650441146,"20.267195727060823"],[1650441160,"20.66315906411513"],[1650441174,"20.250997004459787"],[1650441188,"20.648673197378255"],[1650441202,"20.285107305526015"],[1650441216,"20.667808244317847"],[1650441230,"20.266363768498234"],[1650441244,"20.66428465511158"],[1650441258,"20.243166806223638"],[1650441272,"20.632376597299267"],[1650441286,"20.264063647766363"],[1650441300,"20.264063647766363"],[1650441314,"20.657531109132897"],[1650441328,"20.268321318057268"],[1650441342,"20.65410539740458"],[1650441356,"20.243656193613397"],[1650441370,"20.66736779566706"],[1650441384,"20.269593725270642"],[1650441398,"20.686698597562557"],[1650441412,"20.251975779239306"],[1650441426,"20.64847744242235"],[1650441440,"20.23024697913399"],[1650441454,"20.6026218440019"],[1650441468,"20.258778263956962"],[1650441482,"20.600370662009006"],[1650441496,"20.268957521663957"],[1650441510,"20.268957521663957"],[1650441524,"20.599979152097198"],[1650441538,"20.25481422609991"],[1650441552,"20.609081757546722"],[1650441566,"20.265091361284856"],[1650441580,"20.629636027916614"],[1650441594,"20.28133902262487"],[1650441608,"21.55061415670478"],[1650441622,"20.539441931983962"],[1650441636,"20.69643740661877"],[1650441650,"20.37349066811656"],[1650441664,"20.753304221308806"],[1650441678,"20.412690598036285"],[1650441692,"20.7242346103571"],[1650441706,"20.37853135823108"],[1650441720,"20.37853135823108"],[1650441734,"20.730792401379876"],[1650441748,"20.37662274741102"],[1650441762,"20.732113747332225"],[1650441776,"20.392185266405367"],[1650441790,"20.622393094548176"],[1650441804,"20.284666856875234"],[1650441818,"20.655133110923078"],[1650441832,"20.358515413989924"],[1650441846,"20.716942738249685"],[1650441860,"20.392821470012056"],[1650441874,"20.75761083033869"],[1650441888,"20.374175810462223"],[1650441902,"20.73142860498656"],[1650441916,"20.409998967392607"],[1650441930,"20.409998967392607"],[1650441944,"20.74204831134434"],[1650441958,"20.365611531141433"],[1650441972,"20.683860150701953"],[1650441986,"20.34300183373455"],[1650442000,"20.705393195851364"],[1650442014,"20.433146990928226"],[1650442028,"20.736958682490844"],[1650442042,"20.423652875566894"],[1650442056,"20.71870453285282"],[1650442070,"20.373294913160656"],[1650442084,"20.709259356230465"],[1650442098,"20.385627475382588"],[1650442112,"20.680972765102375"],[1650442126,"20.364730633839866"],[1650442140,"20.364730633839866"],[1650442154,"20.688998718294428"],[1650442168,"20.356704680647812"],[1650442182,"20.71938967519848"],[1650442196,"20.365464714924506"],[1650442210,"20.695360754361296"],[1650442224,"20.3770631960618"],[1650442238,"20.714300046344984"],[1650442252,"20.35239807161793"],[1650442266,"20.706714541803716"],[1650442280,"20.3809293564409"],[1650442294,"20.707644377844257"],[1650442308,"20.354698192349797"],[1650442322,"20.69173928767708"],[1650442336,"20.351125664404552"],[1650442350,"20.351125664404552"],[1650442364,"20.71087433461667"],[1650442378,"20.37349066811656"],[1650442392,"20.710580702182817"],[1650442406,"20.35332790765847"],[1650442420,"20.735588397799518"],[1650442434,"20.399966525902542"],[1650442448,"20.717774696812278"],[1650442462,"20.372218260903182"],[1650442476,"20.728149709475176"],[1650442490,"20.388563799721148"],[1650442504,"20.71048282470486"],[1650442518,"20.359347372552513"],[1650442532,"20.67255530199851"],[1650442546,"20.34226775264991"],[1650442560,"20.34226775264991"],[1650442574,"20.713810658955225"],[1650442588,"20.360130392376128"],[1650442602,"20.720074817544145"],[1650442616,"20.356557864430886"],[1650442630,"20.742880269906934"],[1650442644,"20.360766595982817"],[1650442658,"20.683615457007072"],[1650442672,"20.358711168945824"],[1650442686,"20.700352505736845"],[1650442700,"20.371973567208304"],[1650442714,"20.71219568056902"],[1650442728,"20.377650460929512"],[1650442742,"20.702848381424616"],[1650442756,"20.389444697022714"],[1650442770,"20.389444697022714"],[1650442784,"20.712636129219806"],[1650442798,"20.341729426521173"],[1650442812,"20.725751711265357"],[1650442826,"20.40202195293953"],[1650442840,"20.70196748412305"],[1650442854,"20.401581504288746"],[1650442868,"20.725017630180716"],[1650442882,"20.410341538565437"],[1650442896,"20.724772936485834"],[1650442910,"20.455414117162277"],[1650442924,"20.698297078699852"],[1650442938,"20.427616913423947"],[1650442952,"20.72883485182084"],[1650442966,"20.422771978265327"],[1650442980,"20.422771978265327"],[1650442994,"20.70632303189191"],[1650443008,"20.448024367576913"],[1650443022,"20.68317500835629"],[1650443036,"20.368743610435892"],[1650443050,"20.703435646292327"],[1650443064,"20.395170529482897"],[1650443078,"20.68317500835629"],[1650443092,"20.412103333168574"],[1650443106,"20.701869606645097"],[1650443120,"20.428399933247558"],[1650443134,"20.71532775986348"],[1650443148,"20.392625715056152"],[1650443162,"20.705980460719076"],[1650443176,"20.411760761995744"],[1650443190,"20.411760761995744"],[1650443204,"20.724919752702764"],[1650443218,"20.411809700734718"],[1650443232,"20.74351647351362"],[1650443246,"20.391695879015607"],[1650443260,"20.69629059040184"],[1650443274,"20.383718864562532"],[1650443288,"20.71170629317926"],[1650443302,"20.3965897529132"],[1650443316,"20.71111902831155"],[1650443330,"20.426882832339306"],[1650443344,"20.746844307763983"],[1650443358,"20.390178778107355"],[1650443372,"20.70906360127456"],[1650443386,"20.416899329588215"],[1650443400,"20.416899329588215"],[1650443414,"20.728688035603913"],[1650443428,"20.469361657770417"],[1650443442,"20.794608517004498"],[1650443456,"20.505429508395686"],[1650443470,"20.786582563812445"],[1650443484,"20.508072200300386"],[1650443498,"20.809192261219327"],[1650443512,"20.49089470291983"],[1650443526,"20.800530104420588"],[1650443540,"20.50107396062683"],[1650443554,"20.786680441290397"],[1650443568,"20.524956065247085"],[1650443582,"20.75951944115875"],[1650443596,"20.4578121153721"],[1650443610,"20.4578121153721"],[1650443624,"20.772145635814542"],[1650443638,"20.470878758678673"],[1650443652,"20.767153884439"],[1650443666,"20.48007924160615"],[1650443680,"20.761917439368574"],[1650443694,"20.473717205539277"],[1650443708,"20.720368449978004"],[1650443722,"20.398694118689168"],[1650443736,"20.73774170231446"],[1650443750,"20.422576223309424"],[1650443764,"20.694333040842803"],[1650443778,"20.431238380108162"],[1650443792,"20.73162435994247"],[1650443806,"20.42477846656334"],[1650443820,"20.42477846656334"],[1650443834,"20.716453350859926"],[1650443848,"20.41973777644882"],[1650443862,"20.711755231918236"],[1650443876,"20.408726560179232"],[1650443890,"20.730694523901924"],[1650443904,"20.414648147595322"],[1650443918,"20.71410429138908"],[1650443932,"20.39428963218133"],[1650443946,"20.73426705184717"],[1650443960,"20.416654635893337"],[1650443974,"20.73000938155626"],[1650443988,"20.43451727561955"],[1650444002,"20.733679786979454"],[1650444016,"20.415675861113815"],[1650444030,"20.415675861113815"],[1650444044,"20.728688035603913"],[1650444058,"20.417339778239"],[1650444072,"20.739503496917592"],[1650444086,"20.439557965734075"],[1650444100,"20.75883429881309"],[1650444114,"20.425463608909002"],[1650444128,"20.744446309554164"],[1650444142,"20.406817949359173"],[1650444156,"20.810073158520893"],[1650444170,"20.478904711870726"],[1650444184,"20.726632608566923"],[1650444198,"20.367030754571736"]]}]}}

**Comment by UlricQin** [comment]
result这个数组里有2条记录导致的
