### ISSUE TITLE
有个东西我感到疑惑，为啥做了监控大盘的隔离，告警规则的隔离，为啥快捷视图不做隔离

### ISSUE THREAD

**Issue by 2bstronger** [didi/nightingale#928]
**夜莺版本**:ulric2019/nightingale:5.6.3

**问题和复现方法**:登录账号，查看快捷视图

**Comment by 2bstronger** [comment]
![lALPJtuZWuhWs_TNBfzNCgA_2560_1532](https://user-images.githubusercontent.com/51631197/165426952-c7c67f5e-c2f5-41c0-ad8e-b0dcd60ff2ba.png)

**Comment by UlricQin** [comment]
快捷视图从对象视角演化而来，没有太多自定义的需求。正常做法是管理员统一配置，公开给公司所有人，个别人如果有自定义的需求，就自己定义自己的视图。
管理员修改内置视图的能力在5.7.0版本放出：https://github.com/didi/nightingale/releases/tag/v5.7.0

**Comment by opslinux** [comment]
快捷视图能实现组内分享么，组内成员可以看到业务组配置的视图

**Comment by UlricQin** [comment]
> 快捷视图能实现组内分享么，组内成员可以看到业务组配置的视图

快捷视图的配置可以导出，把导出的json分享给团队里的其他同事，然后其他同事导入json即可

**Comment by opslinux** [comment]
你好，我暂不在。有事，请暂停联系。
