### ISSUE TITLE
docker启动， monapi无法连接myqsl

### ISSUE THREAD

**Issue by zengshing** [didi/nightingale#93]
![image](https://user-images.githubusercontent.com/39617342/79411394-563fba00-7fd5-11ea-8d3f-a6129f845b07.png)

我使用docker-compose启动， 出现上图报错，怎么解决

**Comment by chenjiandongx** [comment]
你用的是本地原有的 MySQL 还是使用 compose 部署的？

**Comment by yimeng** [comment]
应该是compose部署中docker在mac上不支持host模式，so~~~

**Comment by chenjiandongx** [comment]
所以这不是 compose 本身的问题，建议关闭 issue 哈。

**Comment by UlricQin** [comment]
@zengshing 看看配置文件里配置的什么密码，mysql那边也设置一下，默认好像是1234，你上面报错是密码不对
