### ISSUE TITLE
告警处理备注

### ISSUE THREAD

**Issue by GitHamburg** [didi/nightingale#930]
**What would you like to be added**:
告警支持处理备注
**Why is this needed**:
告警多了，有些可能是忽略、处理中、具体处理细节等，让活跃告警的当前状态更清晰

**Comment by UlricQin** [comment]
这是事件处理的需求，应该有一个通用的产品接收各个监控系统的告警事件，统一分组统一跟进，在那个系统里备注处理状态，这个功能超出了夜莺的产品边界。可以关注我们后面推出的产品。
