### ISSUE TITLE
键盘大盘变量支持更多元化的查询方式

### ISSUE THREAD

**Issue by chenginger** [didi/nightingale#931]
**What would you like to be added**:
监控大盘变量限制变量定义.通过label_values如果历史metric labels数据较多非常庞大.查询是否可以支持下拉选择外支持更多搜索方式:
例如搜索框(用户自己填写).checkbox(定义参数)
**Why is this needed**:
让查询变的更灵活.可以自定义一些查询条件

**Comment by UlricQin** [comment]
现在支持搜索，和grafana交互保持一致
