### ISSUE TITLE
订阅规则告警规则支持多个或者业务组

### ISSUE THREAD

**Issue by GitHamburg** [didi/nightingale#935]
**What would you like to be added**:
订阅规则告警规则支持多个或者业务组
**Why is this needed**:

1. 例如订阅mysql相关告警，如果有20个规则，需要订阅操作20次，是否能够支持按业务组或者选择多个告警规则
2. 减少订阅规则列表数量，便于维护

**Comment by UlricQin** [comment]
没有计划，这种情况应该为这类告警规则打上特定的附加标签。当然，如果使用最新版本的夜莺，流经n9e-server的监控数据会自动打上busigroup的标签，可以利用busigroup这个标签做订阅
