### ISSUE TITLE
n9e-server，不配置Writers url无法正常告警，填写错误Writers url或者填写正确Writers url然后不开启remote-write-receiver特性，可以正常告警。

### ISSUE THREAD

**Issue by 2bstronger** [didi/nightingale#936]
**夜莺版本**:  前端版本：5.3.0   后端版本：5.7.0

**问题和复现方法**:   server.conf，不配置Writers url无法正常告警，填写错误Writers url或者填写正确Writers url然后不开启remote-write-receiver特性，可以正常告警。

希望可以在不配置 Writers url 情况下可以正常告警

**Comment by UlricQin** [comment]
有报错日志？现在的代码逻辑就是不需要配置writer也可以告警

**Comment by 2bstronger** [comment]
天啦撸，刚才测试了一下，又没问题了，不填写writer也可以正常告警。不过当时确实是我填写了writer后才正常的。

**Comment by 2bstronger** [comment]
谢谢你，辛苦啦~
