### ISSUE TITLE
可以支持第三方tag吗

### ISSUE THREAD

**Issue by IAOTW** [didi/nightingale#937]
**What would you like to be added**:
target表目前只有一个tags字段让用户添加标记，能否另加一个标记字段，用于第三方系统的标记？

**Why is this needed**:
比如外部系统想对接夜莺，然后外部系统上也有一些信息需要标记到target上，这类tag和管理员加的tags可以区分开来，不用混在一起

**Comment by UlricQin** [comment]
没看到这么设计的必要性，或许你们的场景可以用备注来解决

**Comment by IAOTW** [comment]
问下备注信息也会加入到metrics的标签上吗
