### ISSUE TITLE
告警规则配置中添加其他监控数据，用于告警

### ISSUE THREAD

**Issue by yansuan** [didi/nightingale#940]
**What would you like to be added**:
告警规则中可以配置多个其他监控数据，接收者能看到关于此告警的更多信息
**Why is this needed**:
比如当一个端口挂掉时，希望能能同时看到CPU,MEM等信息

**Comment by UlricQin** [comment]
这个功能的性价比比较低，没有计划支持。你可以姑且拿着告警的机器去查询。

当下采集器各异，指标体系没有规范，需要用户非常灵活的配置才可以做到，且要把告警的事件中的labels提取出来，作为关联查询的变量带入，很麻烦。
