### ISSUE TITLE
飞书报警富文本 markdown支持

### ISSUE THREAD

**Issue by Ohimma** [didi/nightingale#942]
**What would you like to be added**:
现在飞书报警，在编写template时，好像只能编写简单的文本消息，但是支持颜色、url别名、加粗等。
导致飞书报警要比钉钉报警支持的文本样式更简陋
是不是可以考虑支持下？

**Why is this needed**:
公司目前较依赖飞书，希望飞书报警支持的文本样式可以丰富一些，谢谢

**Comment by UlricQin** [comment]
你们可以定制一下那个notify.py，在脚本里把内容搞丰富一些，用markdown发送

**Comment by Ohimma** [comment]
可以的哦

**Comment by kurilanz** [comment]
您好，方便讲一下是怎样修改的可以吗，谢谢
