### ISSUE TITLE
前端可以启动，但访问出错

### ISSUE THREAD

**Issue by yimeng** [didi/nightingale#95]
npm run start
yarn start

fetk.config.js

都有下面的报错。

[HPM] Error occurred while trying to proxy request /api/portal/tree? from localhost:8010 to http://10.86.92.17:8058 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /api/portal/self/profile from localhost:8010 to http://10.86.92.17:8058 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

**Comment by yimeng** [comment]
懂了 后端的服务API没起来，但为啥8058端口?是本地做了个nginx的端口吗？

**Comment by jsers** [comment]
@yimeng 
单独 run 前端的开发环境这里有一层 proxy，8058 是我们这的后端 API 环境地址，你可以在 fetk.config.js 里修改成你自己的地址。
